### ISSUE TITLE
HTTP Segment Ingest: Adding duration & other missing metadata to source segment 

### ISSUE THREAD

**Issue by angyangie** [livepeer/go-livepeer#1002]
Issue originally brought up here: https://github.com/livepeer/go-livepeer/pull/972

**Summary of discussion:**

(Josh) Durations: The duration of the source segment is currently not passed in. The duration is necessary to insert valid timings for the resulting HLS playlist. Other features such as latency-based O selection need the duration.

To solve this, it would be nice to send a HTTP header, eg Content-Duration with the value in seconds. We could also probe each segment but that's not desirable on the broadcaster: it's format-specific and another step in the process.

(Josh) Other Missing Metadata: Might be nice to incorporate the width/height of the source segment as a header. We use this information in the master playlist to describe the dimensions of the source stream.

> Durations / Other Missing Metadata

(Eli) Confirmed this issue — the durations show up as zero in the M3U8, which stymies a variety of HLS players including our own. ffplay shrugs it off but polls for new segments from the manifest relentlessly, many times per second.

Something about passing duration/resolution as HTTP headers rubs me the wrong way, feels like a very ad-hoc protocol, but I don't really have a better solution at the moment. The data is actually present in the incoming manifests from both Wowza and ffmpeg, but I'm not wild about requiring that. Messy.

> The data is actually present in the incoming manifests from both Wowza and ffmpeg

(Josh) Is the data available programmatically if you're able to access the source segments within Wowza? I have a little patch adding this to ffmpeg that should be cleaned up and submitted...

(Angie) Re: missing metadata - are we suggesting adding content-duration to seg := &stream.HLSSegment & width/height? Where exactly would these be used? I see we need the former for valid timings for the resulting HLS playlist ... is that something that happens in LPMS? What about height/width? I also see arguments against requiring content-duration/resolution.

(Eli) Yeah... this is my biggest area of ambivalence in this PR. I see a few possible paths forward:

A. Ship as-is, with the segment lengths for the source stream being listed as zero in the HTTP output.

B. Provide bitrate/duration data in HTTP headers. I like that this is low-overhead and could be implemented quickly. I dislike that it's an ad-hoc, Livepeer-specific protocol that won't be followed by any "HLS Push" except for LivepeerWowza's implementation.

C. Implement ffprobe-style discovery of bitrate/duration. This would definitely work but is really unfortunate overhead for the broadcaster to incur. If we go this route, it should probably enabled/disabled through a CLI flag.

D. Consume the manifests that are being provided by the LivepeerWowza plugin and ffmpeg, get the bitrate data from there. I like that this feels closest to the HLS spec. I also like that the work to implement this would likely overlap with the work necessary to implement an "HLS Pull" feature in go-livepeer.

Loosely held ranking of these: D, B, A, and C.

> Option D to get bitrate data from manifests that are being provided by the LivepeerWowza plugin and ffmpeg sounds reasonable. Where do we use the bitrate/duration data?

(Josh) The problem with doing this is that we have to handle it across separate requests: one request to receive the M3U8, and another request to receive the mpegts file. (And I don't think we can always depend on receiving one before or after the other.) That's increased bookkeeping we really could do without.

> I like that this feels closest to the HLS spec. I also like that the work to implement this would likely overlap with the work necessary to implement an "HLS Pull" feature in go-livepeer.

(Josh) Note that this is much closer to "HLS Push" rather than "HLS Pull". A true "HLS Pull" feature wouldn't have the client also pushing segments or manifests.

Another downside here is that we'd be baking in the expectation of a corresponding manifest, when there is otherwise no reason to need one. The less we can make this HLS-specific, the better.

> Option B ... I dislike that it's an ad-hoc, Livepeer-specific protocol that won't be followed by any "HLS Push" except for LivepeerWowza's implementation.

(Josh) Which is totally OK, because nearly all APIs are ad-hoc like that. "HLS Push" isn't a standard in any meaningful sense.

**Comment by iameli** [comment]
I'm totally cool with moving forward on B.

**Comment by iameli** [comment]
Proposed header names:

Segment duration: `Content-Duration: 1.655`
Segment resolution: either `Content-Resolution: 1920x1080` or `Content-Width: 1920` `Content-Height: 1080`
Segment bitrate: is this necessary? Presumably bitrate is implied by `Content-Length / Content-Duration`. But failing that `Content-Bitrate`?

**Comment by iameli** [comment]
Proposed headers for information:

Segment length: `Content-Duration`
Segment bitrate:
Segment resolution:

**Comment by angyangie** [comment]
Notes from 1 on 1 with @j0sh :
- `Content-Duration` should be done in milliseconds or in microseconds so that we don't have to deal with the float point numbers.
- `Content-Resolution` works
- Bitrate is not necessary (if we calculate it using other headers, number would only be an average). We can hold off on this for now.

Headers would be inserted into HLS segments

**Comment by j0sh** [comment]
Resolved by https://github.com/livepeer/go-livepeer/pull/972
