### ISSUE TITLE
HTTP segment ingest: Add multipart response types

### ISSUE THREAD

**Issue by angyangie** [livepeer/go-livepeer#1003]
Original discussion here: https://github.com/livepeer/go-livepeer/pull/972

(Josh) Responses: Currently, nothing is returned in response. A [multipart/mixed implementation ](https://github.com/livepeer/go-livepeer/blob/3b6a1918a646383f4413b8a3a8f3469d9fa27818/server/ot_rpc.go#L145-L160) can be borrowed from the standalone transcoder.

(Eli) Let's allow for both no-return and multipart/mixed implementations as determined by the presence or absence of the Accept: multipart/mixed header? I think they both have valid use cases.

(Josh) Haven't checked yet but is a response like 200 OK even returned right now? If not, should it be?

I like using the Accept header to signal the format of the response body. Part of me wonders if we should make the default a bit more user-friendly, like a list of transcoded URLs or even a zip/tar file with the results (would be a super cool feature in conjunction with "Non-Segmented Transcodes") but that's something we can figure out later.

(Angie) Why do we need something to be returned in responses here, to require a multipart/mixed implementation? Which response are we talking about? I see a comment on returning "a list of transcoded URLs or even a zip/tar file with the results" ... do we agree what should be returned?

(Eli) I think there is not consensus on the point. I would be entirely comfortable shipping this PR without any return type at all — as discussed [here](https://github.com/livepeer/go-livepeer/pull/972#issuecomment-510196290), any future return types can be added through the Accept: header.

**Comment by iameli** [comment]
Some feedback from Jaron at MistServer that I 

>I'd say [not returning the HTTP response until the transcoding is complete is] actually a really useful feature: if the endpoint doesn't respond to the POST until the transcode is complete, we can use that fact to not have to continuously poll the playlist for updates, and get the output as soon as it's ready with perfect timing.
> It sounds like you're planning to change the behaviour so the return is immediate; may I suggest making it an option instead? I'd like to be able to rely on this behaviour to optimize timing. 😁
> Or, even better: perhaps have the endpoint respond with either the transcoded data itself, or a redirect towards it? HTTP status code 300 "Multiple choices" sounds like a great candidate for this when encoding multiple profiles at once. (Though we'd be perfectly fine working with either all qualities concatenated after each other or having them in a single TS mux) I'm not sure if all that's feasible for you or not, but it would greatly simplify integration I'd say.

`300 Multiple Choices` is a cool idea for what we could return.

**Comment by j0sh** [comment]
> we can use that fact to not have to continuously poll the playlist for updates, and get the output as soon as it's ready with perfect timing.

💯 

> It sounds like you're planning to change the behaviour so the return is immediate

Who says we're planning to change the behavior?
