### ISSUE TITLE
HTTP segment ingest: path prefix and port numbering

### ISSUE THREAD

**Issue by angyangie** [livepeer/go-livepeer#1004]
Original discussion here: https://github.com/livepeer/go-livepeer/pull/972

(Josh) Path Prefix: Currently /live/ , as opposed to the proposed /stream/. LPMS hijacks the /stream/ prefix so it's easier to just use a new prefix. Transcoded HLS is still available for playback under /stream/ as before.

(Josh) Port numbering: Currently use port 7935, mostly out of expediency - the B doesn't pass in a custom mux that can be shared between LPMS and the goclient.

We have an internal CLI API running on port 7935 that is mostly used for node management and diagnostics. An "external" port lives on 8935. The broadcaster uses the external port for HLS playback. (O uses 8935 for gRPC and segment handling as well).

We may want to switch the /live/ endpoint to port 8935. One bit of concern here is relating to "safe defaults". Historically, we have attempted to keep all potentially Eth-draining operations segregated from the port on 8935, which is considered public. Since there is no authentication by default, a B operator may unintentionally open itself up to drive-by transcoding.

One mitigating factor is that the broadcaster listens to 8935 on localhost by default. (We do the same for RTMP.) Another layer of safety would be to have a flag to toggle the push API. For an improved UX, this flag could be enabled by default. It would be disabled by default if 8935 is listening to non-localhost and webhook auth is not enabled. Enabling the flag under those conditions would be an explicit signal - "I know this is potentially an expensive choice, do it anyway."

(Eli) I think your defaults are reasonable, but I kind of also want the ability to run the HTTP ingest on a separate port entirely. I know it seems like we're getting up to an unreasonable number of HTTP servers, but I like the idea of RTMP and HTTP ingest having the same security story — listening on localhost by default, optionally enhanced with a webhook. There are lots of current hobbyist workflows that involve setting up a local server, exposing 8935 publicly, and streaming OBS to localhost over RTMP — it'd be a shame not to be able to implement that same pattern using HTTP without a webhook.

> run the HTTP ingest on a separate port entirely

(Josh) Yeah, that's a potential use case. I'm torn, because I also like minimizing the exposed surface area on the node. Curious what others think.

(Angie) HTTP ingest - arguments were made for port 7935 (current setup), for 8935 and using a flag for push API, disabling it automatically if there is no webhook auth present/non-localhost, and setting it up on a different port entirely. We should get consensus around this!

(Eli) I'm leaning toward - it should be at http://0.0.0.0:8935/live but the webhook should be required unless explicitly disabled through a CLI flag. --allow-anonymous-http-push or some such.

(Josh) Note that the broadcaster listens to localhost by default. I don't think we should change it.

So your proposal is that we make --allow-anonymous-http-push a required flag unless -authWebhookUrl is also specified?

I'm unsure because it basically means we're introducing a required CLI flag on the broadcaster. Personally, I think I would rather toggle the push API based on:

Whether we're running on localhost - default enabled
Non-localhost - default disabled unless explicitly enabled

**Comment by iameli** [comment]
`/live` now runs on port 8935 and hits the webhook. Can this be closed?

**Comment by j0sh** [comment]
Resolved by https://github.com/livepeer/go-livepeer/pull/972
