### ISSUE TITLE
HTTP Segment Ingest: Reconstruct target URL

### ISSUE THREAD

**Issue by angyangie** [livepeer/go-livepeer#1006]
Original discussion here: 

**Reconstruct Target URL**: The golang request.URL field is simply extracted from the Request-URI part of the HTTP request, and is usually missing the scheme, host, port, etc. Having the full target URL would be useful for the auth webhook. The URL needs to be reconstructed from the data available in the Request object.

(Angie) Reconstruct target URL section: I see "having the full target URL would be useful for the auth webhook" .... where are we connecting to the auth webhook?

(Eli) I totally forgot that I made a branch to test @mk-livepeer's proposed fix for this! https://github.com/livepeer/go-livepeer/tree/eli/liveingest-request-uri <-- if that works, my concern is fully addressed.

(Josh) I don't think that will actually be any different from what we're currently sending, since golang already populates the URL field with the request URI [1]. If this is an issue that needs to be resolved, we need to manually rebuild the address with the scheme / host as the writeup describes.

**Comment by j0sh** [comment]
Resolved by https://github.com/livepeer/go-livepeer/pull/972
