### ISSUE TITLE
Refactor eth.UnbondingService to use blockwatch

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1040]
**Is your feature request related to a problem? Please describe.**

`eth.UnbondingService` currently creates a subscription with a remote ETH node in order to watch for unbond, rebond and withdraw events. Instead, it can subscribe to `blockwatch.Watcher` (all such services will rely on the same reliable stream of blocks from the watcher).

**Describe the solution you'd like**

Refactor `eth/eventservices/unbondingservice.go` to use `blockwatch.Watcher`.

This will involve:

- Passing an instance of `blockwatch.Watcher` (that has already started watching for blocks) as an argument when creating `UnbondingService`
- `UnbondingService` will create a block subscription when it is started
- Add an event decoder implementation that uses the JSON ABI definitions for the unbond, rebond and withdraw events to decode logs that are emitted from the block subscription

**Comment by kyriediculous** [comment]
I propose to add a method to the blockwatcher that allows us to add topics to it while `Watcher.Watch()` is already running on a seperate worker. 

We can then add topics for each of the event services we need. 
 
`Watcher.addLogs()` will then build a `FilterQuery` for these topics. 

This in turns allows us to filter the block subscription result's logs faster in the seperate services for the event we need.

**Comment by yondonfu** [comment]
`blockwatch.Watcher` already accepts an array of topics in the [Config](https://github.com/livepeer/go-livepeer/blob/master/eth/blockwatch/block_watcher.go#L50) that it is constructed with. For each event service, we can define the relevant topics and pass them into the `Config` struct prior to constructing a new `blockwatch.Watcher`.

One thing worth noting is that `blockwatch.Watcher` can only be configured with an array of topics, but not an array of contract addresses. Thus, an event signature collision between 2 contracts that use the same signature for an event (i.e. the `Transfer()` event in 2 ERC20 contracts) is possible. I don't think we need to handle this immediately, but we should make a note about this possibility and track it in an issue to fix later on.

**Comment by kyriediculous** [comment]
That however requires starting up a new blockwatcher for every event service just because we want to filter on a specific topic, which seems redundant and therefore not very ideal. 

My thought was to init these event services with an already initiated blockwatcher, not create new instances of Watcher for every event service we need. We could then add those topics to the `watcher.topics` array rather than having different workers running watchers. 

Also keep in mind that every new instance of a blockwatcher will be using the same DB table. 
If we have multiple watchers that filter for multiple topics, we'd have those overwriting eachother.

My preferred approach would be to extend the original subscription to be able to subscribe to event topics (and by extension contract addresses) or build an event subscription on top of the blockwatch subscription.

____ 

The alternative would be as I did in my MVP for the RoundsWatcher is to filter the returned miniheaders from a blockwatch subscription by topics in the event watcher service itself. 


```
func (rw *RoundsWatcher) Listen() {
        // Add new topic for this listener
	rw.watcher.topics = append(rw.watcher.topics, rw.abi.Events["NewRound"].Id())
	// TODO: Initialize by RPC call then subscribe
        // Subscribe to blockwatch headers
	events := make(chan []*Event)
	sub := rw.watcher.Subscribe(events)
	for {
		select {
		case err := <-sub.Err():
			log.Fatal(err)
		case log := <-events:
			for _, l := range log {
                                 // Filter for "NewRound" events
				nr, err := rw.filterAndParseHeaderLogs(l.BlockHeader)
				if err != nil {
					glog.Error("Could not parse and filter logs", err)
				}
				if nr != nil {
					fmt.Println(*nr)
				}
			}
		}
	}
}
```

**Comment by yondonfu** [comment]
> That however requires starting up a new blockwatcher for every event service just because we want to filter on a specific topic, which seems redundant and therefore not very ideal.

This is not the case. We can start a single `blockwatch.Watcher` and provide the topics we care about when constructing it.

> My thought was to init these event services with an already initiated blockwatcher, not create new instances of Watcher for every event service we need. We could then add those topics to the watcher.topics array rather than having different workers running watchers.

I believe we're saying the same thing. My suggestion is that since `blockwatch.Watcher` can already be constructed with a slice of topics we don't need to modify its API to update the slice of topics it is filtering for during runtime because we can specify those topics up front. There might be a use case for modifying the slice of topics it is filtering on in the future, but I don't see an immediate need at the moment.

**Comment by kyriediculous** [comment]
I thought you meant that you wanted to start a seperate blockwatcher for every event service with an array of of topics that particular event service needs. 

> I believe we're saying the same thing.

I believe so too, except that  I propose to only add the topics to the Watcher when we start the seperate event watchers, not beforehand when we're starting the blockwatcher itself. I think it reduces potential developer error if we add it in the constructors of those seperate services.
