### ISSUE TITLE
Use new LPMS Transcode3() method to access encoded pixel count

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1049]
**Is your feature request related to a problem? Please describe.**

After livepeer/lpms#147 is merged, the `Transcode()` method should be used by `Transcoder` interface implementations. 

**Describe the solution you'd like**

After livepeer/lpms#147 is merged, the `Transcode3()` method should be used by `Transcoder` interface implementations. This involves:

- Updating the vendored version of LPMS
- Updating the `Transcode()` method implementation for both `LocalTranscoder` and `NvidiaTranscoder` to call `ffmpeg.Transcode3()`
- Use the result returned by `ffmpeg.Transcode3()` to populate the `Pixels` field of each `TranscodeData`

Note: `ffmpeg.Transcode3()` will return both the decoded and encoded pixel count, but for now we will only use the encoded pixel count because the broadcaster won't be able to verify the decoded pixel count until a solution for livepeer/lpms#139 is implemented.

**Comment by j0sh** [comment]
The [`RemoteTranscoderManager`](https://github.com/livepeer/go-livepeer/blob/f8c5c4dff1de45e6a0725d1a353e4d171a0524e8/core/orchestrator.go#L803-L821) will also probably need its signature updated.

At some point https://github.com/livepeer/go-livepeer/issues/1050 will need to be done as well, but I suspect for the purposes of unblocking PM, just the implementaiton can be adjusted to match the interface, and the actual values can be stubbed out until https://github.com/livepeer/go-livepeer/issues/1050 is implemented.

> the broadcaster won't be able to verify the decoded pixel count until a solution for livepeer/lpms#139 is implemented.

Just to clarify : https://github.com/livepeer/lpms/pull/147 enables the B to count the returned pixels in transcoded segments to check the O's accounting. livepeer/lpms#139 helps for the B to better understand the number of pixels in a given source segment, so it can better gauge the number of tickets required for a given segment (and may help approximate the actual pixels B should expect as well).

**Comment by yondonfu** [comment]
> helps for the B to better understand the number of pixels in a given source segment, so it can better gauge the number of tickets required for a given segment

livepeer/lpms#147 allows B to check the pixel count for transcoded results i.e. the # of pixels that O encoded, but B wouldn't be able to check the pixel count of the original input segment i.e. the # of pixels that O decoded. So, if O wanted to charge B for the total pixels decoded & encoded for a given input segment and the requested renditions, B wouldn't be able to check that the total pixels decoded by O is correct unless B knows the # of pixels in the input segment sent to O (which I believe livepeer/lpms#139 would enable). I think it is fine to just charge for encoding for now, but just thought I'd mention B's ability to check that O is accurately reporting the # of pixels it decoded when O is charging for decoding.

**Comment by j0sh** [comment]
Yep - so  livepeer/lpms#139 enables a number of things:

* Allows charging for decoded pixels
* Allows the broadcaster to better estimate the number of pixels in the transcoded result it should expect from the transcoder. (Currently we have the duration and the resolution, but not the frame rate or a frame count which would enable this approximation.)
  * B can to better generate the appropriate number of PM tickets.
  * B can perform a quick check on the actual returned pixel count using the estimated count, without having to check the video itself. If the returned count is more than a few percent of the expected count, then that would be a signal for more intensive checking (eg, full pixel count and/or verification).
