### ISSUE TITLE
Memory leak in orchestrator when there is a lot of RAM available... maybe?

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#1053]
Edited description:

Not sure what to make of this. When I run an orchestrator on VMs in a particular GCP instance group, it proceeds to use it all of the available memory and crash. I do not know why. The only difference I can figure between this instance group and some others is that this one has an unusually high amount of RAM, 32GB. Perhaps us or x264 or someone else is handling things poorly when there's a lot of RAM available?

 [Here's some logs showing `free -m` running every ten seconds.](https://gist.github.com/iameli/f53f9209974376c0d99ee421a0fef62d) The orchestrator and braodcaster logs are there too. The rate of memory consumption appears to be around 300 mb/s - seems like that would have to be decoded frames caught in memory somewhere?

I've got one OBS stream flowing into the broadcaster at about 5000 kb/s.

Orchestrator command:
```
livepeer -orchestrator -transcoder -datadir=/root/.lpData/transcoder -cliAddr=":7936" -v=6 -serviceAddr="127.0.0.1:8936"
```

Broadcaster command:
```
livepeer -broadcaster -datadir=/root/.lpData/broadcaster -orchAddr=127.0.0.1:8936 -rtmpAddr=0.0.0.0:1935 -currentManifest -httpAddr=0.0.0.0:8080 -v=6 -transcodingOptions=P240p30fps16x9,P360p30fps16x9,P720p30fps16x9
```

`livepeer -version`:

```
Livepeer Node Version: 0.3.3-f8c5c4df
Golang runtime version: gc go1.12.7
Architecture: amd64
Operating system: linux
```

**Comment by iameli** [comment]
Hrmph. I can't reproduce this except on the one specific server that was originally having the problem. Can't imagine what the problem would be... closing for now but if anyone else runs into a weird memory leak, I encountered it too!

**Comment by iameli** [comment]
Tentatively reopening with edited title and description. I can reproduce it on fresh servers with lots of RAM, so maybe it's that?

**Comment by j0sh** [comment]
Does this lead to adverse behavior? Maybe it's just the golang GC not being run because it knows it has plenty of RAM available?

**Comment by iameli** [comment]
Hmm. The problem I'm encountering specifically is that Kubernetes is keeping memory earmarked for other processes on the same server, so go-livepeer is getting "OOM Killed" for exceeding its defined [memory limit](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/), even though there's technically available memory on the server.

I'll try fiddling with the GOGC environment variable and `ulimit` — if it's just the GC, that should get me the behavior I want. Will reopen if I run into any other issues.
