### ISSUE TITLE
Cap transcode retries.

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#1057]
Currently broadcaster tries to transcode segment indefinitely (it only stops if there is not orchestrators left in its list). This can lead to the situation when segment is transcoded, but window of live playlist is already passed, so that segment is not needed. 
This will make broadcaster pay for the work it is not needed and will skew results of our tests - transcode will be recorded as successful, but for broadcaster it is actually a failure to get result too late.

Probably we could step trying to transcode if there is (LIVE_LIST_LENGTH-1)*SegLen seconds passed since start of this segment transcoding attempts.

Something like this:
```golang
	start := time.Now()
	for {
		// if fails, retry; rudimentary
		if err := transcodeSegment(cxn, seg, name); err == nil {
			return nil
		}
		if time.Since(start) > (core.LIVE_LIST_LENGTH-1)*SegLen {
			return fmt.Errorf("Timed out")
		}
	}
```

**Comment by j0sh** [comment]
@darkdarkdragon Curious: does your testing show that some segments consistently take longer than `(core.LIVE_LIST_LENGTH-1)*SegLen` seconds to process?

If there is a case where a single segment quickly runs through all Os , then it might be possible that there's something wrong with the segment itself. 

A supplementary option alongside this is to simply cap the number of retries, perhaps  something like `MaxRetries = (core.LIVE_LIST_LENGTH-1)*SegLen / core.HTTPTimeout`. But this might also have unintended consequences, such as more drops at the beginning of the stream as B tries to converge on an optimal set of Os.

**Comment by darkdarkdragon** [comment]
@j0sh 
>  Curious: does your testing show that some segments consistently take longe

I haven't looked at it, I'm bringing it up because I think it _could_ happen, and our test will miss it.

**Comment by iameli** [comment]
Per discussion after our benchmarking session today, I'd be in favor of making the cap on retries a count that's configurable with a CLI option. @j0sh Did you mention you had a local patch for the retry cap?

**Comment by j0sh** [comment]
> Did you mention you had a local patch for the retry cap?

Only this:

```diff
diff --git a/server/broadcast.go b/server/broadcast.go
index dbc36d44..8668f03c 100644
--- a/server/broadcast.go
+++ b/server/broadcast.go
@@ -290,7 +290,7 @@ func processSegment(cxn *rtmpConnection, seg *stream.HLSSegment) ([]string, erro
                sv = verification.NewSegmentVerifier(Policy)
        }
 
-       for {
+       for i := 0; i < 3; i++ {
                // if fails, retry; rudimentary
                if urls, err := transcodeSegment(cxn, seg, name, sv); err == nil {
                        return urls, nil
@@ -304,6 +304,7 @@ func processSegment(cxn *rtmpConnection, seg *stream.HLSSegment) ([]string, erro
 
                // recoverable error, retry
        }
+       return nil, errors.New("MaxRetries")
 }
```

This is going to take some more work to incorporate a CLI flag, unit tests, etc.
