### ISSUE TITLE
Gracefully shutdown B when using HTTP ingest

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#1065]
**Is your feature request related to a problem? Please describe.**
Currently, if client (Wowza plugin) is in the process of transcoding stream using B's HTTP ingest, and B is shut down (say, for upgrade), then client should re-submit this segment to another B. This will increase latency for that segment, plus it will increase load (at start) to new B, because it will receive this segment and next one close to each other in time then it will be under normal circumstances. 

**Describe the solution you'd like**
Ideally, upon receiving SIGINT or SIGTERM, B node should
1. Stop accepting new segments through HTTP ingest
2. Wait for last received segment to be transcoded and sent back to client
3. Shut down

**Additional context**
Currently transcoded segment is get back to the client using pull (Wowza plugin re-reads .m3u8 from B to find out if segment is ready), so there is not clean way to find out if client received transcoded data. So this ticket will be easier to implement after pull model changed to push.

**Comment by iameli** [comment]
Perhaps the shut-down process could look like:

1. Stop accepting new segments through HTTP ingest (probably by returning an HTTP 503?)
1. Wait for last received segment to be transcoded
1. Wait `LAST_SEGMENT_LENGTH * 2`-ish seconds
1. Stop serving new HLS segments (probably by shutting down the HTTP server entirely)
1. Finish remaining pending requests and shut down
