### ISSUE TITLE
CircleCI failing on localdocker build

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1071]
**Describe the bug**
Recent builds are failing on CircleCI. Examples:

https://circleci.com/gh/livepeer/go-livepeer/2773?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://circleci.com/gh/livepeer/go-livepeer/2771?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**To Reproduce**
1. Push a go-livepeer branch to Github (doesn't have to be a PR)
1.  Wait for CI to run
1. CI fails

**Expected behavior**
1. CI to pass

**Additional context**
Not sure if this is an issue on Circle's end because recent merges seem to have been OK.

**Comment by j0sh** [comment]
Looks like this is an issue again: https://circleci.com/gh/livepeer/go-livepeer/2803?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link and https://circleci.com/gh/livepeer/go-livepeer/2797?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Do we know why? Will go modules prevent this from happening by freezing our unvendored dependencies?

**Comment by darkdarkdragon** [comment]
@j0sh switching to go modules will allow me to completely remove .deps file.
I've created WIP branch (0d76b6e4498d2b4376542fe38c9c95c16ff3dda5) there I've added `go.mod`, removed `vendor` dir and removed links to `ipfs` in code.
It builds, but tests are failing, will look at them tomorrow.
