### ISSUE TITLE
Failing ticket redemptions due to expired ticket

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1084]
**Describe the bug**

Observed a few failing ticket redemption transactions for an orchestrator running on the internal testnet.

**Screenshots**

Grepped the orchestrator logs for failed transactions. Note: I started the orchestrator with a hardcoded gas limit to skip gas estimation which allows failing transactions to be submitted - otherwise gas estimation would prevent failing transactions from being submitted.

<img width="1679" alt="Screen Shot 2019-09-11 at 10 29 04 PM" src="https://user-images.githubusercontent.com/5933273/64749444-b0c6e400-d4e3-11e9-9853-6170e2d330fa.png">

Used the hash of failed transaction to fetch the transaction and re-run it locally at the block that it failed in in order to extract the revert reason. It appears that the ticket expired.

<img width="870" alt="Screen Shot 2019-09-11 at 10 29 44 PM" src="https://user-images.githubusercontent.com/5933273/64749446-b3c1d480-d4e3-11e9-958d-70d3b37e385b.png">

This is unexpected behavior because the orchestrator should be rejecting any expired tickets and should not be redeeming them.

**Comment by kyriediculous** [comment]
Were these tickets queued or redeemed instantly upon receiving the ticket?

**Comment by yondonfu** [comment]
I believe that the tickets were redeemed instantly upon receiving them.
