### ISSUE TITLE
Create a release process issue template

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1087]
As we prepare to do more frequent releases, it would be useful to document a release process. An example of a documented release process is [IPFS](https://github.com/ipfs/go-ipfs/blob/master/docs/RELEASE_ISSUE_TEMPLATE.md). We could include a description of the process and a checklist in an issue template which serves as the starting point for release preparation.

**Comment by j0sh** [comment]
Should we close this now https://github.com/livepeer/go-livepeer/pull/1295 is merged?

**Comment by yondonfu** [comment]
Yep - closing.
