### ISSUE TITLE
Statically Linked TLS Library

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1094]
**Describe the bug**
We try to static link as much as possible to minimize dependency headaches when distributing builds. So far we've been pretty successful at this, but sometimes things slip through. In this case, GnuTLS is dynamically linked. We would prefer to have a statically linked TLS library.

```
$ otool -L livepeer
livepeer:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/usr/local/opt/gnutls/lib/libgnutls.30.dylib (compatibility version 54.0.0, current version 54.2.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1570.15.0)
	/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 944.3.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.251.4)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
```

**To Reproduce**
Build Livepeer, making sure to follow the `install_ffmpeg.sh` steps to ensure static linking of video-related dependencies

**Expected behavior**
The TLS library should be statically linked.

**Desktop (please complete the following information):**
 - OS: macOS, Linux

**Additional context**

We have tried to fix this in the past, but GnuTLS itself has a lot of knock-on dependencies that have proven challenging to cleanly link statically. We have looked at other libraries such as OpenSSL (and derivatives) but the licensing situation around those is unclear.

We have looked at mbedTLS in the past (which also has a more friendly license) but had trouble getting it to work. Might be good to give that another attempt.

**Comment by iameli** [comment]
Specific problem I ran into with mbedTLS was it complaining that the orchestrator HTTPS certificate wasn't trusted - probable that getting it to work could be as easy as flipping some switch to make it not care about that.

The alternative is figuring out how to get gmp, nettle, hogweed, and I think a few other things all statically linking on Linux, Darwin, and Windows (mingw64). I did not have fun last time I attempted that, but it's certainly not impossible.
