### ISSUE TITLE
Prevent datadir reuse on different networks

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1098]
**Is your feature request related to a problem? Please describe.**

There have been issues in the past where the same data directory would be used on different networks (eg, mainnet vs Rinkeby). This leads to odd results due to the state cached in the DB not matching the current network.

While we've made structural changes to datadir handling to make this type of collision less likely, it's still a possibility if a custom `-datadir` is specified, but the `-network` changes between runs.

**Describe the solution you'd like**

We should try to detect this problem at runtime, and inform the user of a mismatch. One approach to doing this is as follows:

* The DB should record the network it's running on when the DB is first created.
* After a node restart, if the current network doesn't match the network recorded in the DB, then the node should exit with an error message.
* The network name can be recorded in the `kv` table.

**Describe alternatives you've considered**

Generated file names (DB, private key, certificate, etc) could all be based on the network name, which would allow data for multiple networks to coexist within the same data directory.

**Comment by kyriediculous** [comment]
As mentioned in the issue outline we already try to mitigate against `datadir` collisions by concatenating the network name to a non-custom `-datadir`. 

Collision when providing `-datadir` flags makes it an end-user responsability however which isn't ideal. 

For this reason I actually like the proposed alternative better than the current structure. I would even go a step further and employ `name+chainID`. 

That being said the simplest and most robust solution seems to store the `chainID` for a network name, on node startup we would then make an RPC call to the provided `ethUrl` (or infura when not provided) and compare that against the ID from the database. 

This should prevent even changing networks but keeping the name the same which is an edge case unhandled by simply storing the network name.

**Comment by yondonfu** [comment]
Agreed that storing the chainID in the DB would be a more robust solution.

If we store the chainID in the DB, we should also define the expected behavior when the node is running in off-chain mode.

One approach is to set the default value for chainID to be 0 which does not correspond to a valid chain. The node would treat chainID = 0 as an indication that the DB was configured in off-chain mode. An alternative is to not set the chainID at all, but this would require error handling and special casing errors when querying for the chainID.
