### ISSUE TITLE
Policy Implementation

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1100]
Currently, the [transcode loop](https://github.com/livepeer/go-livepeer/blob/78142f04ff58d2aaac765ebb7c18ff497ee5d06f/server/broadcast.go#L279-L304) retries a segment until one of the following "exit conditions" is met:
* It runs out of orchestrators
* A non-error value is returned from the transcode function.

With policy-based enforcement, we may see the set of "exit conditions" be expanded to accommodate various policy parameters, and to have policy-related code commingled with various parts of the transcode logic. While this is in a sense more "straightforward" to read through, the broadcast-related code is already fairly sprawling, and it does not seem desirable to increase that complexity further with increased branchiness around the details of policy implementation in various spots.

A design decision here is to preserve the existing flow with minimal changes. This implies keeping any policy and verification-related bookkeeping entirely self-contained. That way, a policy-driven verifier can influence the transcoding flow only via error codes, with some light handling of particular return values at the verifier call site. This also facilitates better isolation of policy-related code for off-chain use.

The goal of keeping the verifier and policy parts self-contained suggests the following signature for the primary entry point to the verifier:
```

// Call NewSegmentVerifier to instantiate a 
// fresh verifier policy for a given segment.
NewSegmentVerifier(p Policy) Verifier

type Verifier interface {
  Verify(params *VerificationParams) (ret *VerificationParams, err error)
}
```

Since policy enforcement will entail a certain amount of bookkeeping for each segment (tracking retries, sorting results, etc), a fresh verifier should be instantiated for each segment. `NewSegmentVerifier` is the proposed name of this function to instantiate fresh verifiers.

The semantics of the `Verify` function are as following:

* `params` holds all the parameters for the current set of renditions, including information on the source segment.
 
Currently, there are a lot of [parameters](https://github.com/livepeer/go-livepeer/pull/1096/files#diff-98d66d2dc5372dedc76d5fdde7bedebcR11-R26) so it is easier to put them into a struct. Moreover, different verifiers may use different subsets of parameter fields without changing the signature.

* `ret` indicates the parameter set that has been accepted by the verifier, if any. A nil return value indicates the given parameters were not immediately accepted, while a non-nil value indicates an accepted set of parameters.
 
The returned set of parameters will not necessarily match what was just passed into `params`. For example, hitting the retry limit with `params` could result in returning a different set of parameters for `ret` if an earlier set resulted in a better score.

* `err` indicates how the current set of parameters was handled by this invocation of the verifier. If this is `nil`, it means the current set of parameters was accepted.

If this is the last retry for the given segment, then both `err` and `ret` may be non-nil. This slightly unusual circumstance occurs if the current `params` did not meet the verifier's success threshold, while the policy still returned some other best-scoring set of parameters with `ret`.

### Error Handling

The following types of errors need to be distinguished:

### Fatal errors
Should immediately remove the orchestrator from the broadcaster's working set. Examples of fatal errors include:
* Sig check failure
* Pixel count mismatch
* Audio hash mismatch

Fatal errors generally should lead to a retry if there are any attempts left.
 
### Verifier errors
Verifier errors occur when the transcoded renditions did not satisfy the requirements of the policy.

Verifier errors generally lead to a retry if there are any attempts left.
 
 ### Other Errors
 
 These errors are the remaining errors that do not fall under the other categories. Such errors include:
 
 * Network errors: verifier down, timeout, etc.
 * Other errors from verifier, outside classification (eg, malformed request or response parameters)

How to handle these errors will generally depend on the policy. Options may include dropping the segment, using it anyway, or retrying.

### Tamper Handling

Policy based verification only attempts to select the best renditions out of a given set of renditions. It does not attempt to pass judgement on whether an orchestrator tampered with a segment, nor does it prescribe how to handle orchestrators that submit lower quality renditions.

### Tradeoff: Repeated Orchestrator Selection

Currently, after a transcode appears to succeed (prior to any post-processing such as downloading), we re-add the orchestrator to the working set in order for it to be available to process the next segment. 

However, this proposed "self-contained" design of PBV requires special consideration: we do not want to retry a segment, only to re-select the same orchestrator! There are several options here to mitigate the issue:

* Maintain a running list of orchestrators used for a segment, and exclude those when attempting a retry.

This requires the most changes: additional bookkeeping and changes to the session manager.

* Don't re-add the orchestrator to the working set until *after* verification is complete.

This method is simple, but has the tradeoff of the orchestrator being unavailable to process other segments while verification runs. In turn, this may increase pressure on the working set, leading to higher rates of refresh or even failure (NoOrchestrators).

As a workaround, we may optimize the session management flow here for verification-less operation, but that means incurring "branchy" code for the verifier.

* Lift the one-segment-per-orchestrator restriction.

While conceptually simple, this removes a powerful feedback mechanism and makes decisions around load balancing more difficult.

### Errors Prior to Verification

Except for a few types of "unrecoverable" errors, the broadcaster typically attempts to retry a segment if a transcode fails for any reason. Under the current proposal, these retries are not counted towards the policy: only successful transcodes that hit the verifier are counted.

There is certainly an argument to be made that we should limit failed transcode attempts. That brings up whether "transcode policies" should be generalized outside verification specifically. Generalizing verification policies to cover other aspects of transcoding may require some re-working of the proposed flow. Such "transcoding policies" may also work best separately, outside of the verification policy.

### Parallel / Redundant Transcodes

One extension is to run multiple transcodes in parallel as outlined in https://github.com/livepeer/research/issues/37 . This can be done without large structural changes around verification, however the transcode loop would have to kick off a corresponding amount of `transcodeSegment` goroutines based on the policy parameters.

### Policy Interface

Each policy integrates a particular verifier: it invokes the verifier, interprets the results (returning a pass/fail), and stores configurable parameters around the usage of the verifier itself.

```golang
type VerificationParams interface {
}
type VerificationResult interface {
  // needs to be sortable in order to select winners
  sort.Interface

  // Returns the number of pixels decoded 
  Pixels() []int
}

type Policy interface {
  Verify(params *VerificationParams (*VerificationResult, error)
  
  Retries() int
  SampleRate() float // TBD!
  Redundancy() int // How many parallel transcodes to support. For later!
}
```

Example policies could be implemented for:
* The Epic Labs classifier
* Hypothetical SSIM-only verifier
* coersion pixel-matching

### Policy Usage Example

Here is an simplified implementation of the `Verifier` interface. This only addresses policy usage, and does not look at other aspects such as pixel counting, sig checking, and so forth.

```golang
// Concrete type, implementing Verifier interface
type SegmentVerifier struct {
  policy Policy
  results []struct {
    // Parameters for the corresponding results
    params VerificationParams
    
    // Results themselves
    res VerificationResult
    
    // Implement sort.Interface based on `res`
  }
  
  // Number of invocations of the verifier
  count int
  
}
func NewSegmentVerifier(p *Policy) Verifier {
  return &SegmentVerifier{p: p}
}


func (sv *SegmentVerifier) Verify(params *VerificationParams) (*VerificationParams, error) {

  res, err := sv.policy.Verify(params)
  if err == nil {
      // Segment passed verifier!
      return params, nil
  }
  p.count++
  
  if _, fatal := err.(FatalError) ; !fatal {
      r := { params: params, res: res }
      pe.results = append(pe.results, r)
  }
  
   // Check for max retries
   // if so, return best params so far
  if p.count >= sv.policy.Retries() {
    if len(pe.results > 0) return nil, nil
    sort.Sort(pe.results)
    return pe.results[0].params, err
  }
  return nil, err
}
```

Within the `server/broadcast.go`, implementation of the verifier could look like this (assuming a the policy/verification bits live in a `verification` package:)

```golang
// in broadcast.go 

// ... in `transcodeSegment` ...
{
  // Only verify if we have a verifier specified
  if segmentVerifier != nil {
    // ***Override*** any existing `data`
    // The `dlFunc` helper would have to be       // modified to make the downloaded data   
    // available from the function.

    data, err = verify(segmentVerifier, ... )
    if err != nil return err
  }

  for i, v := range data {
    // Insert `data` into broadcaster OS
    // Insert resulting URL into playlist
  }
}

func verify(sv *SegmentVerifier, ... , renditions [][]byte) ([][]byte, error)  {

    params := &VerifierParams {
       renditions: renditions,
       // .. and others fields ...
    }
    ret, err := sv.Verify(params)

    // Remove O session from working set on fatal error
    if _, fatal := err.(FatalError); fatal {
      bsm.removeSession(sess)
    }
    
    if ret != nil {
      // A segment has been accepted by the verifier!
      // Ignore any errors from the Verify call
      // because we don't need to retry anymore
      return ret.renditions, nil
    }

    return nil, err
}

```

**Comment by yondonfu** [comment]
What do you think about incorporating a banning policy into the verification policy? The banning policy would describe when an O should be banned (i.e. permanently excluded from working set creation unless the user chooses to manually unban the O) based on the type of error encountered during verification.

An example banning policy could the following:

- Drop and ban an O for fatal errors (i.e. failed sig check, audio hash mismatch, incorrect pixel count)
- Os that trigger a verifier error would not be dropped from the working set, but we would do some bookkeeping to determine whether O should be dropped/banned if it continues to trigger verifier errors
- Let `failedVerificationPolicies` be the # of times an O has failed a verification policy
- Let `verificationCount` be the # of times an O has been subject to verification
- Let `maxFailedVerificationPolicies` be the maximum # of times an O can fail a verification policy
- Let `verificationCountResetThreshold` be the # of of verification invocations at which B will consider resetting O's verification history i.e. set `failedVerificationPolicies` and `verificationCount` to 0
- If `verificationCount >= verificationCountResetThreshold`, B will non-deterministically check if it should reset O's verification history. This check is non-deterministic to defend against O predicting when the history will be reset
- After a verification, if `failedVerificationPolicies > maxFailedVerificationPolicies`, drop & ban O

`maxFailedVerificationPolicies` and `verificationCountResetThreshold` can be set based on the current false negative rate of the verifier being used. For example, if the false negative rate is 1%, we could set `maxFailedVerificationPolicies = 2` and `verificationCountResetThreshold = 100`. We set `maxFailedVerificationPolicies = 2` instead of 1 to give a little breathing room.

If permanent bans feel too harsh in the early days due to the uncertainties around verifier performance we can also consider time based bans i.e. banning an O for a couple of days.

**Comment by j0sh** [comment]
Specifying the ban parameters as part of the overall policy parameters seems sensible, and the behavior as outlined sounds good.

I'm wondering where the actual enforcement of that should happen though. As currently planned,, the verifier only holds state on a per-segment basis. Would we be expanding that to also track per-stream or global verification history? This also will likely affect O selection.

Also, I'm thinking this would be a good addition post-Phase 2 or even Phase 3 (or an additional intermediate stage) as outlined in https://github.com/livepeer/go-livepeer/issues/1093 - the note here is mostly related to the tasks around Phase 1/2.

**Comment by yondonfu** [comment]
> I'm wondering where the actual enforcement of that should happen though.

I was thinking of enforcing bans by maintaining the ban list using the DB.

> Would we be expanding that to also track per-stream or global verification history?

I was thinking of creating a ban policy per broadcast session. If that session is dropped then the ban policy state is cleared as well. In cases where the session is dropped due to a verifier related error, then the O that corresponds to the session would be banned as well (since we either drop for a fatal error which results in a ban or for exceeding `maxFailedVerificationPolicies` which also results in a ban).

Here is a very quick & dirty sketch of what it might look like in code:

```
package verification

type SegmentVerifier struct {
    ...
    banPolicy BanPolicy
}

func (sv *SegmentVerifier) Verify(params *VerificationParams) (*VerificationParams, error) {
    ...
    if err := sv.banPolicy.CheckVerifierErr(err); err != nil {
        return err
    }
    ...
}

type BanPolicy interface {
     CheckVerifierErr(orch ethcommon.Address, err error) error
}

type SimpleBanPolicy struct {
    failedVerificationPolicies int
    verificationCount int

    *db.DB
}

func (bp *SimpleBanPolicy) CheckVerifierErr(orch ethcommon.Address, err error) error {
    bp.verificationCount++

    if err == nil {
        return nil
    }

    // Ban Os for fatal errors
    if _, fatal := err.(FatalError); err != nil {
        return bp.db.BanOrch(orch)
    }

    bp.failedVerificationPolicies++

    // Ban Os for exceeding max failed verification policies
    if bp.faliedVerifcationPolicies > maxFailedVerificationPolicies {
        return bp.db.BanOrch(orch)
    }

    if bp.verificationCount >= verificationCountResetThreshold && rand.Float64() < verificationCountResetProb {
        bp.failedVerificationPolicies = 0
        bp.verificationCount = 0
    }

    return nil
}
```

> This also will likely affect O selection.

Yeah this would impact O selection in that banned Os would be excluded from working set creation as mentioned in #1215. While ban policies affect selection, I don't think selection design needs to be exposed to how the ban policies are implemented. The selection design just needs to be aware of a ban list so that members of the ban list can be excluded from working set creation.

> Also, I'm thinking this would be a good addition post-Phase 2 or even Phase 3

Agreed. I don't think we need to add this until the policy implementation with sequential retries is complete.

**Comment by j0sh** [comment]
Most of this has been incorporated into https://github.com/livepeer/go-livepeer/pull/1096 . What's left is:

* Distinguishing fatal errors from non-fatal retryable errors
* Ban policy
