### ISSUE TITLE
Deploy a more geographically diverse network

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#111]
We should have seed nodes in different geo locations (at least in Germany, Ohio, Oregon, and Tokyo)

Should have a management tool to automate this (perhaps similar to Puppeth)

**Comment by dob** [comment]
Yah, in general I think that we should have multiple bootnodes and public
full nodes on the open internet regardless of location. That way if one
crashes or is in a weird state, the others will still be available and
we'll have a more connected network of relay nodes.

**Comment by ericxtang** [comment]
It would also be nice to have it across multiple service providers.  Terraform can handle the deployment across AWS, GC, Azure and Digitalocean.
