### ISSUE TITLE
source.m3u8 is empty

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#1118]
**Describe the bug**
When testing running a broadcaster, the result HLS stream has:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=4000000,RESOLUTION=1280x720
test-stream-id/source.m3u8
```
But `test-stream-id/source.m3u8` is empty and gives a 404.

**To Reproduce**
1. Run the broadcaster with `./livepeer -broadcaster -rtmpAddr 0.0.0.0:1935 -httpAddr 0.0.0.0:8935`
2. Stream an RTMP video stream to port 1935
3. Curl the result video on port 8935
4. Try to watch the video
5. See a 404 error

**Expected behavior**
`source.m3u8` should return the playlist that contains the source video stream.

**Additional context**
When we configure the broadcaster to actually transcode, the transcoded streams appear in the playlist just fine.  But the source stream still gives 404.

Used `https://build.livepeer.live/0.3.3-28747b26-dirty/livepeer-linux-amd64.tar.gz`. (Build from master on 10/5/2019)

**Comment by j0sh** [comment]
A fresh build from master works here, even in view-only mode where no transcoding happens - the resulting `source.m3u8` is populated and ffplay picks it up.

Perhaps describe on how the RTMP is being fed into the broadcaster? Can you paste logs from the broadcaster here?

**Comment by ericxtang** [comment]
Can't repro anymore... I must be possessed... Closing for now.
