### ISSUE TITLE
Throughput benchmark design

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#1119]
Will use for testing two sources - one standard big bunny file used by test harness, and will generate test video using Ffmpeg's testsrc filter with same resolution/length/framerate - this is to check if throughput depends on image complexity.

Will be measuring Mb/sec, Pixels/sec and Frames/sec and Speed (transcode time divided by video time). All measured as (source metric (bytes, pixes, frames) + result metric)/time. For Mb/sec it will be size of source file plus sizes of all the resulting transcoded files (for all the
renditions) divided by transcode duration.

Tests will be done with three variants of renditions: with only `P240p30fps16x9`, with only `P720p30fps16x9` and with four renditions `P240p30fps16x9,P360p30fps16x9,P576p30fps16x9,P720p30fps16x9`

Tests to do:
1. Just transcode one file, on one GPU. Repeat ten time, take average values.
2. Transcode one video on each of GPUs (simultaneously). Results will be per GPU.
3. Run simultaneous transcodings on one GPU. Start with two videos, and increase number of simultaneously transcoded videos until speed is slower than realtime.
4. Same simultanious transcoding but on all the GPUs simultaniously.

Benchmark results will be output in console in csv format, and should have date, card name(s) and video memory size in it.

----
Things to find out:
1. How video complexity affect throughput (after thinking about it, it probably boils down
  to bitrate).
2. How target frame size affects throughput (P240 vs P720 target)
3. How multiple renditions scales (some benchmarks on the internet suggests that encoding
   hardware is faster than decoding, so multiple renditions show leverage that).
4. How real simultanious transcoding scales (does transcoding two streams simultaneously
   only two times slower than transcoding one?)

----
Another type of test to do:
All the same tests, but instead of transcoding whole file at once, first pass it through our segmenter - then transcode each segment, one by one.
This will show us how much segmented transcoding decreasing performance.

**Comment by mkrufky** [comment]
I think it would be interesting to repeat the tests, but while also mining ethereum in the background.  It would be interesting to see these numbers both with and without mining side by side.
