### ISSUE TITLE
The CLI Broadcaster stats show the Max Price Per Pixel stat inverted

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#1143]
**Describe the bug**
If you set your broadcaster pricing to be 100,000,000 wei per unit, and the pixels per unit as 1, then the CLI broadcaster stats show this inverted as 100,000,000 pixels / 1 wei.

**To Reproduce**
1. Run your broadcaster node.
2. Choose option 16 in the CLI to set your broadcaster config. Set 1 pixel per unit, and 100000000 wei/pixel as your price.
3. Choose option 1 to view your node stats.
4. Observe the Broadcaster Stats section to show the value incorrectly.

```
+-----------------+
|BROADCASTER STATS|
+-----------------+
*-------------------------------*-------------------------------*
|           Max Price Per Pixel |      100000000 pixels / 1 wei |
*-------------------------------*-------------------------------*
```

**Expected behavior**
I would expect it to say 100000000 wei / 1 pixel.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X
 - Version: 0.5.0 - Streamflow testnet initial release.

**Comment by yondonfu** [comment]
Closed by #1169
