### ISSUE TITLE
Error getting pending stake

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1145]
**Describe the bug**

When the an account's last claim round is equal to the current round the following errors occur.

The node webserver tries to fetch the account's pending stake with the end round set to the current round, but fails to do so because the contract function `BondingManager.pendingStake()` reverts if the end round is not after the last claim round. See the node's error logs:

```
E1030 14:17:59.523431   28470 client.go:640] Error getting pending stake: abi: improperly formatted output:�y� (end round must be after last claim round - Bytes: [[8 195 121 160 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 40 101 110 100 32 114 111 117 110 100 32 109 117 115 116 32 98 101 32 97 102 116 101 114 32 108 97 115 116 32 99 108 97 105 109 32 114 111 117 110 100 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
E1030 14:17:59.523462   28470 webserver.go:672] abi: improperly formatted output:�y� (end round must be after last claim round - Bytes: [[8 195 121 160 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 40 101 110 100 32 114 111 117 110 100 32 109 117 115 116 32 98 101 32 97 102 116 101 114 32 108 97 115 116 32 99 108 97 105 109 32 114 111 117 110 100 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
```

The CLI sends a request to the webserver API in order to fetch a delegator's information which includes the delegator's pending stake. Since the webserver hits an error, it does not return a proper JSON response, but the CLI does not handle the error correctly. See the CLI's error logs:

```
ERROR: logging before flag.Parse: E1030 14:18:05.421090    9646 wizard_stats.go:220] Error getting delegator info: unexpected end of JSON input
```

**To Reproduce**
1. `docker run -d -p 8545:8545 -p 8546:8546 --name geth-with-livepeer-protocol livepeer/geth-with-livepeer-protocol:streamflow`
2. `go run cmd/devtool/devtool.go setup transcoder`
3. Run the devtool generated script (i.e. `run_orchestrator_<ADDRESS>.sh`)
4. Run `livepeer_cli`
5. Select the option to claim earnings and enter the current round as the end round
6. Refresh the wizard and observe errors in both the node's logs and the CLI

**Expected behavior**

No errors if an account's last claim round equals the current round.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: v0.5.0

**Comment by kyriediculous** [comment]
Fixed by https://github.com/livepeer/protocol/pull/365
