### ISSUE TITLE
Add a TranscoderWatcher event watcher

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1150]
**Is your feature request related to a problem? Please describe.**

Create a `TranscoderWatcher` in `eth/watchers` that watches for emitted `TranscoderActivated` and `TranscoderDeactivated` events in order to be able to determine the current active orchestrator set. 

The TranscoderWatcher will update the `ActivationRound`/`DeactivationRound` fields for the subject orchestrator in the database. 

**Describe the solution you'd like**
`TranscoderWatcher` watches for on-chain events emitted by the `BondingManager` pertaining to orchestrator activation and deactivation

- watch for `TranscoderActived` events
- watch for `TranscoderDeactivated` events

```
type transcoderWatcher struct {
    db      *common.DB
    dec     *EventDecoder
    lpEth   eth.LivepeerEthClient
    quit    chan struct{}
}
```

#### Handling events

- Event added: update values in DB with the `ActivationRound` and `DeactivationRound` arguments emitted by the event
- Event removed: Make an RPC call to `BondingManager.GetTranscoder()` and update the DB with the returned `ActivationRound` and `DeactivationRound` values

##### Watch

Start watching the `blockwatch` subscription for `TranscoderActivated` and `TranscoderDeactivated` events

```
func (tw *transcoderWatcher) Watch() error
```

##### Stop

Unsubscribe from `TranscoderActivated` and `TranscoderDeactivated` events propagated by `blockwatch` 

```
func (tw *transcoderWatcher) Stop()
```

**Additional context**

Full spec for active orchestrator set tracking: https://hackmd.io/@AO8Ceb4zScyJGk3uD6Tnhw/B1B-rsO9H

**Comment by yondonfu** [comment]
Closed by #1173
