### ISSUE TITLE
Add a ServiceRegistry event watcher

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1151]
**Is your feature request related to a problem? Please describe.**

Create a `ServiceURIWatcher` that watches for updates to an orchestrator's `serviceURI` through the `ServiceURIUpdate` event emitted by the `ServiceRegistry` contract. This event watcher will live in `eth/watchers`

**Describe the solution you'd like**
_a seperate ServiceRegistryWatcher is needed because `EventDecoder` can only deal with a single contract ABI in its current implementation._

`ServiceRegistryWatcher` watches for on-chain events emitted by the `ServiceRegistry` contract, in particular the `ServiceURIUpdate` event. 

```
type ServiceRegistryWatcher struct {
    db      *common.DB
    dec     *EventDecoder
    lpEth   eth.LivepeerEthClient
    quit    chan struct{}
}
```

#### Handling events

- Event added: update serviceURI in the DB for O with the `serviceURI` argument emitted by `ServiceURIUpdate` event
- Event removed: Make an RPC call to `ServiceRegistry.getServiceURI` for O and update the DB with the returned value

##### Watch

Start watching the `blockwatch` subscription for `ServiceURIUpdate` events

```
func (sw *ServiceRegistryWatcher) Watch() error
```

##### Stop

Unsubscribe from `ServiceURIUpdate` events propagated by `blockwatch` 

```
func (sw *ServiceRegistryWatcher) Stop()
```

**Additional context**
Full spec for active orchestrator set tracking: https://hackmd.io/@AO8Ceb4zScyJGk3uD6Tnhw/B1B-rsO9H

**Comment by yondonfu** [comment]
Closed by #1181
