### ISSUE TITLE
activeOrchCount SQL query

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1153]
**Is your feature request related to a problem? Please describe.**

Currently the orchestratorPool size for `DBOrchestratorPoolCache` is retrieved by first retrieving all URL's as a slice, then returning the length of the slice. 

Instead, with the updates to the DB in #1146, we can implement a new `activeOrchCount` query, which is then called from `DBOrchestratorPoolCache.Size()`

**Describe the solution you'd like**
Instead of fetching all orchestrator URL's from the database and getting the length of the returned slice, we can instead return a direct row count from an SQL query: 

```SELECT count(serviceURI) FROM orchestrators WHERE <filter>``` 

**Additional context**
Full spec for active orchestrator set tracking: https://hackmd.io/@AO8Ceb4zScyJGk3uD6Tnhw/B1B-rsO9H

**Comment by yondonfu** [comment]
Closed by #1180
