### ISSUE TITLE
Persist a Broadcaster's Transcoding Options between sessions

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1159]
**Is your feature request related to a problem? Please describe.**

Every time I restart my Broadcaster node, I have to set the Transcoding Options.

**Describe the solution you'd like**

For Transcoding Options to be persisted somewhere, so that if I restart my `-broadcaster` node, then I don't have to set the Transcoding Options again, because it would have stored my configuration from previous session.

If I want to change the Transcoding Options, I can do that via the cli.

**Describe alternatives you've considered**

To set the Transcoding Options every time I start the process. This is laborious, and makes testing not fun.

**Comment by j0sh** [comment]
Thanks @chrishobcroft  - this is a duplicate of a long-standing feature request https://github.com/livepeer/go-livepeer/issues/390 . Agree that it would be good to have.

**Comment by chrishobcroft** [comment]
OK, sure, but for the record, it's really painful trying to get the PM stuff working and having to set the Transcoding Options every time you restart the broadcaster.

**Comment by j0sh** [comment]
A workaround for now is to just start up the node with the `-transcodingOptions` flag. Putting this in a script is a handy way to quickly get a node up and running with your preferred configuration. Eg,

```
livepeer \
              -datadir datadirs/broadcaster \
              -orchAddr :8936 \
              -rtmpAddr 0.0.0.0 \
              -httpAddr 0.0.0.0 \
              -currentManifest -maxSessions 36 \
              -transcodingOptions P720p30fps16x9,P576p30fps16x9,P360p30fps16x9,P240p30fps16x9 \
              -broadcaster -v 99 2>&1 | tee bcast.log
```

**Comment by chrishobcroft** [comment]
Thank you very much for that, @j0sh
