### ISSUE TITLE
Allow changing of Transcoding Options during a stream

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1160]
**Is your feature request related to a problem? Please describe.**

As a Broadcaster, I am currently paying for Transcoding work, and nobody is watching the Transcoded content. This is a waste of my money.

**Describe the solution you'd like**

I would like to be able to start a stream without any Transcoding work being done, and then to request Transcoding as and when my viewers require it.

Also, if viewers which require transcoded content stop watching, I want to request that the Transcoding work stops.

**Describe alternatives you've considered**

To continue paying for Transcoding even if nobody is watching it, and to pay the cost of something which is of no value to me as a Broadcaster.

**Comment by hthillman** [comment]
This should be implemented at the application layer
