### ISSUE TITLE
Understand performance bottleneck in the transcoding cluster

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#1165]
We didn't observe CPU saturation, but we did observe resource constraint behaviors (transcoding took slower than real-time).

Things started out fine (transcoding was taking less than 2s), but after about a minute we observed segment lengths varying in the Wowza output.

For context - Martin was running on AWS in Frankfurt, our EU cluster is in the UK.

**Comment by ericxtang** [comment]
We discovered that Martin's issue was a bottleneck on the Wowza plugin (addressed by uploading segments in parallel).  

Next step here is to run concurrent streams with the Wowza plugin and see whether we are CPU bound in the transcoding cluster.  Ideally we should be able to push the CPU usage up to over 70%.

**Comment by j0sh** [comment]
Is this particular report still relevant?

**Comment by ericxtang** [comment]
Not relevant anymore because we are moving onto GPUs.  Closing.
