### ISSUE TITLE
livepeer_cli shows incorrect parameters for "Max Price Per Pixel"

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1168]
**Describe the bug**

In Broadcaster mode, the `Broadcaster Stats` shown on livepeer_cli displays the `Max Price Per Pixel` as e.g. `2000000 pixels / 1 wei` when it should be `2000000 wei / 1 pixel`.

**To Reproduce**

1. Run livepeer in `-broadcaster` mode and with `-network rinkeby`
2. Run livepeer_cli
3. Run the `Set broadcast config` command
4. Enter an amount of `99` pixels for 1 unit
5. Enter a maximum price to pay of `1234` wei for 1 unit
6. Run the `Get node status` command
7. See it printed that the Max Price Per Pixel is `1234 pixels / 99 wei`.

The units are the wrong way round.

**Expected behavior**

It should read `1234 wei / 99 pixels`, instead of `1234 pixels / 99 wei`.

**Screenshots**

![Screenshot from 2019-11-04 18-29-17](https://user-images.githubusercontent.com/2212651/68147024-160de300-ff31-11e9-95be-754b62a00289.png)

![Screenshot from 2019-11-04 18-29-26](https://user-images.githubusercontent.com/2212651/68147025-160de300-ff31-11e9-9a77-250e5113b1d4.png)

**Desktop (please complete the following information):**

```
ubuntu@ip-172-31-43-225:~$ ./livepeer_cli -version
livepeer-cli version 0.5.0
ubuntu@ip-172-31-43-225:~$ ./livepeer -version
Livepeer Node Version: 0.5.0
Golang runtime version: gc go1.13
Architecture: amd64
Operating system: linux
```

**Comment by yondonfu** [comment]
Closed by #1169
