### ISSUE TITLE
Balance synchronization problem when timing out for slow orchestrators

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1174]
**Describe the bug**

The default HTTP timeout is currently 8 seconds for requests sent by a broadcaster. Thus, if an orchestrator takes longer than 8 seconds to return a transcoded result, the HTTP timeout will be triggered and the broadcaster will retry the segment with a different orchestrator. However, the orchestrator is not aware of the HTTP timeout so it will finish transcoding the segment, debit the transcoding fees for the segment from the broadcaster's balance for the stream and then write the data to the still active connection with the broadcaster. This will result in the orchestrator having a different view of the stream balance than the broadcaster.

**To Reproduce**

This is a problem in the following scenario:

Let `balance_b` be the broadcaster's view of the stream balance.
Let `balance_o` be the orchestrator's view of the stream balance.
Let X be the minimum credit requirement for the orchestrator - it will not transcode a segment unless the stream balance is at least X.

1. Broadcaster submits segment 0 with a payment worth X to the orchestrator. At this point, `balance_b = X`
2. After the orchestrator receives the segment and payment, `balance_o = X`
3. The HTTP timeout is triggered because the broadcaster did not receive a response from the orchestrator within 8 seconds
4. At this point, `balance_b = 0` because the broadcaster considers any existing credit to have been spent when it does not receive a result from the orchestrator
5. Orchestrator finishes transcoding segment 0 and debits the transcoding fees `Y` where `Y > X`. Now, `balance_o < 0`
6. Broadcaster is only aware of this orchestrator so it retries segment 0 with the same orchestrator. It sends segment 0 with a payment worth X to the orchestrator. At this point `balance_b = X`
7. After the orchestrator receives the segment and payment, `0 < balance_o < X`. Since `balance_o < X`, the orchestrator returns an insufficient balance error

**Expected behavior**

The broadcaster should not encounter an insufficient balance error in the above scenario

**Screenshots**

Orchestrator logs:
![Screen Shot 2019-11-06 at 11 32 11 AM](https://user-images.githubusercontent.com/5933273/68317478-32249800-0089-11ea-9af6-4d0b3d399cd8.png)

Broadcaster logs:
![Screen Shot 2019-11-06 at 11 32 23 AM](https://user-images.githubusercontent.com/5933273/68317465-2a64f380-0089-11ea-917e-88b1c4e20204.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by yondonfu** [comment]
The main problem here is that the orchestrator does not know that the broadcaster is no longer listening for the result due to the HTTP timeout and the orchestrator still debits the transcoding fees from its view of the stream balance, but the broadcaster is unable to debit the transcoding fees from its view of the stream balance since it never receives the result.

An initial stab at a solution is to have the broadcaster include a `timeout` field in the request to the orchestrator. The default value for `timeout` could be the HTTP timeout or it could be the maximum transcode latency. If the orchestrator finishes transcoding within `timeout`, it will debit the transcoding fees from its view of the stream balance. If the orchestrator fails to finish transcoding within `timeout`, it will not debit the transcoding fees from its view of the stream balance because it did not meet the `timeout` requirement dictated by the broadcaster and the broadcaster is no longer listening for the result.

**Comment by j0sh** [comment]
Note that if a HTTP timeout occurs, then the B will evict the O from its working set. It's only after an O refresh that the O *may* be re-added back to the working set. Presumably we hit this issue when that happens within some TTL such that the stream balance isn't cleared on both sides.

If there's a balance mismatch, the O could state its balance, with the B attempting a reconcilation, eg accepting the O's view of the balance, assuming it is within a reasonable interval (1-2 tickets worth).

We've had a number of related issues around balance synchronization ( https://github.com/livepeer/go-livepeer/issues/1174 , https://github.com/livepeer/go-livepeer/issues/1129 , https://github.com/livepeer/go-livepeer/issues/1079 ). One solution to most of these is to maintain a separate "manifestID" per O. This "manifestID" would simply correspond to a session identifier that gets generated per O at session refresh time. This solves a number of issues:

* Re-connecting to previously evicted Os would get a new session ID
* Connecting to multiple Os, each get a separate session ID

This further emphasizes the distinction between the user-visible "stream name" and the internal identifiers that the manifestID is being appropriated for.  Related: https://github.com/livepeer/go-livepeer/issues/695 , https://github.com/livepeer/go-livepeer/issues/871

Generating a new session ID per O "connection" still has a flaw in "resetting" negative balances by starting a new session to wipe out debt. There may be approaches around that, eg front-loading the minimum credit for a new session by 2-3x, such that the B has an incentive to continue reusing existing sessions, rather than overpaying for each new session. That is - an O has a minimum credit of X, but a new session must start off with a credit of 2X before the O will process any work. This could still break down if the transcode job is especially "heavy", but I believe that's a weakness inherent to the current system, absent solutions such as https://github.com/livepeer/lpms/issues/129 . The minimum credit could also be adjusted per-B based on the most expensive segment the O has processed for that B so far, globally across all streams from the B.

**Comment by yondonfu** [comment]
> Presumably we hit this issue when that happens within some TTL such that the stream balance isn't cleared on both sides.

Yep the scenario was that B directly connected to O (using the `-orchAddr` flag) so the O was the only one in the working set. After the HTTP timeout, the working set was refreshed and a subsequent segment was sent to O within the TTL so B & O's view of the stream balance was out of sync.

> If there's a balance mismatch, the O could state its balance, with the B attempting a reconcilation, eg accepting the O's view of the balance, assuming it is within a reasonable interval (1-2 tickets worth).

At the moment, the problem with balance reconciliation is that O's view of the balance can be quite different from B's view of the balance if B has not received the transcoded result for its most recent segment. In this case, O would have debited the transcoding fee from its view of the stream balance, but B would not have done so. If the configured ticket EV is low, then the difference between B's view of the balance (prior to debiting the transcoding fee) and O's view of the balance (after debiting the transcoding fee) can be many multiples of the ticket EV. For example:

1. `ticketEV = 1 gwei`
2. B's view of the balance = 1 gwei
3. O's view of the balance = 1 gwei
4. O transcodes a segment with `transcodingFee = 1280 * 720 * 30 * 2 * 50000000 = 2764800 gwei`
5. B disconnects so it does not receive the transcoded result

At this point:
- B's view of the balance = 1 gwei
- O's view of the balance = -2764799 gwei

This problem can be addressed if the B uses an estimate of the transcoding fee in order to determine the # of tickets to send to O. In the example, B could estimate the transcoding fee to be 2764800 gwei (we can apply a small multiplier here to be safe if needed) and calculate that it needs to send 2764800 / 1 = 2764800 tickets. Initially we would just be estimating the encoding fee since the transcoding fee = the encoding fee, but if we implement livepeer/lpms#139, the transcoding fee = the encoding fee + the decoding fee so we can estimate the decoding fee as well.

If B sends tickets based on an estimated transcoding fee AND O implements livepeer/lpms#129 sessions should never have debt - they could only have a small amount of credit if B overpaid O for a segment. B would have an incentive to reuse existing sessions in order to take advantage of leftover credit from a previous payment.

> This further emphasizes the distinction between the user-visible "stream name" and the internal identifiers that the manifestID is being appropriated for

I think we definitely need a fix for #695 (maybe just the proposed solution!) to patch the current vulnerabilities around manifestID collisions. However, a fresh sessionID in the case where B connects with a O that it previously worked prior to clearing its view of the stream balance seems less useful if B sends tickets based on estimated transcoding fee and O implements livepeer/lpms#129 since there would never be debt for sessions. Thus, even if B & O's view of the stream balance is out of sync, in this scenario, B would be sending tickets based on a stream balance of 0 and O would be receiving tickets based on a stream balance > 0. B would be overpaying since it has existing credit, but it would not encounter an insufficient balance error.

Based on these thoughts, I'm current inclined to add encoding fee estimation for the broadcaster and the immediate first step to addressing this balance synchronization issue.

**Comment by j0sh** [comment]
Agreed that https://github.com/livepeer/lpms/issues/139 paired with https://github.com/livepeer/lpms/issues/129 would be a better way to prevent this type of issue.

We can implement a workaround for the missing fps as described in https://github.com/livepeer/lpms/issues/139 by hard-coding the input framerate to 60fps or something. That should over-estimate for the typical case. The resolution *should* be generally available as well, but it'll fall apart if the resolution changes mid-stream. All this can be done in go-livepeer today without LPMS changes, as a stopgap to a more complete solution.

**Comment by yondonfu** [comment]
So, the immediate next step is to implement encoding fee estimation which can look something like this:

```
func estimateFee(seg *stream.HLSSegment, outProfiles []ffmpeg.VideoProfile, priceInfo *big.Rat) (*big.Rat, error) {
    // TODO: Estimate the number of input pixels
    var outPixels int64
    for _, p := range outProfiles {
        // Add width * height * framerate * seg.Duration
        outPixels += ...
    }

    feeEstimate := new(big.Rat).Mul(new(big.Rat).SetInt64(outPixels), priceInfo)
    // Multiply the estimate by a constant factor to make sure we never underpay
    factor := big.NewRat(102, 100)

    return feeEstimate.Mul(feeEstimate, factor), nil
}
```

The output of `estimateFee()` can be passed as an argument to [newBalanceUpdate()](https://github.com/livepeer/go-livepeer/blob/master/server/segment_rpc.go#L487) which will calculate the # of tickets needed to cover the estimated fee.

We can wait to incorporate decoding fees into the logic of `estimateFee()` until we decide to add decoding costs to the accounting workflow of both B & O.
