### ISSUE TITLE
Improve logging on "Could not create payment: ticket faceValue higher than max faceValue"

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1177]
**Is your feature request related to a problem? Please describe.**

I'm trying to set up the parameters for PM, and I'm hitting an error `Could not create payment: ticket faceValue higher than max faceValue`.

I am aware of [the notes in the documentation about how to resolve this issue](https://livepeer.readthedocs.io/en/latest/streamflow-public-testnet.html#broadcasting-video), but it would be really helpful if the error logging could be more informative - in order to help expose some of the inner workings of the PM setup.

This issue is related to https://github.com/livepeer/go-livepeer/issues/1176

**Describe the solution you'd like**

It would really help to log the values of the `ticket faceValue` and `max faceValue` that are being compared, so that a user can understand how far off they are.

`Could not create payment: ticket faceValue = 123456789 higher than max faceValue = 123456788`.

In addition, in general, it would be really useful to expose the parameters being used to "govern" the PM parameters, to help users to know what's going on "under the hood", and thus allow them to understand via their own worked examples.

**Describe alternatives you've considered**

Showing some of the static node-specific PM parameters in the `livepeer_cli` could be an effective way of shedding some light on what's going on inside these nodes.

For example, a section which shows the `max faceValue` and other metrics used to calculate the ticket parameters, and to govern what is and is not allowed.

**Additional context**

None.

**Comment by chrishobcroft** [comment]
Case in point, I'm starting a B with the following command:
```
./livepeer
-broadcaster
-rtmpAddr 0.0.0.0
-httpAddr 0.0.0.0
-currentManifest
-network rinkeby
-orchAddr https://52.29.226.43:8935
-transcodingOptions P720p30fps16x9
-depositMultiplier 1
-maxPricePerUnit 60000000
-pixelsPerUnit 1
-maxTicketEV 100000000000000000000000000000000000000000000000
```
and I'm seeing an error of `Could not create payment: ticket faceValue higher than max faceValue
`.

I'm very interested to know what the `ticket faceValue` is in this case, and if it really is higher than `100000000000000000000000000000000000000000000000`.

Logs attached.

[broadcaster_2019-11-07.log](https://github.com/livepeer/go-livepeer/files/3819632/broadcaster_2019-11-07.log)
[orchestrator_2019-11-07.log](https://github.com/livepeer/go-livepeer/files/3819633/orchestrator_2019-11-07.log)

**Comment by yondonfu** [comment]
@chrishobcroft Thanks for providing the logs!

In the scenario documented by the logs, we know the following:

- The broadcaster sends a ticket with EV = 1 gwei and faceValue = 10000000 gwei
- Before the orchestrator transcodes segment 0, the stream balance is 1 gwei
- We can approximate the transcoding fee for a single segment as:

```
1280 (output width) * 720 (output height) * 30 (FPS) * 2 (duration) * 50000000 (price per pixel) = 2764800000000000 wei = 2764800 gwei
```
- After the orchestrator transcodes segment 0, the stream balance is:

```
1 gwei - 2764800 gwei = -2764799 gwei
```

- The broadcaster calculates the # of tickets it needs to send with the next segment as follows:

```
abs(-2764799 gwei / 1 gwei) + 1 = 2764800 tickets
```

if the broadcaster sends 2764800 tickets with its next segment, then stream balance will be set to 1 gwei again

At the moment, the `ticket faceValue higher than max faceValue` appears when the *sum* of the faceValues of each ticket to be sent with a segment exceeds the max faceValue where the max faceValue is determined by dividing the broadcaster's current deposit by `depositMultiplier`. So, in this scenario, the sum of the faceValues of each ticket to be sent with the segment is:

```
2764800 * 10000000 gwei = 27648 ETH
```

This number is huge and is clearly larger than the broadcaster's current max faceValue.

#1179 should help with this.
