### ISSUE TITLE
Invalid ticket creation round when starting a broadcaster after being offline for awhile

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1187]
**Describe the bug**

When starting a broadcaster up after being offline for awhile, the broadcaster encountered consecutive payment related errors when submitting segments to an orchestrator. The orchestrator logged the following error repeatedly:

```
Error receiving ticket manifestID=f recipientRandHash=5638662d577dbb78d15bf3698feee72a42b3034c1fdc3d26d9e942de88790791 senderNonce=1: invalid ticket creation round
```

It is possible that the broadcaster and orchestrator's views of the current round were different for some reason.

**Screenshots**

Orchestrator logs:
![Screen Shot 2019-11-11 at 3 05 05 PM](https://user-images.githubusercontent.com/5933273/68617186-b82f4d00-0494-11ea-8f6b-c048bd95c286.png)

Broadcaster logs:
![Screen Shot 2019-11-11 at 3 05 27 PM](https://user-images.githubusercontent.com/5933273/68617201-bfeef180-0494-11ea-80ab-4ccabc0a4f34.png)

**Comment by kyriediculous** [comment]
`RoundsWatcher` will query a remote ethereum node for the last initialized round number and blockhash when `RoundsWatcher.Watch()` is started. The only way I can see these values getting out of sync between B and O is if (a) the remote ethereum node is out of sync , (b) O has an out of date view of the current round due to not correctly processing a `NewRound` event.

Do you remember if this bug occured on rinkeby or internal test net?

**Comment by yondonfu** [comment]
> Do you remember if this bug occured on rinkeby or internal test net?

This was on Rinkeby.

**Comment by criticaltv** [comment]
I am seeing this again today on Rinkeby. Transcoding is still happening.

```
E0121 12:37:55.191638    2408 orchestrator.go:177] Error receiving ticket manifestID=hello_world recipientRandHash=9d5a0e27b1a5ead14998ac696bca492c4c2238ac706b90ae490f2dd48ec553fb senderNonce=4: invalid ticket creation round
I0121 12:37:55.191668    2408 orchestrator.go:168] Receiving ticket manifestID=hello_world faceValue=10000000000000000 winProb=0.1000000000 ev=1000000000000000.00
```

I started nodes with these commands:

Orchestrator:
```
./livepeer-linux-amd64/livepeer -network rinkeby -orchestrator -cliAddr 127.0.0.1:7936 -httpAddr 127.0.0.1:8936 -serviceAddr 127.0.0.1:8936 -pricePerUnit 2000000000 -pixelsPerUnit 1 -ticketEV 1000000000000000 -orchSecret secret -v 99
```
Transcoder:
```
./livepeer-linux-amd64/livepeer -network rinkeby -transcoder -orchAddr 127.0.0.1:8936 -cliAddr 127.0.0.1:7937 -httpAddr 127.0.0.1:8937 -orchSecret secret -maxSessions 1 -v 99
```
Broadcaster:
```
./livepeer-linux-amd64/livepeer -network rinkeby -broadcaster -cliAddr 127.0.0.1:7935 -rtmpAddr 127.0.0.1:1935 -httpAddr 0.0.0.0:8935 -orchAddr 127.0.0.1:8936 -transcodingOptions P144p30fps16x9 -depositMultiplier 1 -maxPricePerUnit 5000000000 -pixelsPerUnit 1 -maxTicketEV 1000000000000000000 -v 99
```
Publisher:
```
ffmpeg -re -f lavfi -i testsrc=size=256x144:rate=30,format=yuv420p -f lavfi -i sine -threads 1 -c:v libx264 -b:v 1000k -preset ultrafast -x264-params keyint=30 -strict -2 -c:a aac -f flv rtmp://127.0.0.1:1935/hello_world
```

Here is the BROADCASTER STATS from `livepeer_cli`:

```
+-----------------+
|BROADCASTER STATS|
+-----------------+
*-------------------------------*---------------------------*
|           Max Price Per Pixel | 5000000000 wei / 1 pixels |
*-------------------------------*---------------------------*
| Broadcast Transcoding Options |            P144p30fps16x9 |
*-------------------------------*---------------------------*
|                       Deposit |                     0 WEI |
*-------------------------------*---------------------------*
|                       Reserve |  1.417722740055137366 ETH |
*-------------------------------*---------------------------*
```
```

```

**Comment by criticaltv** [comment]
I am observing this "on a loop" on my O right now:

```
I0314 10:59:14.087832    3867 orchestrator.go:172] Receiving ticket manifestID=hello_world faceValue=0.01 ETH winProb=0.1000000000 ev=1000000000000000.00
E0314 10:59:14.088131    3867 orchestrator.go:180] Error receiving ticket manifestID=hello_world recipientRandHash=99594579fbb9307dc01a0becd825ab7e0b68fb26fd9b985e51f9aa4dbc3878cc senderNonce=1: invalid ticket creation round
E0314 10:59:14.088155    3867 segment_rpc.go:70] error processing payment: invalid ticket creation round
```

Transcoding is happening, but no winning tickets had been cashed for 16 hours (prior to this, they were coming ~2-3 every minute). Broadcast deposit was ~30 ETH and reserve ~4 ETH.

So... then I restarted the O, and experienced this issue: https://github.com/livepeer/go-livepeer/issues/1420

So then I stopped streaming into the B, restarted the O, waited for a T to register, and then started streaming again into the B again.

Now the O is receiving tickets again, transcoding is happening, and winning tickets being redeemed again ~2-3 every minute.

**Comment by kyriediculous** [comment]
Not sure what you mean with "on a loop" as this is not looped, could you elaborate ?

This issue has been on my radar though and definitely not forgotten. 

In the meantime could you try decreasing your blockPollingInterval ? This defaults to 5 seconds and rinkeby blocktime is also 5 seconds which could lead to sync issues between O and B in terms of last block viewed for brief periods of time. 

I think the Potential  fix I’ve discussed with @yondonfu is to have the orchestrator send an expected creation round along with the TicketParams to B. This would make B not dependent on it’s own last seen block to generate valid tickets adding protocol certainty for B that if it uses the expected creation round that an O provides it will not encounter this error and avoid disruption of transcoding.

**Comment by criticaltv** [comment]
The same things was being printed out in the logs again and again and again and again and again...

**Comment by criticaltv** [comment]
How do I decrease my block polling interval?

**Comment by kyriediculous** [comment]
-blockPollingInterval flag on node startup

Op za 14 mrt. 2020 om 15:26 schreef criticaltv <notifications@github.com>

**Comment by criticaltv** [comment]
I set it at `-blockPollingInterval 2` and same thing happened

```
I0315 18:49:47.622958   21350 gaspricemonitor.go:134] Cached gas price: 1000000000
I0315 18:49:47.908291   21350 orchestrator.go:172] Receiving ticket manifestID=hello_world faceValue=0.01 ETH winProb=0.1000000000 ev=1000000000000000.00
E0315 18:49:47.908575   21350 orchestrator.go:180] Error receiving ticket manifestID=hello_world recipientRandHash=69f5d1e58b2c8aab4be07c7b8eec15ac7ce7c4ae76b43cbf138e3a1a1f60cd5b senderNonce=1: invalid ticket creation round
E0315 18:49:47.908593   21350 segment_rpc.go:70] error processing payment: invalid ticket creation round
```
