### ISSUE TITLE
Investigate Prometheus Volume Filling Up

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#1190]
Prometheus volume filled up 5G of data within a 5 days.  Let's look into why this is, and make a decision on whether we should cut down on the things we log, or maintain a much larger disk.

**Comment by darkdarkdragon** [comment]
Another option - use another DB for long term storage, like [here](https://www.percona.com/live/e17/sessions/using-prometheus-with-influxdb-for-metrics-storage)

Also [here](https://dev.to/mhausenblas/revisiting-promcon-2018-panel-on-prometheus-long-term-storage-5f1p) is the list of possible options.
