### ISSUE TITLE
Add "transfer" function to livepeer_cli

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#120]
This way the CLI can begin to serve as a Livepeer wallet, and let you transfer token to other addresses. It should probably ask who you'd like to transfer to, and how many LPT you'd like to transfer.

**Comment by ericxtang** [comment]
To do this, we need to:
* Add a "Transfer" function in the eth.client (make sure to add to the StubClient).  This talks to the smart contract.
* Add a "transfer" endpoint in the webserver, so the CLI can call it
* Add a "Transfer test Livepeer Token" in the cli (after "become a transcoder")
* Make sure all the tests still pass by running `bash test.sh` in the project root

**Comment by yondonfu** [comment]
Added in #260
