### ISSUE TITLE
Orchestrator should check if it is active before accepting work

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1202]
**Is your feature request related to a problem? Please describe.**

At the moment, an orchestrator will accept segments/payments even if it is not in the active set during the current round. A non-active orchestrator will not be able to draw from a broadcaster's reserve in the event that the broadcaster's deposit is insufficient to cover all of the winning tickets that it has sent out.

**Describe the solution you'd like**

An orchestrator should check if it is active in the current round before accepting segments/payments. If the orchestrator is not active it should reject segments/payments. The orchestrator operator should be able to override this behavior and accept segments/payments from certain broadcasters even if the orchestrator is not active (which is useful for testing). The orchestrator could accept an allow list of broadcaster ETH addresses.

**Comment by kyriediculous** [comment]
>  If the orchestrator is not active it should reject segments/payments. The orchestrator operator should be able to override this behavior and accept segments/payments from certain broadcasters even if the orchestrator is not active (which is useful for testing).

We can add a flag `-bcastWhitelist` that takes in an array of addresses (or we can start with a single address for simplicity). We can add this whitelist to `Orchestrator`

We can then start `DBOrchestratorPool` on the Orchestrator as well (stored on `LivepeerNode`. We can then call `pool.Size()` in `orchestrator.ProcessPayment` (can create an unexported helper), this should return `1` if O is active and `0` is O is inactive. If O is inactive we can check if `payment.Sender` is contained in `orchestrator.bcastTestList`.

This means though that an O can spin up his node for testing purposes but ideally though to run in production beyond initial testing the node should be restarted without `bcastWhitelist` flag. 

If it were the case that in the future we do want O to have information on all other O's or wants to expand its `OrchestratorWatcher` addressFilter, we can always add a `pool.Contains(address)` method, but that seems premature for now.

**Comment by yondonfu** [comment]
> The orchestrator operator should be able to override this behavior and accept segments/payments from certain broadcasters even if the orchestrator is not active (which is useful for testing)

Thought about this a bit and I think it would be better to not add support for overriding this behavior for now.

If O is not active in the current round, then the contract state variable [earningsPool.claimableStake](https://github.com/livepeer/protocol/blob/streamflow/contracts/bonding/libraries/EarningsPool.sol#L23) might be 0. Fee shares are calculated by allocating a fixed amount to O based on its on-chain `feeShare` rate and allocating the rest to O's delegators with each delegator getting an amount proportional to its stake relative to `earningsPool.claimableStake` for the round. So, if `earningsPool.claimableStake = 0`, then every delegator (including O as a self-delegated delegator) will get 0. Thus, O would need to set its `feeShare` to 0% in order to make sure that fees that it sends to itself from its own B can be withdrawn from the contract later on. Otherwise, if the `feeShare` is greater than 0%, then O will not be able to withdraw `100% - feeShare` of the fees.

I think the benefits of having O always checking if it is active before accepting work and not supporting overrides of this behavior as:

- O does not need to worry about setting its `feeShare` to 0% when testing its transcoding setup and then setting its `feeShare` to something else once it becomes active - it just needs to set its `feeShare` once during initial setup
- No additional impl for a whitelist

The downsides of this approach are:

- O will have to wait until its activation round in order to test its transcoding setup

While the downside is not ideal, I think it is preferable to exposing O to the requirements around setting `feeShare` in order to test its transcoding setup.

**Comment by kyriediculous** [comment]
I just finished the implementation , but I'll check out a new branch and remove it (that way I don't lose the work I did on a `bcastTestList`). 

Or what do you think of making this behaviour only accesible for rinkeby where the value not being able to be withdrawn doesn't matter? This gives O the ability to check his setup in an on-chain environment not too different from mainnet. https://github.com/livepeer/go-livepeer/tree/nv/o-active-check

**Comment by yondonfu** [comment]
> Or what do you think of making this behaviour only accesible for rinkeby where the value not being able to be withdrawn doesn't matter? This gives O the ability to check his setup in an on-chain environment not too different from mainnet.

Let's avoid adding special case logic for a network allowing funds to be stuck even if it is on a testnet. O will still be able to check its transcoding setup - it will just need to wait until its activation round (the wait will be shorter on Rinkeby vs. mainnet due to the different in round length).
