### ISSUE TITLE
Cache stake of all active orchestrators at when a new round is initialized

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1213]
**Is your feature request related to a problem? Please describe.**

The stake of active orchestrators will be used in selection. Instead, of querying for the stake of an active orchestrator every time we need it, we can cache the stake of all active orchestrators when a new round is initialized because the stake of an active orchestrator is locked in for the duration of a round when it is initialized. 

**Describe the solution you'd like**

- [ ] Add a `stake` column to the `orchestrators` table in the DB
- [ ] When a new round is initialized, fetch all the active orchestrators from the DB, iterate through each of them and write their stake for the round to the DB
    - The DB caching logic can be placed in `watchers.OrchestratorWatcher` which is already responsible for updating the DB based on on-chain activation/deactivation events
    - We can subscribe to new round initialization events using `watchers.RoundsWatcher.Subscribe()`
    - For each active orchestrator in the DB, we can call `LivepeerEthClient.GetTranscoderEarningsPoolForRound()` using the orchestrator's address and the current round. The struct returned by this method will include a `totalStake` field that will represent the orchestrator's stake for the round

**Comment by kyriediculous** [comment]
Considering we did a go-livepeer 0.5.0 release, is database versioning a concern for this issue? 

Secondly I assume we want to store stake as a `string` rather than an `int64` ?

**Comment by kyriediculous** [comment]
The current PR submitted for this issue caches stake when a new round is initialized.

It seems to me however that we'd also want to cache stake when we cache orchestrators in `DBOrchestratorPoolCache` ? Should we address this as part of the scope for this issue?

**Comment by yondonfu** [comment]
I think it’s fine to not worry about database versioning/migrations until
we get to a mainnet compatible release.

Good point about caching the stake of active Os when
DBOrchestratorPoolCache is created - we need to make sure that if the node
starts in the middle of a round that the stake cached for active Os is
accurate. Let’s also cache the stake of active Os when
DBOrchestratorPoolCache is created.

**Comment by kyriediculous** [comment]
May I suggest we first merge #1182 as that changes/moves quite a bit of the
caching logic. We can then rebase this PR and add caching stake on node
startup. That seems like the easiest route.
