### ISSUE TITLE
Confirm readthedocs instructions for running on testnet works for running on GPUs

### ISSUE THREAD

**Issue by mk-livepeer** [livepeer/go-livepeer#1221]
The following instructions have been confirmed to work with CPU transcoders at one point.

Now, we must confirm that the same instructions apply to GPU transcoding rigs:

https://livepeer.readthedocs.io/en/latest/streamflow-public-testnet.html

**Comment by mkrufky** [comment]
I had some trouble with the ReadTheDocs instructions, but they had nothing to do with the fact that I was using GPUs.  See #streamflow-protocol discord channel for more info.

I think we need to idiot-proof these instructions and make sure newbies can follow along without trouble.

I confirm that the procedure does indeed work when running with GPUs.

**Comment by mkrufky** [comment]
I had some trouble with the ReadTheDocs instructions, but they had nothing to do with the fact that I was using GPUs.  See #streamflow-protocol discord channel for more info.

I think we need to idiot-proof these instructions and make sure newbies can follow along without trouble.

Apart from that, I confirm that the procedure does indeed work when running with GPUs.

**Comment by mkrufky** [comment]
We should mention that when building from source, set the HIGHEST_CHAIN_TAG flag, like so:
```
HIGHEST_CHAIN_TAG=rinkeby make livepeer
```
Some say that users will always use a pre-built binary, but I believe that we'll find otherwise when it comes to GPU rig builds.

**Comment by mkrufky** [comment]
We should mention that the orchestrator might need to set `-serviceAddr` and explain why / how.

**Comment by mkrufky** [comment]
I don't think the document describes the need to be part of the active set, and how to do so.  I lucked out due to https://github.com/livepeer/go-livepeer/issues/1202

**Comment by mkrufky** [comment]
Also might be a good idea to mention the verbosity `-v` flag, so that users can see some evidence that things are actually working when they try things out for the first time.

**Comment by yondonfu** [comment]
> We should mention that when building from source, set the HIGHEST_CHAIN_TAG flag

Tracking in #1244 

> I don't think the document describes the need to be part of the active set, and how to do so.

This is described in [this section](https://github.com/livepeer/docs/blob/master/docs/source/streamflow-public-testnet.md#activation), but perhaps we can make the description clearer/more concise.

livepeer/docs#49 also adds a note in the docs about the active requirement when testing your transcoding setup.
