### ISSUE TITLE
Translate readthedocs instructions to bot-miner-setup instructions for b/o/t setup for host system install

### ISSUE THREAD

**Issue by mk-livepeer** [livepeer/go-livepeer#1222]
After confirming that https://livepeer.readthedocs.io/en/latest/streamflow-public-testnet.html works for GPU-based transcoding rigs, create a section in https://github.com/livepeer/bot-miner-setup that will allow the user to setup a b/o/t network using the testnet.

**Comment by mkrufky** [comment]
It looks like the compile-time option, `HIGHEST_CHAIN_TAG=rinkeby`, is not enabled in the docker image:
```
orchestrator_1  | I1204 21:00:18.864900       1 livepeer.go:199] ***Livepeer is running on the rinkeby network: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea***
orchestrator_1  | E1204 21:00:19.189303       1 livepeer.go:332] node does not support chainID = 4 right now
```

Apparently, CI attempts to pass the environment variable here:
https://github.com/livepeer/go-livepeer/blob/master/.circleci/config.yml#L22

...but this is not going to work.  It either must be passed in via command line and the Dockerfile must be changed to expect it, or it should be set within the Dockerfile itself.

I think it would be better to simply enable it by default in the Makefile
