### ISSUE TITLE
Translate readthedocs instructions to bot-miner-setup instructions for docker-compose based b/o/t setup

### ISSUE THREAD

**Issue by mk-livepeer** [livepeer/go-livepeer#1223]
After confirming that https://livepeer.readthedocs.io/en/latest/streamflow-public-testnet.html works for GPU-based transcoding rigs, create a section in https://github.com/livepeer/bot-miner-setup that will allow the user to setup a b/o/t network using the testnet via docker-compose.

**Comment by mkrufky** [comment]
It looks like the compile-time option, `HIGHEST_CHAIN_TAG=rinkeby`, is not enabled in the docker image:
```
orchestrator_1  | I1204 21:00:18.864900       1 livepeer.go:199] ***Livepeer is running on the rinkeby network: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea***
orchestrator_1  | E1204 21:00:19.189303       1 livepeer.go:332] node does not support chainID = 4 right now
```

Apparently, CI attempts to pass the environment variable here:
https://github.com/livepeer/go-livepeer/blob/master/.circleci/config.yml#L22

...but this is not going to work.  It either must be passed in via command line and the Dockerfile must be changed to expect it, or it should be set within the Dockerfile itself.

I think it would be better to simply enable it by default in the Makefile

**Comment by yondonfu** [comment]
Summary from Discord discussion:

We should be able to modify the Dockerfile to be aware of the `HIGHEST_CHAIN_TAG` env var and then pass in the env var as a build argument in the CI config. Something like:

`docker/Dockerfile.build`:

```
ARG HIGHEST_CHAN_TAG
ENV HIGHEST_CHAIN_TAG $HIGHEST_CHAIN_TAG
```

`.circleci/config.yml`:

```
docker build -t livepeerci/build:latest --cache-from=livepeerci/build:latest --build-arg HIGHEST_CHAIN_TAG -f docker/Dockerfile.build .
```

**Comment by mk-livepeer** [comment]
You missed a detail :-P

In addition to the `ARG` and `ENV` lines, the build line also needs to change within the docker file, like so:
```
RUN HIGHEST_CHAIN_TAG=${HIGHEST_CHAIN_TAG} make livepeer livepeer_cli
```
I created https://github.com/livepeer/go-livepeer/issues/1246 to capture this, and propose a solution in PR: https://github.com/livepeer/go-livepeer/pull/1248

**Comment by j0sh** [comment]
Note that this means we need to ensure compatibility with Rinkeby on master. As soon as we break compatibility, this option needs to be disabled.

FWIW, I'm inclined to leave things as default offchain and just explicitly enable $network for formal releases when we know things are compatible at that point. But I'll leave that up to you guys.

**Comment by mk-livepeer** [comment]
We need to enable Rinkeby testnet in the docker image in order to get things moving for people today.

To address @j0sh 's comment, we could simply add a new build target.  We could have a Rinkeby image and a main net image.

Meanwhile, why are we doing this to ourselves?  This should be a RUNTIME option rather than a compile time option.

**Comment by j0sh** [comment]
> This should be a RUNTIME option rather than a compile time option.

Which network to use is run time option; the compiler option simply prevents people from connecting to unsupported networks. The alternative would be to manually adjust the code for network checking every time we re-add or (break!) support for a given network. Related: https://github.com/livepeer/go-livepeer/issues/1092
