### ISSUE TITLE
Close RTMP connection when sender validation fails

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1247]
**Is your feature request related to a problem? Please describe.**

#1212 removes any checks pertaining to an on-chain setup and introduces new sender validation logic, these validations for `pm.Sender` are however not ran anymore until an RTMP connection is already established. 

If these sender validation checks end up failing mid-stream we will currently not terminate the RTMP connection but always retry segments instead  and do not propagate/handle errors from `transcodeSegment()`. To properly propagate errors and close RMPT connections when validation checks fail we can introduce a non-retryable error. If a non-retryable error, such as failing sender validation checks), is encountered then the error would be propagated from `transcodeSegment()` up to the caller of `processSegment()` which can then close the RTMP connection to alert the user. Prior to the introduction of a non-retryable error, B would just keep logging errors from sender validation as it continually retries segments (without actually submitting the segments).

**Additional context**
See the original discussion outlining the problem [here](https://github.com/livepeer/go-livepeer/pull/1212#discussion_r352184948)

**Outline**

1. We can introduce a `NonRetryableTranscodeError` type to wrap possible returned errors inside of `server.transcodeSegment()`

```
type NonRetryableTranscodeError struct {
 error
}
```

2. Wrap errors in `SubmitSegment` and `transcodeSegment` that would cause segments to fail to be transcoded , regardless of the orchestrator used, in a `NonRetryableTranscodeError`

3. In `processSegment` we can do a type assertion for the error returned , if this is of type `NonRetryableTranscodeError` we can break out of the retry loop and call `cxn.Stream.Close()` to close the RTMP connection. 

```
func processSegment(cxn *rtmpConnection, seg *stream.HLSSegment) error {
    ... 

	for {
		// if fails, retry; rudimentary
                err := transcodeSegment(cxn, seg, name);
                 if err == nil { return nil }
		if _, ok := err.(NonRetryableTranscodeError); ok {
                   cxn.stream.Close()
                   return err
                }
	}
}
```
```

**Comment by yondonfu** [comment]
Closed by #1318
