### ISSUE TITLE
add support for encoding chainID in pm ticket 'auxData'

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1255]
**Is your feature request related to a problem? Please describe.**

https://github.com/livepeer/protocol/issues/366 will introduce `chainID`  validation for pm tickets to prevent cross-chain replay attacks whereby a message signed off-chain could be re-used on a different chain if the same keys are used.

Since this check is required we need to add support to the livepeer node for encoding the `chainID` in the `auxData` field for pm tickets. 

**Describe the solution you'd like**
We can query the chainID when starting the node and store it  (unexported) on `pm.Sender` when instantiating it. 

Then we can add it as an argument to `pm.NewTicket()` which we call in `Sender.CreateTicketBatch()`. 

In `Ticket.AuxData()` we can then encode the chainID at the end of the slice.

**Describe alternatives you've considered**

**Additional context**
[EIP1344](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1344.md)

**Comment by hthillman** [comment]
closing pending payment protocol work
