### ISSUE TITLE
Accept Ethereum passphrase via file on disk rather than command line

### ISSUE THREAD

**Issue by mk-livepeer** [livepeer/go-livepeer#1256]
When bringing up a nodes on an actual network, `-ethPassword` can be specified on the command line to supply the Ethereum account's passphrase and allow unattended startup and operations.  This works for now, but it is very insecure.  A attacker can compromise a system, run `ps aux` and then see all command lines, including the go-livepeer command line containing the Ethereum passphrase in clear text.

We should consider adding alternate solutions such as a text file, for the future.  A text file can have permissions set to only allow the appropriate user access to it.

Both GETH and PARITY give the user a command-line option to specify a file that contains password(s) for one or more Ethereum account.  We should do the same.

I also think we should remove the cleartext passphrase on the command line option, but first thing's first.  We can start by supporting both but from a single command line argument.  If we can fstat the file, then we read it for the passphrase.  If we can't fstat it, then we assume its a cleartext passphrase.

**Comment by j0sh** [comment]
Similarly, this would also be a good idea for the `-orchSecret` option which is also currently visible via CLI flags.

**Comment by darkdarkdragon** [comment]
We could just integrate this library `github.com/peterbourgon/ff`, like I did [here](https://github.com/livepeer/go-livepeer/blob/04f37328fc1f72d0f3f6966999122d2c5927c017/cmd/livepeer/livepeer.go#L149-L155).
It allows to read command line parameters from environment variables or from config file, without changing our code. It will also finally close #101 😄

**Comment by mkrufky** [comment]
We can actually allow the user to provide not only the passphrase, but a JSON keystore file as well.  I wrote the following code that signs a transaction based on a JSON keystore and passphrase on disk, and I run it on my pools in production to pay miners without ever having to unlock an eth account.  (I will be open sourcing this feature soon, so here's a peek):
```golang
import (
	[...]

	"github.com/ethereum/go-ethereum/accounts"
	"github.com/ethereum/go-ethereum/accounts/keystore"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/ethclient"
)

func (r *RPCClient) SendSignedTransaction(from, to string, gas, gasPrice, value *big.Int) (string, error) {

	if r.wallet == nil {
		return "", fmt.Errorf("cannot send signed transactions without keystore wallet and password")
	}

	ctxt := context.Background()

	client, err := ethclient.Dial(r.Url)
	if err != nil {
		log.Fatal(err)
	}

	ks := keystore.NewKeyStore(
		r.wallet.KeystoreDir,
		keystore.LightScryptN,
		keystore.LightScryptP)

	// Create account definitions
	fromAccDef := accounts.Account{
		Address: common.HexToAddress(from),
	}

	// Find the signing account
	signAcc, err := ks.Find(fromAccDef)
	if err != nil {
		return "", err
	}

	b, err := ioutil.ReadFile(r.wallet.PasswordFile)
	if err != nil {
		return "", err
	}
	signPassphrase := strings.TrimRight(string(b), "\r\n")

	// Unlock the signing account
	err = ks.Unlock(signAcc, signPassphrase)
	if err != nil {
		return "", err
	}

	nonce, err := client.PendingNonceAt(ctxt, fromAccDef.Address)
	if err != nil {
		return "", err
	}

	gasLimit := gas.Uint64() // in units

	var data []byte
	toAddress := common.HexToAddress(to)
	tx := types.NewTransaction(nonce, toAddress, value, gasLimit, gasPrice, data)

	// Open the account key file
	keyJSON, err := ioutil.ReadFile(r.wallet.JSONKeystoreFile)
	if err != nil {
		return "", err
	}

	// Get the private key
	keyWrapper, err := keystore.DecryptKey(keyJSON, signPassphrase)
	if err != nil {
		return "", err
	}

	signedTx, err := types.SignTx(tx, types.NewEIP155Signer(big.NewInt(r.wallet.ChainID)), keyWrapper.PrivateKey)
	if err != nil {
		return "", err
	}

	// Send the transaction
	return signedTx.Hash().String(), client.SendTransaction(ctxt, signedTx)
}
```
