### ISSUE TITLE
Use EIP155 signer in bind.TransactOpts.Signer

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1257]
**Is your feature request related to a problem? Please describe.**

Contract bindings generated using `abigen` currently use the [types.HomesteadSigner](https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/base.go#L237) by default when signing txs. go-ethereum#17046 proposes to change the default to `types.EIP155Signer`, but based on the conversation in the thread it sounds like eventually the base code for contract bindings will not prescribe a signer and it will instead be the responsibility of the caller to define the signer used in `bind.TransactOpts.Signer`. Regardless of what decision is made, we should be signing txs based on [EIP155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md).

**Describe the solution you'd like**

Pass in a `types.EIP155Signer` to [am.SignTx()](https://github.com/livepeer/go-livepeer/blob/master/eth/accountmanager.go#L128). We will need access to the current chainID.

**Comment by kyriediculous** [comment]
we can add a type assertion in accountManager.SignTx() to see if the signer passed in there is an EIP155Signer and if it is not overwrite the signer passed in as argument with an EIP155Signer

we can store the `chainID` on the `accountManager` when calling `NewAccountManager` during eth client setup where we can fetch it using `backend.ChainID()`

**Comment by yondonfu** [comment]
> we can add a type assertion in accountManager.SignTx() to see if the signer passed in there is an EIP155Signer and if it is not overwrite the signer passed in as argument with an EIP155Signer

If we're always using the EIP155Signer, we can skip the type assertion, ignore the first param of `bind.TransactOpts.Signer` and always instantiate `EIP155Signer` within the function.

> we can store the chainID on the accountManager when calling NewAccountManager during eth client setup where we can fetch it using backend.ChainID()

👍
