### ISSUE TITLE
Spec: webhook specified object stores

### ISSUE THREAD

**Issue by wohlner** [livepeer/go-livepeer#1263]
## Abstract
We should allow to provide object store credentials in web hook response.

## Motivation
Right now object store credentials is specified per broadcaster, we want to specify it per stream.

## Proposed Solution
Web hook response should send web hook credentials to the broadcaster.

## Implementation Tasks and Considerations
Eli Edit: This will follow the fields and syntax defined here https://github.com/livepeer/go-livepeer/issues/1572

## Additional Context
We should also add authentication for web hook, but this is out of scope for this spec.

**Comment by wohlner** [comment]
lower priority this week

**Comment by iameli** [comment]
We decided not to do this before but now we do want to do it for recording. The syntax will follow what's described in https://github.com/livepeer/go-livepeer/issues/1572
