### ISSUE TITLE
Prometheus/Grafana bundled supercontainer

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#1274]
## Abstract
Let's move our Prometheus/Grafana tools into one Docker container that can be configured with environment variables.

## Motivation
Recently, there have been a few requests for go-livepeer monitoring in a variety of contexts:

* We have a variety of Kubernetes deployments that require monitoring. Even within the same cluster, we sometimes want different deployments to be monitored separately.
* Folks are running [the docker-compose BOT setup](https://github.com/mk-livepeer/bot-miner-setup) and would like stats
* Many users are just running go-livepeer binaries and would like stats there too.

Our existing Prometheus deployments within the test-harness or the Kubernetes clusters are specialized for their environments and difficult to dynamically adapt to these different contexts. [Prometheus does not support configuration with environment variables](https://github.com/prometheus/prometheus/issues/2357), further complicating dynamic configuration.

## Proposed Solution

Let's combine our Prometheus and Grafana configurations into a single Docker container. This container will be configured by environment variables. At runtime, a script in the container will take care of generating a prometheus.yml file appropriate for the environment. Here are some examples:

For a host that's just running two go-livepeer binaries, say

`livepeer -broadcaster -metrics -cliAddr=127.0.0.1:7935 -orchAddr 127.0.0.1:8936`
and
`livepeer -orchestrator -transcoder -serviceAddr 127.0.0.1:8936 -cliAddr=127.0.0.1:7936 -metrics=true`

The host could run a monitoring deployment that manually inspect these two targets

```
docker run
  -e LP_PROM_BROADCASTERS=http://127.0.0.1:7935/metrics
  -e LP_PROM_ORCHESTRATORS=http://127.0.0.1:7936/metrics
  livepeer/monitor
```

For a Kubernetes deployment, we could specify the value of the `prometheus.io/scrape` value to automatically discover and scrape from pertinent pods:

```
env:
- name: LP_PROM_KUBE_SCRAPE_VALUE
  value: testnet
```

wip the rest of this, need to hit a different meeting

**Comment by iameli** [comment]
@ya7ya and I discussed this further; for the initial shippable version of this we'll do a container that just allows for the Prometheus Kubernetes namespace to be customized at runtime so it can accommodate a variety of our environments. Everything else can be built atop that later as necessary.

**Comment by wohlner** [comment]
Also write a guide or read me

**Comment by kyriediculous** [comment]
Not sure if this can be of help https://github.com/kyriediculous/livepeer-promgraf
