### ISSUE TITLE
Multi-profile Transcoding Bottleneck

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#1277]
**Describe the bug**
This comes from the manual benchmarking I did on crypto mining rigs.  We currently handle over 60 concurrent streams for (1080p -> 720p) bbb transcoding, with a single B and single OT node running on a 8x1080ti rig.  However, if we add more transcoding profiles (for example, 1080p -> 720p+360p+240p), we get a significant performance hit and only able to transcode 16 concurrent streams.  We also observe that during the 1080p -> 720p+360p+240p transcoding, CPU, RAM, and GPU is not fully utilized.

**To Reproduce**
1. Be sure you are running on a 8xGPU mining rig.
2. Start an OT node (for example, using `livepeer -v=6 -orchestrator -transcoder -monitor=true -cliAddr=0.0.0.0:7934 -httpAddr=0.0.0.0:8934 -serviceAddr=127.0.0.1:8934 -maxSessions=80 -nvidia=0,1,2,3,4,5,6,7 -datadir ./.lpData_OT 2>&1 | tee ot.out`)
3. Start a B node with a single transcoding profile, connected to the OT node (for example, `livepeer -broadcaster -orchAddr=127.0.0.1:8934 -rtmpAddr=0.0.0.0:1935 -cliAddr=0.0.0.0:7935 -httpAddr=0.0.0.0:8935 -transcodingOptions=P720p30fps16x9 -maxSessions=70 -datadir ./.lpData_B 2>&1 | tee b.out`)
4. Start multiple streams using ffmpeg, you should be able to gradually increase to 50. Transcoding time should be between 100ms to 500ms, and you will see CPU, RAM, and GPU utilization increase, and you should see the success rate higher than 99%.
5. Stop the streams.
6. Start another B node with multiple transcoding profiles, connected to the OT node.  (For example, adding `P360p30fps16x9`,`P144p30fps16x9`).
7. Start multiple streams using ffmpeg, and you are only able to go up to 16 streams before success rate starts to go down significantly.  You will also see CPU, RAM, and GPU utilization not close to being maxed out.

**Expected behavior**
We should be able to fully utilize the system resources (CPU, RAM, GPU) when doing multi-profile tarnscoding.

**Comment by wohlner** [comment]
As discussed in the Jan 24 eng leads meeting, the goal is to **get within 30% of ffmepg**.
cc: @j0sh @darkdarkdragon

**Comment by wohlner** [comment]
As of planning Jan 27, still unclear what is happening, but haven't been about to connect the dots. Mostly following up on suspicious finding from last week. Will follow up in discord.

**Comment by wohlner** [comment]
"We currently handle over 60 concurrent streams for (1080p -> 720p) bbb transcoding, with a single B and single OT node running on a 8x1080ti rig. However, if we add more transcoding profiles (for example, 1080p -> 720p+360p+240p), we get a significant performance hit and only able to transcode 16 concurrent streams. " From the description.

This has nothing to do with GPU performance. There is an additional bottleneck. @ericxtang, please make a separate ticket and assign it to @darkdarkdragon.

**Comment by j0sh** [comment]
Resolved by https://github.com/livepeer/go-livepeer/pull/1364
