### ISSUE TITLE
Initialize DB with new file name post-Streamflow

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1286]
**Is your feature request related to a problem? Please describe.**

The DB schema in Streamflow compatible nodes (>= v0.5.0) contains backwards incompatible changes from the DB schema in V1/alpha compatible nodes (< v0.5.0). If a Streamflow compatible node starts using a DB file that was created by a V1/alpha compatible node, it will crash.

**Describe the solution you'd like**

We can [initialize the DB with a new file name](https://github.com/livepeer/go-livepeer/blob/master/cmd/livepeer/livepeer.go#L221) i.e. `lp2.sqlite3`. With this change, a Streamflow compatible node will create a fresh DB file instead of using an existing DB file created by a V1/alpha compatible node (which would've created DB files with the name `lp.sqlite3`).

**Describe alternatives you've considered**

We already have a [guide](https://livepeer.readthedocs.io/en/latest/streamflow-public-testnet.html#migrating-to-streamflow) for migrating from V1/alpha -> Streamflow nodes so we could skip this. But, making this change would make the upgrade process easier since it doesn't require any user intervention.

**Comment by yondonfu** [comment]
Reposting a Discord comment from @kyriediculous 

> I don't think this is a good idea as it will leave a stale database on the user's system and the name change is unnecessary in that regard if there is nothing that needs to be transferred it seems better to just remove it and start fresh. Furthermore there's plenty of existing users that in the meantime are already acquainted with the upgrade path of backing up and removing the old data dir. Changing this process at this point for this sole release seems not necessary.

**Comment by yondonfu** [comment]
The existence of multiple DB files in the node's data directory might also be confusing.

I'm leaning towards not creating a new DB file right now and making it explicit/clear to users that a backwards incompatible database change has occurred that requires a fresh DB (as we have been doing in the [release notes](https://github.com/livepeer/go-livepeer/releases/tag/v0.5.2)). Later on we could start adding DB migrations that can be automatically run by the node on startup as well.

**Comment by j0sh** [comment]
>  it will leave a stale database on the user's system

It's also totally harmless, and will only be there for nodes that have upgraded to Streamflow.

> it seems better to just remove it and start fresh

How do you propose to do that without also clearing the DB on every restart, which defeats the point of a persistent data store?

> making it explicit/clear to users that a backwards incompatible database change has occurred that requires a fresh DB

People don't read, and this leads to entirely avoidable bug reports such as https://github.com/livepeer/go-livepeer/issues/1293 .

Moreover, there is something to be said for a low-maintenance upgrade process. The more manual fiddling a user has to do, the more likely things are going to go wrong (especially considering this is the same folder where the keyfile lives), and we're also making assumptions about the comfort level that some users have with these types of actions (leaving aside the question of whether such users are Livepeer's target audience, but they are out there).

> Later on we could start adding DB migrations that can be automatically run by the node on startup as well.

Absolutely. TBH I would have preferred we do this for the Streamflow release as well, but this is what it is.

**Comment by yondonfu** [comment]
Agree on the points about a low-maintenance upgrade process.

I was also hesitant about renaming the DB file because it felt like if DB migrations are the medium/long term solution then we shouldn't get into the habit of renaming the DB file. But, I also see the value of doing a one-off DB file rename for the sake of improved UX. Perhaps we could rename the file to something that does not imply some type of versioning i.e. instead of `lp2.sqlite3`, `lpdb.sqlite3`? I'd be ok with renaming the DB file in this manner and then using DB migrations going forward.

**Comment by j0sh** [comment]
> instead of lp2.sqlite3, lpdb.sqlite3

Sure - done here https://github.com/livepeer/go-livepeer/pull/1299

**Comment by kyriediculous** [comment]
Could we at least remove the old DB for the user in a future migration then?
