### ISSUE TITLE
Add custom profiles to auth webhook docs

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1292]
**Describe the bug**
There is no documentation for how to use custom transcoding profiles via the authentication webhook.

**To Reproduce**
Go to https://github.com/livepeer/go-livepeer/tree/master/doc and observe the lack of documentation around this feature.

**Expected behavior**
This needs to be documented in https://github.com/livepeer/go-livepeer/blob/master/doc/rtmpwebhookauth.md

**Comment by criticaltv** [comment]
Is there support for audio-only Transcoding option? Or only audio-visual?
