### ISSUE TITLE
When upgrading from 0.5.1 -> 0.5.2 DB Error

### ISSUE THREAD

**Issue by jedidefault** [livepeer/go-livepeer#1293]
**Output:**
E0111 07:23:00.473987   20633 db.go:228] Unable to prepare updateOrch table orchestrators has no column named stake
I0111 07:23:00.474013   20633 db.go:321] Closing DB
E0111 07:23:00.474084   20633 livepeer.go:227] Error opening DB: table orchestrators has no column named stake

**To replicate:**
After starting Ochestrator on Rinkeby Testnet 0.5.1 to 0.5.2 There seems to be a break in DB for updateOrch. livepeer and livepeer_cli being run from bin/. Unable to provide upgrade at this time.

**To resolve:**
Roll back to 0.5.1

**Comment by yondonfu** [comment]
If you're upgrading your node you will need to delete the node's old DB file. The release notes for [0.5.2](https://github.com/livepeer/go-livepeer/releases/tag/v0.5.2) contains a "Breaking Changes" section with instructions on how to delete your node's old DB file prior to upgrading.

**Comment by jedidefault** [comment]
Thanks brother.
