### ISSUE TITLE
test flake: "race: limit on 8128 simultaneously alive goroutines is exceeded, dying"

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#1296]
This message causes CI to fail periodically, most recently in this CircleCI build: https://app.circleci.com/jobs/github/livepeer/go-livepeer/4035

I can't really figure out which test triggers this error, but here's the full context: https://circleci.com/api/v1.1/project/github/livepeer/go-livepeer/4035/output/105/0?file=true&allocation-id=5e1aa93293317303ee00d767-0-build%2F57668373

**Comment by kyriediculous** [comment]
Wondering if it has something to do with https://github.com/golang/go/issues/23611 / https://go-review.googlesource.com/c/go/+/103160/

**Comment by iameli** [comment]
Could be. Is that the same situation, there? Are we running all of our tests in parallel?

**Comment by kyriediculous** [comment]
The parellel tests are just from the example code, this happens when running any large number of goroutines when using the `-race` option.

To reproduce: 

```
$ go test ./core -race -run LB_
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
FAIL	github.com/livepeer/go-livepeer/core	1.987s
FAIL
```

I tried looking through the code but I think it might be caused by https://github.com/flyingmutant/rapid if it generates more goroutines than the allowed cap ?

**Comment by yondonfu** [comment]
[TestLB_ConcurrentSessionErrors](https://github.com/livepeer/go-livepeer/blob/master/core/lb_test.go#L144) has a nested loop that spins up 500 goroutines with 50 goroutines nested within each parent goroutine which might be triggering this error. cc @j0sh since he wrote the LB tests.

**Comment by kyriediculous** [comment]
Yeah that's the one indeed. But it doesn't always fail. 

```
nico@Nicos-MacBook-Pro go-livepeer (nv/o-active-check2) $ go test ./core -run LB_ConcurrentSessionErrors -race -count 1
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
FAIL	github.com/livepeer/go-livepeer/core	2.214s
FAIL
nico@Nicos-MacBook-Pro go-livepeer (nv/o-active-check2) $ go test ./core -run LB_ConcurrentSessionErrors -race -count 1
ok  	github.com/livepeer/go-livepeer/core	2.477s
nico@Nicos-MacBook-Pro go-livepeer (nv/o-active-check2) $ go test ./core -run LB_ConcurrentSessionErrors -race -count 1
ok  	github.com/livepeer/go-livepeer/core	2.436s
nico@Nicos-MacBook-Pro go-livepeer (nv/o-active-check2) $ go test ./core -run LB_ConcurrentSessionErrors -race -count 1
ok  	github.com/livepeer/go-livepeer/core	2.426s
nico@Nicos-MacBook-Pro go-livepeer (nv/o-active-check2) $ go test ./core -run LB_ConcurrentSessionErrors -race -count 1
ok  	github.com/livepeer/go-livepeer/core	2.322s
nico@Nicos-MacBook-Pro go-livepeer (nv/o-active-check2) $ go test ./core -run LB_ConcurrentSessionErrors -race -count 1
ok  	github.com/livepeer/go-livepeer/core	2.395s
nico@Nicos-MacBook-Pro go-livepeer (nv/o-active-check2) $ go test ./core -run LB_ConcurrentSessionErrors -race -count 1
ok  	github.com/livepeer/go-livepeer/core	3.703s
```

**Comment by j0sh** [comment]
@yondonfu  is correct the issue is around `TestLB_ConcurrentSessionErrors` , usually earlier goroutines exit quickly enough that new goroutines don't hit the ceiling under `-race`, but looks like this doesn't always happen, especially under slower environments such as CI. Will bump down the numbers so this test passes more consistently.
