### ISSUE TITLE
Latest Ffmpeg adds 2 seconds of latency to RTMP segmenting

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#1303]
Current build, which is built against Ffmpeg's master, shows average segmenting latency around 2s.
If built against ffmpeg 4.2.2 (installed by `brew` on MacOS), average segmenting latency is 140ms.

**To Reproduce**
Stream to broadcaster node using stream-tester with latency option:
`./stream-tester -latency`.

Stream-tester will report segmenting latency in `Source latencies` row.
It is measured by stream-tester from time when last RTMP packet of segment was sent till time source segment was downloaded.

**Comment by j0sh** [comment]
Are we sure this isn't just a reflection of the segment length? If a segment begins at time X, it wouldn't be available for at least N seconds, or at time X+N. In this case, 2 seconds is our segment length.

If we're certain it's not an issue with how we do the measurement, then `git bisect` can be used on ffmpeg to narrow down the change that caused the issue.

**Comment by darkdarkdragon** [comment]
> Are we sure this isn't just a reflection of the segment length? 

Sure. I've built node locally with `PKG_CONFIG_PATH` pointing to ffmpeg built using `install_ffmpge.sh` and compiled same code without `PKG_CONFIG_PATH` - so it was built against ffmpeg installed by `brew`. These two version shows difference in segmenting times.

>  If a segment begins at time X, it wouldn't be available for at least N seconds, or at time X+N. I

stream-tester accounts for that

> then git bisect can be used on ffmpeg to narrow down the change that caused the issue.

Sure, it just takes time...
If it is problem in `hlsenc.c` - then probably it won't take too long - it didn't had much changes...

**Comment by darkdarkdragon** [comment]
This commit https://github.com/FFmpeg/FFmpeg/commit/cff309097a3af4f7f2acb5b5f9fb914ba9ae45c3 causing increased latency.
