### ISSUE TITLE
Reduce logging level of acceptable payment errors

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1313]
**Is your feature request related to a problem? Please describe.**

Currently, orchestrators log an error message when they encounter an acceptable payment error (the orchestrator treats this acceptable error as acceptable because it gives the broadcaster a grace period in case it has not received up-to-date ticket params and pricing yet).

For example:

```
E0117 08:57:13.146220    2574 orchestrator.go:177] Error receiving ticket manifestID=bbb_sunflower_1080p_30fps_normal_t02mp4_6c67e1336b01bc927139_1 recipientRandHash=dfc7e94ef532392a861c2a9d1d49759a2270f56d26124dded37836e31eb45aa9 senderNonce=1: invalid ticket faceValue 29687500000000000
E0117 08:57:13.146331    2574 segment_rpc.go:86] Acceptable error occured when processing payment: error receiving tickets with payment
```

This logged error confuses users because it leads them to believe that something is wrong with their node when acceptable payment errors are normal. Users shouldn't need to worry about acceptable payment errors.

**Describe the solution you'd like**

Reduce the logging level of acceptable payment errors.

**Comment by kyriediculous** [comment]
closed because we no longer have acceptable payment errors since #1383 was merged
