### ISSUE TITLE
Remove the Publisher's stream_key from the playback URL

### ISSUE THREAD

**Issue by criticaltv** [livepeer/go-livepeer#1314]
**Is your feature request related to a problem? Please describe.**

When publishing an RTMP stream into Livepeer running in `-transcoder` mode, the Publisher's `stream_key` is encoded into the URL for a Viewer to use to play the stream.

This introduces opportunity to deny service on specific URLs, for example, if you would like to stream using http://1.2.3.4:8935/stream/{stream_key} then a rogue Publisher can stream using your {stream_key}, and deny you service.

**Describe the solution you'd like**

I would like some kind of translation mechanism to translate a) the {stream_key} provided by the Publisher, into b) the stream identifier coded into the URL to allow a viewer to access the stream. 

This would make it hard for a rogue Publisher to deny service using a specific stream_key

For example, a simple (but insecure) method could be for:

- Publisher uses their own `private_key` as stream key
- Broadcaster simply uses this to generate the associated `public_address` using `sha256`
- Broadcaster publishes user's stream at http://1.2.3.4:8935/stream/public_address

**Describe alternatives you've considered**

A more comprehensive potential solution would be to use sha256 and Ethereum's signing functionality to allow a Publisher to generate their own `stream_key` by signing a message, which a Livepeer node could validate.

The flow could be something like:

- Broadcaster starts with `-broadcastSecret secret`
- Publisher uses private key to sign the `secret` to create `signed_secret`
- Publisher passes in a string consisting of their `public_address` concatenated with the `signed_secret`
- Broadcaster validates that the private key associated with the public address signed the secret
- Broadcaster publishes user's stream at http://1.2.3.4:8935/stream/public_address

**Additional context**

This solution of encoding the user's public address into the stream can be very useful in terms of directing payment towards

**Comment by j0sh** [comment]
This is already possible with webhook authentication by specifying a `manifestID`. This means you can stream into rtmp://host/stream1 , then set the `manifestID` to `stream2` and the resulting HLS stream would only be available via `stream2` . The RTMP ingest stream name can be validated as needed within the webhook handler, including enforcing a RTMP URL structure and checking public keys.

The `streamKey` field is also available to further protect RTMP playback, but that works best as a random string unless you need predictability to help any other tooling.

 See the webhook documentation: https://github.com/livepeer/go-livepeer/blob/master/doc/rtmpwebhookauth.md

**Comment by criticaltv** [comment]
I definitely need to get my head around this. Thank you @j0sh
