### ISSUE TITLE
–rtmpAddr and -httpAddr options don't seem to work

### ISSUE THREAD

**Issue by faridnsh** [livepeer/go-livepeer#1321]
**Describe the bug**
–rtmpAddr and -httpAddr options don't seem to work

**To Reproduce**
Steps to reproduce the behavior(with a eth account already set up):
1. Run `curl -L https://github.com/livepeer/go-livepeer/releases/download/v0.5.3/livepeer-linux-amd64.tar.gz | tar -xz`
2. Run `livepeer-linux-amd64/livepeer -v 6 -network rinkeby -broadcaster –rtmpAddr 0.0.0.0:1935 -httpAddr 0.0.0.0:8935`
3. view that it's listening on 127.0.0.1:1935 and 127.0.0.1:8935
4. wonder why it's not 0.0.0.0

**Expected behavior**
It should listen on 0.0.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/822510/73079363-60658700-3ec4-11ea-8101-217394fe4532.png)

 - OS: Darwin, Mac OS 10.15.2, and also Ubuntu 19.10

**Comment by j0sh** [comment]
It looks like the hyphen you have for `-rtmpAddr` is not actually a hyphen but some other character (dash?). If you replace that one character, things should work.

Interesting bug though, normally the CLI should error out on arguments it doesn't understand.

**Comment by faridnsh** [comment]
Ah right, yeah. Thanks for looking into it. I didn't see that. I copied that from some page. Yeah the cli actually doesn't seem to show error for unexpected arguments

**Comment by j0sh** [comment]
@alFReD-NSH If the args were copy-pasted from some Livepeer doucmentation then let us know, that should be fixed

**Comment by faridnsh** [comment]
Yeah, found it: https://github.com/livepeer/docs/pull/56
