### ISSUE TITLE
Add docs for multipart/mixed return

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1323]
**Is your feature request related to a problem? Please describe.**

#1280 added support for returning transcoded data using `multipart/mixed` encoding when a broadcaster is using HTTP push, but there are no docs describing how to use the feature.

**Describe the solution you'd like**

We should add docs in `doc` directory describing how to use the `multipart/mixed` feature for a broadcaster using HTTP push. The docs can likely be as simple as describing the request and response objects.

**Describe alternatives you've considered**

We could add more context describing *why* someone would use the `multipart/mixed` feature, but that seems unnecessary right now. A guide for using `multipart/mixed` within a more complex system feels like its own separate thing.

**Comment by wohlner** [comment]
audience for this is someone like Jaron at LP.

https://github.com/livepeer/go-livepeer/blob/master/doc/ingest.md , This would be a subsection of that section.
