### ISSUE TITLE
Move sig verification into verification.SegmentVerifier

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1325]
**Is your feature request related to a problem? Please describe.**

The broadcaster currently runs orchestrator sig verification for transcoded results [here](https://github.com/livepeer/go-livepeer/blob/9cb8a3ddb7492434284cd00509193f53cacd4515/server/broadcast.go#L489).

There are a few downsides with how we handle the orchestrator sig verification for transcoded results right now:

- It is run after the results are inserted into the playlist. We should verify the sig before inserting into the playlist
- The check is outside of `verification.SegmentVerifier` which contains logic for content verification logic. Ideally, all verification logic for transcoded results could live in the same package in order to avoid fragmented verification operations and to improve code readability

**Describe the solution you'd like**

Move the orchestrator sig verification into `verification.SegmentVerifier` (see this [TODO](https://github.com/livepeer/go-livepeer/blob/9cb8a3ddb7492434284cd00509193f53cacd4515/verification/verify.go#L101)).

Sig verification should only be run when the node is on-chain mode. One way to check if the node is in on-chain mode is to check if `params.Orchestrator.TicketParams != nil` (we would only be receiving ticket params from an orchestrator when running in on-chain mode).

A few things to consider:

The [VerifySig()](https://github.com/livepeer/go-livepeer/blob/9cb8a3ddb7492434284cd00509193f53cacd4515/pm/helpers.go#L22) helper is currently defined in the `pm` package. We can avoid importing the `pm` package into the `verification` package by:
- Moving the `VerifySig()` helper into the `eth` package and removing the `DefaultSigVerifier` struct from the `pm` package - the `pm` package doesn't need to be exposed to the details of how sig verification is implemented
- Defining a `SigVerifier` struct that calls `VerifySig()` in the `eth` package. This struct can be passed in as a dependency of [pm.Validator](https://github.com/livepeer/go-livepeer/blob/9cb8a3ddb7492434284cd00509193f53cacd4515/pm/validator.go#L39)

Currently, if the broadcaster is results are not uploaded directly to its own external OS, it will download the result data into its own OS and generate the [hashes](https://github.com/livepeer/go-livepeer/blob/9cb8a3ddb7492434284cd00509193f53cacd4515/server/broadcast.go#L418) for the results which are passed into the sig verification operation. We could consider moving the hash generation into `verification.SegmentVerifier`. A known issue that we have is that if a results are uploaded directly to a broadcaster's external OS we currently never download the data from the external OS and we cannot do sig verification without the data. As we consider how to do hash generation we should consider whether we want to unconditionally download data for sig verification (see [this comment](https://github.com/livepeer/go-livepeer/blob/9cb8a3ddb7492434284cd00509193f53cacd4515/server/broadcast.go#L487)).

**Comment by mkrufky** [comment]
Moving `VerifySig()` into the `eth` package causes circular dependencies.  We might be better off putting it into its own package.

```diff
diff --git a/eth/helpers.go b/eth/helpers.go
index 32aca220..ddeca1dc 100644
--- a/eth/helpers.go
+++ b/eth/helpers.go
@@ -1,12 +1,14 @@
 package eth
 
 import (
+       "errors"
        "fmt"
        "math/big"
        "regexp"
        "strings"
        "time"
 
+       "github.com/ethereum/go-ethereum/accounts"
        ethcommon "github.com/ethereum/go-ethereum/common"
        "github.com/golang/glog"
        "github.com/livepeer/go-livepeer/common"
@@ -166,3 +168,42 @@ func FromBaseAmount(v *big.Int) string {
 
        return intPart + "." + decPart
 }
+
+func VerifySig(addr ethcommon.Address, msg, sig []byte) bool {
+       recovered, err := ecrecover(msg, sig)
+       if err != nil {
+               return false
+       }
+
+       return recovered == addr
+}
+
+func ecrecover(msg, sig []byte) (ethcommon.Address, error) {
+       if len(sig) != 65 {
+               return ethcommon.Address{}, errors.New("invalid signature length")
+       }
+
+       s := new(big.Int).SetBytes(sig[32:64])
+       if s.Cmp(secp256k1halfN) > 0 {
+               return ethcommon.Address{}, errors.New("signature s value too high")
+       }
+
+       v := sig[64]
+       if v != byte(27) && v != byte(28) {
+               return ethcommon.Address{}, errors.New("signature v value must be 27 or 28")
+       }
+
+       // crypto.SigToPub() expects signature v value = 0/1
+       // Copy the signature and convert its value to 0/1
+       ethSig := make([]byte, 65)
+       copy(ethSig[:], sig[:])
+       ethSig[64] -= 27
+
+       ethMsg := accounts.TextHash(msg)
+       pubkey, err := crypto.SigToPub(ethMsg, ethSig)
+       if err != nil {
+               return ethcommon.Address{}, err
+       }
+
+       return crypto.PubkeyToAddress(*pubkey), nil
+}
diff --git a/pm/helpers.go b/pm/helpers.go
index e95520fc..5917ecfa 100644
--- a/pm/helpers.go
+++ b/pm/helpers.go
@@ -4,10 +4,7 @@ import (
        "math/big"
        "math/rand"
 
-       "github.com/ethereum/go-ethereum/accounts"
        ethcommon "github.com/ethereum/go-ethereum/common"
-       "github.com/ethereum/go-ethereum/crypto"
-       "github.com/pkg/errors"
 )
 
 var (
@@ -19,44 +16,6 @@ var (
 // is produced by a given ETH address
 //
 // TODO refactor to a package that both eth and pm can import
-func VerifySig(addr ethcommon.Address, msg, sig []byte) bool {
-       recovered, err := ecrecover(msg, sig)
-       if err != nil {
-               return false
-       }
-
-       return recovered == addr
-}
-
-func ecrecover(msg, sig []byte) (ethcommon.Address, error) {
-       if len(sig) != 65 {
-               return ethcommon.Address{}, errors.New("invalid signature length")
-       }
-
-       s := new(big.Int).SetBytes(sig[32:64])
-       if s.Cmp(secp256k1halfN) > 0 {
-               return ethcommon.Address{}, errors.New("signature s value too high")
-       }
-
-       v := sig[64]
-       if v != byte(27) && v != byte(28) {
-               return ethcommon.Address{}, errors.New("signature v value must be 27 or 28")
-       }
-
-       // crypto.SigToPub() expects signature v value = 0/1
-       // Copy the signature and convert its value to 0/1
-       ethSig := make([]byte, 65)
-       copy(ethSig[:], sig[:])
-       ethSig[64] -= 27
-
-       ethMsg := accounts.TextHash(msg)
-       pubkey, err := crypto.SigToPub(ethMsg, ethSig)
-       if err != nil {
-               return ethcommon.Address{}, err
-       }
-
-       return crypto.PubkeyToAddress(*pubkey), nil
-}
 
 // RandHash returns a random keccak256 hash
 func RandHash() ethcommon.Hash {
diff --git a/pm/sigverifier.go b/pm/sigverifier.go
index 127db337..4d25a3fd 100644
--- a/pm/sigverifier.go
+++ b/pm/sigverifier.go
@@ -2,6 +2,7 @@ package pm
 
 import (
        ethcommon "github.com/ethereum/go-ethereum/common"
+       "github.com/livepeer/go-livepeer/eth"
 )
 
 // SigVerifier is an interface which describes an object capable
@@ -20,7 +21,7 @@ type DefaultSigVerifier struct {
 // Verify checks if a provided signature over a message
 // is valid for a given ETH address
 func (sv *DefaultSigVerifier) Verify(addr ethcommon.Address, msg, sig []byte) bool {
-       return VerifySig(addr, msg, sig)
+       return eth.VerifySig(addr, msg, sig)
 }
 
 // ApprovedSigVerifier is an implementation of the SigVerifier interface
```
results in:
```
$ make
GO111MODULE=on CGO_LDFLAGS="" go build -tags "" -ldflags="-X github.com/livepeer/go-livepeer/core.LivepeerVersion=0.5.4-6080ed3a-dirty" cmd/livepeer/*.go
import cycle not allowed
package main
	imports github.com/livepeer/go-livepeer/common
	imports github.com/livepeer/go-livepeer/pm
	imports github.com/livepeer/go-livepeer/eth
	imports github.com/livepeer/go-livepeer/common
import cycle not allowed
package main
	imports github.com/livepeer/go-livepeer/common
	imports github.com/livepeer/go-livepeer/pm
	imports github.com/livepeer/go-livepeer/eth
	imports github.com/livepeer/go-livepeer/pm
Makefile:20: recipe for target 'livepeer' failed
make: *** [livepeer] Error 1
```

**Comment by mkrufky** [comment]
Things work well if I move it to its own separate package:

https://github.com/livepeer/go-livepeer/commit/0b0d85983c1d9ab2f994638944155731bbd66a9d

**Comment by mkrufky** [comment]
Updated patch moves `pm.VerifySig()` to `signature.Verify()`
https://github.com/livepeer/go-livepeer/commit/a5174c3b2cd2219a314f3e3ec645b0674297ce02

**Comment by mkrufky** [comment]
Updated patch moves `pm.VerifySig()` to `signature.Verify()`

https://github.com/livepeer/go-livepeer/commit/7e9aa6e65f895dbddcc381696f25df57d855ae60
