### ISSUE TITLE
Display git tip rev hash in startup logging

### ISSUE THREAD

**Issue by mk-livepeer** [livepeer/go-livepeer#1333]
It is difficult to determine exactly what version of the code is running from within a docker container:
```
# livepeer --version
Livepeer Node Version: 0.5.3
Golang runtime version: gc go1.13.4
Architecture: amd64
Operating system: linux
```
It would make life easier for everybody if we include the tip rev hash in both the startup message and the `--version` output.

**Comment by iameli** [comment]
I like the idea of adding the `livepeer -version` output to the startup message. That's always a lifesaver when I'm looking at logs from external users.

> It would make life easier for everybody if we include the tip rev hash

This is already true in every case except for tagged semver releases; my current go-livepeer built off of master reports as `0.5.4-10873651`. So if you ever see someone with `Livepeer Node Version: 0.5.3`, it's easy enough to find the commit sha with `git show v0.5.3`.

**Comment by thomshutt** [comment]
@emranemran This is similar to the work you're doing for https://github.com/livepeer/go-livepeer/issues/2415, just with outputting the hash on startup
