### ISSUE TITLE
add armhf and arm64 builds to CI

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#1334]
Not a terribly high priority, I think I'm the only one that's tried running a broadcaster on a Raspberry Pi. But it works great; the build and everything work fine out of the box. No GPU support, to my knowledge.

I shipped the Windows version over the course of 2019... so maybe I'll slowly chip away at this over the course of 2020. But if anyone else is looking for ARM builds, let me know here!

**Comment by darkdarkdragon** [comment]
I've also ran broadcaster on arm - works great. I even looked into the state of GPU support on ARM - at the time my conclusion was that it will work only on Raspberry PI, which I don't have, so I've abandoned this idea.

**Comment by iameli** [comment]
Oh, interesting - you're thinking of support for the Pi's built-in decoder? That'd be really nice for broadcaster verification. On the encode side, I think there might be a hardware H264 encoder but I doubt it produces particularly nice-looking video.

**Comment by darkdarkdragon** [comment]
I was thinking about using cheap arm device as transcoder :)
> but I doubt it produces particularly nice-looking video.

And this poses interesting question - what if someone implement this? It will produce correctly transcoded segments, but, presumably, not very `nice-looking`? 
And it should be verifier's job to reject such segments?
Maybe we should implement this just to have data for the verifier to check against?
