### ISSUE TITLE
Broadcaster not refreshing session for long running stream

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#1345]
**Describe the bug**
One of the broadcasters in AC, for one long running stream (13000 segments), stuck in the state where `selectSession` returns `nil` but `refreshSessions` either not called or not returns early - broadcaster not trying to contact orchestrators (though broadcaster's list of orchestrators is not empty).

logs are looking like this:
```
Feb 03 13:58:50 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:31.346619       6 census.go:785] Logging SourceSegmentAppeared... nonce=8531230601938080808 seqNo=13111 manifestid=d0b71a90-0ee6-4da9-b89b-88a653d46d07 profile=source
Feb 03 13:58:50 broadcaster-squirtle-7f9f54c5fd-zhbtj chi E0203 21:58:31.346680       6 census.go:862] Logging SegmentTranscodeFailed subtype=NoOrchestrators nonce=8531230601938080808 seqNo=13111 error='ErrNoOrchs'
Feb 03 13:58:50 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:31.346811       6 broadcast.go:326] No sessions available for segment nonce=8531230601938080808 manifestID=d0b71a90-0ee6-4da9-b89b-88a653d46d07 seqNo=13111
Feb 03 13:58:52 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:33.524777       6 census.go:767] Logging SegmentEmerged... nonce=8531230601938080808 seqNo=13112
Feb 03 13:58:52 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:33.524908       6 census.go:785] Logging SourceSegmentAppeared... nonce=8531230601938080808 seqNo=13112 manifestid=d0b71a90-0ee6-4da9-b89b-88a653d46d07 profile=source
Feb 03 13:58:52 broadcaster-squirtle-7f9f54c5fd-zhbtj chi E0203 21:58:33.524993       6 census.go:862] Logging SegmentTranscodeFailed subtype=NoOrchestrators nonce=8531230601938080808 seqNo=13112 error='ErrNoOrchs'
Feb 03 13:58:52 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:33.525064       6 broadcast.go:326] No sessions available for segment nonce=8531230601938080808 manifestID=d0b71a90-0ee6-4da9-b89b-88a653d46d07 seqNo=13112
Feb 03 13:58:54 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:35.299455       6 census.go:767] Logging SegmentEmerged... nonce=8531230601938080808 seqNo=13113
Feb 03 13:58:54 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:35.299535       6 census.go:785] Logging SourceSegmentAppeared... nonce=8531230601938080808 seqNo=13113 manifestid=d0b71a90-0ee6-4da9-b89b-88a653d46d07 profile=source
Feb 03 13:58:54 broadcaster-squirtle-7f9f54c5fd-zhbtj chi E0203 21:58:35.299576       6 census.go:862] Logging SegmentTranscodeFailed subtype=NoOrchestrators nonce=8531230601938080808 seqNo=13113 error='ErrNoOrchs'
Feb 03 13:58:54 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:35.299611       6 broadcast.go:326] No sessions available for segment nonce=8531230601938080808 manifestID=d0b71a90-0ee6-4da9-b89b-88a653d46d07 seqNo=13113
Feb 03 13:58:56 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:37.289527       6 census.go:767] Logging SegmentEmerged... nonce=8531230601938080808 seqNo=13114
Feb 03 13:58:56 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:37.289626       6 census.go:785] Logging SourceSegmentAppeared... nonce=8531230601938080808 seqNo=13114 manifestid=d0b71a90-0ee6-4da9-b89b-88a653d46d07 profile=source
Feb 03 13:58:56 broadcaster-squirtle-7f9f54c5fd-zhbtj chi E0203 21:58:37.289666       6 census.go:862] Logging SegmentTranscodeFailed subtype=NoOrchestrators nonce=8531230601938080808 seqNo=13114 error='ErrNoOrchs'
Feb 03 13:58:56 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:37.289705       6 broadcast.go:326] No sessions available for segment nonce=8531230601938080808 manifestID=d0b71a90-0ee6-4da9-b89b-88a653d46d07 seqNo=13114
Feb 03 13:58:58 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:39.376696       6 census.go:767] Logging SegmentEmerged... nonce=8531230601938080808 seqNo=13115
Feb 03 13:58:58 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:39.376780       6 census.go:785] Logging SourceSegmentAppeared... nonce=8531230601938080808 seqNo=13115 manifestid=d0b71a90-0ee6-4da9-b89b-88a653d46d07 profile=source
Feb 03 13:58:58 broadcaster-squirtle-7f9f54c5fd-zhbtj chi E0203 21:58:39.376820       6 census.go:862] Logging SegmentTranscodeFailed subtype=NoOrchestrators nonce=8531230601938080808 seqNo=13115 error='ErrNoOrchs'
Feb 03 13:58:58 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:39.376854       6 broadcast.go:326] No sessions available for segment nonce=8531230601938080808 manifestID=d0b71a90-0ee6-4da9-b89b-88a653d46d07 seqNo=13115
Feb 03 13:59:00 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:41.376858       6 census.go:767] Logging SegmentEmerged... nonce=8531230601938080808 seqNo=13116
Feb 03 13:59:00 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:41.376956       6 census.go:785] Logging SourceSegmentAppeared... nonce=8531230601938080808 seqNo=13116 manifestid=d0b71a90-0ee6-4da9-b89b-88a653d46d07 profile=source
Feb 03 13:59:00 broadcaster-squirtle-7f9f54c5fd-zhbtj chi E0203 21:58:41.376994       6 census.go:862] Logging SegmentTranscodeFailed subtype=NoOrchestrators nonce=8531230601938080808 seqNo=13116 error='ErrNoOrchs'
Feb 03 13:59:00 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:41.377031       6 broadcast.go:326] No sessions available for segment nonce=8531230601938080808 manifestID=d0b71a90-0ee6-4da9-b89b-88a653d46d07 seqNo=13116
Feb 03 13:59:02 broadcaster-squirtle-7f9f54c5fd-zhbtj chi I0203 21:58:43.181437       6 census.go:767] Logging SegmentEmerged... nonce=8531230601938080808 seqNo=13117
```

**To Reproduce**
Happened once to day

**Expected behavior**
Should not stuck

**Desktop (please complete the following information):**
"Version":"0.5.3-685a797b"
"GolangRuntimeVersion":"go1.13.4"
"GOArch":"amd64"
"GOOS":"linux"

**Comment by j0sh** [comment]
It appears the log level here isn't high enough to record refresh attempts, so there's context missing here. Could we make it a habit to run internal nodes with `-v 9` ?

**Comment by darkdarkdragon** [comment]
@j0sh I believe it will spam our Papertrail account with logs we're not using most of the time. I was thinking about adding CLI endpoint to change log level in runtime. wdyt?

**Comment by j0sh** [comment]
> CLI endpoint to change log level in runtime

This probably incurs a lock or other synchronization for the log level flag on each access, so I'm not a huge fan of the idea. Some other options:

* Determine whether this is actually a problem for us. It's not a good sign if our debugging capability, especially for something as critical as logging, is artificially constrained by an essentially superfluous third-party service such as Papertrail.
* Reduce the retention period for Papertrail so it doesn't cost more
* Reduce the amount of logging we do (eg, the census stuff does not need to be logged and that's the majority of the logs here; related https://github.com/livepeer/go-livepeer/issues/1316 )
* Disable Papertrail entirely and fetch logs from the node when this happens. Do we actually use Papertrail for anything? Because it doesn't seem like we actually capture anything very useful right now.

**Comment by darkdarkdragon** [comment]
> This probably incurs a lock or other synchronization for the log level flag on each access

No, `glog` already has all the needed synchronisation in it. And this will be useful option to have in any case.

> Reduce the amount of logging we do

Too much effort if done in one sweep. Probably we should do this step by strep, and be mindful about levels of logging in new PRs.

> Do we actually use Papertrail for anything? 

Yes, it actually very convenient in cases like this. Yesterday I've spent a lot time in it. Would be much longer without.
Ideally, we should send lower level logs to the Papertrail and save logs with highest level locally. Bet here we're getting back to #808

**Comment by j0sh** [comment]
> No, glog already has all the needed synchronisation in it

Ah that's cool.

One of the things that CLI-configurable logging won't give us is the ability to capture transient issues. The only reason we got a whiff of this issue is because it stuck around long enough for us to investigate a bit. We really need full logging regardless, and that seems like a higher priority than a CLI-configurable loglevel feature. So I'd figure out a way to make this work with Papertrail.
