### ISSUE TITLE
Leaking goroutines

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#1348]
**Describe the bug**
In the long running (three days) broadcaster there was 1300 goroutines in this state:

```
goroutine 488903 [select, 4457 minutes]:
github.com/livepeer/lpms/stream.NewBasicRTMPVideoStream.func1(0xc001070070)
        /go/pkg/mod/github.com/livepeer/lpms@v0.0.0-20200110164555-e34a4737b857/stream/basic_rtmp_videostream.go:41 +0x23d
created by github.com/livepeer/lpms/stream.NewBasicRTMPVideoStream
        /go/pkg/mod/github.com/livepeer/lpms@v0.0.0-20200110164555-e34a4737b857/stream/basic_rtmp_videostream.go:38 +0x12b
```

**To Reproduce**
Connect to the broadcaster that served many stream
http://localhost:7935/debug/pprof/goroutine?debug=2
Count `basic_rtmp_videostream.go:41`.

**Expected behavior**
Shouldn't leak goroutines.

**Comment by j0sh** [comment]
Was this broadcaster ingesting RTMP or HTTP?

It appears we may not have a chance to invoke EOF under HTTP, which would leave the initial goroutine hanging [1]. The solution may be to call `cxn.stream.Close()` within mediaserver's `removeRTMPStream` handler.

Ideally we'd refactor this area of the LPMS code so it's not so dependent on RTMP-specific behavior but that's a larger task.

[1]

https://github.com/livepeer/lpms/blob/8e9e76cda927ba9faa2efc0fe01ac5d379916be1/stream/basic_rtmp_videostream.go#L38-L62

**Comment by darkdarkdragon** [comment]
> Was this broadcaster ingesting RTMP or HTTP?

Don know, it was same B I was inspecting in #1345, so could be anything.

> It appears we may not have a chance to invoke EOF under HTTP,

Looks like it is the case.

> The solution may be to call cxn.stream.Close() within mediaserver's removeRTMPStream handler.

Will do the fix.
