### ISSUE TITLE
integrating GPU metrics into go-livepeer

### ISSUE THREAD

**Issue by ya7ya** [livepeer/go-livepeer#1349]
**Is your feature request related to a problem? Please describe.**
We'd like to monitor GPU specific metrics for each O/T , and in certain deployments (like on `AC`) the GPUs are only exposed to the O/T pods, not the metrics pod. 

**Describe the solution you'd like**
the simplest solution is to poll `nvidia-smi` periodically and piping that into prometheus, here is an [example implementation](https://github.com/ya7ya/nvidia_smi_exporter/blob/master/nvidia_smi_exporter.go)

we could add this to go-livepeer existing metrics endpoint and have seamless GPU metrics whenever it's activated

**Describe alternatives you've considered**
The current solution is to poll `nvidia-smi` separately , this works on single rigs but not on something that we don't manage ourselves like in `AC`

**Comment by yondonfu** [comment]
Closing because I don't think this is required anymore.
