### ISSUE TITLE
Publish latest release to `latest` tag on DockerHub

### ISSUE THREAD

**Issue by ya7ya** [livepeer/go-livepeer#1352]
**Is your feature request related to a problem? Please describe.**
currently the default docker pull command doesn't work because the default `latest` tag isn't published

```bash
$ sudo docker pull livepeer/go-livepeer
Using default tag: latest
Error response from daemon: manifest for livepeer/go-livepeer:latest not found: manifest unknown: manifest unknown
```
**Describe the solution you'd like**
setup the circleci build to publish the latest release to `latest` during the auto build process.

**Comment by iameli** [comment]
Good point! I'm leaning toward `latest` being an alias of `mainnet`? That'd mean `livepeer/go-livepeer:latest` always points at our most recent semver mainnet-compatible release, which I think is mostly consistent with how `:latest` tags are handled.
