### ISSUE TITLE
Should check if GPUs accessible at start

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#1373]
**Is your feature request related to a problem? Please describe.**
If node is configured with wrong GPU number it starts successfully, but can't transcode:
```
Feb 10 20:12:16 orchestrator-1080-9fbd9957d-ndqvp chi [AVHWDeviceContext @ 0x7fdec9240180] cu->cuDeviceGet(&hwctx->internal->cuda_device, device_idx) failed -> CUDA_ERROR_INVALID_DEVICE: invalid device ordinal
Feb 10 20:12:16 orchestrator-1080-9fbd9957d-ndqvp chi Freeing input based on OPEN INPUT error
Feb 10 20:12:16 orchestrator-1080-9fbd9957d-ndqvp chi E0211 04:12:19.078064       6 ffmpeg.go:292] Transcoder Return : Unknown error occurred
Feb 10 20:12:16 orchestrator-1080-9fbd9957d-ndqvp chi I0211 04:12:19.078123       6 lb.go:189] LB: Stopping transcoder due to error for 2378debc-8e2d-4a10-90c5-6738cf096dbb_8
```

**Describe the solution you'd like**
Try to transcode some test segment at node startup and refuse to start if can't transcode.

**Comment by iameli** [comment]
> Try to transcode some test segment at node startup and refuse to start if can't transcode.

Love that. This also would have caught https://github.com/livepeer/go-livepeer/issues/1385 a bit faster, as it would have crashed on boot.
