### ISSUE TITLE
Monitor / manage GPU backlog

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1397]
**Is your feature request related to a problem? Please describe.**

With https://github.com/livepeer/go-livepeer/pull/1364 a per-GPU stack is used to prioritize segments for transcoding. The LIFO behavior maximizes responsiveness for recent segments at the expense of higher tail latencies for segments in the backlog. If the transcoder is under load, the backlog could be very large and a segment could be pending indefinitely. We currently do not limit the backlog at all.

**Describe the solution you'd like**

- [ ] Monitor the transcode backlog. We already have a way to gather metrics on the depth of the backlog. Observing its behavior over time may give us a better idea of how to handle the backlog.
  
- [ ] Clear out the backlog as appropriate. TBD the best / easiest approach to this. Some options:

- Drop segments when the rate of incoming segments exceed the rate of completed transcodes.  But over what period? How many to drop, how many should we buffer?
- Having a fixed size stack and dropping older segments as new ones are added?
- Having a wall clock limit on pending segments - drop segments after some time?

Note many of these may also be dependent on factors such as the job complexity, the type of GPU in use, etc.

**Comment by yondonfu** [comment]
Closing because a per-GPU stack is no longer used to prioritize segments for transcoding.
