### ISSUE TITLE
CLI: SetOrchestratorConfig should fetch the current set values and display those as defaults rather than the vanilla defaults

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1401]
**Is your feature request related to a problem? Please describe.**

FeeCut and RewardShare are required params when setting orchestrator config in the CLI. The user however has to remember the previous values set if it doesn't want to change these. The CLI only displays the "factory defaults" rather than what is currently set by the user.

**Describe the solution you'd like**
Only display default when not set , otherwise display set values.

**Comment by yondonfu** [comment]
Adding a note just as a reminder that a user in Discord requested this feature again recently.

**Comment by kyriediculous** [comment]
This would probably require us to create an endpoint `/getOrchestratorConfig` and then GET it before prompting orchestrator config
