### ISSUE TITLE
Mitigate high memory usage with local disk storage

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1405]
**Is your feature request related to a problem? Please describe.**

There have been reports of excessive memory utilization on the node ( https://github.com/livepeer/go-livepeer/issues/1155 , https://github.com/livepeer/go-livepeer/issues/1310 ). The current baseline recommendation for an active orchestrator is >10 GB of memory. It would be nice to reduce that wherever possible.

**Describe the solution you'd like**

- [ ] Support on-disk local storage. ( https://github.com/livepeer/go-livepeer/issues/867 ) Some quick testing has shown that using external OS offers significant savings in the amount of RAM requested by the node (~25 on the O, -50% on the B). This is probably due to segments within the node being shorter lived, hence reclaimed quicker and memory recycled more. The on-disk storage should follow the same cache / expiration / removal policies followed by the current in-memory OS (although maybe optionally tunable for other use cases). This local disk storage should be optional, eg via a `-diskStore` boolean flag.

- [ ] To fully operationalize this, support a separate path for media (eg, `-mediaDir`). This allows segments to be placed in fast and volatile storage (such a tmpfs) with long-lived files (keyfiles, DB, etc) in persistent storage. While we'd still be using RAM with the disk backed by a tmpfs, it would be outside the purview of golang's allocator and GC. This flag should also be separate from the `-diskStore` flag in order to propagate the media working directory in places where the OS isn't used such as the segmenter, transcoder, verification, etc. If `-mediaDir` is not set, the `-datadir` should be used by default for local disk storage, same as it is now.

I suspect that implementing this will also help address https://github.com/livepeer/go-livepeer/issues/846#issuecomment-489236016 as long as we are careful about passing local paths acquired from local disk storage only to local transcoders.

**Comment by hthillman** [comment]
closing because we're about to look at stream-based transcoding, which will likely address memory issues
