### ISSUE TITLE
Web player broken on mobile for desktop-published streams

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#141]
Not able to stream videos published from a desktop broadcaster (mobile broadcasting seems to work)

**Comment by ericxtang** [comment]
Turns out to be an ffmpeg issue.  OBS works, closing the bug for now.

**Comment by dob** [comment]
Do you think we should remove the Broadcast option from the CLI and the
docs? The stream doesn't work in firefox or safari either right now, so it
might be a little misleading. We could either figure out what's wrong with
the ffmpeg output and fix, or else just point people to using OBS or other
broadcasters. I think asking them to download and install OBS is a big
barrier though to trying things out. Maybe if there's a web -> RTMP
broadcaster that we could link to that would be a good way for peole to
test.
