### ISSUE TITLE
MP4 Support

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1418]
## Abstract

Currently, go-livepeer works on mpegts segments. This proposal extends go-livepeer to support receiving MP4 segments in HTTP push, and allows the transcoder to output MP4.

## Motivation

Multiple input and output formats has been requested by users. This is also helps lay the groundwork for more robust VOD support, where diverse format support may be a requirement.

## Proposed Solution

* Accept MP4s as an HTTP ingest format
* The default output from the transcoder should match the input format. If a MP4 was ingested, the transcoded result should also be MP4 (and vice versa for mpegts).
* Stretch goal: configure the output format via webhook. This would allow for the ingest and output formats to differ. 

### HTTP Ingest

Currently, we reject any non-ts input for HTTP ingest. The only place this is "checked" is in ensuring the [request suffix](https://github.com/livepeer/go-livepeer/blob/master/server/mediaserver.go#L590-L596) ends with ".ts" [1]. This can be extended to accept `.mp4` or a Content-Type of `video/mp4`.

Once the ingest content type is determined, it needs to be passed on to the output so the output matches, unless specified otherwise. How to do this is TBD; most likely through inspecting the stream parameters after the [stream is authorized, but prior to registering the stream](https://github.com/livepeer/go-livepeer/blob/6c8dabd79c51d441048f4f56e9ef1cf905489183/server/mediaserver.go#L614-L623). Will probably need an "undefined" value for the output format in order to distinguish between an unset value and a default such as mpegts.

[1] In fact, it is possible today to send a MP4 [2] into Livepeer, and receive an output in mpegts. One only has to make the request with a `.ts` extension.

```
curl --data-binary "@video.mp4" http://localhost:8935/live/josh/10.ts
```

[2] A MP4 can be sent... or any arbitrary format that ffmpeg can read, really.  🐰🥚  

### LPMS Transcoding Changes

Currently, LPMS supports arbitrary [muxers and options](https://github.com/livepeer/lpms/blob/a886f6ba53baef55e872922d5df986f028e29af7/ffmpeg/ffmpeg.go#L56). However, the most straightforward way to propagate the specified muxer from the RPC layer would be to add the information to the [VideoProfiles struct](https://github.com/livepeer/lpms/blob/a886f6ba53baef55e872922d5df986f028e29af7/ffmpeg/videoprofile.go#L20-L26), slotting into our existing RPC conversion [1][2] .

The addition to the VideoProfiles will be an enum to facilitate validity checking and to minimize the user-exposed surface area for errors. The tradeoff here is a bit more boilerplate, in exchange for safety.

Adding muxing options to the VideoProfiles may be a bit redundant since the transcoder itself already supports arbitrary muxers, but it appears to be the most straightforward path to propagate the information through go-livepeer.

The API for the LPMS transcoder will not change: specifying a custom muxer outside what's made available within VideoProfile will still require setting the corresponding [options](https://github.com/livepeer/lpms/blob/a886f6ba53baef55e872922d5df986f028e29af7/ffmpeg/ffmpeg.go#L56). Setting muxer within the VideoProfile acts as a 'shortcut' for the given set of options. For example, the MP4 muxer may have the "faststart" option enabled to make the resulting MP4s playable from HTTP.  If both the VideoProfile and the TranscodeOptions both specify different muxers, then only the configuration enabled by the VideoProfile shortcut is used.

[1] [RPC "FullProfiles" to VideoProfile](https://github.com/livepeer/go-livepeer/blob/6c8dabd79c51d441048f4f56e9ef1cf905489183/server/segment_rpc.go#L206-L222)

[2] [Webhook response to VideoProfile](https://github.com/livepeer/go-livepeer/blob/6c8dabd79c51d441048f4f56e9ef1cf905489183/server/mediaserver.go#L203-L217)

### LPMS Playback Changes

The LPMS [segment handler](https://github.com/livepeer/lpms/blob/d03c749890cbbe028ab6daedf4855b711354abfd/vidplayer/player.go#L107-L108) is hard coded to only take m3u8 and ts files. This will have to be extended to also support mp4.

It is unclear whether such path constraints are even necessary.  However, removing those constraints are out of scope here, because further study will be needed to gauge the impact of doing so.

### Protobuf

Modify the [VideoProfile protobuf struct](https://github.com/livepeer/go-livepeer/blob/6c8dabd79c51d441048f4f56e9ef1cf905489183/net/lp_rpc.proto#L131-L146)  to take a muxer. The shape of the protobuf changes  should mirror that of [ffmpeg.VideoProfile](https://github.com/livepeer/lpms/blob/a886f6ba53baef55e872922d5df986f028e29af7/ffmpeg/videoprofile.go#L20-L26), so any decisions from ffmpeg should carry over, such as using an enumeration to restrict the muxers in use. (Enums would also have the advantage of being significantly smaller on the wire.)

### RPC Compatibility: Un-upgraded B working with upgraded O

If muxer is not specified by B within the RPC request, then use the mpegts by default. This will allow matching the current behavior. This way, an un-upgraded B working with an upgraded O can still get the results it expects: a mpegts segment.

### RPC Compatibility: Upgraded B working with non-upgraded O  - Protocol Versioning

Upgraded Bs using non-upgraded Os presents a problem: the non-upgraded Os will ignore the directive to output in a specific format, and return mpegts in all cases.

Ideally, the B could specify some minimum version (or at least, `O.version >= B.version`) Currently, we are missing a version signaling mechanism during orchestrator discovery. This can be implemented by adding a `version` field within [OrchestratorInfo](https://github.com/livepeer/go-livepeer/blob/6c8dabd79c51d441048f4f56e9ef1cf905489183/net/lp_rpc.proto#L87-L102), and filtering out [responses](https://github.com/livepeer/go-livepeer/blob/6c8dabd79c51d441048f4f56e9ef1cf905489183/discovery/discovery.go#L54-L64) within the discovery mechanism.

We previously had such a versioning mechanism earlier as part of an auth token exchange, but it was [removed](https://github.com/livepeer/go-livepeer/commit/fae70f384ab151b2f2c50495f3c406c706ef0412). Also see https://github.com/livepeer/go-livepeer/issues/695

```
curl --data-binary "@video.mp4" http://localhost:8935/live/josh/11.ts
```

### Documentation

This feature and all its implicit behaviors needs to be fully documented prior to merging, with [existing documentation](https://github.com/livepeer/go-livepeer/blob/master/doc/ingest.md#http-push) updated.

### Webhook Configurability

As a stretch goal, we may want to configure the output via webhook. This would involve modifying the expected [webhook response](https://github.com/livepeer/go-livepeer/blob/6c8dabd79c51d441048f4f56e9ef1cf905489183/server/mediaserver.go#L103-L114), then adding corresponding tests and documentation.

## Testing Tasks and Considerations

Each new or modified behavior should have complete test coverage.

## Additional Context

The MP4 support proposed here does not include fragmented MP4 (fMP4). This would require further work around managing the fMP4 initializer, and is currently not in scope.

The output of the RTMP segmenter would remain as mpegts. There does not seem to be a need to make this configurable (and would likely imply fMP4 anyway). However, the transcoded output can still be configured as MP4.

Taking RTMP input, transcoding that to MP4 poses problems for consumption, because inserting non-fragmented MP4s in HLS playlists violates the [HLS spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-3.1). While we could explicitly disable RTMP-to-MP4, it may still be useful to directly pull segments asynchronously.

While this work is being done as part of the groundwork for VOD, there remains much left to do for reasonable VOD support. Some short-term considerations include ingesting longer MP4s which may run up against the current 8-second HTTP timeout. Depending on user feedback, we may also have to make the timeout configurable, or make the timeout a multiplier over the content duration.

**Comment by darkdarkdragon** [comment]
> [2] A MP4 can be sent... or any arbitrary format that ffmpeg can read, really. 🐰🥚

install_ffmpeg.sh has all demuxers except ts and flv disabled, to add mp4 support I had to add 966fd438c06440bf922165a53ea8cd292b5c8455

> Whether to make this a bit restrictive and safer by explicitly enumerating the supported formats, rather than leaving it as a free-form string. 

I think it is better to add enum - it is better to have more control over input.

**Comment by yondonfu** [comment]
> Currently, we are missing a version signaling mechanism during orchestrator discovery.

+1 for adding a versioning signaling mechanism for the networking protocol. This would've helped avoid #1427

**Comment by j0sh** [comment]
> install_ffmpeg.sh has all demuxers except ts and flv disabled, to add mp4 support I had to add

Indeed, it only works if you build with a non-barebones ffmpeg. Good note on adding the mp4 de/muxer, added that to https://github.com/livepeer/go-livepeer/pull/1429

> I think it is better to add enum - it is better to have more control over input.

Agreed, that's the approach that I went with in https://github.com/livepeer/lpms/pull/176 . Updated this writeup to reflect that.

**Comment by chrishobcroft** [comment]
Am I correct in thinking that this will effectively open an ingest point for publishing to a B using port `8935`, i.e. the port currently used for serving `hls` (or whatever) content?

If so, that does present some security risks for people operating with e.g. an open `8935` (but a closed `1935`) as anyone can publish to the B and receive transcoded results from the B.

Will this `HTTP` push feature be "disable-able"? Or indeed could it be opened on a different port than 8935, perhaps by default, e.g. 5935?

**Comment by j0sh** [comment]
@chrishobcroft These questions are a bit besides this PR but I'll run through some of them quickly. If you have more concerns, please open a separate issue on the topic.

> this will effectively open an ingest point for publishing to a B using port 8935

We've had HTTP ingest for quite some time - since https://github.com/livepeer/go-livepeer/pull/972 .

> If so, that does present some security risks for people operating with e.g. an open 8935 (but a closed 1935) as anyone can publish to the B and receive transcoded results from the B.

The B listens to 8935 on localhost by default; it'd need to be explicitly opened up for access from the outside.

Moreover, the preferred mode of operation for HTTP ingest is [multipart return](https://github.com/livepeer/go-livepeer/blob/master/doc/ingest.md#http-push), which means 8935 isn't necessary for "receiving transcoded results" since the results come as part of the response body after the transcode request. This allows you to use external tooling to further lock down requests to `/stream/` for playback (or even better, only allowing `/live` as needed). This does mean you need to do your own playlist handling on the request side if you still want HLS delivery.

> Will this HTTP push feature be "disable-able"?

There are a few options for preventing access to the feature:

* Use webhook auth to reject HTTP ingest. The `url` field will contain a HTTP address which can be used to disambiguate from RTMP.

* Use external tooling such as a reverse proxy to only allow certain paths through. Livepeer HTTP ingest is accessed via `/live/` while playback is accessed via `/stream/`.

This all points to the need for better documentation around *how* to use the system and how the various components can work together. Pull requests are welcome for improving this!
