### ISSUE TITLE
O not receiving content from the B under "normal" operations.

### ISSUE THREAD

**Issue by criticaltv** [livepeer/go-livepeer#1421]
**Describe the bug**

The O isn't receiving content from the B under "normal" operations

**To Reproduce**

1. Start an O with:
```
./livepeer-linux-amd64/livepeer -network rinkeby -orchestrator -cliAddr 127.0.0.1:7936 -httpAddr 127.0.0.1:8936 -serviceAddr 127.0.0.1:8936 -pricePerUnit 2000000000 -pixelsPerUnit 1 -ticketEV 1000000000000000 -v 99 -orchSecret secret
```
2. Enter password to decrypt private key
3. Start a T with:
```
./livepeer-linux-amd64/livepeer -network rinkeby -transcoder -orchAddr 127.0.0.1:8936 -cliAddr 127.0.0.1:7937 -httpAddr 127.0.0.1:8937 -orchSecret secret -maxSessions 1 -v 99
```
4. Start a B with:
```
./livepeer-linux-amd64/livepeer -network rinkeby -broadcaster -cliAddr 127.0.0.1:7935 -rtmpAddr 127.0.0.1:1935 -httpAddr 0.0.0.0:8935 -orchAddr 127.0.0.1:8936 -transcodingOptions P144p30fps16x9 -depositMultiplier 1 -maxPricePerUnit 5000000000 -pixelsPerUnit 1 -maxTicketEV 1000000000000000000 -v 99
```
5. Enter password to decrypt private key
6. Wait for the B to report `LPMS Server listening on rtmp://127.0.0.1:1935`
7. Start publishing into the B with:
```
ffmpeg -re -f lavfi -i testsrc=size=640x360:rate=30,format=yuv420p -f lavfi -i sine -threads 1 -c:v libx264 -b:v 1000k -preset ultrafast -x264-params keyint=30 -strict -2 -c:a aac -f flv rtmp://127.0.0.1:1935/hello_world
```
6. Observe that the B start to receive an process content
7. Run the following command:
```
curl http://127.0.0.1:8935/stream/hello_world.m3u8
```
8. Observe the following results:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=4000000,RESOLUTION=640x360
hello_world/source.m3u8
```
9. Observe that the O and T are inactive (aside from the O caching gas prices)
10. Stop the process I started in step 7.

**Expected behavior**

At step 8 above, I expect to see:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=4000000,RESOLUTION=640x360
hello_world/source.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=400000,RESOLUTION=256x144
hello_world/P144p30fps16x9.m3u8
```

At step 9 above, I expect that the B will start sending content to the O, which in turn will send content to the T for transcoding, and then the O will serve the transcoded content to the B.

**Server**
 - OS: Ubuntu 18.04
```
Livepeer Node Version: 0.5.5
Golang runtime version: gc go1.13.4
Architecture: amd64
Operating system: linux
```

**Log Files**

From the O
[Orchestrator Logs.txt](https://github.com/livepeer/go-livepeer/files/4329435/Orchestrator.Logs.txt)

From the T
[Transcoder Logs.txt](https://github.com/livepeer/go-livepeer/files/4329436/Transcoder.Logs.txt)

From the B
[Broadcaster Logs.txt](https://github.com/livepeer/go-livepeer/files/4329437/Broadcaster.Logs.txt)

**Comment by criticaltv** [comment]
Turns out that a reboot of the server solved this one...

**Comment by criticaltv** [comment]
Or it might have been that the B had no funds deposited... but the server didn't report it...

**Comment by yondonfu** [comment]
> Or it might have been that the B had no funds deposited... but the server didn't report it...

Yeah this is a bug. If the B's deposit was zero, then the node should log an error message. 

I believe the node is failing to log an error message in this case because 0.5.5 includes an [additional ticket param validation step](https://github.com/livepeer/go-livepeer/blob/ce819a15a616277a7081b5cb91339c4121a22538/server/broadcast.go#L363) before submitting a segment, but there is no error log if the ticket param validation step fails (one way this step could fail is if B's deposit is zero) with any error besides an expiration error.

Thanks for reporting! Will fix.
