### ISSUE TITLE
Streaming for 28 days continous - ended with this error (0.5.3)

### ISSUE THREAD

**Issue by criticaltv** [livepeer/go-livepeer#1422]
**Describe the bug**

After 28 days uninterrupted of using ffmpeg to publish a stream into a B, my B's stream failed, and the stream finished.

**To Reproduce**

- Run a B with the following command:
```
./livepeer-linux-amd64/livepeer -network rinkeby -broadcaster -cliAddr 127.0.0.1:7935 -rtmpAddr 127.0.0.1:1935 -httpAddr 0.0.0.0:8935 -orchAddr 127.0.0.1:8936 -transcodingOptions P144p30fps16x9 -depositMultiplier 1 -maxPricePerUnit 5000000000 -pixelsPerUnit 1 -maxTicketEV 1000000000000000000 -v 99
```
- Run a P (Publisher) with the following:
```
ffmpeg -re -f lavfi -i testsrc=size=256x144:rate=30,format=yuv420p -f lavfi -i sine -threads 1 -c:v libx264 -b:v 1000k -preset ultrafast -x264-params keyint=30 -strict -2 -c:a aac -f flv rtmp://127.0.0.1:1935/hello_world
```
- Wait for 28 days

- Observe a failure per the logs attached below

**Expected behavior**

I don't expect a B to fail :)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: Livepeer 0.5.3

**Log files**

[Broadcaster - Error after 28 days continuous streaming.txt](https://github.com/livepeer/go-livepeer/files/4329509/Broadcaster.-.Error.after.28.days.continuous.streaming.txt)
[Publisher - Error after 28 days continuous streaming.txt](https://github.com/livepeer/go-livepeer/files/4329510/Publisher.-.Error.after.28.days.continuous.streaming.txt)

**Comment by iameli** [comment]
Ah yeah, that doesn't surprise me to hear — that's a pretty common restriction with contiguous livestreams. Pertinent error:

`DTS 8 < 2147483623 out of order`

Basically the DTS — the internal decoding timestamp — rolled all the way around to the maximum 32-bit value of `2147483647` after 28 days and rolled back around to zero.

Potentially go-livepeer could do something more useful here but I also think this is probably possible to work around on the encoder's side with something like ffmpeg's `-enc_time_base` option. I'm not 100% sure how to do it, but the idea is that you make the internal DTS clock tick up more slowly, allowing for a longer livestream without restarts.

**Comment by criticaltv** [comment]
Thanks @iameli - closing, perhaps you can add a "won't fix" tag somehow?
