### ISSUE TITLE
install ffmpeg: error libx264 not found

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1440]
**Describe the bug**
Ran into an error when installing go-livepeer from source on an Ubuntu VM

At the step `./install_ffmpeg.sh` I got the following error: `error libx264 not found`

Was able to resolve by install the libx264 headers package: `sudo apt-get install yasm libvpx. libx264.`

**Comment by iameli** [comment]
Hm. The following just worked for me on a completely empty Ubuntu 18.04 Docker container:

```
apt update
apt install -y build-essential git curl autoconf automake pkg-config
git clone https://github.com/livepeer/go-livepeer /root/go-livepeer
cd /root/go-livepeer
./install_ffmpeg.sh
```

At a guess, are you maybe missing `pkg-config`? That could cause something like this.

> Was able to resolve by install the libx264 headers package: sudo apt-get install yasm libvpx. libx264.

Nothing wrong with that, though your resulting binary will now have libx264 as a runtime dependency on the host system.

**Comment by j0sh** [comment]
> Nothing wrong with that, though your resulting binary will now have libx264 as a runtime dependency on the host system.

Sometimes there are API or output incompatibilities, which is the reason for specifying a particular checkout in git. So I wouldn't encourage that path for users that are self-building unless they're comfortable troubleshooting any issues that come up. (It's more of an issue with other dependencies such as ffmpeg; less so with x264 itself which only receives minor updates these days.)

**Comment by yondonfu** [comment]
@kyriediculous Do you know if you had `pkg-config` installed when you ran into this issue? Or are you able to reproduce this issue?
