### ISSUE TITLE
livepeer_cli Orchestrator registration process failing, and not reporting error

### ISSUE THREAD

**Issue by criticaltv** [livepeer/go-livepeer#1449]
**Describe the bug**

When registering as an Orchestrator, using `13. Invoke multi-step "become an orchestrator"`, the `bond` function completed, but the `transcoder` function failed, citing an _always failing transaction_. 

No error message was logged in the `livepeer_cli`, and everything appeared to have happened successfully.

Information displayed in the `livepeer_cli`, when calling `1. Get node status` was not complete, and the Livepeer Explorer listed the node as being registered, but without accurate values for the Reward Cut and Fee Share.

**To Reproduce**

Start with enough ETH for gas, and >0 LPT

1. Run `./livepeer-linux-amd64/livepeer -network mainnet -orchestrator -cliAddr 127.0.0.1:7935 -httpAddr 127.0.0.1:8935 -serviceAddr 127.0.0.1:8935 -pricePerUnit 2000000 -pixelsPerUnit 1 -ticketEV 1000000000000 -transcoder -v 99` with version `0.5.5` - and log in with password
2. Run `./livepeer-linux-amd64/livepeer_cli`
3. Choose option `13. Invoke multi-step "become an orchestrator"`
4. Enter the following:
```
Enter block reward cut percentage (default: 10) - > 100
Enter fee share percentage (default: 5) - > 90
Enter amount of pixels that make up a single unit (default: 1 pixel) > 1
Enter the price for 1 pixels in Wei (required) > 200000000000000   
Enter the public host:port of node (default: XXX.XXX.XXX.XXX:8935)> 
You must bond to yourself in order to become a orchestrator
Enter bond amount - > 100000000000000000000
```
5. See confirmation message:
```
Transaction sent. Once confirmed, please restart your node.
```
6. Restart node, and login with password etc.
7. Run `1. Get node status` in `livepeer_cli`
8. See the following:
```
+------------------+
|ORCHESTRATOR STATS|
+------------------+
*----------------------*--------------------------------*
|               Status |                     Registered |
*----------------------*--------------------------------*
|               Active |                          false |
*----------------------*--------------------------------*
|          Service URI |                                |
*----------------------*--------------------------------*
|      Delegated Stake |                        100 LPT |
*----------------------*--------------------------------*
|       Reward Cut (%) |                              0 |
*----------------------*--------------------------------*
|        Fee Share (%) |                              0 |
*----------------------*--------------------------------*
|    Last Reward Round |                              0 |
*----------------------*--------------------------------*
| Base price per pixel | 200000000000000 wei / 1 pixels |
*----------------------*--------------------------------*
```
9. View the node's transactions on Etherscan, and see that `bond(uint256 _amount, address _to)` transaction was mined successfully, but no `transcoder` transaction.

**Expected behavior**

If the `transcoder` function doesn't succeed in being sent, due to _always failing transaction_, I would expect that the `livepeer_cli` would report that something has not happened successfully.

**Comment by kyriediculous** [comment]
Hi ! 

If the transaction can't be mined it should in theory return an error. If the transaction is mineable but is 'stuck' and waiting for it to be mined doesn't return within 600 seconds then it will timeout and also return an error.

Could you provide orchestrator logs please? Thanks !

**Comment by chrishobcroft** [comment]
Sorry for the delay in getting back to you on this @kyriediculous 

I was able to recreate situations where the following 3 errors were reported in the `livepeer` process, but _not_ reported in `livepeer_cli` during the Orchestrator setup process:

1. **current round locked** - assuming the round had not been initialised on rinkeby

2. **Orchestrator is already registered** - this one is most strange.

As you can see from [the address's account on rinkeby.etherscan.io](https://rinkeby.etherscan.io/address/0xd301cf3ed06e09938894a4689A84D3Ae08dddF9A), this address never successfully called transcoder, however the `livepeer` process reported `Orchestrator is already registered`. 

I wonder whether something was recorded in the local database, that the Orchestrator had already tried (and failed) to call `transcoder` (from "current round locked"), and thus it wouldn't allow it to call `transcoder` a second time.

3. **Round already initialized** - called to check that the round was initialised before invoking 13. I acknowledge that this is a minor issue, and also not especially part of the Orchestrator setup process. However I feel there should be better error handling for this (and any other errors) in the `livepeer_cli`

[current round locked - livepeer.log](https://github.com/livepeer/go-livepeer/files/4651186/current.round.locked.-.livepeer.log)
[current round locked - livepeer_cli.log](https://github.com/livepeer/go-livepeer/files/4651188/current.round.locked.-.livepeer_cli.log)
[Orchestrator is already registered - livepeer.log](https://github.com/livepeer/go-livepeer/files/4651189/Orchestrator.is.already.registered.-.livepeer.log)
[Orchestrator is already registered - livepeer_cli.log](https://github.com/livepeer/go-livepeer/files/4651190/Orchestrator.is.already.registered.-.livepeer_cli.log)
[Round already initialized - livepeer.log](https://github.com/livepeer/go-livepeer/files/4651191/Round.already.initialized.-.livepeer.log)
[Round already initialized - livepeer_cli.log](https://github.com/livepeer/go-livepeer/files/4651192/Round.already.initialized.-.livepeer_cli.log)

**Comment by chrishobcroft** [comment]
Further, I was able to complete a fully successful registration on Rinkeby.

Here are the logs:

[successful process - livepeer.log](https://github.com/livepeer/go-livepeer/files/4651174/successful.process.-.livepeer.log)
[successful process - livepeer_cli.log](https://github.com/livepeer/go-livepeer/files/4651175/successful.process.-.livepeer_cli.log)

**Comment by kyriediculous** [comment]
Thanks Chris, I acknowledge we can do a way better job of conveying error messages from the CLI webserver back to the user which usually doesn't happen all that often.

Currently the user is expected to check it's node logs when using the CLI but we should really pass through everything to the UI as well. 

I'll take a look at the different error paths and what we can do as quick improvements, the CLI is due for an overhaul anyway so I don't think it makes sense to spend considerable effort on fixups.

**Comment by chrishobcroft** [comment]
OK, I understand. But this is really concerning. It would appear that:

IF you try to call `transcoder`

WHEN the round is locked (i.e. during the `10%` of blocks at the end of the round when it's not possible to update `rewardCut` / `feeShare`)

THEN it fails, with `livepeer` process reporting `current round locked` and `livepeer_cli` reporting the **_false positive_** `Transaction sent. Once confirmed, please restart your node.`

When you restart with a new round, it calls `reward()` and succeeds, even though it isn't registered.

And then when you try to use `livepeer_cli` to call `transcoder` again, via the `Invoke multi-step "become an orchestrator"`, the `livepeer` process gives an error of `Orchestrator is already registered`. The `livepeer_cli` reports the false positive of `Transaction sent. Once confirmed, please restart your node.`...

**_But it never called `transcoder`!?!?!?!_**

It's very likely to be the experience of a random 10% who tried to register when the round was locked. Perhaps we could have 1/9 (11.1%) more Orchestrators... :(

Here's the key (no password), can someone try to register this as an Orchestrator using `livepeer_cli`, or perhaps by other means?

[UTC--2020-05-19T16-03-19.548204778Z--8b0423d75855fddc04bc6162c9af5acd75881809.txt](https://github.com/livepeer/go-livepeer/files/4651854/UTC--2020-05-19T16-03-19.548204778Z--8b0423d75855fddc04bc6162c9af5acd75881809.txt)

https://rinkeby.etherscan.io/address/0x8b0423d75855fddc04bc6162c9af5acd75881809

**Comment by chrishobcroft** [comment]
On startup now, this key reports `Orchestrator 0x8B0423d75855FdDC04bc6162C9af5acD75881809 is active`

Here's session output:
```
ubuntu@cibulka:~/5.5/livepeer-linux-amd64$ ./livepeer -network rinkeby -orchestrator -cliAddr 127.0.0.1:7935 -httpAddr 127.0.0.1:8935 -serviceAddr 127.0.0.1:8935 -pricePerUnit 2000000 -pixelsPerUnit 1 -ticketEV 1000000000000 -transcoder -v 99
I0519 22:03:26.290582   52791 livepeer.go:204] ***Livepeer is running on the rinkeby network: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea***
I0519 22:03:26.291414   52791 db.go:316] Initialized DB node
I0519 22:03:27.961999   52791 accountmanager.go:61] Found existing ETH account
I0519 22:03:27.962024   52791 accountmanager.go:188] Defaulting to first ETH account in keystore 0x8B0423d75855FdDC04bc6162C9af5acD75881809
I0519 22:03:27.962041   52791 accountmanager.go:70] Using Ethereum account: 0x8B0423d75855FdDC04bc6162C9af5acD75881809
I0519 22:03:28.597191   52791 accountmanager.go:104] Unlocked ETH account: 0x8B0423d75855FdDC04bc6162C9af5acD75881809
I0519 22:03:28.597399   52791 client.go:215] Controller: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea
I0519 22:03:28.878461   52791 client.go:236] LivepeerToken: 0x23b814a57D53b1a7A860194F53401D0D639abED7
I0519 22:03:29.206111   52791 client.go:257] ServiceRegistry: 0xa7AFBB45eb8C27a26379F9C550B3b9be7f09c3eA
I0519 22:03:29.493369   52791 client.go:278] BondingManager: 0xe75a5DccfFe8939F7f16CC7f63EB252bB542FE95
I0519 22:03:29.788615   52791 client.go:299] TicketBroker: 0x40897Ff6e44Ca2e145A691701897844669Bf7cee
I0519 22:03:30.063024   52791 client.go:320] RoundsManager: 0x572d1591bD41f50130FD0212058eAe34F1B17290
I0519 22:03:30.339785   52791 client.go:341] Minter: 0xe5056d1fE48F562dd8AcB1BBFFa147223d448C1B
I0519 22:03:30.614417   52791 client.go:362] LivepeerTokenFaucet: 0x6b752dA302C80795ACc9347AF8f472D3473b19f2
I0519 22:03:30.924897   52791 livepeer.go:469] Price: 2000000 wei for 1 pixels
 
I0519 22:03:32.571035   52791 livepeer.go:898] Orchestrator 0x8B0423d75855FdDC04bc6162C9af5acD75881809 is active
I0519 22:03:32.833344   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:03:33.092733   52791 livepeer.go:777] ***Livepeer Running in Orchestrator Mode***
I0519 22:03:33.092912   52791 webserver.go:70] CLI server listening on 127.0.0.1:7935
I0519 22:03:33.092831   52791 mediaserver.go:141] Transcode Job Type: [{P240p30fps16x9 600k 30 426x240 16:9} {P360p30fps16x9 1200k 30 640x360 16:9}]
I0519 22:03:33.093045   52791 cert.go:83] Private key and cert not found. Generating
I0519 22:03:33.093655   52791 cert.go:22] Generating cert for 127.0.0.1
I0519 22:03:33.094537   52791 rpc.go:155] Listening for RPC on 127.0.0.1:8935
I0519 22:03:35.093878   52791 rpc.go:223] Connecting RPC to https://127.0.0.1:8935
I0519 22:03:35.099447   52791 rpc.go:195] Received Ping request
I0519 22:03:38.110095   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:03:43.116890   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:03:48.110779   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:03:53.104626   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:03:58.095271   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:04:03.131215   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:04:08.095998   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:04:13.111827   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:04:18.101139   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:04:23.090515   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:04:28.092846   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
I0519 22:04:33.100439   52791 gaspricemonitor.go:134] Cached gas price: 1000000000
```

**Comment by chrishobcroft** [comment]
OK, further to offline conversation with @yondonfu, it appears that an Orchestrator registers by virtue of bonding to itself. It then becomes active in the next round, and can call `reward`.

This explains why any further calls of `13. Invoke multi-step "become an orchestrator"` result in error (at least in the `livepeer` process, if not in the `livepeer_cli` itself).

The issue relating to the `livepeer_cli` misleading new Orchestrators who try to register when round is locked is still open though, and I have raised another issue to describe that case specifically https://github.com/livepeer/go-livepeer/issues/1509

I will also leave this issue open, to guide any work being done on improving the error handling, and error reporting in the `livepeer_cli`.

**Comment by kyriediculous** [comment]
Yeah not all CLI operations wait for the tx to be mined, this is an inconsistency.

Even when you don't change any on-chain parameters through that CLI option it will logged to check a tx even though there is nothing to check for or to wait mining for. 

Thanks for reporting these issues. I have brought up the CLI rework many times but at this point reliability that can drive demand onto the network is just a bigger priority at the moment.
