### ISSUE TITLE
Change default `-transcodingOptions` to include 144p (P144p30fps16x9)

### ISSUE THREAD

**Issue by criticaltv** [livepeer/go-livepeer#1451]
**Problem statement**

The current default option for the transcoding requested by a B does not demonstrate the full potential of Livepeer, in terms of making content _as lightweight as possible_ in terms of bandwidth required.

The default options for transcoding are `360p` (that's 640x360 pixels = 230,400 pixels) and `240p` (426x240 pixels = 102,240 pixels). Livepeer is (currently) able to transcode to as little as `144p` (that's 256x144 pixels = 36,864 pixels).

`144p` requires approximately 36% of the bandwidth required by `240p`, and requires approximately 16% of the bandwidth required for `360p`, hence significantly less bandwidth is required to consume a stream in `144p`.

**Proposed solution**

I propose that the default options for transcoding should be `144p` and `240p`.

**Describe alternatives you've considered**

Other options:

- `144p` and `720p`
  - Pros: demonstrates a broader range of transcoding options.
  - Cons: source content is less likely to be larger than `720p` than larger than `240p`
- `144p`, `240p` and `360p`
  - Pros: shows a broader range of capabilities.
  - Cons: it may overload a O/T in terms of processing power.
- `144p` only
  - Pros: lowest barrier to entry for a O/T to service, cuts down on bandwidth / processing power required for initial use
  - Cons: doesn't demonstrate that multiple transcoding options are possible, reduces O/T default revenue.

**Additional context**

Thank you for reading my contribution.

**Comment by thomshutt** [comment]
Hey @criticaltv, thanks for submitting this issue and sorry that it's taken us so long to get to it.

Since the aim of the default profile set is to provide for the majority use case, I think that 144p is probably too low to be useful; people operating in bandwidth-constrained environments etc. can still choose to use it as part of a custom profile set, so I'm going to close this issue.
