### ISSUE TITLE
implement `accept: application/x-tar` in addition to `accept: multipart/mixed`

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#1454]
I think this would be a good idea at some point... it's kind of difficult to write a simple `curl` command-line example with multipart return that actually outputs the right files. Supporting `accept: application/x-tar` would make that very easy, would be nice for documentation.

(Cursory Googling indicates there's no official MIME type for an uncompressed `tar` archive but [Wikipedia says `application/x-tar` is in use](https://en.wikipedia.org/wiki/List_of_archive_formats) so that's good enough for me.)

**Comment by hthillman** [comment]
closing because of move to stream-based transcoding
