### ISSUE TITLE
Transcode long segments

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1478]
## Abstract

Much of the code base was built around the assumption of processing [2-second segments](https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/server/mediaserver.go#L57). Transcoding longer segments is a useful capability to have. One of the barriers to handling longer segments is our use of a fixed timeout for transcode requests, set at 8 seconds in a few places around the codebase: ([1](https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/server/segment_rpc.go#L45)) ([2](https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/core/orchestrator.go#L682-L692))([3](https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/server/segment_rpc.go#L110-L116)).

Rather than use a fixed timeout, the segment duration should be used as the basis for the timeout.

Accommodating longer segments via expanded timeouts can be accommodated on the broadcaster in a relatively low-risk manner. A PR is open for this: https://github.com/livepeer/go-livepeer/pull/1477

Accommodating longer segments on the orchestrator, however, is more fraught due to the risk of DoS and under-payment.

This spec seeks clarity on a few issues:

* Timeout multiplier
* Hard cap on segment lengths
* Orchestrator processing of longer segments in on-chain mode
* Any other considerations that may have been overlooked.

## Segment Duration

We will depend on the segment duration as supplied by the HLS segmenter (for RTMP ingest) or the `Content-Duration` header for HTTP ingest. The default length for a missing Content-Duration remains at 2 seconds ([1](https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/server/mediaserver.go#L667-L671)).

If the `Content-Duration` is missing, then the received segment could be probed in an attempt to determine its duration. However, implementing this probe is out of scope right now, as users have indicated they already have the information necessary to supply the duration. Note there are some drawbacks to probing: increased CPU processing requirements, increased latency, and a requirement to have the segment available on the broadcaster, which would negate any advantage from use cases such as pre-posting the segment to an object store so the broadcaster only needs to pass through the URL without fully downloading the segment.

At the moment, the duration is taken at face value. Some minor consequences of mis-specifying the duration on the broadcaster are as follows: this would have effects on latency calculations for O selection, and result in incorrect playlist values if HLS playback is used. Other more significant consequences of mis-stating the duration are described below. 

## Timeout multiplier

Currently, our 8-second fixed timeout has an implicit multiplier of 4 with assumed 2-second segments. The PR in https://github.com/livepeer/go-livepeer/pull/1477/ keeps that multiplier of 4 against the segment duration.

For example, a 10-second segment would have a timeout of 40 seconds. A 1-minute segment would have a timeout of 4 minutes. To accommodate the overhead associated with extremely short segments, the minimum timeout remains at 8 seconds. This minimum was simply carried over from the old timeout, but can be adjusted as needed.

Setting the multiplier lower makes the broadcaster fall back more quickly to seek out faster orchestrators, at the expense of a lower success rate in marginal situations when most of the network is under load.

This multiplier could be adjustable via CLI flags, or even on a per-stream basis to tune the quality-of-service, but that feature is likely out of scope for now. For example, a multiplier of <1.0 could be used to enforce faster-than-realtime transcoding to cope with live streams, but this substantially increases the risks of drops, and requires more headroom in the network's provisioned capacity.

### Hard cap on segment lengths

Some sort of hard cap on segment lengths is probably needed. 5 minutes? 10? 15? 20? 
The current recommendation is a hard cap of 5 minutes. 

With a multiplier of 4, the maximum timeout for a 5-minute segment would be 20 minutes. For 15 minutes, an hour. Longer timeouts increase the risk of a broken connection. At the moment, there is no way to recover a transcode from a broken connection. A long-term solution to accommodate extremely long segments, such as full VOD videos, might include "fire-and-forget" functionality where the results could be submitted and then queried later, but that is out of scope at the moment.

Because the duration is user-specified via HTTP push, there are a few consequences to mis-stating the duration on the broadcaster:

* If the broadcaster takes input from semi-trusted sources, then over-specifying the duration could result in over-payment to the orchestrator. A smaller hard cap minimizes the value at risk.

* This hard cap may not be absolute. The duration could also be under-specified for longer segments in the hopes that the transcode completes before the timeout triggers. From the broadcaster's perspective, this is probably an OK trick, but the orchestrator does need to be aware of it as described below.

### Orchestrator processing of longer segments in on-chain mode

Orchestrators face a substantial risk of under-payment when processing longer segments. Currently, the broadcaster does take the segment duration into consideration when [estimating fees](https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/server/segment_rpc.go#L559-L560). However, the orchestrator does not double-check that fee estimation, due to not having the segment duration available.

Currently, the segment duration is not transmitted to the orchestrator, and timeouts are fixed at 8 seconds in various places on the O side, eg for transcode requests to [standalone T](https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/core/orchestrator.go#L682-L692). Accommodating longer segments would likely require transmitting the segment duration to the orchestrator, in order to appropriately set a time-out for transcode requests to remote Ts.

The broadcaster does not currently have an incentive to be honest about the segment's true duration, and the orchestrator wants to avoid a probing step for the same reason we'd prefer the broadcaster receive a pre-computed duration via the`Content-Duration` header. There are a few reasons the orchestrator wants an accurate duration: the orchestrator only wants to handle the request for as long as necessary, and the duration gives some indication of how much the transcode should cost. Further, the duration information could also be incorporated into [load balancing](https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/core/lb.go#L218).

One way to mitigate this is to have the orchestrator receive the duration from the B, estimate the fees based on the duration, then compare that estimate against the [total EV](https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/core/orchestrator.go#L156) of the received tickets, and rejecting the payment if the estimate is greater than the total EV.

This isn't a watertight: the broadcaster could still send a low duration in the hopes that the transcode completes before the timeout. And it doesn't actually stop the transcode itself, whether on a remote T or a combined OT node. The best way to mitigate understated durations would be to short-circuit the transcoding: https://github.com/livepeer/lpms/issues/129. While the broadcaster should make up any deficit on the next segment, it's less likely that there will be a "next segment" if the segments themselves are long. (A hard cap on segment durations for the orchestrator is less helpful than it appears; the broadcaster could always lie about the duration, absent short-circuit transcoding, and it's not clear how to make this work with existing broadcasters that currently don't supply the duration.)

Note there is a bug with fee estimation right now. In FPS pass-through mode, the frame rate is set to zero. This results in an estimated fee of zero due to the calculation of `[outputPixels=w*h*framerate*duration](https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/server/segment_rpc.go#L559-L560)`. The workaround could be to conservatively estimate the framerate as 60fps or 120fps. Short-circuit transcoding would also help mitigate this issue.

### Other Considerations

Unknown. More feedback welcome as to the risks and mitigations of handling longer segments.

**Comment by chrishobcroft** [comment]
I have only one question on this - which is whether this optimisation is primarily to help cater for Video-on-demand (VOD) transcoding, and thus inevitably dilutes focus on optimising for Livestream transcoding.

**Comment by ericxtang** [comment]
@chrishobcroft this particular issue is mostly for VOD transcoding.  While VoD would definitely take some effort to get right, it could also bring a tremendous amount of transcoding demand to the network.  It can also help GPU miners without super fast networking connection to win work and earn money on the network.  Pretty interesting!

**Comment by kyriediculous** [comment]
I think we should definitely support arbitrary segment lengths at some point (up until a certain limit). 

> It can also help GPU miners without super fast networking connection to win work and earn money on the network. 

Ah I feel like this is actually the opposite , cfr block size debate. Larger segments will require more bandwith to download and upload within an acceptable time and actually compete out smaller GPU miners that don't have access to as much affordable bandwith.  

There's counters to this as well though:
- timeout could grow linear with segment duration
- segment duration of a couple of seconds will still not require data center level bandwith for an operator (I hope?)

However if we want to take into account remote transcoding setups as well (eg crypto miners connecting to Livepeer inc O's) then they would require access to better bandwith as well which makes it a cascading effect.

**Comment by j0sh** [comment]
@chrishobcroft This would help for VOD that is pre-segmented but not necessarily on 2-second boundaries. Or even live videos; nothing says these have to be 2 second segments, either.

I agree that trying to accommodate both live and full-length VOD under the same workflow is a recipe for mediocrity. The current workflow is still heavily tuned for live transcoding, and this isn't going to change.

As the writeup mentions, supporting full length VOD would need a lot more work. If we ever get to that point, my suspicion is that would entail a different approach to processing video in order to better leverage the properties of VOD, rather than trying to compromise the current workflow to support one or the other.

**Comment by yondonfu** [comment]
> This multiplier could be adjustable via CLI flags, or even on a per-stream basis to tune the quality-of-service, but that feature is likely out of scope for now.

I like the idea of starting off with a multiplier flag that applies to all streams.

> A smaller hard cap minimizes the value at risk.

Did some quick math to get a better sense of how much value might be at risk for this hard cap:

If the ETH/USD price = $165 and an O is charging $1 per hour for a 1080p @ 30fps stream transcoded to 720p, 480p, 360p @ 30fps then the minimum payment (factoring in both decoded & encoded pixels) per 5 min segment would be:

```
# 108979200 = pixels per second
# 300 = seconds per segment
# 15447.91743 = price per pixel (wei)
# 10 ** 18 = wei per ETH
# 165 = ETH/USD price
(((108979200 * 300) * 15447.91743) / (10 ** 18)) * 165 = 0.0833333333177790
```

Of course the value at risk also increases with the price per pixel that B is willing to pay, but a cap of 8 cents of value at risk per segment in the setting described might be reasonable although we should encourage users to use segment lengths shorter than the cap if possible to minimize the value at risk.

> estimate the fees based on the duration, then compare that estimate against the total EV of the received tickets, and rejecting the payment if the estimate is greater than the total EV.

This might be tricky once O charges for decoding as well since O wouldn't know the resolution or FPS of the segment - B might have to also signal the segment resolution and FPS to O.

Seems like this check would be unnecessary if short-circuited transcoding is implemented Regardless of whether B overshoots or undershoots the segment duration, O will only transcode as many pixels that are paid for by B.

IIUC, even with short-circuited transcoding, signaling the segment duration would still be useful for:
- Setting timeouts on the O (both for itself in OT mode or for a remote T)
- Estimating the transcode cost for load balancing

I thought a little bit about whether B could signal the timeout instead of the segment duration. 

If B signals the timeout then O can use that timeout for both itself in OT mode or for a remote T - the timeouts set by O wouldn't be perfectly aligned with the timeout set by B since O won't start the timer until it receives the request, but they would be a rough approximation of the timeout set by B. This might be useful for establishing a service agreement between B & O - if O finishes transcoding within the timeout, it will debit the transcoding fees from its view of the stream balance and if O does not finish transcoding within the timeout, it will not debit the transcoding fees from its view of the stream balance because it did not meet the requirements of the service agreement and because B is no longer listening for the result. Using the timeout value for the transcode cost estimation for load balancing may not work though since the timeouts could be based on different multipliers set by B...

> Note there is a bug with fee estimation right now. In FPS pass-through mode, the frame rate is set to zero...The workaround could be to conservatively estimate the framerate as 60fps or 120fps.

Ah right. That workaround of conservatively estimating the FPS seems reasonable.

**Comment by j0sh** [comment]
> I like the idea of starting off with a multiplier flag that applies to all streams.

To be clear, I was going to just hard code the multiplier in. We can have a node-wide flag for either the multiplier, or the max duration if folks think that's something that we'll want to tune in the short term. Other than the capability to support longer segments, we haven't really needed these types of knobs in the past. Not sure if we're going to need them in the near future either, given that this is approaching the limits of the current segment transcoding architecture anyway.

Flags would be easy to add but I just want to make sure it's generally *useful* and won't lead to confusion among users trying to adjust knobs with unclear outcomes. At the very least, we'd need to gravitate towards having a better documentation process, because I think we need more than a one-line description for the effects of adjusting the timeout multiplier. https://github.com/livepeer/go-livepeer/issues/708

Long term, it might be too coarse of a knob to be handled globally; for a B that handles diverse content, we probably want a more robust strategy to handle this. Maybe it's a per-stream knob, maybe it's dynamically determined based on the input and transcoding config, etc. Not sure yet.

> a cap of 8 cents of value at risk per segment in the setting described might be reasonable although we should encourage users to use segment lengths shorter than the cap if possible to minimize the value at risk.

Thanks for running the numbers!

This is where the "semi-trusted source" qualification comes from, eg if a B is running a public SaaS, then the value-at-risk is an externality for the B's customers. So it seems desirable for the B to be able to clamp down on that risk.

> This might be tricky once O charges for decoding as well since O wouldn't know the resolution or FPS of the segment ... Seems like this check would be unnecessary if short-circuited transcoding is implemented

Agreed, short-circuit transcoding would solve a lot of things for us. 

> if O does not finish transcoding within the timeout, it will not debit the transcoding fees from its view of the stream balance because it did not meet the requirements of the service agreement and because B is no longer listening for the result

Haven't we been operating under the assumption that if an error occurs, the transcoding fees are considered "spent" ? It's been a while since I've traced through that portion of the code though.

Debiting fees based on an implicit SLA is an interesting idea. Actually enforcing this, eg accounting for transport latency, might be tricky. We'd also need a much better mechanism for workload estimation, which may be difficult to generalize across diverse hardware and transcoding configurations.

**Comment by yondonfu** [comment]
> Flags would be easy to add but I just want to make sure it's generally useful and won't lead to confusion among users trying to adjust knobs with unclear outcomes

Makes sense 👍 Hardcoding the multiplier for now sounds good to me.

> So it seems desirable for the B to be able to clamp down on that risk.

Later on it may make sense for B to be able to control this. But, as with the timeout multiplier, starting off with a hardcoded value until there is a strong reason to expose an adjustable knob makes sense to me.

> Haven't we been operating under the assumption that if an error occurs, the transcoding fees are considered "spent" ?

Yeah good point. I was initially thinking about the case where after an error O debits fees such that B's balance is negative and then B encounters a insufficient balance error when submitting a segment to O before its balance is cleared. But, this is less likely to occur now that B is estimating fees when sending a payment (we'll just need to fix the current bug with passthrough FPS) which reduces the likelihood that B's balance would be negative after O debits fees and since O will be suspended for a period of time after returning an error which reduces the likelihood of B submitting a segment to O before its old balance is cleared. 

Will think about the debiting fees based on a SLA idea some more separately. Since as you mention accounting for transport latency is tricky and since sending the segment duration makes it easier to do transcode cost estimation for load balancing, sending the segment duration seems like the best option for now.
