### ISSUE TITLE
 "error processing payment: orchestrator is inactive" -> but orchestrator is active

### ISSUE THREAD

**Issue by 0xVires** [livepeer/go-livepeer#1482]
**Describe the bug**
Getting the following error messages:
`error processing payment: orchestrator is inactive, cannot process payments`
But my orchestrator is active and successfully calling rewards and the round is initialized.

**Screenshots**
![image](https://user-images.githubusercontent.com/25792899/81064212-91008800-8ed9-11ea-9005-9b6517c6ddaf.png)

**Comment by kyriediculous** [comment]
Thanks for opening the ticket.

I'm just going to add some additional information from our discord conversation

1. Is it possible that the orchestrator address used to do the self active check has been overwritten by another address as shown in this pic? Coincidentally that is an inactive orchestrator. This would be strange though as no changes happened to this area of the codebase that could result in significant operational differences. 

DB dump:

![image](https://user-images.githubusercontent.com/22256858/81070295-4f74da80-8ee3-11ea-8de1-c71a07e5311f.png)


2. This is a fresh install on 0.5.6
yes, but the point is that this is not my orchestrator... never seen this address
pulled the latest livepeer release 5 days ago - installed on a fresh server


3. O shows as _active_ in the orchestrators's own DB as well as in the explorer. 


Hunch for reproduction steps in a local environment:

Register two O's on-chain 
Start node for first O
Fully unbond second O
See if first O is still considered "active" on a node level. 

Alternative explanation could be that the `currentRound` used in the `DBOrchFilter` for the `orch.isActiveCheck` was actually lower than the O's `activationRound` (1611).

**Comment by 0xVires** [comment]
update: After restarting the node, the problem seems to be gone. I received a few test streams and didn't get the `error processing payment: orchestrator is inactive, cannot process payments` again.

**Comment by kyriediculous** [comment]
From an other user report it seems like the CLI does report the node as active, but the node process itself does not. 

The CLI grabs the data on-chain while the node process assesses the current round vs the O's activation/deactivation round

Since we know this is either an issue with the `currentRound`, `activationRound` or `deactivationRound` values it would be good to know what the latest  `NewRound` event is and what the state of the values in the database is.

**Comment by pschroedl** [comment]
is this a duplicate of https://github.com/livepeer/go-livepeer/issues/1610 and https://github.com/livepeer/go-livepeer/issues/1777?

**Comment by yondonfu** [comment]
Based on a DB dump of the orchestrators table that an affected user provided in Discord, I suspect an old `updatedAt` timestamp recorded for the orchestrators might be the cause of this issue.

When an orchestrator query is constructed, there is a clause that filters out orchestrator entries that haven't been [updated in the last day](https://github.com/livepeer/go-livepeer/blob/e1518db8fb0350c520c6b304a1fb7046380dc3da/common/db.go#L825). The `updatedAt` timestamp for an orchestrator entry is updated whenever [UpdateOrch()](https://github.com/livepeer/go-livepeer/blob/e1518db8fb0350c520c6b304a1fb7046380dc3da/common/db.go#L497) is called. At the moment, an active orchestrator node will invoke the `UpdateOrch()` method for its own ETH address:

- On node startup
- When a [new round event is received](https://github.com/livepeer/go-livepeer/blob/master/eth/watchers/orchestratorwatcher.go)

I suspect there may be a problem with the latter.
