### ISSUE TITLE
Update stakes for O's after node startup

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1485]
**Is your feature request related to a problem? Please describe.**
Currently the stakes for an orchestrator are updated in the DB _on node startup only_

https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/discovery/db_discovery.go#L57

We currently cache the orchestrators in the DB on a set interval 
https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/discovery/db_discovery.go#L222

https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/discovery/db_discovery.go#L23

We should really update orchestrator stakes after node startup as well so that the broadcaster always has an up to date view of recent stake weights. There's two possible solutions here

**Solution 1 (Naive but quick)** 
Add a call to cache the stakes to the ticker

**Solution 2 (Good but little more engineering work)**
Since stake weights are determined from _active_ stake , which is only updated at the beginning of a round we can get away with only caching the stake when receiving a "New Round"  event. This can be accomplished by subscribing to  the `roundsWatcher`. 

The benefit of solution 2 is that it  reduces the number of remote ETH node requests, which can be beneficial for end users now we have discontinued "sponsored" infura endpoints and have adopted a BYON (bring your own node) policy

**Comment by yondonfu** [comment]
As discussed offline, the node already implements solution 2 [here](https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/eth/watchers/orchestratorwatcher.go#L166) so closing this.
