### ISSUE TITLE
Automatically determine if node is a transcoder in livepeer_cli

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#150]
TODO - 
* Add a "Transcoder" field in LivepeerNode and accept an additional parameter in NewLivepeerNode() (livepeernode.go) 
* Set it in livepeer.go depending on `*transcoder`
* Add an endpoint in webserver.go called `/isTranscoder` to determine if the node is started as a transcoder
* Call `/isTranscoder` when starting livepeer_cli to determine if the node was started as a transcoder.

**Comment by rahulbansal16** [comment]
I am picking this up !!

**Comment by rahulbansal16** [comment]
What will be the value of the trancoder.Transcoder in the livepeer.go ?
whatever I understood is, I need to have *transcoder.Transcoder field in livepeerNode.go
and after that I need to modify the NewLivepeerNode function to pass a transcoder.Transcoder object which is FFmpegSegmentTranscoder in the livepeer.go file line number 169?

**Comment by ericxtang** [comment]
I think we can just have a bool in livepeerNode to indicate whether the node is started as a transcoder for now, so no need for referencing the FFmpegSegmentTranscoder.  (btw, make sure you have the latest version - I see something different in livepeer.go line 169)

**Comment by rahulbansal16** [comment]
@ericxtang correct me if I am wrong, If the transcoder_cli is running without -transcoder flag, then I will check the status of the livepeernode and I will set the wizard.Transcoder status based on that, but if the -transcoder flag is already set in that case I need not check the status, because the user may want to enable the node as transcoder.

**Comment by ericxtang** [comment]
@r-a-x I think the point here is to remove the `-transcode` flag in livepeer_cli, the cli will just always check the endpoint and see if the node was started as a transcoder, and display the appropriate UI. (We assume the node is already started when we run livepeer_cli)

**Comment by ericxtang** [comment]
Done
