### ISSUE TITLE
Add more flexibility to -transcodingOptions

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1503]
## Problem Statement

By default, a Broadcaster is limited to only being able to request that an Orchestrator transcodes into one or more from 13 transcoding profiles.

This is too limiting, as:

1. It fails to cater to the vast majority of "screen resolutions that are defined by standards or in common use" (source: [wikipedia](https://en.wikipedia.org/wiki/List_of_common_resolutions)), or "systems that have a lower screen resolution" (source: [wikipedia](https://en.wikipedia.org/wiki/Low-definition_television#Resolutions)).

2. The aspect-ratio requested by the Broadcaster is overlooked by the Orchestrator/Transcoder, which instead chooses to return content in the same aspect-ratio as the source (see https://github.com/livepeer/go-livepeer/issues/1501).

## Analysis

Current available options are:

| Aspect | Frame size | 25fps | 30fps | 60fps |
|-------:|------------|------:|------:|------:|
|   16x9 | 256x144    |       |   **YES** |       |
|    4x3 | 320x240    |       |   **YES** |       |
|   16x9 | 426x240    |   **YES** |   **YES** |       |
|    4x3 | 480x360    |       |   **YES** |       |
|   16x9 | 640x360    |   **YES** |   **YES** |       |
|    4x3 | 960x720    |       |   **YES** |       |
|   16x9 | 1024x576   |   **YES** |   **YES** |       |
|   16x9 | 1280x720   |   **YES** |   **YES** |   **YES** |

Observations

1. Options are heavily biased towards a `16x9` (10 of 13).

2. Options are heavily biased towards streaming in `30fps` (8 of 13).

3. Options for other frame-rates (e.g. `25fps` or `60fps`) are entirely biased toward streaming in `16x9` aspect ratio.

4. There are no options for transcoding into e.g. 1920x1080, which will likely become more necessary with the rapid emergence of 4k / 8k cameras

## Requirements

As a Broadcaster, I want more control over what Transcoding I can request.

**First and foremost**, I would like to be able to limit the **video-bitrate** of each outputted stream, in order to allow me to adapt content to all network speeds.

I consider this to be Livepeer's "killer feature": increasing the accessibility of content by reducing the _download bitrate_ required to retrieve the content. I acknowledge that the act of reducing frame-size and frame-rate tends to reduce the **video-bitrate**, however this is not something that can be specifically requested by a Broadcaster.

Specifically, I would like to have the flexibility to limit the output **video-bitrate** based on the instructions shown in [FFmpeg's wiki page on Limiting the output bitrate](https://trac.ffmpeg.org/wiki/Limiting%20the%20output%20bitrate).

**Secondarily**, I would like to be able to configure the exact **frame-size** of the outputted stream, in order to allow me to scale content to all screen resolutions that are defined by standards or in common use (source: [wikipedia](https://en.wikipedia.org/wiki/List_of_common_resolutions))

Specifically, I would like to have the flexibility to configure scaling based on [FFmpeg's wiki page on Scaling](https://trac.ffmpeg.org/wiki/Scaling). Perhaps the first step can be to allow a B to configure only "the scale filter in its most basic form" defined under "Simple Rescaling".

**Thirdly, and finally**, I would like to be able to change the **frame-rate** of the transcoded content. For example, being able to reduce the frame-rate allows a B to reduce the video's bitrate while maintaining the quality of individual frames (albeit with less smooth video playback).

## Example Use

1. When starting a `-broadcaster` with:
```
./livepeer -broadcaster \
                -transcodingOptions \
                maxrate14400
```

This will request one transcoded stream with the same _frame-rate_ and _frame-size_ as the source, but with maximum bitrate of 14.4 kbps.

2. When starting a `-broadcaster` with:
```
./livepeer -broadcaster \
                -transcodingOptions \
                maxrate14400;maxrate56600
```

This will request two transcoded streams, both with the same _frame-rate_ and _frame-size_ as the source, but:

1st. with maximum bitrate of 14.4 kbps
2nd. with maximum bitrate of 56.6kbps.

3. When starting a `-broadcaster` with:
```
./livepeer -broadcaster \
                -transcodingOptions \
                maxrate14400framesize256:144;maxrate56600;framerate1
```

This will request three transcoded streams:

1st. same framerate as source, frame size 256:144, maximum bitrate of 14.4 kbps.
2nd. same framerate and framesize as source, and maximum bitrate of 56.g kbps.
3rd. same frame size as source, frame rate of 1 frame-per-second, and default bitrate.

4. When starting a `-broadcaster` with:
```
./livepeer -broadcaster \
                -transcodingOptions \
                maxrate512000framesize640:-1
```

This will request one transcoded stream with the same frame-rate as the source.

## Additional Context

Livepeer relies very heavily on `FFmpeg` as a technology. Further, many developers who may find Livepeer useful, may already be familiar with how to use `FFmpeg`.

Aligning the terminology to `FFmpeg` will reduce barriers to entry for users who view Livepeer as a way to outsource anything they currently do "in-house" using `FFmpeg`.

In addition to the proposal to align terminology, I believe there would be substantial value to be gained by enabing other features already included in `FFmpeg`.

**Comment by j0sh** [comment]
Most of what you're asking for can be accomplished via [webhook configuration](https://github.com/livepeer/go-livepeer/blob/master/doc/rtmpwebhookauth.md) [1].  Being able to configure transcoding preferences in more detail via the CLI is sensible, but that work likely has to be scoped out some more (eg, structure of the flags / options). My guess is it'll be less unwieldy to use a config file - https://github.com/livepeer/go-livepeer/issues/101 .

[1] The exception is we currently don't have a way to pass through the resolution. That can be addressed separately.

**Comment by hthillman** [comment]
This is all supported via json file: https://github.com/livepeer/go-livepeer/blob/master/doc/transcodingoptions.md
