### ISSUE TITLE
Allow Broadcaster to publish a content index on the same port as streams are served.

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1504]
**Is your feature request related to a problem? Please describe.**

It is not possible for a Broadcaster to publish an index of content being served without exposing itself to unnecessary security risks.

By default, the B does publish a full index of current streams at `:7935/status`, however there are undesirable implications to opening port `7935` for public access: this is the port that the `livepeer_cli` connects to.

The B can also choose to publish `:8935/stream/current.m3u8` on the same port that it publishes video content, however this only includes the stream which started most recently (if it's still streaming). More details in https://github.com/livepeer/go-livepeer/issues/1492.

**Describe the solution you'd like**

I would like to be able to configure a Broadcaster to serve a content index on the same port as streams are served.

This index should be disabled by default, but enabled by running `livepeer` with the `-broadcaster` and `-index` flags.

A proposed approach would be for the index to contain 1 entry for each individual input stream, keyed off the stream-key, containing metadata to locate the source + all transcodings of that input stream.

For example, if there are 6 `rtmp` streams being published into the Broadcaster, the index would contain the following entries:
```
/stream/hello_world.m3u8
/stream/chrishobcroft.eth.m3u8
/stream/0xDAC817294c0c87ca4fA1895eF4b972EAde99f2fd.m3u8
/stream/0x3be017ff0f949e247110173E862bBE2D39ca04A1.m3u8
/stream/0x4b4E19E18EbADdFB57DC1f07E07268b827A0EC18.m3u8
/stream/0xd6E9bA2F0fB21e29Cb984d948C043bA26A97467f.m3u8
```

and then for example, running a `curl http://127.0.0.1:8935/stream/hello_world.m3u8` would give:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=4000000,RESOLUTION=426x240
hello_world/source.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=400000,RESOLUTION=256x144
hello_world/P144p30fps16x9.m3u8
```

The details for a) how an index should be formatted (e.g. `json`, `xml`, `html`, `m3u8`,  etc.), b) what additional meta-data is included in an index (e.g. current sequence number, program-id, etc.) can be decided as part of the implementation.

**Describe alternatives you've considered**

- exposing port 7935 - undesirable

- parsing content served on 7935 and publishing an index on another port - hacky

**Additional context**

With this feature, the B becomes substantially more useful as a way for **Consumers** to _discover_ content being broadcast using Livepeer.

**Comment by j0sh** [comment]
> parsing content served on 7935 and publishing an index on another port - hacky

What's wrong with this approach? Having a proxy that can filter routes is SOP for most production deployments.

There is something to be said for making data better structured / more accessible from the CLI port. Feel free to make an issue for that. But I'm not sure about putting diagnostic / usage information on the main streaming port.

**Comment by chrishobcroft** [comment]
@j0sh thanks again for your prompt response on these matters.

> I'm not sure about putting diagnostic / usage information on the main streaming port.

Can you clarify what you mean "diagnostic / usage information"?

The proposed feature is solely about exposing an index of content being broadcast "on the main streaming port".

Not so much about usage or diagnostics.

> What's wrong with this approach?

Right now, `livepeer` is able to empower a Broadcaster with some pretty powerful tools. By simply running `./livepeer -broadcaster`, they get a [simple multi-channel livestreaming platform](https://github.com/videoDAC/simple-streaming-server). This may seem insignificant to you, but as a tool for decentralised freedom of speech and expression, it's yuge.

But there's a catch... if a B then wishes to publish an index of what content is streaming, they then have to _also_:

a) install a web server,
b) configure it to proxy a URL from an "internal" port,
c) open an additional public port alongside `8935` to serve content `index`,
d) communicate to whomever is developing systems to consume / playback content that they need to manage connection to 2 ports on the Broadcaster (and the reasons why),
e) support / manage this extra complexity.

Now, you (@j0sh) understand well how to set something like this up. I could also work out how to set something like this up. But the vast majority of users (e.g. Transcoders, Orchestrators, Broadcasters) would need to have a strong incentive to go through all this, and it's often difficult to get their focus, especially with so many other decentralising permissionless projects to evaluate, and YouTube / Facebook livestreaming is "just easy, and it works".

If only it could be as easy as running `./livepeer -broadcaster -index`, then it has the power to appeal to a far wider community, and could even result in Broadcasters building their own registries of content on Ethereum, and then there is a possibility that Livepeer could actually get users in the form of people watching content being streamed via Livepeer... from the grass-roots (as well as via corporate partnerships via Inc.)

With an `index` published on "the main streaming port", this would be enormously beneficial... allowing Broadcasters to easily share, and Consumers to discover. Without it, we're back to a conversation about a) through e).

>  Having a proxy that can filter routes is SOP for most production deployments.

Perhaps you're right.

However, this feature isn't catering to "production deployments" in the traditional sense, run by people who are seasoned devOps professionals who know how to run system.

I'm seeking to cater to _properly_-decentralised self-hosted deployments, running on bare metal in the homes of Livepeer community members. The easier I can make it for them to "just run Livepeer" and get some utility from it, the better.

Please can you re-open this issue, I would like to continue to champion this feature request, and discuss with other members of the community.
