### ISSUE TITLE
`livepeer_cli` misleads 10% of new Orchestrators who try to register when round is locked

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1509]
## Describe the bug

If a new O attempts to use `livepeer_cli` option `13. Invoke multi-step "become an orchestrator"`, to call `transcoder` _**during the period where the current round is locked**_ (10% of blocks at the end of each round), the transaction fails, with the `livepeer` process reporting `current round locked`.

Meanwhile, the `livepeer_cli` process reporting the false positive of `Transaction sent. Once confirmed, please restart your node.`

In this case, the O gets registered, and active in the next round - by virtue of having bonded to itself by calling `approve` and `bond`. However:

a) it will have failed to call `setServiceURI` (hence it cannot receive any work), and 
b) it will **not** have set a `RewardCut` or `FeeShare` (as it has not called `transcoder`).

**_If_ the new O is aware of the failure**, they can call `transcoder` and `setServiceURI` via `14. Set orchestrator config`.

However, it is very unlikely that they will be aware of the failure (without some complicated debugging), due to a) the false positive reported by the `livepeer_cli`, and b) the false evidence that everything was successful.

**_It is statistically likely that 10% of all new Orchestrators trying to register are experiencing the above issue._**

## Current Behaviour

Steps to reproduce the behaviour:

1. Delete (or backup) your `.lpData` - make sure it's fresh and clean, imagine you are a new user.
2. Run `./livepeer-linux-amd64/livepeer -network rinkeby -orchestrator -cliAddr 127.0.0.1:7935 -httpAddr 127.0.0.1:8935 -serviceAddr 127.0.0.1:8935 -pricePerUnit 2000000 -pixelsPerUnit 1 -ticketEV 1000000000000 -transcoder -v 99`
3. Press return key twice (to create up a keystore file without an empty password)
4. Send 0.1 Rinkeby ETH to the address created by the node, and wait for the transaction to confirm
5. In another Terminal, run `./livepeer-linux-amd64/livepeer_cli`
6. Choose `16. Get test LPT`, and wait for the `livepeer_cli` to return
7. Choose `13. Invoke multi-step "become an orchestrator"`
8. Press return key three times (to accept the defaults for reward cut, fee share, pixels per unit)
9. Enter `1000000` as the `price for 1 pixels in Wei`
10. Press return key once (to accept the detected public IP address)
11. WAIT until the livepeer round enters the end-of-round "locked" state (currently 10%)
12. Enter `10000000000000000000` as the `bond amount`.
13. Observe the `livepeer` process reporting calls to `approve` and `bond` successfully
14. Observe the `livepeer` process reporting `current round locked`
15. **Unexpected Behaviour 1**: Observe the `livepeer_cli` process report `Transaction sent. Once confirmed, please restart your node.`
17. Cancel (ctrl-c) the `./livepeer` process
18. Run the same again `./livepeer-linux-amd64/livepeer -network rinkeby -orchestrator -cliAddr 127.0.0.1:7935 -httpAddr 127.0.0.1:8935 -serviceAddr 127.0.0.1:8935 -pricePerUnit 2000000 -pixelsPerUnit 1 -ticketEV 1000000000000 -transcoder -v 99`
19. Observe the node call `reward`
20. In the `livepeer_cli`, run `1. Get node status`
21. **Unexpected Behaviour 2**: See `ORCHESTRATOR STATS`:
```
+------------------+
|ORCHESTRATOR STATS|
+------------------+
*----------------------*------------------------*
|               Status |             Registered |
*----------------------*------------------------*
|               Active |                   true |
*----------------------*------------------------*
|          Service URI |                        |
*----------------------*------------------------*
|      Delegated Stake |                 10 LPT |
*----------------------*------------------------*
|       Reward Cut (%) |                      0 |
*----------------------*------------------------*
|        Fee Share (%) |                      0 |
*----------------------*------------------------*
```

## Expected behaviour

At step 15, I would expect the `livepeer_cli` to report `current round locked`

At step 21. I would expect to see blank entries for `Reward Cut` and `Fee Share` (or perhaps `undefined`), to help the new to be aware that these have not been actively set on the system.

(perhaps though, `0` and `0` are the default settings for `Reward Cut` and `Fee Share` - I don't know)

## Environment

![Screenshot from 2020-05-20 17-15-07](https://user-images.githubusercontent.com/2212651/82442535-7b848400-9abd-11ea-9ddc-263534a9507e.png)

```
ubuntu@cibulka:~/5.5$ ./livepeer-linux-amd64/livepeer -version
Livepeer Node Version: 0.5.5
Golang runtime version: gc go1.13.4
Architecture: amd64
Operating system: linux
```

## Logs and Keystore

[livepeer.log](https://github.com/livepeer/go-livepeer/files/4656527/livepeer.log)
[livepeer_cli.log](https://github.com/livepeer/go-livepeer/files/4656528/livepeer_cli.log)

[UTC--2020-05-20T10-32-46.005274458Z--42a7ed25ac630d6441bca10c41223ff3fbbec006](https://github.com/livepeer/go-livepeer/files/4656525/UTC--2020-05-20T10-32-46.005274458Z--42a7ed25ac630d6441bca10c41223ff3fbbec006.txt)

## Other thoughts

Perhaps consider breaking the `13. Invoke multi-step "become an orchestrator"` into multiple single-step options? This is failing half way through its 4 steps...

**Comment by dob** [comment]
Thanks. I think this could be simplified to a first step of the CLI checking if we're currently in the round lock period when they choose the option to register as on orchestrator, and preventing them from doing so with the appropriate warning/error.

**Comment by chrishobcroft** [comment]
Like "come back in 575 blocks and try again"?

In some ways, it would be a shame to stop them from registering as an O (i.e. bonding to themself) in the current round... I would make it so that `13. Invoke multi-step "become an orchestrator"` should correctly report and explain the error, and tell the new O that they are registered, but that they must set their Reward Cut and Fee Share at the start of the next round.
