### ISSUE TITLE
Revisit how `distributeFees` is called

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#151]
We currently have the transcoder call distributeFees.  Given the new changes planned for fixing stuck fees in the protocol, do transcoders still need to do this?  Not sure if the transcoder has any inherit incentive to make this call.

**Comment by dob** [comment]
Who else would call `distributeFees()` if the transcoder didn't?

**Comment by yondonfu** [comment]
Transcoders have an incentive to call distributeFees to collect their own fee share and the rest is placed in a fee pool that delegators can claim for later on so I don't thinks this is an issue anymore -closing for now.
