### ISSUE TITLE
mp4 HTTP push request produces empty results

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#1514]
**Describe the bug**
Consecutive mp4 transcoding push requests result in empty response for the later requests:

```
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Server: openresty/1.15.8.2
Date: Mon, 25 May 2020 03:13:56 GMT
Content-Type: multipart/mixed; boundary=68a8316cd7e8caf2b4f6
Transfer-Encoding: chunked
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains

--68a8316cd7e8caf2b4f6
Content-Disposition: attachment; filename="384p_23_315_5.mp4"
Content-Length: 262
Content-Type: video/mp4; name="384p_23_315_5.mp4"
Rendition-Name: 384p_23_315

^@^@^@ ftypisom^@^@^B^@isomiso2avc1mp41^@^@^@^Hfree^@^@^@^Hmdat^@^@^@Ömoov^@^@^@lmvhd^@^@^@^@^@^@^@^@^@^@^@^@^@^@^Cè^@^@^@^@^@^A^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^B^@^@^@budta^@^@^@Zmeta^@^@^@^@^@^@^@!hdlr^@^@^@^@^@^@^@^@mdirappl^@^@^@^@^@^@^@^@^@^@^@^@-ilst^@^@^@%©too^@^@^@^]data^@^@^@^A^@^@^@^@Lavf58.35.101
--68a8316cd7e8caf2b4f6
Content-Disposition: attachment; filename="480p_23_570_5.mp4"
Content-Length: 262
Content-Type: video/mp4; name="480p_23_570_5.mp4"
Rendition-Name: 480p_23_570

^@^@^@ ftypisom^@^@^B^@isomiso2avc1mp41^@^@^@^Hfree^@^@^@^Hmdat^@^@^@Ömoov^@^@^@lmvhd^@^@^@^@^@^@^@^@^@^@^@^@^@^@^Cè^@^@^@^@^@^A^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^B^@^@^@budta^@^@^@Zmeta^@^@^@^@^@^@^@!hdlr^@^@^@^@^@^@^@^@mdirappl^@^@^@^@^@^@^@^@^@^@^@^@-ilst^@^@^@%©too^@^@^@^]data^@^@^@^A^@^@^@^@Lavf58.35.101
--68a8316cd7e8caf2b4f6--
```

_This seems to ONLY happen in the deployed version.  I cannot reproduce it in the local version._

**To Reproduce**
1. Create mp4 segments by running `ffmpeg -i 'bbb_1080p.mp4' -codec copy -f segment -break_non_keyframes 0 -map 0 ./datadir/bbb_%03d.mp4`
1. Create a stream via the hosted API
2. Send a POST request to transcode a MP4 segment. This should be successful.
3. Send another POST request to transcode a MP4 segment. This gives an empty response.

For example, the 2 consecutive requests can be:
```
curl -i -X POST "https://chi-broadcaster-squirtle.livepeer-ac.live/live/7a462989-a26e-443e-baa9-e52d8e640903/1.mp4" -H "Accept: multipart/mixed" --data-binary "@datadir/bbb_001.mp4" > output1
```
and
```
curl -i -X POST "https://chi-broadcaster-squirtle.livepeer-ac.live/live/7a462989-a26e-443e-baa9-e52d8e640903/2.mp4" -H "Accept: multipart/mixed" --data-binary "@datadir/bbb_002.mp4" > output2
```
They need to be sent within a few seconds of each other (before the transcoding session expires on the node)

**Expected behavior**
All consecutive transcoding requests should be successful.

**Comment by j0sh** [comment]
Thanks for the report. Some questions to preempt a few lines of inquiry:

1. Are the segments generated consecutively from a video, eg with `ffmpeg -f hls`? That is, does the second segment starts from a timestamp *after* the last timestamp of the last segment? If not, probably hitting this issue with out-of-order segments: https://github.com/livepeer/lpms/issues/180 . This only happens with GPU transcoding in go-livepeer. You'd see it if trying to transcode the same segment twice.

2. Does it only happen specifically with MP4, or is mpegts affected as well?

**Comment by darkdarkdragon** [comment]
Did some testing. It does not reproduced locally (using software transcoding) and on esh claster.
Reproduced on chi cluster.
Was using same segment, sending it to transcode two times in a row.
Strange thing:
transcoding mp4 to mp4 results in empty response on second transcode.
ts to ts -> results in segment with audio but with broken video
ts to mp4 -> same, has audio but broken video
mp4 to ts -> works normally.

**Comment by ericxtang** [comment]
@j0sh - here are the 2 mp4 files I used for my test.  I was ONLY getting this error when transcoding mp4 files.  mpegts files worked fine for me.

https://eric-test-livepeer.s3.amazonaws.com/bbb/bbb_out_002.mp4
https://eric-test-livepeer.s3.amazonaws.com/bbb/bbb_out_003.mp4

@darkdarkdragon can you upload the ts files you used?

**Comment by darkdarkdragon** [comment]
@ericxtang 
This one
[zz1.zip](https://github.com/livepeer/go-livepeer/files/4684415/zz1.zip)
But I've used same one in both transcoding attempts, so maybe that's the difference...
