### ISSUE TITLE
Cannot run Livepeer on CentOS 7

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1556]
**Describe the bug**

Builds do not work on CentOS (tested on v7.8)

**To Reproduce**
1. Start with a fresh CentOS machine. I made a new one via GCP.
2. Download a Livepeer build.
3. Run the following:

```
[josh@ja-centos livepeer-linux-amd64]$ cat /etc/centos-release
CentOS Linux release 7.8.2003 (Core)
[josh@ja-centos livepeer-linux-amd64]$ ./livepeer
./livepeer: /lib64/libc.so.6: version `GLIBC_2.22' not found (required by ./livepeer)
```

**Expected behavior**

Things should work.

**Additional context**

If we can't get things to work across distros out-of-the-box (GPU support especially may be tricky), then it might be good to have CI do separate builds for specific distros.

**Comment by iameli** [comment]
Dang, looks like CentOS/RHEL uses glibc 2.17 from 2012. Tricky. Options:

1. Figure out how to change the existing build to use that version of glibc in the existing container, perhaps by building a glibc version manually. I've never done that, no idea how hard it is.
2. Change the build to use CentOS. Totally feasible, especially considering we have no compile-time CUDA requirements thanks to clang. [The tricky part here is getting the correct versions of golang and clang installed](https://github.com/livepeer/go-livepeer/blob/master/docker/Dockerfile.build-linux#L16) — I haven't used `yum` in a long time. But the resulting binaries should work everywhere.
3. Switch to using a libc that's more friendly for static linking, like musl. Often this leads to weird bugs where glibc and musl handle things slightly differently. Given our reliance on some pretty low-level and high-performance C libraries I'd be a little nervous about going this way.

**Comment by iameli** [comment]
Looks like we run just fine on CentOS 8, for what it's worth.

**Comment by j0sh** [comment]
Great know that we run on CentOS 8.

FWIW, I was able to eventually get Livepeer to build on CentOS 7 but ran into a bunch of annoying build issues with gnutls and Cgo. I may try cleaning things up into a proper PR (the changes *should* be portable) but it might be better to just tell folks to use CentOS 8 if that works out-of-the-box and not support 7 at all.
