### ISSUE TITLE
ci: Empty branch name for Windows build GH action

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1563]
**Is your feature request related to a problem? Please describe.**

When the Windows build [GH action](https://github.com/livepeer/go-livepeer/blob/master/.github/workflows/main.yml) is run the [branch name](https://github.com/livepeer/go-livepeer/blob/master/ci_env.sh#L24) in `ci_env.sh` is empty (or at least this was the case when I pushed to the `rinkeby` and `mainnet` branches).

From a brief glance, I noticed that:
- The `CIRCLE_BRANCH` env var is set in the upload build step, but it is not set in the build livepeer step
- We use `github.head_ref` to fetch the source branch name, but according to the [docs](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) this is only available when the trigger is a pull request. I'm guessing that if we want to be able to trigger a build by pushing to a branch (i.e. `rinkeby` or `mainnet`) then we may need to a different way to get the branch name.

**Describe the solution you'd like**

Make sure that the branch name in `ci_env.sh` is set properly when running the Windows build GH action.

**Comment by iameli** [comment]
Looks like `github.ref` might be what we're looking for.

**Comment by yondonfu** [comment]
Using `github.ref` now. See https://github.com/livepeer/go-livepeer/blob/ffabc358fe3115c81e0fb6fc83f1b6b281194498/.github/workflows/windows.yml#L26
