### ISSUE TITLE
Transcoding Protocol Authentication

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#1569]
## Abstract

Currently, there is no authentication for the transcoding network protocol. A method of authentication is proposed for the transcoding network protocol which re-introduces an [authentication token](https://github.com/livepeer/go-livepeer/commit/fae70f384ab151b2f2c50495f3c406c706ef0412) that is acquired during discovery. This authentication scheme will also be useful for broadcasters running [Livepeer ingest](https://gist.github.com/j0sh/df016ea5da7e4e368e4f648faa9d4a32) ("proxy mode") and helps resolve some other [long-standing](https://github.com/livepeer/go-livepeer/issues/695) issues.

## Motivation

There are a few scenarios that might want access to be checked:

* Staging / testing environments that may be otherwise publicly accessible
* Livepeer.com hosted service - for both hosted broadcasters (proxy - authenticating customers) and orchestrators (for usage by internal / trusted Bs)
* Other types of private networks
* Onchain orchestrators that may want to implement an allow-list or deny-list of broadcaster addresses
* External rate limiting of jobs or certain addresses

## Proposed Solution

* Configure offchain broadcasters with an identifier. Use this value in the [`OrchestratorRequest.address`](https://github.com/livepeer/go-livepeer/blob/9fd21617aee0d73ac10e191ab4b6c5b33789c1dc/net/lp_rpc.proto#L29-L32) RPC field. This could be an API key, for example. If omitted, the value can remain empty.
* For onchain broadcasters, this identifier remains the ETH address.
* During [OrchestratorInfo handling](https://github.com/livepeer/go-livepeer/blob/9fd21617aee0d73ac10e191ab4b6c5b33789c1dc/server/rpc.go#L245-L253), make a webhook call if a webhook is configured. The configuration can reuse the `-authWebhookUrl` flag.
* The `url` field of the webhook request can be something like `livepeer://<broadcaster-address>` , where the address is encoded, maybe as hexadecimal (Eth standard), base64 (more compact), base32 (human friendly), etc. Optionally, it might help someday to distinguish the modes in use, eg proxy or on-chain, such as `livepeer+proxy://<broadcaster-address>` (B in proxy mode) or `livepeer+mainnet://<broadcaster-address>` (O on mainnet) or `livepeer+proxy+rinkeby://<broadcaster-address>` (B in proxy mode using Rinkeby).
* Assume only a 200 OK response is needed for webhook success. Later on, additional values may be returned from the webhook response in order to further control the flow. Any other non-200 response is an error.
* If webhook fails, error out from the RPC call, which will propagate back to the broadcaster.
* If no webhook is configured, assume success.
* If authentication succeeds, generate a token, something like: `token=hmac(secret, transcode-index|expiration)` and return an opaque blob to the broadcaster as part of the OrchestratorInfo message.
* The blob should be a base64'd Protocol Buffers message containing the token, transcode index and expiration.
* The secret can be generated once at start-up time, or derived based on the address. Should not be predictable and does not need to persist across restarts. This does mean that nodes which restart mid-stream will need to have the streams re-authenticate, but that seems OK for simplicity.
* Use `transcode-index` as a job identifier. This should be an unpredictable / random value that is generated fresh for each discovery call.
* Set a reasonable expiration; say 30 minutes or so. This prevents token reuse in the far future.
* Auth tokens with an updated expiration can be [refreshed](https://github.com/livepeer/go-livepeer/blob/9fd21617aee0d73ac10e191ab4b6c5b33789c1dc/server/broadcast.go#L399-L406) in the same manner that payment parameters are refreshed.
* Broadcaster-side, the blob should be incorporated into an auth header for each segment. The broadcaster doesn't need to process the blob or be aware of its structure, other than to copy it into the header. See the [old auth token](https://github.com/livepeer/go-livepeer/commit/fae70f384ab151b2f2c50495f3c406c706ef0412) for an example.
* Auth token should be validated at submission time for each segment. The HMAC means auth tokens don't need to persist between discovery calls; persistence only happens once a transcode session is started.

## Implementation Tasks and Considerations

Implementing transcoding auth should open the way for resolving https://github.com/livepeer/go-livepeer/issues/695 and the associated issues within that ticket; the `transcode-index` value within the HMAC construction can be used as a key into the transcode index.

The broadcaster transmitted manifest ID becomes unnecessary at this point, and its use should be removed from the orchestrator. (Broadcasters should opt to continue transmitting the manifest ID to maintain compatibility with older orchestrators.) However, the orchestrator still has its own uses for the manifest ID, for various indexing / naming purposes. The orchestrator's own manifest ID should be populated with the `transcode-index` value.

Depending on the roll-out timeline, orchestrators may opt to continue using broadcaster-supplied Manifest IDs if the auth token is absent, in order to maintain compatibility with older broadcasters. But this may be one case where a hard break is desirable.

Transcoding auth would also make [Livepeer ingest](https://gist.github.com/j0sh/df016ea5da7e4e368e4f648faa9d4a32) available to the hosted service, although the webhook endpoint would likely need to be updated for the new scheme.

## Testing Tasks and Considerations

Test Everything. Including back compat regression testing, eg  https://gist.github.com/j0sh/9d884a19bb92e504092e71fd19d812e5#file-run-sh, which also serves as a form of integration test.

## Known Unknowns

N/A

## Alternatives

Auth could be done via external means such as a proxy in front of the node. But this integrates and extends better into the tooling we already have.

## Additional Context

This is one of the pieces needed to make node-first workable in the hosted production infra, along with Livepeer ingest.

**Comment by iameli** [comment]
This sounds great! The only part I'm not sure of is the title — I assumed we were talking about nodes running in `-network offchain` mode, but this has a variety of uses for on-chain orchestrators as well! Perhaps "Orchestrator Webhook Authentication" or something like that?

Would this process, or perhaps a future O `-authWebhookUrl` parameter, facilitate running on-chain Os that could also handle payment-free offchain requests based on the webhook result? "I'm an orchestrator that usually processes on-chain, but if Eli ever requests transcoding, it's on the house" kind of situation. I'm imagining a hybrid on/off chain API here.

edit: lol sorry whoops wrong button

**Comment by j0sh** [comment]
> I assumed we were talking about nodes running in -network offchain mode, but this has a variety of uses for on-chain orchestrators as well! Perhaps "Orchestrator Webhook Authentication" or something like that?

Yeah, I guess it's more about authentication using the transcoding protocol. The most immediate use case is for Livepeer ingest / proxy mode, which can't be deployed on the hosted service until there is some form of auth. The [proxy mode WIP](https://gist.github.com/j0sh/df016ea5da7e4e368e4f648faa9d4a32) already does webhook authentication, but doesn't directly address the other issues around manifest ID usage, and it's better to be able to short-circuit the process during the discovery phase anyway.

> "I'm an orchestrator that usually processes on-chain, but if Eli ever requests transcoding, it's on the house" kind of situation. I'm imagining a hybrid on/off chain API here.

The webhook could certainly return pricing info. There has been discussion of factoring things out into a blockwatcher service; this could fit into that.

A hybrid dovetails with other ideas that have been proposed around using multiple transcoding networks. Any multi-network support, especially for onchain / offchain, would be a lot of work on the node. But a short term workaround for this specific case would be to always run onchain, but return a price of zero via the webhook. Not entirely sure if that'll work flawlessly right now though, with gas price calculations and everything.

**Comment by yondonfu** [comment]
👍 👍  for this proposal.

> Depending on the roll-out timeline, orchestrators may opt to continue using broadcaster-supplied Manifest IDs if the auth token is absent, in order to maintain compatibility with older broadcasters. But this may be one case where a hard break is desirable.

I think this should be a breaking change since broadcaster-supplied manifestIDs can result in undesirable behavior for orchestrators so orchestrators really shouldn't be accepting broadcaster-supplied manifestIDs at all.

> The most immediate use case is for Livepeer ingest / proxy mode, which can't be deployed on the hosted service until there is some form of auth.

One use case for Livepeer ingest enabled by the authentication mechanism described in this proposal that I think is particularly interesting is connecting an off-chain broadcaster with an on-chain Livepeer ingest/proxy. The on-chain Livepeer ingest/proxy can use an on-chain network for transcoding without exposing the off-chain broadcaster operator to any on-chain details. As a result, the off-chain broadcaster operator can pay the operator of an on-chain Livepeer ingest/proxy using a different payment mechanism than the one used between the on-chain Livepeer ingest/proxy and on-chain orchestrators while still having access to an on-chain network for transcoding. For example, the off-chain broadcaster operator could be charged based on usage tracked for its API key (either using more traditional payment processing i.e. CC or using a crypto based system - its up to the operator of the on-chain Livepeer ingest/proxy).

**Comment by yondonfu** [comment]
Closed by #1731
