### ISSUE TITLE
Send ETH option in CLI

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1571]
**Is your feature request related to a problem? Please describe.**

Similar to `Send LPT` we should have a `Send ETH` option for when users want to get funds out of their wallet. 

Currently a user would have to export the JSON keyfile or the private key. 

**Additional context**
![image](https://user-images.githubusercontent.com/22256858/87251569-ee323000-c46c-11ea-8886-fd04867a3fd6.png)

**Comment by yondonfu** [comment]
Since there are other CLI based tools available such as [seth](https://github.com/dapphub/dapptools/tree/master/src/seth#ether-transactions) that support account management using JSON keystore files and sending ETH I'm going to close this for now.
