### ISSUE TITLE
Local IPFS Stdout Error

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#159]
When setting up a local testing environment, the Livepeer node and the verification daemon talks to the same IPFS node.

However, the verification daemon seems to trigger an error in the Livepeer node when loading data from the IPFS node.  The error seems to be that stdout gets filled with the video data (not sure why Error happens... Could be bad implementation of the IPFS sdk...)

**Comment by yondonfu** [comment]
This is fixed by embedding the IPFS node directly
