### ISSUE TITLE
Orchestrator does not ensure that ticket face value covers estimated tx cost

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1603]
**Describe the bug**

At the moment, it is possible for an orchestrator to accept tickets with a face value that is <= the estimated tx cost of redemption ([example](https://etherscan.io/tx/0xd05bf9676006101c15249494d5a1c83a16d3e8751ae589291d64cdd370b36314)). As of 0.5.10, an orchestrator will not redeem these tickets because it will only redeem a winning ticket if its face value is > the estimated tx cost of redemption. However, the orchestrator should not be accepting tickets with a face value that is <= the estimated tx cost of redemption in the first place.

The cause of this bug is the lack of a check ([relevant code](https://github.com/livepeer/go-livepeer/blob/master/pm/recipient.go#L239)) if a broadcaster's max float is <= the estimated tx cost. In this case, when the default ticket face value (which is based on a target tx cost overhead of 1%) exceeds the broadcaster's max float, the ticket face value is set to the max float meaning that the ticket face value is also <= the estimated tx cost. 

**Expected behavior**

The orchestrator should not accept tickets from broadcasters if their max float is <= the estimated tx cost of redemption. Note the <= instead of < in the previous sentence - since the estimated tx cost of redemption does not include other small costs such as withdrawal or claiming, we use <= to indicate that the max float must be strictly greater than the estimated tx cost.

**Desktop (please complete the following information):**
 - Version [e.g. 22]: 0.5.10

**Comment by chrishobcroft** [comment]
Maybe an elegant solution to this could be to give an O a way to set `-minimimFaceValue` for tickets they wish to receive?

**Comment by yondonfu** [comment]
Closed by #1751
