### ISSUE TITLE
How to ?

### ISSUE THREAD

**Issue by nasolution** [livepeer/go-livepeer#161]
example i make stream id from ffmpeg is: test name
so how can we generate stream id from test -> 1220006b9d9587bbd7b1117909ed3d8e2275130694942ab291f0b0ab13d07e1d659e94a3483bd77c1861031b6379098245051c1aa6b6435e9816c2962493906c215f

by PHP or some another programming language?

Thanks

**Comment by dob** [comment]
I'm not sure I understand exactly.

I think when you broadcast to rtmp port you can pass an `hlsStrmID` param...however the first 32 bytes have to be your node id for the network to route the stream towards you. So while you could change some of the final bytes in the above hls stream id example to pick something specific, you couldn't rename the streamID to `test`. An example is:

rtmp://localhost:1935/movie?hlsStrmID= 1220006b9d9587bbd7b1117909ed3d8e2275130694942ab291f0b0ab13d07e1d659e94a3483bd77c1861031b6379098245051c1aa6b6435e9816c2962493906c215f

Is this right @ericxtang?

**Comment by ericxtang** [comment]
Correct.  Currently the RTMP endpoint will take the `hlsStrmID` parameter, but you have to make sure the ID is prepended with the NodeID (it does that by default if you let the node generate one for you).

**Comment by ericxtang** [comment]
Closing this thread.
