### ISSUE TITLE
Orchestrator is inactive, cannot process payments 

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1610]
**Describe the bug**
My orchestrator is active on mainnet, yet I've received a couple of log messages that it is not active

``` E0826 13:39:13.066702   34438 segment_rpc.go:75] error processing payment: orchestrator is inactive, cannot process payments ```

After a restart of the node the orchestrator no longer shows these messages 

``` 
I0826 13:39:55.089358   25796 livepeer.go:1051] Orchestrator 0xf4e8Ef0763BCB2B1aF693F5970a00050a6aC7E1B is active
```

This [first check](https://github.com/livepeer/go-livepeer/blob/f1e26c0a9d8e4638b1c617fe95d0e45784be0a8e/core/orchestrator.go#L119) however is based on the ticket recipient, the check on start-up is not. 

Potential issues:
- RoundsManager didn't have a valid last seen round or corrupt data 
- Ticket Recipient was not the orchestrator the ticket was sent to 
- The SQL query failed for some other reason. 

**To Reproduce**
No reproduction steps, occured organically after running for a whole

**Expected behavior**
Expect orchestrator to always be active when it is.

**Comment by yondonfu** [comment]
Another report in Discord: https://discord.com/channels/423160867534929930/429350403272998913/827210495677300756

The user was running a node with these flogs:

```bash
livepeer -network mainnet -ethUrl https://mainnet.infura.io/v3/xxx -orchestrator -orchSecret xxx -serviceAddr xxx -blockPollingInterval 10 -pricePerUnit 2000 -monitor=true -reward=false
```

**Comment by windexirc** [comment]
I have also run into this issue today... restarting seemed to work.
flags:
`./livepeer -network mainnet -orchSecret xxx -ethUrl https://mainnet.infura.io/v3/xxx -orchestrator -pricePerUnit 1000 -serviceAddr ip:8935 -cliAddr 0.0.0.0:7935 -monitor -maxSessions 10 -reward=false`

**Comment by kyriediculous** [comment]
Thanks for reporting! We're still working on determining the root cause as log outputs don't provide additional insight until now, once we know how to reproduce the issue can come up with a fix. We hope to resolve this as soon as we can given current priorities.

**Comment by pschroedl** [comment]
I just observed this as well, but appeared to also happen for test streams so possibly not a broadcaster issue ( as noted in https://github.com/livepeer/go-livepeer/issues/1777 ).

flags:
```livepeer -network mainnet -orchestrator -ethUrl https://mainnet.infura.io/v3/xxx  -nvidia all -autoAdjustPrice=false -pricePerUnit 800 -serviceAddr 1.2.3.4:8935 -ethAcctAddr 0x*** -monitor -v 6 -reward=false -orchSecret xxx```

**Comment by pschroedl** [comment]
FWIW, the test streams reported "400 Bad Request" when orchestrator logged these errors.

also, appears to be duplicate of https://github.com/livepeer/go-livepeer/issues/1482 ( which is also tagged 'bounty' )

**Comment by kyriediculous** [comment]
Duplicate of #1482

**Comment by yondonfu** [comment]
Thanks for the report @pschroedl! Will use #1482 to continue track this problem.
