### ISSUE TITLE
monitor: Recording truncated durations

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1628]
**Describe the bug**

Truncated durations are being recorded for a few metrics tracked in the `census.go` file of the `monitor` package.

[An example](https://github.com/livepeer/go-livepeer/blob/master/monitor/census.go#L831):

In the above example, the argument passed to `cen.mUploadTime()` is `float64(uploadDur/time.Second)` where `uploadDur` is a `time.Duration`. If `uploadDur` is not a value in whole seconds (i.e. 0.5s), then `uploadDur/time.Second` will chop off the sub-second portion of the value.

Suppose `uploadDur` is .5s. `float64(uploadDur/time.Second` will be 0 and the upload time will be recorded as 0.

This behavior can be observed by running this code snippet:

```golang
dur := 1500 * time.Millisecond
fmt.Println(dur)
fmt.Println(float64(dur/time.Second))
```

This truncation caused by dividing by `time.Second` occurs in a few other places in the `census.go` file as well.

**Expected behavior**

No truncation of durations when recording metrics.

**Comment by darkdarkdragon** [comment]
Fixed by 0d824410c15794fa11de17908bda717403210a9e
