### ISSUE TITLE
hls playback: allow for configurable buffer size

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#1631]
**Is your feature request related to a problem? Please describe.**
Right now we have a hardcoded five-segment HLS buffer. I think eventually we'll want a more sophisticated buffer based on time rather than segment count but for now the ability to just configure the size of the segment buffer would be great.

**Describe the solution you'd like**
Perhaps `-hlsSegments=10`? And it can default to 5?

**Describe alternatives you've considered**
We should do most of the alternatives too — a time-based rather than segment-based buffer would be great, but that's somewhat trickier and can happen after.

We could also have this webhook-configurable on a per-stream basis; kind of an interesting idea for cases where we're only doing multipart return and we could set the buffer to 0, save some RAM.

**Comment by darkdarkdragon** [comment]
I think before doing that we should do #1405 first
