### ISSUE TITLE
More flexible segment in flight rule

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1658]
Both B & O implement a single segment in flight (SSIF) rule for streams. B will not send another segment to O if it has not responded for a previous segment for the stream yet. O will not accept another segment if it has not finished transcoding a previous segment for a transcode session yet. As a result, for a stream with uniform segment durations, an O will receive all segments in the stream as long as it returns results in real-time. However, there are other considerations to take into account in practice:

- If a stream has variable segment durations (which is not uncommon), segment N + 1 might be shorter than segment N such that even if O can return segment N in real-time, segment N + 1 could be emitted before O returns segment N
- O is slower to transcode the first segment in a transcode session due to GPU session init overhead
- O might return results in real-time most of the time, but slower than real-time sometimes due to factors such as fluctuation in bandwidth capacity
- Combination of all of the above

The points listed above can cause the following problems:
- If B only has access to a single O, it will drop a bunch segments even if those segments could have been transcoded by O in real-time most of the time and an acceptable amount slower than real-time other times
- If B has access to many Os, it will switch Os more often and each switch can potentially trigger a GPU session init which will slow down the transcode for that segment

One way to address these problems might be to update the segment in flight rule to something like:

- If a segment is in flight for O:
    - If the time in flight for the segment is less than `x`:
        - Send the next segment to this O
    - Else:
        - If there are other Os available:
            - Send the next segment to another O
        - Else:
            - If the time in flight for the segment is less than `y`:
                - Send the next segment to this O
            - Else:
                - Drop the segment

The above assumes that the current O would be the one selected for the next segment by B's selection algo. 

Since this might result in multiple segments in flight, we could keep track of the time in flight for the oldest segment in flight.

`x` is the time in flight threshold for continuing to send segments to an O. A default value for this might be the duration of the oldest segment that is in flight. 

`y` is the time in flight threshold for continuing to send segments to an O if the requirement for `x` is not met and if there are other Os available. This value controls how often segments get dropped.

A few implications of this proposed rule if the suggested default value for `x` is used:
- Regardless of the durations of segments in a stream, if an O can return results for each segment in real-time it will receive all the segments of the stream.
- If O fluctuates between real-time and slightly slower than real-time, it can still consistently receive segments of the stream if there are no other Os available which reduces the # of dropped segments
- If there are other Os available, B will still switch if the current Os is not keeping up in real-time

This would require changes to the segment in flight management rule on both B & O.

**Comment by darkdarkdragon** [comment]
I like the idea.
As for the orchestrator side, we could just increase size of the buffer of this channel:
https://github.com/livepeer/go-livepeer/blob/7f9534c365123f455c7fd3bfb9ebcbf5a99cdd43/core/orchestrator.go#L450
This will serialise incoming segments on the orchestrator.

**Comment by ericxtang** [comment]
I think this is a good upgrade to the current "segment in flight" rule, and I like the duration for the last segment as a default for `x`.  Do you think this is a parameter that can be set during node startup?

**Comment by yondonfu** [comment]
> Do you think this is a parameter that can be set during node startup?

Maybe in the future, but for this particular issue I think we should always use the duration of the last segment for now. I'd prefer to hold off on exposing a user configurable flag until we a) think it's absolutely necessary and b) there is at least a process or guidelines a user can use to determine what value to use for the flag.

---

The current workflow for selecting an O for a stream consists of the following:

1. Return a `BroadcastSession` from [selectSession()](https://github.com/livepeer/go-livepeer/blob/ccda73eb159ce23228d887fd130f1e877df6c859/server/broadcast.go#L378). This will invoke the underlying selector used by the `BroadcastSessionsManager` which executes a selection strategy to return the next session to use.
2. Call [SubmitSegment()](https://github.com/livepeer/go-livepeer/blob/ccda73eb159ce23228d887fd130f1e877df6c859/server/broadcast.go#L432) using the `BroadcastSession`.
3. When `SubmitSegment()` returns, use the result to [create an updated the broadcast session](https://github.com/livepeer/go-livepeer/blob/ccda73eb159ce23228d887fd130f1e877df6c859/server/broadcast.go#L442) and pass it `completeSession()` which adds the session back to underlying selector.

The above workflow enforces the SSIF rule because each session is unavailable for further use until `SubmitSegment()` returns. We'll need to update this workflow to enable multiple segments in flight. We might be able to accomplish this by either re-using a single session for multiple segments or using multiple sessions for the same O (or some other approach not listed here?).

Some thoughts on how re-using a single session for multiple segments might work:

- In `selectSession()`
    - Whenever a non-nil session is returned, track that as `lastSess` in `BroadcastSessionsManager`, the last session used for the stream and the session would store `InFlightStart`, the time at which the last segment was submitted and `LastSegDr`, the duration of the last segment that was submitted
    - If we have a non-nil `lastSess` and `now - lastSess.InFlightStart < lastSess.LastSegDur`, return `lastSess`
    - If the selector returns nil, then this might mean there are no more available sessions
        - If `now - lastSess.InFlightStart < lastSess.LastSegDur * N`, return `lastSess`
        - Else, the last segment was in flight for too long and there are no other available sessions so just return nil
    - Else, return the session returned by the selector (which should correspond to a different O)
        - Call `Complete()` on the selector with the old `lastSess` to add it back to the selector
- In `completeSession()`
    - Instead of adding the provided session to the selector using `Complete`, just update `lastSess`

The above workflow aims to always use `lastSess` as long as criteria for the updated in flight rule is met and only uses the selector to select a new session if `lastSess` does not meet that criteria. The updates to `completeSession()` and how `Complete()` is called on the selector attempt to avoid adding a session back to a selector multiple times and instead holding off on adding it back until it no longer meets the in flight rule criteria - not positive that this is enough though. I think this might be promising, but I haven't thought too deeply about details like concurrency safety of re-using an existing `BroadcastSession` that is stored as `lastSess`.

Haven't thought yet about how using multiple sessions for the same O might work.

**Comment by jailuthra** [comment]
Thanks a ton for the writeup @yondonfu 

I've gone through the context and code, and the approach you've described of re-using the same session by maintaining `lastSession` parameter in BSM sounds good to me for now.

I'll proceed by thinking more about concurrency safety if we stick to this particular approach, and if it all seems good I'll start implementing the changes. I'll also go through the BroadcastSessionManager related code in more detail so that I can think more about an alternative solution like using multiple sessions for the same O.

**Comment by darkdarkdragon** [comment]
@yondonfu 
> Some thoughts on how re-using a single session for multiple segments might work:

Did I get it right that this scheme doesn't take into consideration actual time it took for transcoding?
If so, then O can be as slow as it wants - B will be sending all the segments to that O.
Or I've missed something?

**Comment by jailuthra** [comment]
@darkdarkdragon If I understood Yondon's solution correctly, we will update `lastSess.InFlightStart` in [completeSession()](https://github.com/livepeer/go-livepeer/blob/ccda73eb159ce23228d887fd130f1e877df6c859/server/broadcast.go#L442) whenever the oldest segment in flight is successfully transcoded i.e. the `SubmitSegment()` call for it returns.

So if it ever happens that an O is completely un-responsive or very slow for a particular segment, the call for the oldest segment will still be blocked on `SubmitSegment()` and InFlightStart timer will not get updated - so as soon as `now - lastSess.InFlightStart` becomes greater than our bound we will switch to a different Orchestrator.

Please correct me if I've missed something @yondonfu 

I'm still trying to figure out how exactly multiple segments under the same `BroadcasterSession` would be processed at the Orchestrator and if we might have to add extra R(/W) locks for multiple uses of the same underlying session on the B side.

**Comment by darkdarkdragon** [comment]
@jailuthra 
I thought scheme would be:
1. First segment that starts transcoding sets `InFlightStart` var
2. While first one is still being transcoded, second one came, and it also updates `InFlightStart` var with new value
3. When first one completes, we're not updating `InFlightStart`

If instead what we're doing is:
1. First segment that starts transcoding sets `InFlightStart` var
2. While first one is still being transcoded, second one came, and it doesn **not** updates `InFlightStart` var
3. When first one completes, we **are** updating `InFlightStart`

If we're doing second variant - then we're missing start of the second segment, if we're doing first variant - then we're missing end of any segment.

**Comment by jailuthra** [comment]
@darkdarkdragon good point. 

I think second scheme should work if we make an internal queue of segment start times in the B session struct rather than a single `InFlightStart` variable? And then we can check the oldest segment's start-time to decide the O selection logic like described in the initial spec and remove an item from the queue whenever oldest segment completes. I'll think more about this as I go along.
