### ISSUE TITLE
HTTP 500 errors when B is overloaded through Push API

### ISSUE THREAD

**Issue by jailuthra** [livepeer/go-livepeer#1665]
**Describe the bug**
The Broadcaster node sometimes emits HTTP internal error responses (500) without any additional logs when overloaded with input segments through the Push API.

**Reproduction**
1. Start up a local B/OT setup.
2. Send two segments *simultaneously* for a new stream via the Push API by calling parallel curl requests:
```
curl -XPOST --data-binary @test.ts -v http://127.0.0.1:8936/live/test/0.ts -H "accept: multipart/mixed" -i --output out.ts &\
curl -XPOST --data-binary @test.ts -v http://127.0.0.1:8936/live/test/1.ts -H "accept: multipart/mixed" -i --output out2.ts
```

3. One of the segments will successfully return transcoded renditions with an HTTP 200
4. The other segment will not be transcoded and curl will output an HTTP 500 due to the StreamAlreadyExists error at https://github.com/livepeer/go-livepeer/blob/7f9534c365123f455c7fd3bfb9ebcbf5a99cdd43/server/mediaserver.go#L517

**Comment by jailuthra** [comment]
Thanks to the improved logs introduced in recently merged PR #1582,
I was able to track down that the 500 response occurs due to `createRTMPStreamIDHandler` returning `nil` -
https://github.com/livepeer/go-livepeer/blob/2f54db3d67bcf0a598d165ce7ffbe86ffec74eaf/server/mediaserver.go#L744-L748

This is an example of the failure logs -
```
Nov 24 18:36:13Z mdw-staging-livepeer-broadcaster-<> broadcaster I1124 18:36:12.114524       1 mediaserver.go:343] Stream authentication for url=<redacted> dur=26.891972ms
Nov 24 18:36:13Z mdw-staging-livepeer-broadcaster-<> broadcaster E1124 18:36:12.114713       1 mediaserver.go:749] Could not create stream ID: url=<redacted>
Nov 24 18:36:13Z mdw-staging-livepeer-broadcaster-<> broadcaster I1124 18:36:12.123977       1 mediaserver.go:343] Stream authentication for url=<redacted> dur=25.187587ms
Nov 24 18:36:13Z mdw-staging-livepeer-broadcaster-<> broadcaster E1124 18:36:12.124166       1 mediaserver.go:749] Could not create stream ID: url=<redacted>
Nov 24 18:36:13Z mdw-staging-livepeer-broadcaster-<> broadcaster I1124 18:36:12.245237       1 mediaserver.go:723] Got push request at url=<redacted> ua=MistServer/<> addr=<redacted> bytes=79712 dur=1600 resolution=1920x1080
```
There is no other error log except the "Could not create stream ID".

Looking at the `createRTMPStreamIDHandler` function, it usually throws another error when returning `nil` except at one place - 
https://github.com/livepeer/go-livepeer/blob/2f54db3d67bcf0a598d165ce7ffbe86ffec74eaf/server/mediaserver.go#L233-L237

So my current guess is that the error lies somewhere in the `jsonProfileToVideoProfile` function. Will send a quick PR to log the error returned from `jsonProfileToVideoProfile` above ^

But in case somebody has some obvious ideas on what might be failing lmk!!

**Comment by darkdarkdragon** [comment]
@jailuthra 
there is 
```
E1124 18:36:12.124102       1 mediaserver.go:292] Manifest already exists fiolz5txbwy3smsr
```
and usually this is the cause of 500 in staging - because in staging we have have different setup, and all the segments going to one broadcaster - and at the start of the stream they're going to close one to another and hence this error.

**Comment by jailuthra** [comment]
Thanks @darkdarkdragon I saw a ton of those Manifest already exists errors in staging.

I also saw this in staging right at the time when B responds with 500 Error to Mist - 

`E1125 15:48:51.892492       1 mediaserver.go:767] http push error url=http://fra.livepeer.monster/live/<>/0.ts err=StreamAlreadyExists`

This log was added recently too, and confirms that the error is happening when two sessions with same manifestID are being created at the same time.
https://github.com/livepeer/go-livepeer/blob/2f54db3d67bcf0a598d165ce7ffbe86ffec74eaf/server/mediaserver.go#L514-L542

Do you think we need to push record mode PR (with these new logs) to prod as well to be sure that the prod HTTP500s are caused similarly?

Also any ideas on how we could mitigate/handle this better on the B side? (Rather than giving a ton of 500s)

**Comment by darkdarkdragon** [comment]
@jailuthra 
> Do you think we need to push record mode PR (with these new logs) to prod as well to be sure that the prod HTTP500s are caused similarly?

We certainly should push it and check if 500s under the load caused by similar reasons.

> Also any ideas on how we could mitigate/handle this better on the B side? (Rather than giving a ton of 500s)

There is no easy solution:
1. Concentrate on removing Mist - without Mist this problem will go away.
2. Rewrite of HTTP push handler so it handles such case - not easy task, but easier than previous one.

In the meantime we can just add more broadcasters instances - in hope that there be more instance for the Traefik to cycle through and so we will see AlreadyExists errors less often.

**Comment by yondonfu** [comment]
> Also any ideas on how we could mitigate/handle this better on the B side?

Here is my understanding:

The `Manifest already exists` error log comes from [createRTMPStreamIDHandler](https://github.com/livepeer/go-livepeer/blob/master/server/mediaserver.go#L746).

The `StreamAlreadyExists` error comes from [registerConnection](https://github.com/livepeer/go-livepeer/blob/e69e95cb11a9d9a334c2d12402e570f91b631e21/server/mediaserver.go#L542).

In both cases, I think HandlePush is triggered concurrently such that each execution gets past the [existence check](https://github.com/livepeer/go-livepeer/blob/e69e95cb11a9d9a334c2d12402e570f91b631e21/server/mediaserver.go#L745) for the manifestID in the `rtmpConnections` map. Then, within that conditional block one HandlePush call finishes the `registerConnection` call for the manifestID before the other so the other hits an error. Sometimes the second HandlePush hits the error at `createRTMPStreamIDHandler` and sometimes it hits the error at `registerConnection`.

The errors within that existence check conditional block are important because they prevent the creation of more than one [watchdog](https://github.com/livepeer/go-livepeer/blob/e69e95cb11a9d9a334c2d12402e570f91b631e21/server/mediaserver.go#L774) goroutine per manifestID. But, as long as we prevent additional goroutine creation/state updates that should only happen once per manifestID in the `rtmpConnections` map AFAIK (haven't looked too closely so someone correct me if I'm wrong here) continuing with the rest of the code execution in HandlePush should be fine...

Maybe we could handle the "already exists" errors more gracefully and when they are hit we just make sure to use the existing connection for the manifestID from the `rtmpConnections` map. Perhaps wrapping everything in the existence check conditional block in a function and checking for those errors? Something like:

```
if !exists {
    err := rtmpConnectionCreationStuff()
    if err == ErrAlreadyExists {
        // read from rtmpConnections to get the up-to-date connection
    } else {
       // return HTTP error
    }
}
```

**Comment by jailuthra** [comment]
> because in staging we have have different setup, and all the segments going to one broadcaster - and at the start of the stream they're going to close one to another and hence this error.

**Staging**
Just verified that at least on staging we see the 500 returned from B for two different reasons  -

1. A new session of a stream gets started with the same `manifestId`, and the segment is sent on the same B - before the B has closed the old session. This causes a ton of the `manifest already exists` errors until the B deletes the previous stream session. 

2. Mist has no chill and keeps retrying the first two segments `0.ts` and `1.ts` simultaneously when it gets a 500, so when the B stops failing on the manifest re-use, it then usually triggers the deadlock scenario with `StreamAlreadyExists` because the two initial segments were too close.

In both cases Mist gets a 500. But from what I saw the large quantity and high frequency of 500s on staging was due to scenario 1.

Scenario 2 can happen for streams without a preceding 1 as well (and many times it recovers cleanly too).

But 1 somehow makes it more likely for 2 to happen, and in a worse way, as Mist is basically flooding the B by retrying seg0 and seg1 really close together.

I also saw some particular manifestIds in staging *ping-ponging* between Scenario 1 & 2, spawning different session IDs for 5-10 minutes without any success. Which causes the flood of error logs.

**Prod?**
Please correct me if I'm wrong, but I think 1. is less likely to happen on production compared to staging, as prod has some sharding?? Does same manifest ID always land at the same B node in prod like it does in staging?

Currently distinguishing between (1) and (2) on prod is hard because B logs look the same there - once we deploy the logging PRs in prod it will get easier to figure it out.

**Potential Fix**

> 1. Concentrate on removing Mist - without Mist this problem will go away.
> 2. Rewrite of HTTP push handler so it handles such case - not easy task, but easier than previous one.

I'm leaning towards fixing it on mist-side as well if it's easy to add a small delay between seg0 and seg1.

Also if the B can somehow communicate the difference between the two 500s, it should become easy for Mist to know when to flood with retries, and when to wait.

**Comment by ericxtang** [comment]
re: @jailuthra 

> I'm leaning towards fixing it on mist-side as well if it's easy to add a small delay between seg0 and seg1.
> 
> Also if the B can somehow communicate the difference between the two 500s, it should become easy for Mist to know when to flood with retries, and when to wait.

If we look at the http push API as the "transcoding service", is one of the "jobs" of the service to handle the situation where 2 consecutive segments arrive around the same time?  This can happen when the client (like Mist) sends the 2 segments simultaneously, but it could also happen with a network glitch that delays a previous segment, which is out of the client's control.  

For scenario 1, it seems that we were assuming that new sessions on a B would ALWAYS have new manifest IDs.  This might have been true before, but with the current workflow where the manifestIDs on B are named based on the playbackID, this assumption is no longer true.  So this feels like a newly introduced bug that needs to be addressed.  (@iameli please correct me if I'm wrong here)

For scenario 2, this feels like another bug in our system - could be addressed by @yondonfu's suggestion?

**Comment by jailuthra** [comment]
> For scenario 1, it seems that we were assuming that new sessions on a B would ALWAYS have new manifest IDs. This might have been true before, but with the current workflow where the manifestIDs on B are named based on the playbackID, this assumption is no longer true. 

I think the code around manifestID is correct right now. It throws an error if two segments with different sessionIDs ("external manifests" in the PUSH /live/<>/ url) are present in proximity while having the same "internal" manifestID (which is unique for a particular stream/playbackID).

This is completely separate from the 500s caused by the race-condition around too-close-initial-segments - which from my local testing and also staging logs always results in scenario (2) failure with `StreamAlreadyExists`.

We wait for 1 minute to close a stream session for an "external manifest". But from the staging logs, I see mist often retries segments with a different "external manifest" before that 1 minute ends - which causes a lot of 500s too.

We can consider reducing the timeout here, or better communicating the error to the client rather than throwing a generic 500.

But I'm not sure if accepting consecutive segments of different sessionIDs belonging to the same underlying "internal" manifestID would be a very straightforward change, or even something we should consider?

*Steps to reproduce:*
1. Start a local B with `-authWebhookUrl`
2. Start an auth endpoint that always returns `{"manifestID":"SameInternalManifestID"}`
3. Do a HTTP push with a session ID, eg `curl -XPOST --data-binary @input.ts -v http://127.0.0.1:8935/live/session1/0.ts -H "accept: multipart/mixed" -i`
4. Before the `session1` is cleaned up (~1minute), do another HTTP push with a different session ID, eg `curl -XPOST --data-binary @input.ts -v http://127.0.0.1:8935/live/session2/0.ts -H "accept: multipart/mixed" -i`
5. Second push should fail with `Manifest manifestID=SameInternalManifestID already exists for streamID url=http://127.0.0.1:8935/live/session2/0.ts`

> For scenario 2, this feels like another bug in our system - could be addressed by @yondonfu's suggestion?

Ah my bad I didn't go through this deeply. We should definitely not throw a 500 for too-close-segments if we can gracefully handle them when registerConnection returns `errAlreadyExists`. A warning in the logs and to the API client should be good enough here. I'll try to write up a quick patch around Yondon's suggestions.

> If we look at the http push API as the "transcoding service", is one of the "jobs" of the service to handle the situation where 2 consecutive segments arrive around the same time? This can happen when the client (like Mist) sends the 2 segments simultaneously, but it could also happen with a network glitch that delays a previous segment, which is out of the client's control.

I totally agree with fixing errors in our own pipeline, be it for Mist or some other client that sends segments via the push API to the B node. And a fix on our end should solve the scenario (2) issue.

But I do feel there's a difference between simultaneous segments ending up at a B due to a rare network issue (from which we often recover cleanly) - compared to (2) where a client *often/always?* sends simultaneous segments at the start of the stream, and floods the B with retries when that fails. Or in (1) where it starts a new stream session too quickly before previous ends (maybe due to miscommunication of the 1 minute timeout, which can be fixed foshure).

IMO we should be wary of the slippery slope of adding exceptions for a proprietary client's quirky behaviour, while still doing our best to ensure smooth video experience for the end-user.

**My next steps:**
- Write a quick patch to handle scenario (2) better and reduce some 500s.
- Cut a separate issue for scenario (1), as I'm not sure of the fix yet and it might be involved.

**Comment by jailuthra** [comment]
- I've updated the description of this issue to stick to scenario (2).
- Sent a quick PR at #1672 that doesn't return 500 for (2), but still returns a 503 because we can't handle multiple-segments-in-flight between B & O (see: #1658)
- Open a separate issue for (1) moving the repro steps and other info from the comments here. #1673

**Comment by jailuthra** [comment]
Fixed & tested in staging.
