### ISSUE TITLE
Upgrade to go 1.15.5

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1668]
## Motivation

The go team has cut a security release and advises all users to upgrade 
https://groups.google.com/u/1/g/golang-announce/c/NpBGTTmKzpM?pli=1

## Proposed Solution
- Upgrade the minimum used Go version in go.mod 
- Update the go version used for the windows build (.github/main.yaml) 
- Update the go version for the docker.debian image 
- Update the go version for the linux builder to 1.15

**Comment by darkdarkdragon** [comment]
It would be good to also upgrade go version used by LPMS repo

**Comment by kyriediculous** [comment]
Definitely, thanks for pointing that out. I created an issue in the LPMS repo to track that https://github.com/livepeer/lpms/issues/215

**Comment by yondonfu** [comment]
Likely will take some more work to upgrade the go version for Windows so created a separate issue #1701 for that.
