### ISSUE TITLE
Consistent parameters in node logs

### ISSUE THREAD

**Issue by jailuthra** [livepeer/go-livepeer#1669]
**Is your feature request related to a problem? Please describe.**
Many times the error logs of a particular stream are split between displaying either `manifestId=<>` or `streamID url=<sessionId>`. This makes it hard to see all the errors of a particular stream together (without querying some db to find corresponding manifestID-streamID-sessionID links)

**Describe the solution you'd like**
As @iameli suggests, it would be great to have consistent parameters in all the log lines. For example having both `manifestId` and `streamId=` and `seqNo=` as prefix to all error logs. 

Something along the lines of https://stripe.com/blog/canonical-log-lines

**Comment by kyriediculous** [comment]
This would indeed be great to have and I think it's also been mentioned by @iameli in the past. 

I've experienced a similar issue when it comes to getting logs for a particular orchestrator. The logs here are more canonical whereby whenever it's related to transcoding we use an orchestrator's service URI, whenever it's related to e.g. payments we use the Ethereum address. But this results in having to look up the service URI for an Ethereum address on chain to get the logs for that address. 

Within the current structure it's really hard to then for example grep orchestrator logs that include both payment related logs as well as transcoding related logs.

**Comment by yondonfu** [comment]
Related: As noted by this [comment](https://github.com/livepeer/go-livepeer/pull/1670#pullrequestreview-539496177), might be helpful to use standard field names for different measurements of time i.e. `segDur=` for segment duration, `transcodeDur=` for transcode time, `uploadDur=` for upload time, etc.
