### ISSUE TITLE
Document minimum viable steps to create a private testnet

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#168]
We should write up a wiki page that has the minimum viable steps to create a private testnet so that folks can run Livepeer and test broadcasting between two+ nodes without relying on our public testnet which may be experiencing ops issues or be off the current master branch. At the minimum it should include...

1. How to start one node on a unique network ID as a bootnode.
2. How to start a second node on the same network, making it aware of the original bootnode. (Probably with port options since it may be running on the same machine).
3. How to broadcast from one node.
4. How to consume from the second node.

I think as a first stab it's ok if this is in `-offchain` mode to avoid all the geth/faucet setup.

**Comment by dob** [comment]
cc @rayj00

**Comment by dob** [comment]
@rayj00 This isn't a full writeup, but here's how I launched two nodes locally, streamed to 1 of them, and viewed through the other...

## On Node 1

```
dob@junkyard-dog~/development/tmp/.lp0: livepeer --bootnode --offchain --datadir . -v 5
I1026 16:15:32.874012    9948 livepeer.go:144] Monitor is set to 'true' by default.  If you want to disable it, use -monitor=false when starting Livepeer.
I1026 16:15:32.883263    9948 network_node.go:78] Created node: 12200f27ec3f753586ceda302233e9c5e10ed9355b0bee1815aa86dcf8bf180cd3b0 at [/ip4/10.71.57.122/tcp/15000 /ip4/127.0.0.1/tcp/15000 /ip6/::1/tcp/15000 /ip4/10.0.2.86/tcp/15000]
```

Note the node ID, and then the address for localhost (the one with 127.0.0.1). 

Note that we started with the `--bootnode` flag. 

Note that I specified a new data directory. I was within that directory in my shell when I started the node so I gave it as `.`. 

## On node two

```
dob@junkyard-dog~/development/tmp/.lp2: livepeer --offchain --rtmp 1936 --p 15002 --http 8936 --bootID 12200f27ec3f753586ceda302233e9c5e10ed9355b0bee1815aa86dcf8bf180cd3b0 --bootAddr /ip4/127.0.0.1/tcp/15000
I1026 16:18:11.306815    9969 livepeer.go:144] Monitor is set to 'true' by default.  If you want to disable it, use -monitor=false when starting Livepeer.
I1026 16:18:11.328205    9969 livepeer.go:270] ***Livepeer is in off-chain mode***
I1026 16:18:11.328218    9969 livepeer.go:274] 

Setting up Media Server
I1026 16:18:33.194086    9969 mediaserver.go:170] 

Segmenting rtmp stream:
1220354cd445c228356df6625d8646d5000581bd151454c45a4a17879d5aa015b7af7c53d91fddb6b844b67a9cc477c4e84ce550e151ceea1673453898e6c8393af7 
to hls stream:
1220354cd445c228356df6625d8646d5000581bd151454c45a4a17879d5aa015b7afb43d337e1e141b5f8cd1799e7109465e9de0427155709b7be949440f7a1ef6ab
```

Note that I need to give it custom ports for http, rtmp, and p2p interfaces because the default ones were already in use.

Note that I pass in the bootID and bootAddr from the first node so that it can discover it.

At this point I stream to rtmp port 1936 from OBS, and it prints out the HLS stream id.

Then through the media.livepeer.org/player.html link I can view the stream from the first node.

**Comment by ericxtang** [comment]
Done [here](https://github.com/livepeer/test-harness/blob/master/docs/demo.md)
