### ISSUE TITLE
Switching to use 2-channel approach for basicnet

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#171]
@whyrusleeping and I did a quick code review and he suggested to use an income stream + an outgoing stream for each node pair. This way, we don't have to keep the incoming stream around.  I suspect it'll also improve performance and get around weird bugs when we get unexpected packets.

**Comment by ericxtang** [comment]
Fixed

**Comment by whyrusleeping** [comment]
woo!
