### ISSUE TITLE
Auth webhook configurable price

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1723]
See https://github.com/livepeer/go-livepeer/issues/1569#issuecomment-657316909.

**Comment by yondonfu** [comment]
Things to consider:

- An O currently sends back an OrchestratorInfo message with each response in ServeSegment, but the webhook call should only happen during the GetOrchestrator call. After the GetOrchestrator call, B should have a valid auth token so all segment requests will be authenticated so there is no need for a webhook call. We want to avoid a webhook call on the hot transcoding path anyway
- But, without a webhook call in ServeSegment, the O will not have access to the webhook price when creating the OrchestratorInfo message
- O will have access to its locally configured price as well as the price stored in the Payment message sent by B
- The price stored in the Payment message will be the "real price" (i.e. the PM overhead adjusted price). So, if O needs to make further PM overhead adjustments, just this real price will not be enough
- O could make further PM overhead adjustments with access to the base price in addition to the real price
- One way to achieve this might be to store the base price along with the sessionID in the AuthToken passed to B so that O can use the base price (AuthToken is passed back to O) to generate a new OrchestratorInfo message in ServeSegment. This would mean that while PM overhead adjustments can still be made to the base price after each segment, the base price itself would only change when a new auth token is obtained (by default expires after 30 minutes) My hesitance here is that this exposes the concept of a real vs. base price when it would be "cleaner" if there could just be a single price with the details of how it is calculated abstracted away as an implementation detail of O.

**Comment by kyriediculous** [comment]
Another way to address the issue would be to [cache](https://github.com/livepeer/go-livepeer/blob/ccda73eb159ce23228d887fd130f1e877df6c859/server/mediaserver.go#L90) the `authWebhookResponse` for as long as the `authToken` is valid , I believe this would achieve similar behaviour

**Comment by yondonfu** [comment]
After a discussion with @kyriediculous, we think that it could be simpler for O *not* to handle PM overhead adjustments if it is using a webhook price and instead treating the webhook price as the "real price" that should be used for now.

**Comment by yondonfu** [comment]
Closed by #1733 and #1736
