### ISSUE TITLE
Mapping Livepeer Network?

### ISSUE THREAD

**Issue by rayj00** [livepeer/go-livepeer#174]
So, as I am a newbee with Livepeer, I was wondering if there is a way to display the active nodes within the test network?

**Comment by dob** [comment]
It is optional to include your node in this list, but here's a test network
monitor: http://eth-testnet.livepeer.org/

If you click connect yourself, it gives instructions for how to start geth
with the flags that will report your node's statistics back to this
dashboard.

**Comment by yondonfu** [comment]
Closing this as the test network described here is no longer relevant. If mapping nodes on mainnet or Rinkeby is still desired a separate issue can be opened.
