### ISSUE TITLE
Vocabulary update: Change #transcoding discord channels to #video-mining

### ISSUE THREAD

**Issue by wohlner** [livepeer/go-livepeer#1740]

**Comment by chrishobcroft** [comment]
I disagree with this.

The term "mining" is really not viewed positively as it evokes themes around Proof-of-Work mining, which has really bad connotations with respect to environmental unfriendliness. This is especially true in a context of Proof-of-Stake (like eth2) and Delegated-Proof-of-Stake (like Livepeer).

I know that the term "video miner" was coined by @f1l1b0x a few years back, but IMHO we should depart from this and find something with less negative connotation.

I'm all up for improving the nomenclature of channels / of our narrative, but I strongly believe this would be a step in a wrong direction.

**Comment by f1l1b0x** [comment]
I dont care how its named.
