### ISSUE TITLE
Automatic uploads of failed segment transcodes

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1744]
To help with gathering samples of video segments that currently cannot be transcoded.

Based off of https://github.com/livepeer/go-livepeer/issues/1725#issuecomment-760645089

**Comment by iameli** [comment]
Bit of prior art: @darkdarkdragon's draft branch that does something like this https://github.com/livepeer/go-livepeer/pull/1398 and https://github.com/livepeer/go-livepeer/issues/1572 which outlines how a `-failObjectStore` command line argument might work.

**Comment by yondonfu** [comment]
De-prioritizing this feature for now in favor of handling this with Mist [1] which will be able to determine with higher probability vs. a B that a source segment is not transcodeable because Mist has access to multiple Bs each of which can have access to different Os.

[1] In practice, this will involve Mist firing a trigger when it gets a 422 from 2 different Bs for the same segment and a service that consumes that trigger to log the source/transcoding config + upload the segment to a storage bucket for further inspection.

**Comment by yondonfu** [comment]
Closing for the reason mentioned in the previous comment.
