### ISSUE TITLE
Update blockhash used for determining which segments are challenged

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#175]
As per an update to the protocol which reduces a miner's ability to determine which segments to bother transcoding, we need to update the client to check the correct blockhash in determining which segments will be challenged.

https://github.com/livepeer/protocol/pull/108

Currently, we use the blockhash of the block in which the `claimWork` is called. The new update changes this to the blockhash of the block + 1 from which `claimWork` was called.

**Comment by ericxtang** [comment]
Addressed in https://github.com/livepeer/go-livepeer/releases/tag/0.1.4
