### ISSUE TITLE
HTTP listen and serve error getting swallowed

### ISSUE THREAD

**Issue by BisonAl** [livepeer/go-livepeer#1758]
**Describe the bug**
If there's ever an error returned to https://github.com/livepeer/go-livepeer/blob/master/server/webserver.go#L73 it's not reported. If you check out https://golang.org/pkg/net/http/#ListenAndServe, you'll see that `ListenAndServe` could return an error, which we could in turn be logging here.

We've ran into a scenario today where we're seeing the webserver close, however we're having a difficult time debugging because no error gets bubbled up or logged. 

We'll see this webserver start at https://github.com/livepeer/go-livepeer/blob/master/cmd/livepeer/livepeer.go#L914-L917, and know that `wc` channel is eventually getting closed at https://github.com/livepeer/go-livepeer/blob/master/cmd/livepeer/livepeer.go#L988-L990 because the following log gets thrown:

```
livepeer.go:989] CLI webserver shut down
```

**Expected behavior**
If the http webserver crashes, we can can see the relevant error in outputted logs.

**Desktop:**
Running from alpine linux, `v0.5.14`

**Additional context**
Should be a straight forward fix, editing https://github.com/livepeer/go-livepeer/blob/master/server/webserver.go#L73 from:

```
srv.ListenAndServe()
```

to

```
err := srv.ListenAndServe()
glog.Error(err)
```

If you wanted to get even fancier I think you could one-line it as:
```
glogError(srv.ListenAndServe())
```
but I find this hard to read personally^

**Comment by yondonfu** [comment]
Closed by #1759
