### ISSUE TITLE
VideoID assignment policy in StreamID / ManifestID

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#177]
Right now when a new (HLS) stream is created, there is a random portion of the StreamID (VideoID).  This makes streams hard to query.  We propose an alternative naming scheme:
* If running in onchain mode, use the ethAddr by default (40 chars)
* If running in offchain mode, use all zeros by default (40 chars)
* Allow an RTMP URL parameter `randomID`, which will assign a random portion VideoID (40 chars)
* Allow an RTMP URL `hlsManifestID`, which will override the VideoID with what's passed in (padded / truncated to 40 chars)
* When a transcoder creates transcoded streams, it will try to use the VideoID, unless there is already a local version.  In which case, it will assign a random VideoID and use it across the different video profiles.

This will give us some predictability of the ID, the ability to control the ID, and search for a video stream based on a user's identity.

In addition, when a node starts in on-chain mode, it could read from the contract to get the latest streams and insert it into a user->stream map.  This way, when a Dapp wants to query for streams by a specific user, it will be able to get a quick response.

**Comment by dob** [comment]
I'm not sure I follow the reasoning 100%, but one quick comment...

Offchain mode doesn't necessarily mean off-network. It just means they won't be talking to the ethereum network or submitting jobs on chain, but they can still serve video through a network in offchain mode, and other nodes can request it. So if the all 0's portion of the id makes the streamID not unique or not routable, then this may be a problem.

**Comment by ericxtang** [comment]
I had a conversation with @jozanza - realized the streamIDs are hard to work with currently.  What we want is some kind of consistency for user identity, so the Dapps can use it to create streamIDs that are consistent for users.

The offchain default mode will result in a StreamID like `[nodeID|zeros|videoProfile]`.  This is because you don't have to provide an Ethereum address to run a node in offchain mode.

We could also make the ID random by default, and allow users to override it (which is basically what happens now, but with an uglier interface)

**Comment by j0sh** [comment]
We haven't had the notion of a VideoID (as distinct from a ManifestID) for a while now, closing this issue.
