### ISSUE TITLE
Setting only price per pixel in livepeer_cli succeeds on the node, but livepeer_cli reports an error

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1804]
No other on-chain parameters are updated, and only price per pixel is updated. It appears the price is updated on the node, but livepeer_cli reports `Error applying configuration`.

From Discord:

> And to be clear, it does succeed in resetting the pricePerUnit in the node, but it reports a false error in the livepeer_cli, perhaps, as you say, due to there not needing to be any kind of update done onchain. Either way, it's confusing.

**Comment by red-0ne** [comment]
Tested with a devtool setup
```
docker run --rm -p 8545:8545 -p 8546:8546 --name geth-with-livepeer-protocol livepeer/geth-with-livepeer-protocol:confluence
```
```
go run cmd/devtool/devtool.go setup transcoder
...
./run_orchestrator_with_transcoder_0x...
```
```
./livepeer_cli -http 7937
```

Updating `price per pixel` only with option 13, does not yield any error.
It does out put this

```
Transaction sent. Once confirmed, please restart your node if the ServiceURI has been reset
```

Even though no transaction was sent (as expected)
