### ISSUE TITLE
Not able to run the livepeer node.

### ISSUE THREAD

**Issue by Abhi-789** [livepeer/go-livepeer#1832]
Hello i am working  on livepeer to run broadcaster node so i have followed your documentation but when i clone the repo and run on my local machine it throws error of "github.com/ethereum/go-ethereum/crypto/secp256k1 exec: "gcc": executable file not found in $PATH" and when i go to this url the page is showing 404 not found i am running this code on my ubuntu 18.04 machine. Can you please suggest me or help me how can i run the livepeer node successfully with the source code.

**Comment by yondonfu** [comment]
Hi @Abhi-789 - great to hear that you're interested in working on go-livepeer.

Did you follow the [build from source](https://livepeer.org/docs/installation/install-livepeer#build-from-source) docs?

If not, I recommend using the instructions there.

**Comment by yondonfu** [comment]
Closing this issue because it is stale and without a response. Please re-open if more assistance is needed.
