### ISSUE TITLE
Clean Up /tmp directory

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#184]
Currently the Livepeer node writes video segments into the /tmp directory but never cleans it up.  

We should clean up the segments when the video is terminated.

**Comment by dob** [comment]
Related to this, can we use the content in the tmp directory for a specific
video to "record" into IPFS? So if the video is streamed with the --record
option, at conclusion of the stream we could take all the ts segments for
the video, feed into ffmpeg to convert an .mp4, and then write into IPFS?
And then clean up ;)

**Comment by ericxtang** [comment]
Recording is tracked here - https://github.com/livepeer/go-livepeer/issues/31

Cleanup is done here - https://github.com/livepeer/go-livepeer/pull/209
