### ISSUE TITLE
Silence discovery error logs if the request is cancelled

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1846]
**Is your feature request related to a problem? Please describe.**

During discovery, a B will call GetOrchestrator() on all available Os. Once B receives a sufficient number of responses, it will cancel the remaining requests using a context. The cancellation of these requests results in a ton of error messages indicating that the GetOrchestrator() call failed due to a cancellation. As a result, the logs of B can become flooded with these error logs even though the logs don't indicate any issues with the Os because it was the B that cancelled the request.

**Describe the solution you'd like**

Silence discovery error logs if the GetOrchestrator() call was cancelled.

This [draft PR](https://github.com/livepeer/go-livepeer/pull/1837) outlines one potential approach to silencing those discovery error logs by using the new [errors Is() API](https://golang.org/pkg/errors/#Is). But, the code is untested and it is not clear if the `Is()` API is going to work as expected - I'm not sure if the function that returns the error would need to support error wrapping/unwrapping. An alternative would be to check if the error string contains a context cancellation message. Being able to use the errors `Is()` API could be cleaner though as I think this type of error checking is what it is meant for.

**Comment by kyriediculous** [comment]
Had to wrap the errors instead of concatenating the messages as the API docs of `errors.Is()` suggests. Works as expected, tested it on rinkeby and only get insufficient sender reserve errors now.

 https://github.com/livepeer/go-livepeer/pull/1837
