### ISSUE TITLE
Unable to "become an orchestrator" on Mainnet using `geth` running `-syncmode light`

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1857]
## Describe the bug

When attempting to run an Orchestrator / Transcoder on Mainnet, it is not possible to "become an orchestrator" when using an `-ethUrl` connecting to `geth` running in `-syncmode light`.

Specifically: when using `livepeer_cli` to `Invoke multi-step "become an orchestrator"`, the process fails, reporting an error:
```
ERROR: logging before flag.Parse: E0429 07:27:16.780703   13964 wizard_stats.go:230] Error getting delegator info: unexpected end of JSON input
```

_This means that someone who wants to set up a new Orchestrator on Livepeer's Network must either use Infura (which does work, but isn't so sustainable), or `geth` with `fast` or `full` syncmodes (which also work, but represent a higher barrier to entry for new joiners in terms of SSD storage hardware requirements)._

## Steps To Reproduce

1. Deploy a fresh Ubuntu 20.04 server
2. Run the following to download / install / verify livepeer:
```
wget https://github.com/livepeer/go-livepeer/releases/download/v0.5.17/livepeer-linux-amd64.tar.gz
tar -xzf livepeer-linux-amd64.tar.gz
rm livepeer-linux-amd64.tar.gz
./livepeer-linux-amd64/livepeer -version
```
3. Run geth locally in `light` syncmode, with the following commands:
```
wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.10.2-97d11b01.tar.gz
tar -xzf geth-linux-amd64-1.10.2-97d11b01.tar.gz
rm geth-linux-amd64-1.10.2-97d11b01.tar.gz
./geth-linux-amd64-1.10.2-97d11b01/geth -http -syncmode light
```
4. Wait for geth to sync to the latest head, then continue
5. Run `livepeer` with the following commands:
```
./livepeer-linux-amd64/livepeer -network mainnet -orchestrator -transcoder -ethUrl http://localhost:8545 -pricePerUnit 999 -v 99
```
6. Run the livepeer_cli with:
```
./livepeer-linux-amd64/livepeer_cli
```
7. **UNEXPECTED BEHAVIOUR 1**: observe that only the NODE STATS and ORCHESTRATOR STATS are displayed, and the following error message instead of the ORCHESTRATOR STATS and DELEGATOR STATS:
```
ERROR: logging before flag.Parse: E0429 06:46:39.074775   11863 wizard_stats.go:230] Error getting delegator info: unexpected end of JSON input
```
8. Select option `12. Invoke multi-step "become an orchestrator"`
9. **UNEXPECTED BEHAVIOUR 2**: observe that the multi-step process fails at the very beginning, reporting the following error:
```
> 12
ERROR: logging before flag.Parse: E0429 06:57:14.731383   12884 wizard_transcoder.go:89] Error getting delegator info: unexpected end of JSON input

What would you like to do? (default = stats)
```

## Expected Behaviour

At step 7. **UNEXPECTED BEHAVIOUR 1**, I expect to see ORCHESTRATOR STATS and DELEGATOR STATS displayed, under node status.

At step 9. **UNEXPECTED BEHAVIOUR 2**, I expect to be able to run the process to become an Orchestrator.

## Environment
```
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)
```

**Comment by chrishobcroft** [comment]
Full log of what is shown in the console when running [`livepeer_cli` is here](https://github.com/livepeer/go-livepeer/files/6397045/livepeer_cli.log)

**Comment by chrishobcroft** [comment]
Confirmed as a production network issue by @adrianm on Livepeer Discord:

![image](https://user-images.githubusercontent.com/2212651/116542517-55d93f00-a90a-11eb-81a3-f0dc997a899a.png)

**Comment by yondonfu** [comment]
Were there any error logs on the node when you observed the `Error getting delegator info: unexpected end of JSON input` error in `livepeer_cli`?

**Comment by chrishobcroft** [comment]
Well, as a matter of fact, there were, @yondonfu :
```
E0430 10:38:39.551151   30968 client.go:515] Error getting pending stake: execution aborted (timeout = 5s)
E0430 10:38:39.551213   30968 webserver.go:726] execution aborted (timeout = 5s)
```
So, I guess the issue is with geth in light mode not being able to access the data. I will close this now.
