### ISSUE TITLE
Unable to "become an orchestrator" on Rinkeby using `livepeer_cli`

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1858]
## Describe the bug

When attempting to run an Orchestrator / Transcoder on **Rinkeby** Testnet, _it is not possible to "become an orchestrator"_ using the `livepeer_cli`

Specifically: when using `livepeer_cli` to `Invoke multi-step "become an orchestrator"`, the process fails, reporting an error:
```
ERROR: logging before flag.Parse: E0429 07:41:45.766025   14433 wizard_transcoder.go:89] Error getting delegator info: unexpected end of JSON input
```

_**This represents a serious blocker for the onboarding flow for Livepeer Orchestrators.**_

## Steps To Reproduce

1. Deploy a fresh Ubuntu 20.04 server
2. Run the following to download / install / verify livepeer:
```
wget https://github.com/livepeer/go-livepeer/releases/download/v0.5.17/livepeer-linux-amd64.tar.gz
tar -xzf livepeer-linux-amd64.tar.gz
rm livepeer-linux-amd64.tar.gz
./livepeer-linux-amd64/livepeer -version
```
3. Run geth locally in `fast` mode (default), with the following commands:
```
wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.10.2-97d11b01.tar.gz
tar -xzf geth-linux-amd64-1.10.2-97d11b01.tar.gz
rm geth-linux-amd64-1.10.2-97d11b01.tar.gz
./geth-linux-amd64-1.10.2-97d11b01/geth -rinkeby -http
```
4. Wait for geth to sync to the latest head, then continue
5. Start livepeer with the following command, to connect to local geth:
```
./livepeer-linux-amd64/livepeer -network rinkeby -orchestrator -transcoder -ethUrl http://localhost:8545 -pricePerUnit 999999 -v 99
```
6. Run the livepeer_cli with:
```
./livepeer-linux-amd64/livepeer_cli
```
7. **UNEXPECTED BEHAVIOUR 1**: observe that only the NODE STATS and ORCHESTRATOR STATS are displayed, and the following error message instead of the ORCHESTRATOR STATS and DELEGATOR STATS:
```
ERROR: logging before flag.Parse: E0429 06:46:39.074775   11863 wizard_stats.go:230] Error getting delegator info: unexpected end of JSON input
```
8. Select option `12. Invoke multi-step "become an orchestrator"`
9. **UNEXPECTED BEHAVIOUR 2**: observe that the multi-step process fails at the very beginning, reporting the same error as in step 7:
```
...
15. Get test LPT
16. Get test ETH
17. Sign a message
18. Vote in a poll
> 12
ERROR: logging before flag.Parse: E0430 10:26:23.846409   30745 wizard_transcoder.go:89] Error getting delegator info: unexpected end of JSON input

What would you like to do? (default = stats)
1. Get node status
2. View protocol parameters
...
```

## Expected Behaviour

At step 7. **UNEXPECTED BEHAVIOUR 1**, I expect to see ORCHESTRATOR STATS and DELEGATOR STATS printed under node stats.

At step 9. **UNEXPECTED BEHAVIOUR 2**, I expect to begin the process of staking to my own Orchestrator, and setting my parameters.

## Environment
```
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)
```

## Logs

The `./livepeer` process reports this to coincide with the unexpected behaviour:

```
E0430 10:26:23.844052   30721 client.go:515] Error getting pending stake: execution reverted
E0430 10:26:23.844608   30721 webserver.go:726] execution reverted
```

**Comment by zll-t** [comment]
你好，这个问题有解决了吗？

**Comment by bjp99** [comment]
I was able to get Broadcaster and Orchestrator nodes running using Alchemy on RInkeby.  I got same error trying to use infura.  Ran transcoding tests as well and video segments were sent to rinkeby orchestrator.

**Comment by Pegasus-starry** [comment]
I meet the same issue on Rinkeby Testnet now. Is this issue solved? Or is there any solution now? Thanks.

**Comment by yondonfu** [comment]
This should be fixed on the latest version of the Rinkeby testnet. See https://github.com/livepeer/go-livepeer/issues/2184#issuecomment-1013904752
