### ISSUE TITLE
Can't install livepeer docker on synology

### ISSUE THREAD

**Issue by Wisermerill** [livepeer/go-livepeer#1865]
hello,

i m trying to install livepeer on synology in orchestrator mode via docker. during install, i have this message :
“E0502 15:01:59.364010 1 livepeer.go:382] Failed to create Livepeer Ethereum client: liner: function not supported in this terminal”.

can i add a “passphrase parameter” to avoid this ?

Thanks for your help.

**Comment by yondonfu** [comment]
You can use the `-ethPassword` flag when starting the node. The flag can be used in the following ways:

- `-ethPassword pass.txt` where `pass.txt` is a text file containing your password
- `-ethPassword pass` where `pass` is the password

**Comment by Wisermerill** [comment]
Thanks for your help :)

**Comment by yondonfu** [comment]
No problem! If you encounter any additional issues feel free to ask in [Discord](https://discord.gg/uaPhtyrWsF) as well.
