### ISSUE TITLE
same segments appears in recording

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#1889]
## Problem

When Mist gets transcoding error it retries same segment with different broadcaster. 
If recording is enabled every broadcaster will save this segment and it will appear in resulting recording manifest multiple times.

## Proposed solution

We should save segment's hash into json playlist (S3 storage returns hash after save - we can use that to not to calculate our own hash) and on manifest creation we will skip duplicate segments.

**Comment by iameli** [comment]
Oh interesting. I'm not sure hash will work? Two different transcodes aren't byte-identical.

**Comment by darkdarkdragon** [comment]
> Oh interesting. I'm not sure hash will work? Two different transcodes aren't byte-identical.

It's about source segments - they're retried because they wasn't transcoded.
