### ISSUE TITLE
block_watcher stuck on block_watcher.go:227] missing logs for blockNumber=12591793 - fetching on next polling interval

### ISSUE THREAD

**Issue by JJassonn69** [livepeer/go-livepeer#1909]
**Describe the bug**

I have been trying to figure out how to setup Orchestrator. I finally got it to run past 

I0608 07:34:19.910566  343033 rpc.go:167] Listening for RPC on 127.0.0.1:8935
I0608 07:34:21.910016  343033 rpc.go:234] Connecting RPC to https://127.0.0.1:8935

But after

I0608 07:34:21.915074  343033 rpc.go:207] Received Ping request

the block_watcher just keeps on looping on error msg

I0608 07:36:31.257788  343033 block_watcher.go:227] missing logs for blockNumber=12591779 - fetching on next polling interval
I0608 07:39:31.272945  343033 block_watcher.go:227] missing logs for blockNumber=12591791 - fetching on next polling interval
I0608 07:39:32.567379  343033 block_watcher.go:227] missing logs for blockNumber=12591791 - fetching on next polling interval
I0608 07:39:36.614304  343033 block_watcher.go:227] missing logs for blockNumber=12591793 - fetching on next polling interval

I even left the whole thing running whole night thinking maybe it will finally sync or something.

But nope, it just keeps on showing the error.

Semetimes this comes as error

E0608 07:47:13.386689  343033 block_watcher.go:124] blockwatch.Watcher error encountered - trying again on next polling interval err=UNIQUE constraint failed: blockheaders.hash

any help?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"

**Additional context**

**Comment by yondonfu** [comment]
> the block_watcher just keeps on looping on error msg

Unless you see those messages consistently for every single block number, then this is expected behavior. The node will sometimes need to fetch logs its missing from its ETH provider and this generally shouldn't interfere with the operation of the node.

> E0608 07:47:13.386689 343033 block_watcher.go:124] blockwatch.Watcher error encountered - trying again on next polling interval err=UNIQUE constraint failed: blockheaders.hash

Hm haven't seen this one before. Could you try removing your DB file at `~/.lpData/mainnet/lpdb.sqlite3` and restarting your node and seeing if you still encounter this message?

**Comment by yondonfu** [comment]
Neither of the logs in the OP should impact the operation of the node as the node should gracefully automatically handle those conditions. So, closing this issue, but feel free to re-open if actual problems are observed.
