### ISSUE TITLE
Update `0.5.18` release notes to avoid confusion

### ISSUE THREAD

**Issue by dpurhar27** [livepeer/go-livepeer#1913]
**Describe the bug**
Some of the release notes for `0.5.18` are unclear as related to low gas price improvements, and will become more unclear as solutions for #1906 are implemented.

**To Reproduce**
1. Go to the release notes of [`0.5.18`](https://github.com/livepeer/go-livepeer/releases/tag/v0.5.18)

2. Read the below notes highlighting the gas price changes

> This release includes an important gas price monitoring fix that addresses cases where Ethereum JSON-RPC providers occasionally return really low gas prices for the `eth_gasPrice` RPC call

There's a disconnect between these release notes and the relevant issue solved #1851  . The issue accurately describes the specific impact of the low gas prices.

**Expected behavior**
I believe the release notes should be re-worded to accurately reflect the extent of the update from the relevant issue mentioned above.

Something along the lines of:
> Update to accurately price the face value of tickets, which are caused by low gas prices...

The main reason is with upcoming updates which handle low gas prices to a further extent, the release notes will likely clash and make it harder to understand the subsequent updates occurring across `0.5.18`, `0.5.19`, etc. 
Some parties may decide not to update to `0.5.19`, etc. because they believe the main enhancement re: low gas prices handling are relatively the same across versions.

**Comment by yondonfu** [comment]
@dpurhar27 Good point - I agree that the currently wording of the 0.5.18 release notes can lead to confusion since the 0.5.18 addressed only a single symptom of super low gas price estimates, but did not address all symptoms.

I've updated the [0.5.18 release notes](https://github.com/livepeer/go-livepeer/releases/tag/v0.5.18) to use the following wording:

> This release includes an important fix that allows orchestrators to accurately set ticket face values (previously there were cases where orchestrators would inaccurately set ticket face values to a really low value) by discarding really low non-sensical gas prices returned by Ethereum JSON-RPC providers in the gas price monitor

Feel free to re-open this issue if you think the wording is still confusing.

**Comment by dpurhar27** [comment]
The new wording looks good - thanks!
