### ISSUE TITLE
All trancoding dies after "Application provided invalid, non monotonically increasing dts to muxer in stream" error

### ISSUE THREAD

**Issue by Wisermerill** [livepeer/go-livepeer#1916]
When one stream send by a broadcaster got an error "Application provided invalid, non monotonically increasing dts to muxer in stream" all other stream die.

Running Orchestrator alone on ubuntu and Transcoder on 2 windows 10 PC (nvenc  Transcoder)

**Comment by jailuthra** [comment]
Yeah this occurs due to bad input segments, need to handle it better so that other streams don't get affected. Closing this in favor of a duplicate opened here https://github.com/livepeer/lpms/issues/227
