### ISSUE TITLE
Upgrade to ffmpeg 4.4

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1962]

**Comment by jailuthra** [comment]
Things work smoothly in staging after #1979 and some fixes on the `install_ffmpeg.sh` script to enable the new filters that we use https://github.com/livepeer/go-livepeer/pull/1979/commits/9a710fc17c56c17285eb891b2fa454083ffb9668

Closing this issue out!

**Comment by jailuthra** [comment]
Oops closed by mistake - wrong issue.
