### ISSUE TITLE
A sudden peak in gas price for few seconds result in all jobs are canceled.

### ISSUE THREAD

**Issue by Franck-UltimaRatio** [livepeer/go-livepeer#1966]
when the gas price peaks for a few seconds, we lose all the jobs in progress because the price per pixel briefly exceeds the maximum allowed (1200).

This affects the continuity of service for the broadcaster.

**Comment by yondonfu** [comment]
For reference for anyone looking more closely at this issue, there was also a [Discord conversation](https://discord.com/channels/423160867534929930/429350403272998913/869738685409689600) exploring the possibility of orchestrators continuing to transcode at least for bounded time period when gas prices spike causing the advertised price per pixel to exceed the max specified by a broadcaster.

**Comment by yondonfu** [comment]
Copying a suggestion from Discord:

> That's totally normal though. The pixel price you're setting is adjusted with the current gas price. And if the total goes over 1200, it's too expensive for the Livepeer API.
So users adjust the pixel price all the way to 0 during spikes just to keep getting work. 

> But I'd actually prefer for the pixel price NOT to be automatically adjusted and instead just set a maxGasPrice flag. So I could set the pixel price to 1000 wei (and a maxGasPrice of 150gwei) and it would stay like this no matter the current gas price. If the gas price is too high during the time I get the ticket, I would have to manually redeem it at a later time. That way, I could also make sure that I stay profitable when transcoding but would not lose all the sessions during gas spikes.
