### ISSUE TITLE
mkdir: missing operand

### ISSUE THREAD

**Issue by moulin-louis** [livepeer/go-livepeer#1967]
**Describe the bug**
After following all the step for installing livepeer, I start ./install_ffmpeh.sh and this error return:
mkdir: missing operand

**Expected behavior**
I expect that ./install_ffmpeg.sh should successfully install FFmpeg

**Screenshots**
![image0](https://user-images.githubusercontent.com/52115261/127497601-4a609b95-da28-4f05-9d95-748eceee9e5d.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - 
**Additional context**
Just try yesterday and all work fine on an intel pc

**Comment by yondonfu** [comment]
The install script will default to using the `$HOME` dir. I wonder if the `$HOME` env var is not set for some reason.

Could you check if the `$HOME` env var is set by running `echo $HOME`?

If the `$HOME` env var is not set, you can run `./install_ffmpeg.sh <DIR_NAME>` which will install the deps in `<DIR_NAME>` and then you'll want to set `PKG_CONFIG_PATH=<DIR_NAME>/compiled/lib/pkgconfig` when going through the rest of the build steps for go-livepeer.

**Comment by yondonfu** [comment]
@moulin-louis The `install_ffmeg.sh` script has been updated to work even if the `$HOME` env var is not set so the script *should* work now even in that scenario.

**Comment by moulin-louis** [comment]
Thx you for your help !
