### ISSUE TITLE
Help for a newbie

### ISSUE THREAD

**Issue by Ualiquis** [livepeer/go-livepeer#1970]
Hey !
I am totally new in to computers, and I am trying to download and run the livepeer client (as video miner) on windows, but despite the instructions on the site, I don't understand how to do it at all. Any help would be appreciated, even how and where to use the lines of code that sometimes appear.

**Comment by yondonfu** [comment]
Hi @Ualiquis the issues of this GH repository are better suited for specific feature requests/discussions and bug reports so if you are looking for general help with getting setup then I recommend joining the [Discord](https://discord.gg/uaPhtyrWsF) and asking in the #transcoding channel.

**Comment by Ualiquis** [comment]
Okay thanks, I didn't know it existed.
