### ISSUE TITLE
Convenient defaults for starting livepeer binary

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#198]
Joining the testnet from scratch using the livepeer binary should be reduced to simply running the command:

`$ livepeer`

or, I could also see the argument, in the case of making the production network the default, for

`$ livepeer --testnet`

As it currently stands, I had to run

`$ livepeer -controllerAddr 0x7a00d2c99bfb46ab868ffffcd0880c794f642326 -v 4 -bootID 12207f4182a54efac2784c21ebc779bc36040468e0a41e39ba51baccf3495a5fe81f -bootAddr /ip4/13.59.24.145/tcp/15000 -ethIpcPath ./geth1/geth.ipc -ethPassword <a password>`

The `controllerAddr`, `ethIpcPath`, `bootID` and `bootAddr` should use a default, and the `ethPassword` should prompt you in a secure way if you don't want to type it in plaintext.

**Comment by ericxtang** [comment]
Everything here is addressed in https://github.com/livepeer/go-livepeer/releases/tag/0.1.4
