### ISSUE TITLE
Use multiple orchestrators for verification-enabled streams

### ISSUE THREAD

**Issue by jailuthra** [livepeer/go-livepeer#1994]
- Select multiple orchestrators for verification-enabled streams
- Send the segment for transcoding w/ signature generation to one or many Os

Refer to the steps 3 and 4 in the spec #1991 for details

**Comment by yondonfu** [comment]
Re: step 4 in #1991:

> Signal the O to generate mpeg7 signatures for each of the transcoded renditions - by setting a new field CalcSign: true in the core.SegTranscodingMetadata structure:

Just to clarify - does this imply that B requests MPEG-7 signatures for every segment?

**Comment by jailuthra** [comment]
> Just to clarify - does this imply that B requests MPEG-7 signatures for every segment?

Yep even if the B only matches the signatures for every `1/Freq` segments, the O is still expected to generate it for each segment.

We don't want the O to know exactly which segment will be checked - as that would make it trivial to cheat on segments that are not checked. That's also the motivation behind the B checking `1/Freq` segments probabilistically, as opposed to uniformly checking every `Freq`th segment, using sequence numbers, like we chose to do for scene-classification.

A downside of this approach is that the O spends more compute power and time on generating signatures for segments that won't even be checked.

**Comment by yondonfu** [comment]
Closed by #2045
