### ISSUE TITLE
Use verified transcoding results by matching mpeg7 signatures

### ISSUE THREAD

**Issue by jailuthra** [livepeer/go-livepeer#1996]
- Download and match mpeg7 signatures of each untrusted orchestrator across a trusted orchestrator
- Use one of the verified orchestrator's transcoded result and insert it into the playlist

Refer to the steps 6 and 7 in the spec #1991 for details

**Comment by yondonfu** [comment]
Re: step 6 in #1991:

> Pick a rendition at random (suppose 720p)

I believe the MPEG-7 signature is generated for the source segment no? If this is the case, then there would just be a single signature so there wouldn't be a need to pick a rendition.

**Comment by jailuthra** [comment]
> I believe the MPEG-7 signature is generated for the source segment no? 

The original plan was to generate signatures for [each rendition](https://github.com/livepeer/internal-project-tracking/issues/140#issuecomment-867537283) - and on LPMS side the filtergraph is fed frames [after they've been scaled](https://github.com/livepeer/lpms/pull/253/files#diff-acc605002f961264d9038a45f756fe4eed145b48467c34f0208f8d58f97e1903R455).

**Comment by yondonfu** [comment]
> The original plan was to generate signatures for each rendition - and on LPMS side the filtergraph is fed frames after they've been scaled.

Ah I see - thanks for clarifying.

Question about calculating the sig after frames have been scaled and before passing them into the encoder: does the signature filter do any frame re-scaling (I know this happens in other perceptual hash algos) or does it do calculations directly off the provided frame? I ask because I'm curious if the sigs calculated for each output ends up being exactly the same as a sig calculated for the input or if the sigs end up being slightly different for each output (but all of these sigs would result in a match when running the comparison function).

**Comment by jailuthra** [comment]
> does the signature filter do any frame re-scaling 

Yes it scales down the luminance channel to a [32x32 square](https://github.com/livepeer/FFmpeg/blob/b344789a31a2d806be702239d7614f7a9f51f941/libavfilter/vf_signature.c#L206-L213) before it runs the average/difference operations on this 32x32 B&W representation of the original image.

> I'm curious if the sigs calculated for each output ends up being exactly the same as a sig calculated for the input or if the sigs end up being slightly different for each output

Good question. Not sure if they end up being bit-by-bit the exact signature - but they did mostly match during comparison IIRC:

Running the 2nd test in our [script from before](https://gist.github.com/yondonfu/084eb52062cc12a54f5d737174d1d389#file-ffmpeg_sig-sh-L22), where we compared scaled+re-encoded renditions - at max 1-3 frames didn't match for each comparison between 720p vs 360p/240p renditions.

Note that these renditions were re-encoded so artefacts must have been introduced. On the O we generate signatures post-scaling but pre-encoding, so differences are further minimized.

**Comment by yondonfu** [comment]
Closed by #2045
