### ISSUE TITLE
Review Architecture Deck + Diagram

### ISSUE THREAD

**Issue by pglowacky** [livepeer/go-livepeer#2012]
[Notion doc with background](https://www.notion.so/livepeer/Architecture-Review-Process-d5e3b1868d6d43e7a1ee274f05c7580d)

[Architecture Review Deck](https://docs.google.com/presentation/d/1Nf9A7dpL5lGuXYBzH2qeESaHBAqBHfmGInZSbQoxEho/edit#slide=id.gad7e1912bd_2_328)

[Architecture Diagram](https://miro.com/app/board/o9J_lBN5CWA=/)

Have you:

- [ ] Reviewed both the deck and diagram

- [ ] Made updates as necessary 

- [ ] Believe that the deck and diagram is up to date, to your knowledge

**Comment by yondonfu** [comment]
Issue moved to [livepeer/livepeer-infra #671](https://github.com/livepeer/livepeer-infra/issues/671) via [**ZenHub**](https://www.zenhub.com/)
