### ISSUE TITLE
Switch to using `urfave/cli` instead of using the default `flag` package

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#203]
Our command line instructions are a little hard to read.  The app is getting quite big, and we should switch to a more full-featured framework.

https://github.com/urfave/cli

We should also check out https://github.com/manifoldco/promptui

**Comment by samparsky** [comment]
@ericxtang @j0sh is this still needed? I'd like to work on it

**Comment by j0sh** [comment]
Curious, what would the `urfave-cli` output look like over what we have now?

One thing I've been looking at is a way to integrate flag parsing along with a configuration file format. Bitcoin is a good example of this feature. Looks like urfave-cli can do that, I'd prefer to use something like TOML over JSON or YAML.

Generally, how we handle flags needs a **lot** of cleanup. Flag parsing itself isn't really a problem, but rather how we check and use those flags in `cmd/livepeer`. I realize this is probably a little too vague for a bounty right now; just thinking out loud here. Anyway this train of thought probably belongs as a separate ticket...

**Comment by ericxtang** [comment]
Good question @j0sh.  I think we'll need some command line UX design here before proceeding.  This ticket was created a long time ago (I think even before the cli was created).  Now that we have the CLI, it feels like that's where the work should happen.

ps - this issue was initially intended to be less about the flags, and more about how users can interact with the node in the command line.

@samparsky are you familiar with the `livepeer_cli`?  How would you improve it?

**Comment by samparsky** [comment]
@ericxtang 

### Improvements
- The UI currently requires entering the number to select a menu item, with `promptui` we can change to allow using arrow keys to navigate and pressing enter to selecting a menu item.

- Also `promptui` allows to add colors, so we can separate cli tasks under different sections like 

*Informational*
1. Get node status
2. View protocol parameters
3. List registered orchestrators
4. Print latest jobs

*Invoke*
5. Invoke "initialize round"
6. Invoke "bond"
7. Invoke "unbond"
8. Invoke "rebond"
9. Invoke "withdraw stake" (LPT)
10. Invoke "withdraw fees" (ETH)
11. Invoke "claim" (for rewards and fees)
12. Invoke "transfer" (LPT)
13. Invoke "deposit" (ETH)
14. Invoke "withdraw deposit" (ETH)
15. Set broadcast config
16. Set Eth gas price

*Contract*
17. Get test LPT
18. Get test ETH

- `urfave/cli` offers the opportunity to allow config files and flag parsing
- Pretty print details and use table(https://github.com/jedib0t/go-pretty) package to display in a more user friendly way.

- Show a processing icon while the detail is being fetched, currently the terminal is just blank

**Comment by thomshutt** [comment]
Going to close this, since it's gone for so long without being picked up and we now support some of the discussed things (config file) via the `flag` package
