### ISSUE TITLE
Not clear what units to use for `-maxGasPrice` value

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#2032]
## Problem Statement

I want to set the `-maxGasPrice` flag, but I don't know whether it is denominated in wei or gwei.

**Comment by yondonfu** [comment]
@chrishobcroft The value for the `-maxGasPrice` is denominated in wei right now. The help description for the flag can be updated to indicate that the value is denominated in wei.

TODO:

- [ ] Update help description for gas price flags (including `-maxGasPrice`) to indicate denomination in wei
