### ISSUE TITLE
MPEG-7 video signature capability on orchestrators

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#2035]
Implementation is already complete and the relevant commits just need to be cherry picked into a PR that can be merged into master.

**Comment by jailuthra** [comment]
I missed the case of [split O/T setups](https://github.com/livepeer/go-livepeer/issues/1991#issuecomment-924201298) in the original spec.

Extending the scope of this issue to include changes for that, along with rest of the orchestrator side commits, in a single PR.
