### ISSUE TITLE
Ability to configure livepeer with a config file instead or cmd options

### ISSUE THREAD

**Issue by Strykar** [livepeer/go-livepeer#2047]
**Is your feature request related to a problem? Please describe.**

I currently have 13 switches to configure livepeer when it starts.
This just adds to package maintenance woes (I'm currently [packaging](https://aur.archlinux.org/packages/go-livepeer-bin/) livepeer for Arch Linux) as the `Exec` call is 3 lines long (split up) in the systemd unit instead of just:
`Exec = /usr/bin/livepeer -config /etc/go-livepeer/livepeer.conf`

Are there any plans to have it read these from a config file instead on the roadmap?

It would also _not_ expose the ETH wallet address and password via `/proc` and thus tools like `top` / `htop` / system monitors (tho that could be skirted (on linux) by remounting `/proc` with `hidepid=2`) but again, requires more user education and intervention.

**Describe the solution you'd like**
Enable livepeer to read all the switches `livepeer -h` presents from a config text file instead.

**Describe alternatives you've considered**
Create a file with each of the switch values in a systemd environment file in `/etc/go-livepeer/livepeer.conf` and then:
`# mount -o remount,rw,nosuid,nodev,noexec,relatime,hidepid=2 /proc`
`# sysctl -w security.bsd.see_other_uids=0` works on FreeBSD & OpenBSD, unsure of Darwin.

**Additional context**
This feature would save time for packagers across all *nix distributions and even make powershell / batch files clearer to write and maintain. And TBH, I have no idea of the effort involved and don't know Go to have led with a PR.

**Comment by jailuthra** [comment]
From my understanding the wallet password is already read from a file passed in via `-ethPassword /path/to/file/with/password`. The file should ideally be protected via OS file permissions.

Not sure why ETH wallet address is sensitive on a public/decentralized network that anybody can query anyway? But maybe an optional file can be passed for that as well - extracting out the common `ReadFileOrString` functionality like done [here](https://github.com/livepeer/go-livepeer/pull/2044/files#diff-9401368d17f2d5114fe047df94398e27532eb15b3c9c614d140ecb1edef42e39R454).

Aside from the argument privacy concerns, I agree that UX-wise it's definitely easier to have commonly used args in a file, and it sucks to copy them around. But some bash re-direction can make it work even with the current setup:
```
$ livepeer $(< /etc/go-livepeer/livepeer.conf)
```
Although `/proc/PID/cmdline` will still show the argument contents.

**Comment by Strykar** [comment]
You're right, I was aware of it being able to read ethpassword from a file and promptly forgot about it.
Sorry about that, I'll update my package to do that instead.

I feel why expose even ETH wallet addresses at all, especially on a machine that may have other personally identifiable information about the orchestrator, nothing could be gained by exposing this via `/proc`.

The systemd way would of doing`$ livepeer $(< /etc/go-livepeer/livepeer.conf)` would be `$ livepeer $RUNFLAGS` while `EnvironmentFile-=/etc/livepeer.conf` is set.

I'm just trying to make it easier to package, like for compiling from source, the instructions ask to run a shell script to patch ffmpeg. This should probably be fleshed out in to a patch or a separate repo, which I understand may not be a priority right now, but prevents it from being packaged due to distro packaging guidelines, which, correctly, will not allow external scripts.

**Comment by Strykar** [comment]
Case in point, from #transcoding on Discord -
```
ftkuhnsman — Today at 1:27 AM
As a result of testing my idea for an autoscaling solution, I have a question about the way an orchestrator
handles running out of transcoding capacity. Scenario1: I set my O and T maxsessions flag to the same value.
If the O receives excess streams it results in an “OrchestratorCapped” error. Scenario2: I set my
O maxsessions flag to a value higher than my T maxsessions flag. When the T capacity is reached,
any additional streams sent to the O result in an error “no transcoders available”.

Question: are these errors treated differently by broadcasters/the network? What happens if livepeer
sends a test stream in both scenarios? If my O continually produces the “no transcoders available”
error does that affect my Os likelihood of being selected for future streams?
I hope my questions make sense 
```
Adding all the switches to something like `/etc/livepeer/conf` that can be safely `-HUP`'d or adding all of them to the `livepeer-cli` binary would make managing multiple geographically diverse transcoders a bit easier.

**Comment by hthillman** [comment]
Here's a proposed solution that I've discussed with @yondonfu and @Strykar - crossposting here so info is not lost in the Forum:

- Add support for using a config file (#101) so that it is easier to start livepeer with systemd / non-bash setups
- Provide a guide for restarting livepeer if you need to change your configuration without losing any streams that are currently coming in by spinning up a node with the new configuration, moving streams over to that new node and then shutting down the existing node. Something similar to this [Lifecycle - Lotus Docs 1 ](https://lotus.filecoin.io/docs/storage-providers/lifecycle/#safely-restarting-the-miner-daemon)(but hopefully simpler) along with some technical changes to make it easier to do

will update with new labels soon!

_edit: realizing this partially duplicates #101_

**Comment by leszko** [comment]
I think what @hthillman described is exactly right. This issue is a duplicate of #101, so I think we can close this one and continue all the discussion in #101. 

Guide for restarting Livepeer, basically Livepeer Deployment Guide is a completely separate issue, so I created this https://github.com/livepeer/go-livepeer/issues/2129
