### ISSUE TITLE
Add metrics for fast verification

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#2052]
### Metrics to add

Counters:
- Verifications done
- Verifications failed
In Grafana that will be shown as
- Verifications Success = fail / done

Counters:
- for `segment_transcoded_total` counter add tags trusted/untrusted

- add `verify_enabled_current_sessions_total`. It will be number of current sessions that have verification enabled.
In Grafana it will be
`verify_enabled_current_sessions_total`/`current_sessions_total` = percentage of current sessions that have verification enabled

Counters:
- add `using_untrusted_verified_orchestrator_current_sessions_total`. It will be number of current sessions that have verification enabled and actually using untrusted (and verified) orchestartor.
In Grafana it will be
`using_untrusted_verified_orchestrator_current_sessions_total`/`current_sessions_total` = percentage of current sessions that actually use untrusted orchestrator.

**Comment by darkdarkdragon** [comment]
@yondonfu @jailuthra wdyt?

**Comment by jailuthra** [comment]
Overall LGTM! 

If I understand correctly, we'll be able to query and visualize the following high level metrics after the proposed changes are implemented:

> Verifications done
    Verifications failed
    In Grafana that will be shown as
    Verifications Success = fail / done

**(1)** Verification success rate, everytime a segment is sent to multiple Os for verification, if the perceptual hashes match we increment the success counter, else we increment the failure counter.

Given that we pick one trusted O and two untrusted Os, I wonder how the counter update will happen if only one untrusted O's hash matches?

> for `segment_transcoded_total` counter add tags trusted/untrusted

**(2)** Ratio of segments transcoded by a trusted O v/s an untrusted O.

>  `verify_enabled_current_sessions_total`/`current_sessions_total` = percentage of current sessions that have verification enabled
>  `using_untrusted_verified_orchestrator_current_sessions_total`/`current_sessions_total` = percentage of current sessions that actually use untrusted orchestrator.

**(3)** Ratio of on-going stream sessions that have verification enabled via the auth webhook v/s total on-going stream sessions.
**(4)** Ratio of on-going stream sessions that had verification enabled **and** are actively using an untrusted O that passed verification v/s total on-going stream sessions

Maybe we can combine these into a single graph to easily compare untrusted+verified v/s verified v/s total sessions?

**Comment by yondonfu** [comment]
Generally LGTM. One minor suggestion I have is to use the `fast_verification_` or `fast_verify_` prefix for metrics for clarity since other types of verification (i.e. full verification from https://forum.livepeer.org/t/transcoding-verification-improvements-fast-full-verification/1499) will be included in the future.

> Verifications Success = fail / done

@darkdarkdragon Should this be `success % = (done - fail) / done`?

> Given that we pick one trusted O and two untrusted Os, I wonder how the counter update will happen if only one untrusted O's hash matches?

@jailuthra If the phash returned by the trusted O is the source of truth, I think we can record any phash mismatch from an untrusted O as a failure. So, in the above example, for one of the untrusted Os no failure is recorded and for the other untrusted O a failure is recorded. WDYT?

**Comment by darkdarkdragon** [comment]
> @darkdarkdragon Should this be success % = (done - fail) / done?

Sure. What I wrote wasn't exact formula, it was just to show that it will be ratio 😄 

>  So, in the above example, for one of the untrusted Os no failure is recorded and for the other untrusted O a failure is recorded. 

I think yes - that this will count as two verifications done and one failure.

**Comment by jailuthra** [comment]
> I think we can record any phash mismatch from an untrusted O as a failure.
> I think yes - that this will count as two verifications done and one failure.

Sounds good :+1:

**Comment by yondonfu** [comment]
Closed by #2059
