### ISSUE TITLE
Return 422 to HTTP push client when max # of retries is hit

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#2069]
We already return a 422 if the transcoding error is a [non-retryable error](https://github.com/livepeer/go-livepeer/blob/e1518db8fb0350c520c6b304a1fb7046380dc3da/server/mediaserver.go#L931). There are cases where a B cannot currently attribute a transcoding error to the source segment or the O. As a result, B cannot just mark these errors as non-retryable and should retry. However, if the B hits the max # of retries then it is probably safe (given a reasonable cap on the # of retries - the default is 3) to consider the segment as not transcodeable. In these cases, B can return a 422 as well to tell the HTTP push client to not send the segment again.

**Comment by iameli** [comment]
I'd advocate for doing [this](https://github.com/livepeer/go-livepeer/issues/1744) first - I'm more interested in tracking down the root cause of Kryptonite segments rather than mitigating their impact. Both good ideas though! https://github.com/livepeer/go-livepeer/issues/1744

**Comment by yondonfu** [comment]
I hear you on tracking down the root cause of untranscodeable segments being more important and I agree with that. However, I think this issue would only require changes to a couple lines of code and if the changes required on the HTTP push client side (i.e. Mist) is also a single line code change then completing this could be a small quick win that wouldn't interfere with https://github.com/livepeer/go-livepeer/issues/1744 which likely will take a bit longer to complete the implementation + deploy cycle. Plus, ideally in the area of the codebase that we detect non-retryable errors + hitting max retries we can just drop in the code for segment uploads as well.
