### ISSUE TITLE
feature: segment slicing wire protocol

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#2072]
To make clipping work well, we're going to need to make frame-accurate cuts of video clips. When cutting from the end of a video clip (the "from point"), any muxer may simply discard video frames. However, when cutting from the front of a video clip (the "to point"), we need to ensure a keyframe gets created at the appropriate time; we must decode the entire video clip but only start encoding from the given timestamp.

My attempt at accounting for all of the necessary changes to implement such a thing:

### HTTP Ingest

* We already have a `Content-Duration` parameter in milliseconds. Proposal: add two additional HTTP headers to allow for in points and out points, like so:

```
# I'd like to cut one second out of the middle of this eight-second clip, so:
Content-Duration: 8000
Content-Slice-From: 4000
Content-Slice-To: 5000
```

Timestamps are in milliseconds and are calculated from the first timestamp present in the video segment.

### B <> O Wire Protocol

**Discovery**: Only Os that have updated to the latest version will support this feature, so we'll need a new capability for discovery, perhaps `Capability_SegmentSlicing`

**Protobuf**: We'll need two new optional fields on `VideoProfile` to make this happen, perhaps `from` and `to`? I've never named a protobuf field before.

### LPMS

This far down, it should be as simple as using the correct frame-accurate ffmpeg parameters to make the cut, something like: `-ss 00:01:00 -to 00:02:00`.

### Open questions that I don't know the answer to

* Does this muck with our pixel-counting logic at all? We're decoding N frames of video but only encoding N-K frames of video. Is this a DDOS vector — sending in huge video segments and asking for one frame in the middle? Personally, as a user, I'd be 100% fine with paying for the full segment either way even if some of the output frames are discareded.

* Ditto, but does this cause problems with fast verification at all? Is it a problem with the sampling?

**Comment by victorges** [comment]
Instead of `in`/`out`, what do you think of `start`/`end` or `from`/`to`? 

I think the in/out terms are not very obvious and I'd generally relate them to input/output, on which case I don't understand directly what they mean on the video transcoding flow (but I can fuzzily understand that in=start and out=end?)

**Comment by yondonfu** [comment]
> Instead of in/out, what do you think of start/end or from/to?

Slight preference for from/to from the above. Another alternative if we want to follow ffmpeg terminology is seek/to - when you cut a video using ffmpeg it seeks to the specified timestamp and then cuts starting from there until the specified to timestamp [1]. I'm cool with either so defer to others on that.

> Does this muck with our pixel-counting logic at all? We're decoding N frames of video but only encoding N-K frames of video.

I think this should be ok. We just need to make sure LPMS only reports the # of pixels from the N-K encoded frames. Based on a quick glance at [the code](https://github.com/livepeer/lpms/blob/e0a6002c849649d80a470c2d19130b279291051b/ffmpeg/encoder.c#L324) seems like should be fine as long as we only call `encode()` on the frames that need to be encoded and skip the rest.

> Is this a DDOS vector — sending in huge video segments and asking for one frame in the middle?

If we make sure you need to pay for the # of pixels decoded then in this case you should still have pay an amount proportional to the amount of decoding and encoding that is being done. (This is assuming that seeking to the relevant time range is negligible cost wise - although if you really needed to you could probably figure out a way to charge for the # of frames that you need to seek through).

> does this cause problems with fast verification at all? Is it a problem with the sampling?

I think we'll just need to make sure that the signature/signature_cuda filters used in LPMS to calculate the MPEG-7 video signature only receive the frames that are being encoded. Then, I think from B's perspective it would receive renditions/video signatures from a set of Os in the same way that it would for any other segment.

[1] https://trac.ffmpeg.org/wiki/Seeking#Cuttingsmallsections

**Comment by iameli** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Video-User-Team-5dd2c75e4ee08500015994d7/issues/livepeer/go-livepeer/2072?planning-poker) with ZenHub @darkdarkdragon @victorges @ya7ya

**Comment by iameli** [comment]
Reclaiming this issue for addition of slice parameters to the B<>O wire protocol.
