### ISSUE TITLE
Running `./test.sh` locally fails

### ISSUE THREAD

**Issue by leszko** [livepeer/go-livepeer#2095]
**Describe the bug**
Running `./test.sh` fails locally with the following error.

```
--- FAIL: TestPush_MultipartReturnMultiSession (0.03s)
    push_test.go:1661: 
            Error Trace:    push_test.go:1661
            Error:          Not equal: 
                            expected: "UNtrusted transcoded binary data"
                            actual  : "trusted transcoded binary data"
                            
                            Diff:
                            --- Expected
                            +++ Actual
                            @@ -1 +1 @@
                            -UNtrusted transcoded binary data
                            +trusted transcoded binary data
            Test:           TestPush_MultipartReturnMultiSession
    push_test.go:1667: 
            Error Trace:    push_test.go:1667
            Error:          Not equal: 
                            expected: 0x20
                            actual  : 0x1e
            Test:           TestPush_MultipartReturnMultiSession
```

At the same time, the GH Action looks green.

**To Reproduce**
Execute `./test.sh`.

**Expected behavior**
All tests pass.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Ubuntu
- Golang version: 1.17.2

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by yondonfu** [comment]
Initial thoughts on possible reasons for tests passing in CI, but failing locally:

- OS?
- Go version?

**Comment by leszko** [comment]
I checked the Go version and it does not matter. I think it can be related to one of these:
- OS (I use ubuntu 20.04, GH action uses 18.04)
- FFMPEG lib versions

@darkdarkdragon do you maybe have any idea why `TestPush_MultipartReturnMultiSession` may work on some machines and not work on some others?

**Comment by leszko** [comment]
I investigated it deeper and it seems related to LPMS and FFMPEG. I created a related GH Issue in the lpms repo: https://github.com/livepeer/lpms/issues/272

**Comment by darkdarkdragon** [comment]
@leszko @yondonfu @oscar-davids this happens because I've put binary `test.phash` file that is used in this test into git-lfs.
So git-lfs should be properly initialised for the repo
```sh
git lfs install
git lfs pull
```

**Comment by leszko** [comment]
Thanks @darkdarkdragon for the fix. It all works smoothly now!
