### ISSUE TITLE
0% success rate for ~13 minutes

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#2096]
So there was a three-minute CoreWeave outage earlier today:

![image](https://user-images.githubusercontent.com/257909/140842755-1943f8f6-c42c-4026-931d-f4a6e9a2e7e0.png)

Fair enough that the US broadcasters didn't have a great time for those three minutes. However, the 0% success rate went on much longer, about 13 minutes:

![image](https://user-images.githubusercontent.com/257909/140842664-4a27e22d-1785-4c2f-93ff-30c7d170e1e3.png)

A few broadcasters drop all at once, then they drop all at once until they're at a 0% success rate.

I captured logs from one of the affected broadcasters for the whole duration here: https://github.com/livepeer/internal-project-tracking/issues/243

It's hard to figure out what the Bs are doing while it's down — parsing through the logs for each time I find a lot of successful discoveries and transcode attempts but not a lot of explanations as to why the transcodes are failing. There are a lot of watchdog resets too.

**Comment by thomshutt** [comment]
👴 Closing this - can reopen if the issue reoccurs
