### ISSUE TITLE
Transaction Confirmations in 'livepeer_cli'

### ISSUE THREAD

**Issue by hotuan87** [livepeer/go-livepeer#2106]
'livepeer_cli' would benefit greatly from including transaction confirmations to avoid costly mistakes.

(1) It is too easy to accidentally initiate transactions without confirmations, especially for new users exploring it for the first time. In the case of entering the wrong wallet address by accident, a simple "Are you sure? Y/N" confirmation before initiating a transaction would stop an expensive error.

(2) For transactions you intend to make, it would be great if livepeer_cli could at least tell you what transactions are about to be made and what the estimate gas fees are going to be. The documentation for registering and activating an Orchestrator doesn't warn people about the 3 or 4 transactions it needs to run in the process. Perhaps that's because they used to be minimal in cost, but these days, it can be very expensive for first timers who aren't aware of the cost.

Any regular wallet will inform you of transaction fees before you initiate. This is especially a big deal with transaction fees being so high right now. A first time user, in particular, may not realize they are about to spend $500-1,000 in transaction fees just to activate their Orchestrator and stake LPT.

**Comment by hthillman** [comment]
Split into #2212 and #2213

we should be able to easily add #2212, but #2213 will take a little more time
