### ISSUE TITLE
Add `minGasLimit` flag or a buffer to the dynamic gas estimation

### ISSUE THREAD

**Issue by dpurhar27** [livepeer/go-livepeer#2112]
**Is your feature request related to a problem? Please describe.**
The gas estimation logic used by the client is faulty - sometimes it under-estimates the gas required for a txn which leads to txn failure with `out of gas`. This leads to losses to the client operator in the form of wasted txn fees, and potentially missing their periodic rewards claim which means losing rewards.

**Example**

- `rewardWithHint()` call using gas limit of `241,573` fails with `out of gas`: https://etherscan.io/tx/0x4987d681365e83ad2917e7e837b3939892015f789a5c1a986002626421607b36

- The retry of the `rewardWithHint()` call a few minutes later using a higher gas limit of `318,097` succeeds, and ends up using `299,724` (higher than the previous gas limit): https://etherscan.io/tx/0xee7e30252238ea0f0f2f2fa21875f3787e7d5e19b1deff4be0b39dddca96e5cc

Note, both txns input the same parameters, further showing the txn only failed due to faulty estimation of gas limit.

**Describe the solution you'd like**

There's two solutions I have in mind, either would be valid:

1. Add a `minGasLimit` flag (similar to the `minGasPrice` flag), which a client operator can use to set a min. gas limit for txns they will send out. This guarantees certain performance from the client, leading to more stability of the software operation side

2. Continue to only use the dynamic gas estimation functionality, but add a buffer % to whatever the value returned is. This buffer accounts for slight state changes on-chain that may occur before the txn is broadcast and mined, which currently break the gas estimation logic and cause the txn to fail.

The buffer % can be a global value applied to each txn type for simplicity, but would need to be on the higher side (say 30%) - or it can be tailored to each type of txn, considering what state changes and gas used volatility the function to be executed may be affected by to make it more accurate. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by leszko** [comment]
Thanks, @dpurhar27 for creating the GH Issue.

Could you check if maybe the flag [`-gasLimit`](https://github.com/livepeer/go-livepeer/blob/master/cmd/livepeer/livepeer.go#L120) help with the issue you described?

IIUC the current logic works as follows:
- If the flag `-gasLimit` is specified, then it's used for every transaction
- If the flag `-gasLimit` is not specified, then the gas limit is estimated using the [default go-ethereum logic](https://github.com/ethereum/go-ethereum/blob/fa9671851272129c9cba90ed4385d5b0558d34a1/accounts/abi/bind/base.go#L329)

**Comment by leszko** [comment]
There is also a related GH Issue to improve the Gas Limit estimation. Please check: https://github.com/livepeer/go-livepeer/issues/2081

**Comment by dpurhar27** [comment]
HI @leszko , thanks for the response.

Great, it sounds like the `-gasLimit` flag will be a good workaround as a stop-gap for now, until #2081, etc. are fully addressed. 

Naturally, it's sub-optimal to be setting a really high gas limit where it's not necessary. Generally this makes it slower to get included into blocks IIRC because the default ETH client forms full blocks based on gas limits set, not `gas used`.

**Comment by hthillman** [comment]
@leszko can this be closed in favor of #2081?

**Comment by leszko** [comment]
Yes, I think. Closing.

@dpurhar27 Feel free to reopen if needed.
