### ISSUE TITLE
Clear warning on CLI Address List

### ISSUE THREAD

**Issue by hthillman** [livepeer/go-livepeer#2120]
**Motivation**
Users are regularly sending LPT to the contract address. We don't know if this is due to confusion on the CEX side or if people are getting confused in the CLI

**Proposed solutions**
- Add a clear warning "FOR REFERENCE ONLY - DO NOT SEND TOKENS" below any address where users should never send funds
- Update verbiage for "ETH account" -> "Your account"

e.g.,
```
Controller Address
FOR REFERENCE - DO NOT SEND TOKENS
*--------------------------------------------
LivepeerToken Address
FOR REFERENCE - DO NOT SEND TOKENS
*--------------------------------------------
LivepeerTokenFaucet Address
FOR REFERENCE - DO NOT SEND TOKENS
*--------------------------------------------
Your Account

```

![image.png](https://images.zenhubusercontent.com/5ab30f774b5806bc2bcbdfa6/411b2435-90c4-4f18-b468-b1729d1128e7)

**Comment by papabear99** [comment]
I think the first 3 are great ideas and make it very clear to not send anything to those addresses.

Suggestion for the ETH Account update is to still reference ETH Account in the description for users that are aware that ERC20 Tokens should be sent to their ETH account **and** for newer users to know that their "Account" _is_ an ETH account. 

**Your Orchestrator / ETH Account**

Another idea is to remove the following addresses from the default node stats view and move them to Option 2 in the CLI "View protocol parameters"

**Comment by hthillman** [comment]
@papabear99

 > Your Orchestrator / ETH Account

How about just 
```
Orchestrator Account
YOUR WALLET FOR ETH & LPT
```

I want to make it very clear that LPT should go to that account as well

**Comment by leszko** [comment]
I've sent a PR with the update https://github.com/livepeer/go-livepeer/pull/2127

Note that we use also CLI for the Broadcaster, so in case of Brocaster, it prints `Broadcaster Account` instead of `Orchestartor Account`.

**Comment by papabear99** [comment]
All sounds good to me
