### ISSUE TITLE
Bug: cannot process payments

### ISSUE THREAD

**Issue by Shawak** [livepeer/go-livepeer#2128]
**Describe the bug**

Getting the following error message besides having enough stake to be in the active orchestrator set:
```
error processing payment: orchestrator 0xd966[..] is inactive in round 2389, cannot process payments
```

**To Reproduce**

I increased my stake from 10.75 by 12.3 to 23.03. At times writing this ticket, the initial value of 10.75 and ofcourse the 23.03 should be enough to be in the active set of orchestrators. But my orchestrator didn't receive any work a minute after increasing my stake.

**Expected behavior**

Increasing my stake shouldn't kick me out of the active set.

**Screenshots**

- Minimum LPT to be in the active set:
![image](https://user-images.githubusercontent.com/3829602/145169815-2feed59b-b9d0-401b-8404-42633a8dcb88.png)
- My orchestrator:
![image](https://user-images.githubusercontent.com/3829602/145169991-370586e8-fb50-40ef-8f79-4e740151b5f2.png)

**Additional context**
- Please note that this problem is different from https://github.com/livepeer/go-livepeer/issues/1482 and https://github.com/livepeer/go-livepeer/issues/1610, because it wont resolve by restarting the node.
- Also when starting it, I am getting `5259 livepeer.go:1134] Orchestrator 0xd966[..] is inactive`

**Comment by Shawak** [comment]
Looks like waiting for the next round solved the issue.

**Comment by yondonfu** [comment]
Hey @Shawak glad this was resolved for you. FYI when an orchestrator has enough stake to join the active set (i.e. the top 100 orchestrators with the most stake), it will join the active set in the next round which is why you observed this behavior.

**Comment by Shawak** [comment]
Hey @yondonfu, I know. But as mentioned in the ticket, I should've never left the active set because I always had enough stake to be in the top 100.
