### ISSUE TITLE
Add documentation for all error messages

### ISSUE THREAD

**Issue by Strykar** [livepeer/go-livepeer#2138]
**Is your feature request related to a problem? Please describe.**
All the errors logged by the livepeer binary should be documented.

**Describe the solution you'd like**
Add documentation for each error the livepeer binary may log.

**Additional context**
https://github.com/livepeer/go-livepeer/issues/2104

**Comment by AuthorityNull** [comment]
Any documentation that can be provided for the currently vague error messages would help Orchestrators better understand the day to day operation of their node(s) and will help eliminate a lot of the guesswork that exists currently. This would be greatly appreciated.

**Comment by JJassonn69** [comment]
It would be really great if you could search for the common errors and find out the general issue associated with it.

**Comment by JJassonn69** [comment]
The reason for this error is not well known yet. I believe it could be the misconfiguration on the broadcaster side but I could be wrong.

The errors are in the #2167 issue I started.

**Comment by leszko** [comment]
I think the scope of this GH Issue is too big. It's technically not possible to document ALL errors we produce in the code. I suggest taking a more pragmatic approach and creating a list of the most common errors (maybe #2167 by @JJassonn69 is a good start!) and for each error, do the following:

- Try to improve the error message (the best documentation is the code and the error log!)
- If not possible (because e.g. the solution is too long), then create "Troubleshooting" section in our docs and add the solution.

**Comment by hthillman** [comment]
@leszko 

A few common errors:

```
error processing payment: TicketParams expired
```

```
Could not transcode err="ZeroSegments"
```

in the cli, linux only:
```
error creating Ethereum account manager
```

```
disk I/O error
```

plus the error in #2167

**Comment by leszko** [comment]
Thanks @hthillman . I'll document those in one of these two pages: [Video Miners Troubleshoot](https://docs.livepeer.org/video-miners/how-to-guides/troubleshooting) or [Video Developers Troubleshoot](https://docs.livepeer.org/video-developers/how-to-guides/troubleshooting).

If you have some other common errors, please add them here as well.

**Comment by leszko** [comment]
Added documentation here: https://github.com/livepeer/docs/pull/193

One error that I didn't document is `Could not transcode err="ZeroSegments"` because we actually don't know yet the reason for it (here is the investigation GH: https://github.com/livepeer/go-livepeer/issues/2322
