### ISSUE TITLE
Add documentation for all Prometheus metrics emitted by livepeer

### ISSUE THREAD

**Issue by Strykar** [livepeer/go-livepeer#2139]
**Is your feature request related to a problem? Please describe.**
All metrics emitted by livepeer are not documented.

**Describe the solution you'd like**
Document, in brief, every metric emitted by the livepeer binary.

**Additional context**
https://github.com/livepeer/docker-livepeer/tree/master/monitoring and https://forum.livepeer.org/t/guide-transcoder-monitoring-with-prometheus-grafana/1225 are a good start.

**Comment by leszko** [comment]
I see that all metrics that are emitted from Livepeer are defined in [census.go](https://github.com/livepeer/go-livepeer/blob/master/monitor/census.go#L241), so it's relatively simple to find the metric name and the description.

@hthillman 
1. Do you think we should "copy" this into Livepeer Docs? It may be slightly clearer to read, but the drawback is that we'll need to keep it up-to-data, so there is some maintenance effort.
2. If yes, then, where is the right place in the docs? Maybe a separate page called "Monitor Metrics" under [Video Miners: Reference](https://docs.livepeer.org/video-miners/reference)?

**Comment by hthillman** [comment]
> If yes, then, where is the right place in the docs? Maybe a separate page called "Monitor Metrics" under [Video Miners: Reference](https://docs.livepeer.org/video-miners/reference)?

I think that's exactly the right place
