### ISSUE TITLE
Allow Os to receive tickets when they are pending activation

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#2140]
Allow Os to receive tickets if they are pending activation as opposed the current requirement where they need to be active to receive tickets. The reason for this change is to allow Os that are scheduled to be active in the next round after they migrate to L2 to immediately be able to accept work on L2 in order to minimize the period where an O cannot receive work at all. Since the O is pending activation and since tickets are valid for at least 2 rounds (the current ticket validity period), the O will be able to redeem any winning tickets as soon as the next round.

- O calls isActive() [1] in ProcessPayment() [2] which is called whenever O receives a segment [3]
- isActive() queries the DB with a filter in order to see if the O's address is active [4]
- At the moment, `CurrentRound` is set to the last initialized round which means the query should only return addresses that are active as of the last initialized round
- The only address passed to `Addresses` is the O's own address because it just cares if its own address is active
- The actual DB filtering logic is implemented via a dynamically constructed query [5]

One way to implement this feature could be set the `CurrentRound` in the `DBOrchFilter` struct created in `isActive()` to `orch.rm.LastInitializedRound + 1` which would mean an address that is active in the next round would be included in the result. 

If we do this we may want to consider changing the name of the function from `isActive()` to something `isPaymentEligible()` to indicate that an O can be eligible to receive payments even before it is active on-chain - in this case, it is eligible to receive payments since it is pending activation in the next round.

[1] https://github.com/livepeer/go-livepeer/blob/832166f4dbfe7c631a0f6d6ad3dc4916a148d58a/core/orchestrator.go#L127
[2] https://github.com/livepeer/go-livepeer/blob/832166f4dbfe7c631a0f6d6ad3dc4916a148d58a/core/orchestrator.go#L111
[3] https://github.com/livepeer/go-livepeer/blob/832166f4dbfe7c631a0f6d6ad3dc4916a148d58a/server/segment_rpc.go#L101
[4] https://github.com/livepeer/go-livepeer/blob/832166f4dbfe7c631a0f6d6ad3dc4916a148d58a/core/orchestrator.go#L353
[5] https://github.com/livepeer/go-livepeer/blob/832166f4dbfe7c631a0f6d6ad3dc4916a148d58a/common/db.go#L524

**Comment by leszko** [comment]
I've sent a PR https://github.com/livepeer/go-livepeer/pull/2146

One comment is that this change applies only to Orchestrator, but we actually use the same query for the discovery in the broadcaster. Should we update it as well or it'll be done together with the L2-related changes? CC: @yondonfu

**Comment by yondonfu** [comment]
@leszko 

Ah good point.

I think we should adjust the `DBOrchFilter` instances used in https://github.com/livepeer/go-livepeer/blob/master/discovery/db_discovery.go for DB based discovery to also use the next round instead of the current round so Os pending activation can be returned there as well. Feel free to address this in a follow up PR.

EDIT: Tracking in https://github.com/livepeer/go-livepeer/issues/2148
