### ISSUE TITLE
Add a checksums.txt file or equivalent with binary releases

### ISSUE THREAD

**Issue by Strykar** [livepeer/go-livepeer#2147]
**Is your feature request related to a problem? Please describe.**
Currently, the checksum needs to be copy pasted by hand to verify it in a terminal.
Adding a checksum file enables packagers to script the download and verification and integrate it with common distro packaging tools.

**Describe the solution you'd like**
Create a checksums.txt file with every release that places the SHA256 checksums in it.

**Describe alternatives you've considered**
Short of parsing all the HTTP on the page (which breaks every distro's packaging guideline) there are no alternatives.

**Additional context**
Even better, would be for for Livepeer to publish a public PGP key and use that to sign and ship a `.asc` file for each `tar.gz`.

**Comment by yondonfu** [comment]
I like this suggestion. Looks like the [lnd (a client implementation of Bitcoin's Lightning Network protocol)](https://github.com/lightningnetwork/lnd/blob/master/docs/release.md) project does something similar for releases so perhaps we can use that as a reference.

**Comment by hjpotter92** [comment]
> Currently, the checksum needs to be copy pasted by hand to verify it in a terminal. Adding a checksum file enables packagers to script the download and verification and integrate it with common distro packaging tools.

I've started work on this feature.

> Even better, would be for for Livepeer to publish a public PGP key and use that to sign and ship a `.asc` file for each `tar.gz`.

We have published a gpg key (fingerprint: `A2F9039A8603C44C21414432A2224D4537874DB2`). You can fetch the same [from here](https://keys.openpgp.org/vks/v1/by-fingerprint/A2F9039A8603C44C21414432A2224D4537874DB2).

The signed releases would be detached, instead of being encrypted; but the same keys as shared here would be used for publishing.
