### ISSUE TITLE
Allow Bs to discovery Os that are pending activation when using DB discovery

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#2148]
See https://github.com/livepeer/go-livepeer/issues/2140#issuecomment-999225632

**Comment by leszko** [comment]
Sent a PR. There is [one more place](https://github.com/livepeer/go-livepeer/blob/b4605f705bcad5e355bb0c738d784e4503089900/eth/watchers/orchestratorwatcher.go#L172) where this DB Filter is used. It's used to cache the stake of the orchestrators. I believe we don't need to make any changes here. But @yondonfu PTAL.
