### ISSUE TITLE
Orchestrator not recording fields in ticketQueue

### ISSUE THREAD

**Issue by interptr** [livepeer/go-livepeer#2160]
**Describe the bug**
redeemedAt and txHash fields are blank in the ticketQueue table in lpdb.sqlite3 after redeeming a winning ticket.

**To Reproduce**
• Redeem winning ticket
• Check ticketQueue table
• Note missing fields redeemedAt and txHash

**Expected behavior**
All fields should be populated after redemption

**Actual behavior**
```
sqlite3 ~/.lpData/mainnet/lpdb.sqlite3 "select hex(faceValue),sender,redeemedAt, creationRound, txHash, paramsExpirationBlock from ticketQueue"

027F7D0BDB920000|0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E||2413||13900402
```
( ticket was redeemed in round 2413 )

**Desktop (please complete the following information):**
Ubuntu 18.04.5
Livepeer Node Version: 0.5.23-88507988
sqlite3 version: 3.22.0

**Additional context**
All other redeemed tickets before 0.5.23 are properly updated with redeemedAt and txHash

**Comment by hthillman** [comment]
Closing - this was fixed in 0.5.24. Please open a new issue if you see this happening again!
