### ISSUE TITLE
Include chainID in response from /status endpoint

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#2165]
**Is your feature request related to a problem? Please describe.**

At the moment, there is not an easy way for an operator to determine what chain the node is connected to. Today, the node can be connected to a local chain, Rinkeby or mainnet depending on the value passed to the `-network flag`. https://github.com/livepeer/go-livepeer/issues/2149 will introduce the `-network arbitrum-one-rinkeby` option and later on there will be a `-network arbitrum-one-mainnet` option as well. 

Note: At the moment, the term "network" and "chain" are used interchangeably because each network (i.e. the values supported by the `-network` flag) corresponds to exactly one chain. 

**Describe the solution you'd like**

An operator should be able to easily determine what chain their node is connected to.

There is already a [/status](https://github.com/livepeer/go-livepeer/blob/3649803de21ef36e1fe814c51ca6b94bef4daed6/server/webserver.go#L818) endpoint for the CLI webserve that can be queried to fetch information about the node. I propose adding the chainID (i.e. the ID of the chain that the node is connected to) in the response. We can use the chainID because each chain should already have its own unique chainID (i.e. Mainnet = 1, Rinkeby = 4, Arbitrum One Rinkeby = 421611, Arbitrum One Mainnet = 42161).

The operator will then be able to run:

```
curl localhost:7935/status
```

and check if the chainID included in the response corresponds to the chain that they expect their node to be connected to. The response would look something like:

```
{ ... ChainID: 777 ... }
```

A script could easily filter the response specifically for the chainID as well i.e. `curl localhost:7935/status | jq .ChainID`.

In order to implement this we'll need to:

- Update `common.NodeStatus` to include a chainID field
- Update [GetNodeStatus()](https://github.com/livepeer/go-livepeer/blob/3649803de21ef36e1fe814c51ca6b94bef4daed6/server/mediaserver.go#L1544) to set the chainID field in the returned `common.NodeStatus`. We should be able to fetch the chainID via `node.Database.ChainID()` [1]

[1] The chainID of a node is [stored in the node's DB](https://github.com/livepeer/go-livepeer/blob/3649803de21ef36e1fe814c51ca6b94bef4daed6/cmd/livepeer/livepeer.go#L1167) the first time the node connects to the chain.

**Describe alternatives you've considered**

We could include the chainID in the OrchestratorInfo message, but this would be more difficult for an operator to query because an orchestrator will only process a GetOrchestrator request and return a OrchestratorInfo message if the request includes a valid signature from a broadcaster ETH address that has a sufficient deposit/reserve on-chain.

**Additional context**

N/A

**Comment by leszko** [comment]
I see there is already an endpoint [/EthChainID](https://github.com/livepeer/go-livepeer/blob/c2c73fa6f24473311766baee83e2762c87ef708d/server/webserver.go#L1107) which returns exactly the information about the ChainID. Isn't it enough, do we want this information in the `/status` as well?

CC: @yondonfu

**Comment by yondonfu** [comment]
Oh doh you're right I totally missed that! Seems like the `/EthChainID` endpoint will be sufficient for the use case described in the OP. In that case, I don't think this proposed implementation in the OP is necessary.
