### ISSUE TITLE
Broadcaster misconfiguration.

### ISSUE THREAD

**Issue by JJassonn69** [livepeer/go-livepeer#2167]
The following error can be seen often in the orchestrator logs.

I1228 13:42:51.105610    7188 lb.go:131] LB: Created transcode session for 574c7729_0
I1228 13:42:51.105928    7188 lb.go:207] LB: Transcode submitted for 574c7729_0
ERROR: decoder.c:238] Non 4:2:0 pixel format detected in input : Error number -1481657929 occurred
ERROR: decoder.c:285] Unable to open video decoder : Error number -1481657929 occurred
E1228 13:42:51.117218    7188 ffmpeg.go:503] Transcoder Return : Unsupported input pixel format
I1228 13:42:51.117218    7188 lb.go:192] LB: Stopping transcoder due to error for 574c7729_0
I1228 13:42:51.117218    7188 lb.go:123] LB: Deleted transcode session for 574c7729_0

Operating system: Windows

**Comment by Strykar** [comment]
You should chime in with these logs in https://github.com/livepeer/go-livepeer/issues/2138
We need a description of logs from all stakeholders who interact with the B/O/T.

**Comment by hthillman** [comment]
This occurs when someone submits a stream with an unsupported pixel format - this isn't an error with the core software, it just happens when a broadcaster sends in a stream with a bad pixel format
