### ISSUE TITLE
Improve TimeWatcher PubSub mechanism

### ISSUE THREAD

**Issue by leszko** [livepeer/go-livepeer#2168]
**Is your feature request related to a problem? Please describe.**
Currently, blocking any of the [watchers](https://github.com/livepeer/go-livepeer/tree/master/eth/watchers) may result in completely blocking the whole orchestrator. E.g. not processing a transaction may result in the orchestrator's inability to transcode streams.

Here is the scenario:
1. Any of watchers blocks
    - e.g. [roundinitializer in client.CheckTx()](https://github.com/livepeer/go-livepeer/blob/c2c73fa6f24473311766baee83e2762c87ef708d/eth/roundinitializer.go#L124)
2. It causes the channel used for the feed subscriptions to fill up
    - e.g. [blockSink in roundinitializer](https://github.com/livepeer/go-livepeer/blob/c2c73fa6f24473311766baee83e2762c87ef708d/eth/roundinitializer.go#L49)
3. In result, any send to the given feed is blocked
    - e.g. [blockwatcher sending the current block update](https://github.com/livepeer/go-livepeer/blob/c2c73fa6f24473311766baee83e2762c87ef708d/eth/blockwatch/block_watcher.go#L205)
4. The whole feed mechanism stops working
    - e.g. block number is not updated every `blockPollingTime` which implies the wrong block number in `TicketParams` which implies not accepting segments to transcode

**Describe the solution you'd like**

We need to address it because it makes the whole feed mechanism very unreliable. One solution to this would be to make sure that watchers never block in their code. Another solution would be to change the feed pubsub mechanism to not block if the target channel is full.

**Describe alternatives you've considered**
N/A

**Additional context**
This issue was first discovered during analyzing the bug https://github.com/livepeer/go-livepeer/issues/2152

**Comment by leszko** [comment]
Created the related Feature spec explaining the issue in detail and describing the solutions.

https://github.com/livepeer/go-livepeer/issues/2207

**Comment by hthillman** [comment]
closing in favor of #2207
