### ISSUE TITLE
Add `-j` flag to the built binary

### ISSUE THREAD

**Issue by hjpotter92** [livepeer/go-livepeer#2181]
This is to facilitate with the final binary being run with mistcontroller runtime.

**Comment by hthillman** [comment]
@hjpotter92 can you add additional labels & info as appropriate?

**Comment by iameli** [comment]
@hthillman I added a couple, but this is a necessary step toward a version of Mist that has go-livepeer embedded and can transcode directly on mainnet.

Essentially, Mist's main binary — MistController — can query external binaries for their command line options with the flag `-j`. This is expected to return a JSON representation of the available CLI options. The external binary (in this case go-livepeer) then can be configured through the Mist interface.
