### ISSUE TITLE
Evaluate behavior for unset CLI flags

### ISSUE THREAD

**Issue by hthillman** [livepeer/go-livepeer#2194]
**Is your feature request related to a problem? Please describe.**
For several flags (`reward` being the most prominent), we have 3 states: true/truthy, false/falsy, and unset.  This "unset" state is not intuitive for node operators. These flags have defaults, but in certain cases they are ignored for the unset state. This means that the "default" is unreliable.

https://github.com/livepeer/go-livepeer/blob/23a4f3d893b0cc51e5aaf662b096266997d5f65a/cmd/livepeer/livepeer.go#L701

**Describe the solution you'd like**
- short-term: document specific behaviors in https://docs.livepeer.org/video-miners/reference/configuration
- medium-term: evaluate *why* we use this pattern and whether it should be changed

**Comment by RyanC92** [comment]
Moving this from the discord.

My input- 

I think seeing as reward calls make a transaction which if it accidently goes off is more detrimental than missing a day of reward calls. I think by default livepeer, if not told anything should NOT do a reward call unless flagged as -reward=true or reward true 
even with L2 reward calls being cheaper, the fact that it does it without confirmation has a far greater consequence than missing a reward call

**Comment by hthillman** [comment]
We've updated the docs to say that you need to explicitly set reward to false, otherwise it will default to true. Closing for now, we can reevaluate if this continues to cause problems
