### ISSUE TITLE
Transcoding time miscalculation for simultaneous transcodings

### ISSUE THREAD

**Issue by Czar102** [livepeer/go-livepeer#2209]
In `livepeer_bench` transcoding time is not calculated properly when setting `-concurrentSessions` to a high value.
I run the script for approx. 60s, while the displayed time was 600s:

```
*------------------------------*---------------------*
| Concurrent Sessions          | 20                  |
| Total Segs Transcoded        | 600                 |
| Real-Time Segs Transcoded    | 600                 |
| * Real-Time Segs Ratio *     | 1                   |
| Total Source Duration        | 1199.9999999999977s |
| Total Transcoding Duration   | 603.2499090460003s  |
| * Real-Time Duration Ratio * | 0.5027              |
*------------------------------*---------------------*
```

**To Reproduce**
Steps to reproduce the behavior, start benchmark with a test file provided in the docs, with following parameters:
```
$ livepeer_bench -in bbb/source.m3u8 -nvidia all -concurrentSessions 20 -concurrentSessionDelay 50ms
```

Probably any number of `-concurrentSessions` that is greater than machine's capability will reproduce the bug.

**Desktop:**
 - OS: Linux Arch
 - GPU: Nvidia GeForce 1060

**Comment by hthillman** [comment]
The `603s` that's reported refers to the time spent transcoding, and it's measured in parallel.  so `20 streams * 0.5027 * 60 = 603`

if you have any ideas for better ways to display this info, let us know! closing for now but feel free to comment

**Comment by Czar102** [comment]
As far as I understand, `Total Transcoding Duration` should report the total time the graphics card has spent transcoding, not the sum of the transcoding times.
When 10 processes wait for hardware to be freed, the time should not be counted 10 times. On maximum capacity, graphics card is working 1s every second, the number of active threads doesn't matter.

**Comment by hthillman** [comment]
> the total time the graphics card has spent transcoding, not the sum of the transcoding times.

the total time it has spent transcoding *IS* the sum of transcoding times. if it transcodes 2 streams in parallel for an hour, that's 2 hours of transcoding time. If you call that 1hr of transcoding time, you lose the nuance about the amount of work that's actually being done
