### ISSUE TITLE
Y/N Confirmation when sending a transaction via the CLI

### ISSUE THREAD

**Issue by hthillman** [livepeer/go-livepeer#2212]
Split out from #2106 

Whenever the Livepeer CLI will submit a transaction, we should require confirmation from the user. If an action will submit multiple transactions, the user should be warned in advance

**Comment by noisersup** [comment]
Can I work on it?

**Comment by hthillman** [comment]
yes, thanks for getting involved! we'll get you some feedback on that PR as soon as possible

**Comment by hthillman** [comment]
looks like this has been merged, thanks @noisersup! closing 👍

**Comment by chrishobcroft** [comment]
Hey, just checking in on this - I just used `livepeer_cli` `0.5.27` to operate Livepeer on Arbitrum One Rinkeby. Several transactions were sent without any Y/N Confirmation.

**Comment by leszko** [comment]
I see the PR #2215 was only about sending the transfer and for every transaction. So we may consider reopening this GH Issue. @hthillman wdyt?
