### ISSUE TITLE
Return http response codes in livepeer_cli responses

### ISSUE THREAD

**Issue by noisersup** [livepeer/go-livepeer#2217]
**Is your feature request related to a problem? Please describe.**
I was using `livepeer_cli` and i got error:
```ERROR: logging before flag.Parse: E0128 02:49:31.223383      72 wizard_stats.go:98] Error getting current round: http response status not ok```

I have tried to understand what's the problem for a moment and checked the code to check why would it occure:
```
	if resp.StatusCode != http.StatusOK {
		return nil, errors.New("http response status not ok")
	}
```
As you can see from a very wide information about the error, we only return one: was connection successful or not.

**Describe the solution you'd like**
In my opinion it would be nice for users and also livepeer contributors to just return status codes in response.
e.g: `Error getting current round: http response status 418`

**Comment by hthillman** [comment]
@leszko any thoughts here? from my perspective this change makes sense and is a nice step towards standardization

**Comment by leszko** [comment]
Yes, it makes sense. In the long run, it would be even better to check the status errors and give a more human-readable message to the end-users. But I agree, that displaying an error code is better than not displaying anything.

@noisersup I've seen you sent a PR. I'll take care of it.
