### ISSUE TITLE
HTTP server level blocklist

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#222]
Since handling content moderation is an application level decision in the Livepeer ecosystem, the Livepeer node should support an easy interface for an application to moderate a stream/broadcaster. I propose the following:

Nodes can be started with a `--blocklist <filepath>` flag, or can use a default path if not passed in. The blocklist can be a csv file containing entries for both broadcasters and streamIDs to be blocked on that node of the following format:

```
B,<broadcaster_addr>
S,<stream_id>
```

The http interface to the node should expose a POST endpoint: `/moderate?streamID=<strmID>` or `?broadcasterAddr=<broadcasterAddr>` which uses the underlying blocklist interface to write to the blocklist. 

At the application level, moderation workflow could make post requests to this endpoint, or flag buttons could hook up to it, etc. 

Within the Livepeer Node, at the minimum requests for this stream or streams originating with the given broadcaster would not be served through the HTTP endpoint. But it could also go deeper and prevent peer connections or relay requests for these streams so the content never touches this particular server. 

Very open to feedback and ideas around this issue. While the issue of moderation and node's ability to choose what type of content they propagate is a complex and intricate one, this seems like a good first step that allows base level ability to take quick action.

*Note, in the future I hope that decentralized moderation services emerge that applications can tap into directly natively, without requiring every application to build its own moderation flow.*

**Comment by thomshutt** [comment]
Going to close this for now, we can revisit as part of design work around moderation as/when that's prioritised in the future
