### ISSUE TITLE
B reporting lots of `err="TicketParams expired"`, which interrupts transcoding activities

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#2236]
## Bug Description

When running a B, the following Error message is regularly reported in the console:

`segment_rpc.go:438] orchSessionID=e3825a5b Could not create payment bytes=294032 err="TicketParams expired"`

This has the effect of halting any transcoding work being done by the O, as the B is unable to create PM tickets.

After some time, the B starts creating and sending the PM tickets again, before the TicketParams appear to expire again... in a loop, ad infinitum :)

## Observed Behaviour

Pre-reqs: ffmpeg, livepeer `0.5.27`

Steps to reproduce:

1. In Terminal, run
```
./livepeer -orchestrator -transcoder \
        -network arbitrum-one-rinkeby \
        -ethUrl https://rinkeby.arbitrum.io/rpc \
        -pricePerUnit 100000 \
        -serviceAddr 127.0.0.1:8935 \
        -ethPassword password \
        -v 99
```
2. Go through the process of bonding and registering an O, and wait for the new round to commence
3. In another Terminal, run:
```
./livepeer -broadcaster \
        -network arbitrum-one-rinkeby \
        -ethUrl https://rinkeby.arbitrum.io/rpc \
        -httpAddr :8936 \
        -cliAddr :7936 \
        -rtmpAddr :1936 \
        -orchAddr 127.0.0.1:8935 \
        -ethPassword password \
        -transcodingOptions P720p30fps16x9 \
        -pixelsPerUnit 1 \
        -maxTicketEV 1000000000000000 \
        -v 99
```
4. Go through the process of depositing a deposit and reserve.
5. In another Terminal, run:
```
ffmpeg -re -f lavfi \
           -i testsrc=size=1920x1080:rate=30,format=yuv420p \
           -f lavfi \
           -i sine \
           -c:v libx264 \
           -b:v 1000k \
           -x264-params keyint=60 \
           -c:a aac \
           -f flv rtmp://127.0.0.1:1936/test_source
```
6. Observe the B start to receive / serve content, and the O/T starting to transcode content, as well as receiving tickets.
7. After some time, observe the B stop creating and sending PM tickets, and report "TicketParams expired". This halts transcoding work by the O/T
8. After some time, observe the B start creating and sending PM tickets again. This starts the transcoding work by the O/T
9. go to 7... keep looping.

## Expected Behaviour

I expect that a B will continue to send PM tickets, and that Transcoding continues throughout the stream.

## Screenshots

A screenshot of an instance where the B ceases the creation and sending of PM tickets:

![Screenshot from 2022-02-04 17-12-06](https://user-images.githubusercontent.com/2212651/152568468-65be0468-6aec-49fe-9681-965fb5f5977e.png)

A screenshot of an instance where the B recommences the creation and sending of PM tickets:

![Screenshot from 2022-02-04 17-12-21](https://user-images.githubusercontent.com/2212651/152568352-d2085381-0f91-4220-aea5-a5ce824c6ab0.png)

A screenshot of the moments where a B a) ceases sending PM tickets, and b) recommences sending PM tickets:

![image](https://user-images.githubusercontent.com/2212651/152567574-270e1fe4-45c3-43be-8508-97601897b92e.png)

Here's even a video showing the cycle in action: https://vimeo.com/manage/videos/673677376

## Environment

- Livepeer Version 0.5.27

![image](https://user-images.githubusercontent.com/2212651/152572269-fa03362c-78bc-42c0-bed4-7f7f8782e53f.png)

## Additional Notes

Completely anecdotally, this "feels" like it has something to do with the following error which is occasionally thrown by both B and O:
```
E0204 17:42:48.024105  150388 block_watcher.go:124] blockwatch.Watcher error encountered - trying again on next polling interval err="UNIQUE constraint failed: blockheaders.hash"
```

**Comment by chrishobcroft** [comment]
cc. #1575

**Comment by leszko** [comment]
May be related to https://github.com/livepeer/go-livepeer/issues/2220

**Comment by hthillman** [comment]
@leszko when you do testing on Wednesday can you confirm that this issue is addressed?

**Comment by leszko** [comment]
Yes, sure. I assigned this GH Issue to me.

**Comment by leszko** [comment]
I checked exactly the steps you described with the code from `master` and after transcoding 120 segments I didn't encounter the `TicketParams expired` issue in Arbitrum Testnet. Therefore closing this GH Issue. Feel free to reopen if you encounter the issue again.

One more comment, @chrishobcroft I think you should different `-datadir` for orchestrator and broadcaster. Otherwise they may collide. This can actually be the reason for the error `blockwatch.Watcher error encountered - trying again on next polling interval err="UNIQUE constraint failed: blockheaders.hash"`. For example, I see the following parameter in broadcaster.
```
-datadir ~/temp/livepeer/TEST_B_ARBITRUM/
```

**Comment by chrishobcroft** [comment]
@leszko

> One more comment, @chrishobcroft I think you should different -datadir for orchestrator and broadcaster. Otherwise they may collide. This can actually be the reason for the error blockwatch.Watcher error encountered - trying again on next polling interval err="UNIQUE constraint failed: blockheaders.hash". For example, I see the following parameter in broadcaster.

Yeah, this does resolve it, but I'm not sure why this is the case? What does it mean for them to "collide" in this case?

**Comment by leszko** [comment]
> Yeah, this does resolve it, but I'm not sure why this is the case? What does it mean for them to "collide" in this case?

When you start `livepeer` it uses `datadir` to store some data in the internal SQLlite DB. For example, if you start `livepeer` as follows:

```
./livepeer \
  -network rinkeby \
  -ethUrl <RINKEBY_ETH_URL> \
  -broadcaster
```

It uses the following database `~/.lpData/rinkeby/lpdb.sqlite3`. Now if you start multiple livepeer instances with the same `datadir`, they use the same SQLite db and livepeer is not prepared for it. So, in your case, they concurrently fetch and try to store the same blocks.

**Comment by chrishobcroft** [comment]
Thanks @leszko - I understand this.

My question is around what is the data in the database which may cause an unwanted collision?

The blockheaders ought to be the same, and the locally-cached chainstate data ought to also be the same.

What would be the path where two nodes accessing the same database may write conflicting / duplicate data?

**Comment by leszko** [comment]
I think it can be related to the table `blockheaders`, but you'd better double-check it.
