### ISSUE TITLE
Return error on startup if connected to arbitrum-one-mainnet when L1 block < LIP-73 block

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#2247]
**Is your feature request related to a problem? Please describe.**

The contracts on Arbitrum mainnet will start off paused until they are unpaused after the LIP-73 block 14207040 [1]. At the moment, this would mean that the node will connect to the contracts and if any transactions are submitted they will fail. 

[1] https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-73.md

**Describe the solution you'd like**

We can fail fast on startup when connecting to arbitrum-one-mainnet to make it clear that the LIP-73 block has not been reached yet i.e. `LIP-73 has not been activated yet`. Could probably update network config [here](https://github.com/livepeer/go-livepeer/blob/4798627c52b3a183043a95d42cff1827f0ace033/cmd/livepeer/livepeer.go#L208) with the LIP-73 block and then check it against L1 block when starting up?

**Describe alternatives you've considered**

**Additional context**

**Comment by leszko** [comment]
Sent a PR: https://github.com/livepeer/go-livepeer/pull/2251

> We can fail fast on startup when connecting to arbitrum-one-mainnet to make it clear that the LIP-73 block has not been reached yet i.e. `LIP-73 has not been activated yet`. Could probably update network config [here](https://github.com/livepeer/go-livepeer/blob/4798627c52b3a183043a95d42cff1827f0ace033/cmd/livepeer/livepeer.go#L208) with the LIP-73 block and then check it against L1 block when starting up?

I think we don't need to update the network config since this check is actually temporary. I think we should remove it after LIP-73. PTAL.

**Comment by yondonfu** [comment]
> I think we don't need to update the network config since this check is actually temporary. I think we should remove it after LIP-73. PTAL.

👍
