### ISSUE TITLE
Use different hardcoded redeemGas when connected to an Arbitrum network

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#2248]
**Is your feature request related to a problem? Please describe.**

At the moment, we hardcode a [redeemGas](https://github.com/livepeer/go-livepeer/blob/5d9bcaa325d8caa18151b42f50f4f78bf76834d7/cmd/livepeer/livepeer.go#L60) variable to 350000 which is meant to represent a rough estimate of the amount of gas we can expect a ticket redemption to consume. This value is used in the following ways:

- Used in [pm.SenderMonitor](https://github.com/livepeer/go-livepeer/blob/5d9bcaa325d8caa18151b42f50f4f78bf76834d7/cmd/livepeer/livepeer.go#L570) to [estimate the tx cost of redeeming a ticket](https://github.com/livepeer/go-livepeer/blob/5d9bcaa325d8caa18151b42f50f4f78bf76834d7/pm/sendermonitor.go#L386)
- Used in [pm.Recipient](https://github.com/livepeer/go-livepeer/blob/5d9bcaa325d8caa18151b42f50f4f78bf76834d7/cmd/livepeer/livepeer.go#L634) to [estimate the tx cost of redeeming a ticket](https://github.com/livepeer/go-livepeer/blob/5d9bcaa325d8caa18151b42f50f4f78bf76834d7/pm/recipient.go#L235)

The 350000 value is based on gas usage of ticket redemption on L1 Ethereum. However, gas is measured different on Arbitrum networks - see https://developer.offchainlabs.com/docs/arbgas. At the moment, it appears that the gas consumed by ticket redemption on Arbitrum Rinkeby is [around 1100000](https://testnet.arbiscan.io/tx/0xac6617c91654b16dd497090191236685d0a53936a43b347e7833f59b04e94736).

Without any changes, nodes would underestimate the tx cost of ticket redemption on Arbitrum networks which also leads to lower ticket face values for Os since O tries to set a ticket face value that is 100x the estimated tx cost.

**Describe the solution you'd like**

We can use a different hardcoded value for `redeemGas` if we are connecting to arbitrum-one-rinkeby or arbitrum-one-mainnet. 1200000 seems like a reasonable value for now - 1200000 is closer to the gas limit that has been set on these txs which is the value computed during gas estimation and an overestimate of the gas usage feels safer initially to avoid scenarios where the tx cost of redemption is underestimated [1].

[1] Moving away from hardcoded values would be nice in the future.

**Describe alternatives you've considered**

**Additional context**

**Comment by leszko** [comment]
> [1] Moving away from hardcoded values would be nice in the future.

Yeah, agree that we should move away from the hardcoded values, but since Arbtrium migration is just around the corner. Let's hardcode it for now.
