### ISSUE TITLE
"Getting Started" script on readthedocs not working on Ubuntu

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#225]
I am having problems with the "Getting Started" section on readthedocs.io:

https://livepeer.readthedocs.io/en/latest/getting_started.html

ffmpeg is installed on my machine.

These are the steps to recreate:

1. Download and unpack binaries
2. Run the command: ./livepeer -bootnode -offchain
3. In another window, run ./livepeer_cli
4. I select "3. Broadcast video", and this returns the message: "The broadcast command only support darwin for now.  Please download OBS to broadcast."
5. I download and install OBS, and configure it to broadcast to URL: http://localhost:1935/streams with empty stream key
6. I start streaming, and the livepeer process gives me a "New HLS Video" ID (need to update the readthedocs.io to represent this new terminology)
7. Under "Play the stream", I click https://media.livepeer.org/player.html (which maybe should open a new tab from readthedocs.io instead of open in existing window) - using Brave Browser.
8. I enter the "New HLS Video" id to the "Stream ID Here..." field and click "Start".
9. I wait some time, until the following screen is shown, indicating that this isn't working :(

![image](https://user-images.githubusercontent.com/2212651/33901164-eaa905c8-df3e-11e7-88a3-410e2ac2c147.png)

I also tested steps 7-9 using smartphone browser, and also Chromium browser on Ubuntu - with the same results.

**Comment by rayj00** [comment]
I find this same issue for the last few weeks, on Windows!   I have not been able to broadcast for quite a while now.  Have you tried the new player at https://media.livepeer.org/

**Comment by ericxtang** [comment]
https://livepeer.readthedocs.io/en/latest/getting_started.html has been updated.  Closing this issue because it's out of date.
