### ISSUE TITLE
Livepeer_CLI With Redeemer flag shows broadcaster options when it should be orchestrator flags

### ISSUE THREAD

**Issue by RyanC92** [livepeer/go-livepeer#2257]
**Describe the bug**
If you launch livepeer with the ```redeemer``` flag, the options from the livepeer_cli go from the orchestrator flags (shown below)

```
8. Invoke "withdraw stake" (LPT)
9. Invoke "withdraw fees" (ETH)
10. Invoke "transfer" (LPT)
11. Invoke "reward"
12. Invoke multi-step "become an orchestrator"
13. Set orchestrator config
14. Set maximum Ethereum gas price
15. Set minimum Ethereum gas price

```

to when you have the flag turned on it is more around broadcaster settings:

```
11. Invoke "deposit broadcasting funds" (ETH)
12. Invoke "unlock broadcasting funds"
13. Invoke "cancel unlock of broadcasting funds"
14. Invoke "withdraw broadcasting funds"
15. Set broadcast config
```

**To Reproduce**
1. modify your config file to include ```redeemer``` or launch with ```-redeemer``` and run livepeer
2. run livepeer_cli and you can see the settings change

**Expected behavior**
Seeing as the redeemer would be redeeming rewards, redeeming tickets etc. You would expect the livepeer_cli to have options angled at an orchestrator.

**Screenshots**
below you can see the full differences with the two (top options are with redeemer flag, bottom is without)
![image](https://user-images.githubusercontent.com/15055337/153769233-0f9af9b6-a4c7-4122-98bc-eed54948358e.png)

**Desktop (please complete the following information):**
 - OS: Linux (ubuntu 20)
 - Version: 0.5.28-31e63092

**Additional context**
The redeemer flag can become crucial to the scaling strategy for orchestrators without opening them up to extended risk to their wallets/keys. Having the settings properly denoted will allow orchestrators to execute commands when needed from a single trusted source.

**Comment by thomshutt** [comment]
Closing as fixed by https://github.com/livepeer/go-livepeer/pull/2456
