### ISSUE TITLE
Enable Failover ETHURL Address options

### ISSUE THREAD

**Issue by RyanC92** [livepeer/go-livepeer#2258]
**Is your feature request related to a problem? Please describe.**
A few weeks ago when Infura went offline for a few hours many orchestrators instantly dropped sessions, while me on Alchemy this was good, for them it was not. If we could have a flag for ethUrlFailover or something similar, where people could put a geth lite node or alchemy it would allow them to fail over in the event of an outage and continue to operate until normal operation is restored.

**Describe the solution you'd like**
If we could have a flag for ethUrlFailover or something similar, where people could put a geth lite node or alchemy it would allow them to fail over in the event of an outage and continue to operate until normal operation is restored.

**Comment by chrishobcroft** [comment]
Duplicate of https://github.com/livepeer/go-livepeer/issues/1959

**Comment by hthillman** [comment]
closing as dupe, continue any conversation on #1959
