### ISSUE TITLE
Allow a B to elect more than one O (whitelist)

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#2262]
**Is your feature request related to a problem? Please describe.**

Currently, when selecting an Orchestrator to work with, a Broadcaster can choose to either

a) elect a single (1) Orchestrator (using the `-orchAddr` flag or `-ethOrchAddr` flag)
b) use the default selection algorithm to select from the entire active set of (100) Orchestrators

**Describe the solution you'd like**

As a B, I would like to be able to have greater control over how many Orchestrators I work with.

For example, to be able to elect to work with two (2) Orchestrators, perhaps by specifying a ranked comma-separated list of Orchestrator `serviceURI` with `-orchAddr`:

`-orchAddr 104.248.93.14:8935,93.115.28.14:8935`

or with `-ethOrchAddr`:

`-ethOrchAddr 0x525419ff5707190389bfb5c87c375d710f5fcb0e,0xDAC817294c0c87ca4fA1895eF4b972EAde99f2fd`

**Describe alternatives you've considered**

To seek to generally cultivate more variety in terms of selection procedures available by default to Broadcasters entering the Livepeer ecosystem.

**Additional context**

Related to https://github.com/livepeer/go-livepeer/issues/2263 https://github.com/livepeer/go-livepeer/issues/2264

**Comment by leszko** [comment]
I think that specifying multiple orch addrs is already supported. So you can use B exactly as you described:
```
-orchAddr 104.248.93.14:8935,93.115.28.14:8935
```

There is also a possibility of using a webhook that resolves the addresses, so you can set up a webservice that returns the orch addresses and these will be used by B.

**Comment by chrishobcroft** [comment]
OK, thank you, I was not aware of this. I just tried it and it works! If the active O becomes unavailable, it will gracefully fail over to another O on the list.

> There is also a possibility of using a webhook that resolves the addresses, so you can set up a webservice that returns the orch addresses and these will be used by B.

This is a nice touch, but it also makes me wonder whether a neater way to approach this would be via the `-ethOrchAddr` flag e.g. passing it an ETH address of a contract which resolves a list of other ETH addresses (kinda like a B's own service registry. It also could be used to store logic for how the B should balance load between the listed Orchestrators.

## Testing

There is a perceptible skip in the transcoded content though - i.e. the "in-flight" segment being transcoded is lost, and a player pulling content from the B ends up with a missing segment from the playlist, like so (with `262.ts` missing):
```
ubuntu@thinkpad:~/livepeer-linux-amd64$ curl http://127.0.0.1:8936/stream/test_source/P240p30fps16x9.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:253
#EXT-X-TARGETDURATION:2
#EXTINF:2.000,
/stream/test_source/P240p30fps16x9/259.ts
#EXTINF:2.000,
/stream/test_source/P240p30fps16x9/260.ts
#EXTINF:2.000,
/stream/test_source/P240p30fps16x9/261.ts
#EXTINF:2.000,
/stream/test_source/P240p30fps16x9/263.ts
#EXTINF:2.000,
/stream/test_source/P240p30fps16x9/264.ts
#EXTINF:2.000,
/stream/test_source/P240p30fps16x9/265.ts
```
This is probably acceptable though, I mean, it doesn't result in buffering or freezing, and actually brings the viewer "closer to the live action"...

**Comment by chrishobcroft** [comment]
Actually, before we close this, perhaps the `-help` can be updated - right now it states that the flag can be used to select a singleton transcoder - this could be much more explicit to raise awareness of the opportunity to connect to more than one O :) wdyt @leszko?

```
  -orchAddr string
    	Orchestrator to connect to as a standalone transcoder
```

**Comment by leszko** [comment]
> This is a nice touch, but it also makes me wonder whether a neater way to approach this would be via the -ethOrchAddr flag e.g. passing it an ETH address of a contract which resolves a list of other ETH addresses (kinda like a B's own service registry. It also could be used to store logic for how the B should balance load between the listed Orchestrators.

CC: @hthillman , to me it's more a product decision if we should add one or both of these:
- Filtering by Orch Eth Addr
- Resolving by B's own Eth Contract

> Actually, before we close this, perhaps the -help can be updated - right now it states that the flag can be used to select a singleton transcoder - this could be much more explicit to raise awareness of the opportunity to connect to more than one O :) wdyt @leszko?

Yes, agree. I'll fire a PR with this change.

**Comment by chrishobcroft** [comment]
The value in allowing this logic to be stored onchain is that:
a) a B can much more easily decentralise control over their own whitelist, e.g. by putting it under the control of a Multisig/dao
b) whatever onchain logic is created can be integrated with by Mist (eventually) as opposed to any more golang-specific implementation... so in a way it's more "future-proofed" and open.

**Comment by leszko** [comment]
> > Actually, before we close this, perhaps the -help can be updated - right now it states that the flag can be used to select a singleton transcoder - this could be much more explicit to raise awareness of the opportunity to connect to more than one O :) wdyt @leszko?
> 
> Yes, agree. I'll fire a PR with this change.

Here's a PR: https://github.com/livepeer/go-livepeer/pull/2269

**Comment by hthillman** [comment]
In general I think we should aim for the most modular option. 

Broadcasters should be able to specify arbitrary logic for choosing orchestrators. I'm a little concerned about relying on contracts because many broadcasters won't have the technical capacity to do this and tbh I'm not convinced it needs to be onchain. Could we do something like...abstract the selection logic into a library of selection plugins?

**Comment by chrishobcroft** [comment]
> tbh I'm not convinced it needs to be onchain.

It might not _need_ to be onchain, but for me, the fact that it _could be_ means it's always worth considering. 

It can open up unprecedented ways for Bs to cooperate with Os, where the rules of engagement are fully transparent. But maybe I'm getting ahead of myself.
