### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#227]
After running the Livepeer Node for a long time, the node crashed with an error "fatal error: runtime: out of memory".

See attached for log from console at "-v 6" verbosity.

[fatal error - runtime - out of memory.log](https://github.com/livepeer/go-livepeer/files/1555991/fatal.error.-.runtime.-.out.of.memory.log)

Livepeer Node Version: 0.1.6-unstable
Ubuntu 16.04 LTS

There was 39.2Gb of free space on the hard drive

**Comment by chrishobcroft** [comment]
Also, my .lpData/.tmp folder had filled up with 5.6Gb of video segments.

**Comment by chrishobcroft** [comment]
Another error log on this... 
[fatal error: runtime: out of memory.txt](https://github.com/livepeer/go-livepeer/files/1560008/fatal.error.runtime.out.of.memory.txt)

**Comment by rayj00** [comment]
I have also seen this happen on a VPS I am using.  I'm curious why ram is being used at all,  while the .lpData/tmp folder is holding the video segments?
