### ISSUE TITLE
DEAD content being served to the media player - marked as LIVE

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#228]
After a broadcast has ended, the player at https://media.livepeer.org/channels will show ~20s of footage from the most recent broadcast.

See screenshot below to clarify situation.

![image](https://user-images.githubusercontent.com/2212651/33947620-de7b9cca-dff2-11e7-9568-8f1b6ea70747.png)

This is not ideal, as it will confuse the viewers of the channel, allowing them to believe that the content they are seeing is LIVE.

Desired behaviour would be that if a channel is **not** LIVE, it should show "This broadcaster is currently offline" and with an "OFFLINE" symbol in the footer, like so:

![image](https://user-images.githubusercontent.com/2212651/33947250-eadf0700-dff1-11e7-8445-fc2165300348.png)

**Comment by ericxtang** [comment]
This is fixed

**Comment by chrishobcroft** [comment]
I don't agree that this is fixed.

When a stream fails, there is a residue left in the CDN which is served up as though it is live.

I experienced this about 30 minutes ago - 8 seconds of content being played.

**Comment by ericxtang** [comment]
Is this still an issue? I think it's a CDN issue, which may no longer be a problem.
