### ISSUE TITLE
Increase hardcoded discovery timeout on B

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#2286]
**Is your feature request related to a problem? Please describe.**

At the moment, there is a [hardcoded timeout](https://github.com/livepeer/go-livepeer/blob/d85cb21937a0c302f0929889151ad7b3351994d2/discovery/discovery.go#L22) used during discovery. There could be scenarios where using a different timeout could make sense - see https://github.com/livepeer/go-livepeer/issues/2270#issuecomment-1048399522.

**Describe the solution you'd like**

Add a CLI flag `-discoveryTimeout Nms` that can be used to set the timeout for discovery to N ms and use the current value as the default.

**Describe alternatives you've considered**

**Additional context**

**Comment by leszko** [comment]
I think it may make sense to add it. Then, we can run teststream with a higher timeout value, not to lose any Os.

One more thing to consider is that maybe `500ms` is too strict and we should just change the hardcoded value to something like `1s`. From what I understand, this timeout does not affect the stream processing, because we try to select orchestrators "in advance" (when the pool is too small).

**Comment by yondonfu** [comment]
After some discussion, agree with @leszko that the 500ms timeout is probably too low right now and the first step here can be to bump it to 1s instead of jumping to make this configurable. We can try out test streams using the 1s timeout for now. In the future, we could consider dynamically adjusting the timeout as an alternative to configuring it (i.e. increase timeout only if < N Os respond within the initial timeout).

**Comment by stronk-dev** [comment]
Looks like the changed timeout has had an effect! Latest SIN test stream resulted in:

https://interptr-latest-test-streams.vercel.app/?address=0x847791cBF03be716A7fe9Dc8c9Affe17Bd49Ae5e
SIN | 3/2/2022 15:20:48 | No | 0.00 | 0.00 | 0.00 | 0.00 | 0.00 | 36/60 !

So still no stats, but at least it recognized some segments now.
Note that the errors on the website are no longer showing and have changed to 'null'

**Comment by papabear99** [comment]
A few observations:

My latest result had a lower success rate than usual.  Just one test so certainly could be an anomaly.  It's also the only one that has a value for Upload Time. 

https://interptr-latest-test-streams.vercel.app/?address=0x10742714f33f3d804e3fa489618b5c3ca12a6df7
<html>
<body>


SIN | 3/2/2022 05:13:33 | Yes | 0.73 | 0.03 | 0.04 | 0.79 | 2.00 | 20/60 !
-- | -- | -- | -- | -- | -- | -- | -- | --
SIN | 3/1/2022 22:13:44 | Yes | 1.09 | 0.00 | 0.10 | 1.19 | 2.00 | 56/60 !
SIN | 3/1/2022 12:13:53 | Yes | 1.06 | 0.00 | 0.09 | 1.15 | 2.00 | 60/60


</body>
</html>


DeFiCrypto has all zeros but a 60/60 success rate
https://interptr-latest-test-streams.vercel.app/?address=0x9d5611bf0dadddb4441a709141d9229d7f6b3e47
<html>
<body>


SIN | 3/2/2022 06:33:36 | No | 0.00 | 0.00 | 0.00 | 0.00 | 0.00 | 60/60
-- | -- | -- | -- | -- | -- | -- | -- | --
SIN | 3/1/2022 23:32:10 | Yes | 0.16 | 0.01 | 0.03 | 0.20 | 2.00 | 56/60 !
SIN | 3/1/2022 13:32:12 | Yes | 0.15 | 0.01 | 0.04 | 0.20 | 2.00 | 60/60


</body>
</html>

**Comment by papabear99** [comment]
Here are my last 3 SIN test results...Same for DeFiCrypto
<html>
<body>


SIN | 3/3/2022 05:13:55 | No | 0.00 | 0.00 | 0.00 | 0.00 | 0.00 | 60/60
-- | -- | -- | -- | -- | -- | -- | -- | --
SIN | 3/2/2022 22:13:53 | No | 0.00 | 0.00 | 0.00 | 0.00 | 0.00 | 60/60
SIN | 3/2/2022 12:13:43 | No | 0.00 | 0.00 | 0.00 | 0.00 | 0.00 | 60/60


</body>
</html>

**Comment by papabear99** [comment]
Looks like we're getting there.

My last SIN test
<html>
<body>


SIN | 3/3/2022 12:13:59 | Yes | 0.69 | 0.00 | 0.03 | 0.72 | 2.00 | 60/60
-- | -- | -- | -- | -- | -- | -- | -- | --




DeFiCrypto
<html>
<body>


SIN | 3/3/2022 13:37:04 | Yes | 0.34 | 0.00 | 0.03 | 0.37 | 2.00 | 60/60
-- | -- | -- | -- | -- | -- | -- | -- | --



</body>
</html>

**Comment by leszko** [comment]
Yes, I think now all should be fixed! Today, I'll deploy it into all regions. Then, waiting for @yondonfu to review the PR and we'll be able to close this issue 🥳
