### ISSUE TITLE
Error from ffmpeg: signal: killed

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#230]
After 2hrs and 8mins of execution, the process seemed to run out of memory, with the initial error message given as:

> E1213 14:07:54.108287   21361 video_segmenter.go:114] Error from ffmpeg: signal: killed

This is perhaps linked with https://github.com/livepeer/go-livepeer/issues/227

Here is a text dump from the entire log file: [Error from ffmpeg: signal: killed.txt](https://github.com/livepeer/go-livepeer/files/1556760/Error.from.ffmpeg.signal.killed.txt)

System Monitor screenshot, indicating that the process reached 100% memory usage, forcing the CPU usage up, before experiencing the fatal error. The system's responsiveness to input severely deteriorated during the time when the memory reached 100%, before the process died and the system became responsive again (at the time when a load of RAM was released)

![image](https://user-images.githubusercontent.com/2212651/33957804-ad0eab78-e010-11e7-8f02-978ba819cc73.png)

System running Ubuntu 16.04 LTS
Livepeer Node Version: 0.1.6-unstable

**Comment by ericxtang** [comment]
We changed our memory management.  Do we still see this happening?

**Comment by ericxtang** [comment]
Fixed by the memory improvement.
