### ISSUE TITLE
Failed to `go get`

### ISSUE THREAD

**Issue by linuxaged** [livepeer/go-livepeer#231]
when run `go get github.com/livepeer/go-livepeer/cmd/livepeer`, gets the error:

    # cd /Users/apple/workspace/go/src/github.com/livepeer/go-livepeer; git submodule update --init --recursive
    fatal: No url found for submodule path 'vendor/gx/ipfs/QmcRKRQjNc2JZPHApR32fbkZVd6WXG2Ch9Kcy7sPxuAJgd/cbor/test-vectors' in .gitmodules
    package github.com/livepeer/go-livepeer/cmd/livepeer: exit status 128

macOS 10.12.6
go 1.9.2

**Comment by ericxtang** [comment]
Thanks for reporting @linuxaged!  Looks like there is a submodule in one of the new vendored packages.  We'll take a look.

**Comment by linuxaged** [comment]
Maybe it's a network issue, when i run `go get github.com/livepeer/go-livepeer/cmd/livepeer ` at home, it works fine.

**Comment by ericxtang** [comment]
hmm... I'm still having the issue.  Will probably have to update the gx packages at some point.

**Comment by nicolasburtey** [comment]
also having this issue

**Comment by ericxtang** [comment]
To clarify - this is an issue, but it should NOT affect your ability to build from source.

**Comment by ericxtang** [comment]
Fixed in the latest release
