### ISSUE TITLE
Multi-arch Docker image geth-with-livepeer-protocol

### ISSUE THREAD

**Issue by leszko** [livepeer/go-livepeer#2316]
Our current Docker image [livepeer/geth-with-livepeer-protocol](https://hub.docker.com/layers/livepeer/geth-with-livepeer-protocol/streamflow/images/sha256-f627591cd20d20a801ac703a25d812113908030079acc5a2c414bab7ee52dc43?context=explore) supports only the `amd64` arch. Therefore it can't be used on the `arm64` arch. That's especially important, because a lot of developers use Apple M1 chips (`arm64/8`).

As a workaround, Ivan built a separate `arm64/8` Docker image available at [darkdragon/geth-with-livepeer-protocol](https://hub.docker.com/layers/darkdragon/geth-with-livepeer-protocol/streamflow/images/sha256-517579c077f751803c19c8f9ba6b21f38e6a6e51a18e0cd47b1c9c94ae0ee6ed?context=explore). However it's a suboptimal.

The correct solution is create multi-arch Docker image `livepeer/geth-with-livepeer-protocol` which supports both architectures `amd64` and `arm64`. To build such an image `docker buildx` can be used. A command to build and push it may look like this one.

```
docker buildx build --push --platform linux/arm64/v8,linux/amd64 \ --tag livepeer/geth-with-livepeer-protocol:confluence .
```

**Comment by RiccardoBiosas** [comment]
**Related PR**
https://github.com/livepeer/docker-livepeer/pull/94
https://github.com/livepeer/go-livepeer/pull/2433
