### ISSUE TITLE
Change Redeemer Cli to Orchestrator Cli

### ISSUE THREAD

**Issue by Titan-Node** [livepeer/go-livepeer#2338]
**Describe the bug**
Currently when running a Redeemer node, the cli commands are for Broadcaster functions as follows: (Excluding all shared commands, 1-10 and 16-19)

```
11. Invoke "deposit broadcasting funds" (ETH)
12. Invoke "unlock broadcasting funds"
13. Invoke "cancel unlock of broadcasting funds"
14. Invoke "withdraw broadcasting funds"
15. Set broadcast config
```

Since the Redeemer node acts as an Orchestrator node, ie calling reward, these commands are missing key commands such as `11. Invoke "reward"`.

If for instance if a Redeemer nodes misses calling reward, one must launch a standalone Orchestrator node just to submit a manual reward call.

A solution would be to change the Redeemer cli to reflect the Orchestrator cli.

Orchestrator cli commands proposed as follows:

```
11. Invoke "reward"
12. Invoke multi-step "become an orchestrator"
13. Set orchestrator config
```

**Comment by RyanC92** [comment]
Linking duplicate issue: [2257](https://github.com/livepeer/go-livepeer/issues/2257)

**Comment by yondonfu** [comment]
Closing as dup of https://github.com/livepeer/go-livepeer/issues/2257 so all further conversation can be directed to that issue.
