### ISSUE TITLE
Client Should Claim Within 256 Blocks

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#234]
As @yondonfu mentioned in https://github.com/livepeer/go-livepeer/pull/233, 

> Noting here that if the transcoder is assigned to a job, it will need to make the first call to claimWork within 256 blocks (due to the use of block.blockhash in the contract) of the claim block to explicitly set itself as the assigned transcoder for a job. After the first call, all subsequent calls to claimWork can occur at any time. We'll need to change the logic for how a call to claimWork is made - I believe right now it happens when a stream is finished, so we would need to change it such that the first call happens within 256 blocks of the claim block and then perhaps a second call when the stream is finished

We should track the block number in the ClaimManager, and either:
* Do a single claim at the end of a stream if it hasn't been 256 blocks yet, or
* Do a claim towards the end of 256 blocks (anticipating some network congestion, maybe after 246 blocks?), and do another claim at the end of the stream.

**Comment by yondonfu** [comment]
Closed by #249
