### ISSUE TITLE
Secure endpoints

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#236]
We should secure the http endpoints so not all are exposed to everyone.

**Comment by j0sh** [comment]
How should this be done? Via digest auth or a shared secret token?

**Comment by ericxtang** [comment]
I think we can start with a shared token used in both in `rtmp` and `http`, maybe passed in via a parameter when starting the node.

**Comment by j0sh** [comment]
IIRC, RTMP auth is typically a username / pass digest scheme, will have to check on joy4's support for that.

**Comment by ericxtang** [comment]
This is an application-level feature.  Closing.
