### ISSUE TITLE
Performance tests not working since the Arbitrum upgrade

### ISSUE THREAD

**Issue by xbenderCH** [livepeer/go-livepeer#2370]
**Description**
For some orchestrators, the performance tests are not working since the arbitrum upgrade. I'm not 100% sure if it has to do with the upgrade, but it was working some time before the upgrade happened and I noticed that it was no longer working for my orchestrator after the upgrade.

As far as I know, my own [orchestrator ](https://explorer.livepeer.org/accounts/0x41239fb65360981316fcb4a8548320d305f9496d) and at least the orchestrator of [Sundara.eth](https://explorer.livepeer.org/accounts/0x1a196b031ea1a74a53ecbe6148772648e02f9d51) are affected, but there might be more.

My orchestrator is working properly in general since I do get streams that last several hours and I even had a win since the upgrade.

I'm usually running the orchestrator with -v 4, but since it didn't showed any results when a test stream should arrive, I've switched it to -v 6, but the result was the same and no log entry has been written when the test stream should've happened.
The required ports are forwarded and since other streams seem to work properly, I would expect the test streams to come through as well.

**Steps to reproduce the behavior**
All performance test streams just do not reach my orchestrator, so initiating such a test stream should reproduce the behavior.

**Expected behavior**
I would expect that I at least get a log entry on my Orchestrator that a test stream arrived but failed. Of course, a successful test stream (as it was before the upgrade) would be even better.

**Desktop**
 - OS: Windows 10 Home 64bit 20H2
 - Version: go-livepeer v0.5.29
 - GPU: GTX 980 TI, but I've also tried a RTX 2080 TI to see if it helps (w/o success)

**Comment by leszko** [comment]
I found out one interesting thing that might be related. When the Stream tester is connected to the [Canary Livepeer Subgraph](https://api.thegraph.com/subgraphs/name/livepeer/livepeer-canary), the overall results are way better than the [Arbitrum One Livepeer Subgraph](https://api.thegraph.com/subgraphs/name/livepeer/arbitrum-one). 

Any thoughts on that @yondonfu @adamsoffer?

**Comment by yondonfu** [comment]
Related to #2270

**Comment by leszko** [comment]
The issue is already fixed, I will roll this change out to Stream Tester production environment in the next days. So, you should expect to see the correct Stream Test results by the end of this week.

**Comment by leszko** [comment]
FYI: All changes are already in prod, so you should receive the correct test streams right now!

**Comment by xbenderCH** [comment]
It looks good on my side. Thank you very much for your effort to fix this.
