### ISSUE TITLE
Add eth address to "Finished push request" log line

### ISSUE THREAD

**Issue by ecmulli** [livepeer/go-livepeer#2386]
**Is your feature request related to a problem? Please describe.**
When a segment is successfully transcoded we can't map that 1:1 to the orchestrator that actually did the transcoding. 

**Describe the solution you'd like**
eth address added to the logline for a clear connection between the segment and who did the transcoding

**Describe alternatives you've considered**

**Additional context**

**Comment by yondonfu** [comment]
@ecmulli Could you describe the use case that you have in mind here? The context would be helpful to either determine how to best get you the information that you need or whether there is another way to get that information that already exists. IIUC you want to get the ETH address for each completed transcoding request? Are you scraping logs? Would getting that information in a different form (i.e. an exported metric) be okay?

**Comment by ecmulli** [comment]
the use case is to be able to know which orchestrator is doing the transcoding for a segment for a broadcaster. i am querying the grafana logs. right now, it has an orchestrator url but it doesnt match to the subgraph very well. so we need a way to map that relationship.

**Comment by yondonfu** [comment]
@ecmulli Got it. After https://github.com/livepeer/go-livepeer/issues/2371 is addressed (@red-0ne is currently working on it),  it will be possible to aggregate the following metrics based on O:

- `transcode_overall_latency_seconds`: The seconds it took for an O to complete transcoding
- `segment_transcoded_all_appeared_total`: The # of segments transcoded by an O

Then, I think you'd be able to use a querying language like [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) to query for these metrics filtering for a specific O from a Victoria Metrics DB (which I believe is the TSDB that we currently use in most places). Would this serve your use case - should be able to get an aggregate view of these values per O i.e. average, sum, etc.? Or do you actually need the O on a per segment basis?

I think the original plan was to tag the metric with the O's URI, but if having the ETH address is useful for this issue then we can see if we can tag the metric with the ETH address as well.

**Comment by ecmulli** [comment]
That should work. If you are going to tag the metric with the O's URI, you should see if they match up to the subgraph URI's. If the O reroutes the traffic we  might be capturing one that is different (and not very helpful). 

For example, from the subgraph: 
orch: 0xa408138c3c75c927b8614a24a39de02ffd71405f
serviceURI: https://zachroyit.com:8935

from the logs: 
https://zachroyit.ddns.net:8935

this one was fairly simple because of the partial string match but about half of them could not be matched at all.

**Comment by yondonfu** [comment]
> you should see if they match up to the subgraph URI's. If the O reroutes the traffic we might be capturing one that is different (and not very helpful).

Ah good point! I think tagging with the ETH address as well would address this as that should always be stable.

Suggested to also tag metrics with ETH address [here](https://github.com/livepeer/go-livepeer/issues/2371#issuecomment-1124243780).

**Comment by yondonfu** [comment]
@ecmulli 

@red-0ne is going to implement ETH address tagging for metrics as mentioned in [this comment](https://github.com/livepeer/go-livepeer/issues/2386#issuecomment-1124238452) as a part of his PR for https://github.com/livepeer/go-livepeer/issues/2371. We'll close this issue once that work is complete.

**Comment by ecmulli** [comment]
Thanks!

**Comment by yondonfu** [comment]
Looks like this was implemented in #2382.

@ecmulli feel free to reach out to @red-0ne if you have any questions on how to filter the latency + # segments transcoded metrics using an ETH address. If there are any additional issues feel free to re-open.
