### ISSUE TITLE
Missing test stream, but Orchestrator receive normal work

### ISSUE THREAD

**Issue by Nondzu** [livepeer/go-livepeer#2412]
**Describe the bug**
No test streams is sent to my Orchestrator. Consequently, it maintains the last place on the Performance Leaderboard. My O and T are active and working fine and receiving the normal stream for transcoding.

**To Reproduce**
1. Go to [https://interptr-latest-test-streams.vercel.app/?address=0x6c06d3246fbb77c4ad75480e03d2a0a8eaf68121](url)
2. See zero stream in table.

**Node info**
Service URI : https://78.10.222.146:8935 
node addres: 0x6c06d3246fbb77c4ad75480e03d2a0a8eaf68121

**Version:**
Livepeer Node Version: 0.5.29
Golang runtime version: gc go1.17.6
Architecture: amd64
Operating system: linux

**Expected behavior**
Expected behavior is receive test streams and see my Orchestrator on Performance Leaderboard with non zero total score.

**Screenshots**
![image](https://user-images.githubusercontent.com/20000097/169247665-c9189885-6064-4f94-9d95-f6a16f910a6f.png)

**Additional context**
@leszko did some check and test server do not send stream to my Orchestrator 
I see this behavior since more than 1 week.

**Comment by leszko** [comment]
Related to #2370 

FYI: I already know what's the issue. I'll send a PR with the fix probably today, so you can expect to get it working somewhen next week.

**Comment by leszko** [comment]
The issue is already fixed, I will roll this change out to Stream Tester production environment in the next days. So, you should expect to see the correct Stream Test results by the end of this week.

**Comment by leszko** [comment]
FYI: All changes are already in prod, so you should receive the correct test streams right now!

**Comment by Nondzu** [comment]
@leszko many thanks problem solved. I see test streams statistic now 👍
