### ISSUE TITLE
CLI transcoder transaction doesn't save parameters or let you update parameters

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#242]
In livepeer_cli, when started with the `-transcoder` flag, the option for "Become a Transcoder" has the following three bugs:

1. If you use default values for each of the options, the transaction goes through but it displays the three parameters all as 0, rather than using the default values.

2. If you enter your own values instead of the default values, the transaction fails.

3. If you are already a transcoder, the transaction fails saying that this transcoder already exists, but there is no other way through the CLI to update your transcode params.

**Comment by dob** [comment]
After restarting the CLI, and displaying the transcoder stats, rather than showing all the params with 0 values, it shows them with the default values. So while the bug still exists that doesn't let you set your own params, there may be an additional issue which is:

4. After setting your transcode params the CLI still shows 0 values for the params until a restart.

**Comment by yondonfu** [comment]
I believe this is fixed
