### ISSUE TITLE
Password issue connecting remote T to O

### ISSUE THREAD

**Issue by Pon-node** [livepeer/go-livepeer#2452]
**Describe the bug**
I was not able to connect remote transcoder to my orchestrator due to -orchSecret having the ? symbol 

**To Reproduce**
1. Add the ? At -orchSecret orchsecret?
**Expected behavior**
Remote transcoder will not connect to orchestrator

**Comment by thomshutt** [comment]
@Pon-node What exactly is the failure you see here? My shell complains about the question mark: ```zsh: no matches found: secre?``` but when I quote with `-orchSecret "secre?"`, it seems to work fine on zsh / MacOS

**Comment by Pon-node** [comment]
@thomshutt It's been a wile now... Orchestrator was on ubuntu and transcoder was using windows.

**Comment by thomshutt** [comment]
@Pon-node Any chance you can try to reproduce again? Otherwise I think we'll have to close this, since it's not happening locally for me

**Comment by thomshutt** [comment]
Going to close this for now. Feel free to reopen if you see the issue again
