### ISSUE TITLE
Streaming via CLI doesn't result in playable stream in Safari or Firefox

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#247]
If you broadcast using `livepeer_cli` the resulting stream plays in chrome, but not in safari, firefox, or on mobile. There is an error about improper encoding. If you broadcast using OBS, the streams do. Related to https://github.com/livepeer/livepeerjs/issues/19

**Comment by ericxtang** [comment]
We should take a look at the ffmpeg command and at least make the HLS stream to work on Safari, since that's accepted as the standard HLS player implementation.
