### ISSUE TITLE
transmuxing MP4 recording output is broken

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#2476]
**Describe the bug**
Production of MP4 files from recordings is broken.

**To Reproduce**
0. Check out a branch that includes fixes for object-store-without-API functionality: https://github.com/livepeer/go-livepeer/pull/2477
1. Run go-livepeer with ` livepeer -broadcaster -recordStore s3+https://GOOGAMT7AUXJ2SXGAGRI4NQI:[redacted-but-i-can-give-you-it]@storage.googleapis.com/go-livepeer-vod-test`
2. Run `curl http://localhost:8935/recordings/stream%2Bcountdown-Yg3OEth7/source.mp4`
3. You will get an empty file back, zero bytes.

We ran a bisect of go-livepeer and it appears that the first bad commit was 9324731141f90f471bb9d6cca4b3492ef4777eb3 cc @AlexKordic 

Logs:
```
ERROR: decoder.c:308] demuxer: Unable to open input : Invalid data found when processing input
E0627 11:16:35.515189   55340 ffmpeg.go:924] Transcoder Return : Invalid data found when processing input
E0627 11:16:35.515284   55340 mediaserver.go:1246] Error transmuxing to mp4 request=http://localhost:8935/recordings/stream%2Bcountdown-Yg3OEth7/source.mp4 uri=https://storage.googleapis.com/go-livepeer-vod-test/stream+countdown-Yg3OEth7/longos.local/source/0.ts manifestID=stream+countdown-Yg3OEth7 err="Invalid data found when processing input"
I0627 11:16:35.515378   55340 mediaserver.go:1188] Completed mp4 request=http://localhost:8935/recordings/stream%2Bcountdown-Yg3OEth7/source.mp4 manifestID=stream+countdown-Yg3OEth7 sourceBytes=322608 destBytes=0
```

**Comment by gioelecerati** [comment]
https://github.com/acaudwell/Gource/issues/216
https://github.com/songs18/m3u8_To_MP4/issues/10
