### ISSUE TITLE
Add ability to have multiple prices for different Broadcasters

### ISSUE THREAD

**Issue by papabear99** [livepeer/go-livepeer#2486]
**Is your feature request related to a problem? Please describe.**
Having the ability to set price based on Broadcaster will allow Orchestrators to negotiate discounted pricing for Broadcasters that commit to a guaranteed amount of work.  Currently if an O sets their `-pricePerUnit` it applies to all Broadcasters.  

**Describe the solution you'd like**
The ability to specify `-pricePerUnit` to a whitelisted Broadcasters list and a default `-pricePerUnit `

**Describe alternatives you've considered**
Having a dedicated node(s) for a specific client

**Comment by eliteprox** [comment]
I believe @0xB79 is actively working on this. I hope to be able to contribute some to it this week as well.

**Comment by eliteprox** [comment]
@papabear99 This issue should have auto-closed last year with #2592. Can we close this one now?

**Comment by papabear99** [comment]
@eliteprox closed
