### ISSUE TITLE
Spread Round Initialization Across Transcoders

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#250]
Currently, every transcoder will rush to initialize the round during the first block in the round.  This causes every transaction except 1 to fail (only one person can initialize the round).

Per suggestion by @dob, Let's change it to something like `if (block.hash % n == my transcoder's ranking in the active set) then call initializeRound()`, And then if the round was not initialized by the time the next block comes up, repeat, or something like that.

**Comment by yondonfu** [comment]
Closed by #251
