### ISSUE TITLE
Create dms-api project

### ISSUE THREAD

**Issue by thomshutt** [livepeer/go-livepeer#2533]
This will be a small Golang binary containing an HTTP API and allowing us to take in requests from Studio and co-ordinate Mist to do whatever's needed.

Design here: https://www.notion.so/livepeer/Technical-Design-Upload-of-VOD-segments-2463fb28a52c4b8f93d6939f03e08117

This ticket covers:

* Create a new golang project
* Create a HTTP endpoint - e.g print "OK" when the /ok endpoint is hit
* Create an integration test for this endpoint
* Set up Github Actions to build the project and run this test

**Comment by red-0ne** [comment]
Closed as per https://github.com/livepeer/dms-api/pull/1
