### ISSUE TITLE
dms-api: Create "VOD Upload" API endpoint

### ISSUE THREAD

**Issue by thomshutt** [livepeer/go-livepeer#2534]
Operation #1 in https://www.notion.so/livepeer/Technical-Design-Studio-DMS-API-for-VOD-Recording-bba2b160efff4ad4963dae2d4e9ff1a2

This ticket just covers creating the endpoint and associated tests (i.e not the underlying functionality)

1. Create HTTP endpoint, have it always return 200 OK by default
2. Create struct representing input JSON - discuss with @victorges about which (if any) fields should be optional
3. Add integration test that confirms an HTTP 200 is returned for valid JSON
3. Add integration test that confirms an HTTP 400 is returned for invalid JSON (missing required fields)

**Comment by leszko** [comment]
Closing this one after merging https://github.com/livepeer/dms-api/pull/4
