### ISSUE TITLE
dms-api: Trigger Mist segmenting + uploading of new VOD file

### ISSUE THREAD

**Issue by thomshutt** [livepeer/go-livepeer#2537]
TBC exactly how this looks. Design happening in https://www.notion.so/livepeer/Technical-Design-Upload-of-VOD-segments-2463fb28a52c4b8f93d6939f03e08117

**Comment by leszko** [comment]
I plan to do this ticket in a few parts:

- [x] Mist API client + scaffolding of its usage https://github.com/livepeer/catalyst-api/pull/8
- [x] Handling triggers from Mist
- [x] Calling callback URL with notifications

**Comment by leszko** [comment]
I think we can close this issue, because the work is already implemented in #8.

One thing that we need to add is the stream cleanup, but I've created a separate GH Issue for it: #2576
