### ISSUE TITLE
ci: fix arm64 docker build

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#2545]
In https://github.com/livepeer/go-livepeer/pull/2544 we disabled the arm64 docker build so that we could revert to an earlier, more compatible CUDA version. Ideally we'd publish an AMD64 build based on `nvidia/cuda:10.1-cudnn7-runtime` and an ARM64 build based on `nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04` but figuring out how to do that conditionally in the Dockerfile is not immediately clear to me.

**Comment by hjpotter92** [comment]
The newer `nvidia/cuda` images are incompatible with nvidia driver version installed on a lot of systems at present.
