### ISSUE TITLE
Remote T Returns 404 When Connected to O with ServiceAddr as Domain

### ISSUE THREAD

**Issue by AuthorityNull** [livepeer/go-livepeer#2549]
**Describe the bug**
When using a domain name as a serviceAddr, T's in different regions (e.g. NY T - Chicago O) do not communicate with each other properly. The T connects but returns 404 errors instead of segments. When using an IP as the serviceAddr, the remote T operates correctly. 

```I0726 23:12:35.325169 1458311 ot_rpc.go:143] Transcoding taskId=22493 url=https://null.anlivepeer.com:8935/stream/1dcc1c17/390.tempfile
I0726 23:12:35.325228 1458311 drivers.go:210] manifestID=218a210e-cbcd-40a4-9867-a3eb7b3ce286 seqNo=390 orchSessionID=1dcc1c17 taskId=22493 Downloading uri=https://null.anlivepeer.com:8935/stream/1dcc1c                     17/390.tempfile
E0726 23:12:35.327985 1458311 drivers.go:219] manifestID=218a210e-cbcd-40a4-9867-a3eb7b3ce286 seqNo=390 orchSessionID=1dcc1c17 taskId=22493 Non-200 response for status=404 Not Found uri=https://null.anl                     ivepeer.com:8935/stream/1dcc1c17/390.tempfile
E0726 23:12:35.328057 1458311 ot_rpc.go:170] manifestID=218a210e-cbcd-40a4-9867-a3eb7b3ce286 seqNo=390 orchSessionID=1dcc1c17 taskId=22493 Transcoder cannot get segment from taskId=22493 url=https://nul                     l.anlivepeer.com:8935/stream/1dcc1c17/390.tempfile err="404 Not Found"
E0726 23:12:35.328068 1458311 ot_rpc.go:251] manifestID=218a210e-cbcd-40a4-9867-a3eb7b3ce286 seqNo=390 orchSessionID=1dcc1c17 taskId=22493 Unable to transcode err="404 Not Found"
I0726 23:12:35.425612 1458311 ot_rpc.go:297] manifestID=218a210e-cbcd-40a4-9867-a3eb7b3ce286 seqNo=390 orchSessionID=1dcc1c17 taskId=22493 Transcoding done results sent for taskId=22493 url=https://null                     .anlivepeer.com:8935/stream/1dcc1c17/390.tempfile uploadDur=97.5104ms
```

**To Reproduce**
1. Change serviceAddr to domain
2. Connect remote T in a different region to O
3. Wait for stream to come in

**Expected behavior**
Domain name should function properly as serviceAddr.

**Screenshots**
![Screenshot_2022-07-27_095007](https://user-images.githubusercontent.com/95463891/181995723-d1adb266-ff55-429b-8f9e-0fdda525aed3.png)

**Desktop (please complete the following information):**
 - OS: Tested on 2 Linux boxes, as well as a Linux O and a Windows T.

**Additional context**
It's important to be able to use a domain name as the serviceAddr as it adds loadbalancing functionality when using GeoDNS. It's possible this issue stems from GeoDNS itself, in which I am unsure how to proceed. For reference, I tested this using Cloudflare.

**Comment by Titan-Node** [comment]
@AuthorityNull is the domain in your issue using load balancing? Because each segment acts as a new connection and if it's load balancing or switching endpoints each segment you will get this error likely. That's what happened to me so I purposely switched to the IP address method.

**Comment by AuthorityNull** [comment]
> @AuthorityNull is the domain in your issue using load balancing? Because each segment acts as a new connection and if it's load balancing or switching endpoints each segment you will get this error likely. That's what happened to me so I purposely switched to the IP address method.

Yes, but why would each segment be switching endpoints? If the T has  the IP address specified and the O is using a domain as the ServiceAddr, the T should always be sending/receiving streams to that O even if the domain is using Cloudflare load-balancing (GeoDNS), right?

**Comment by AuthorityNull** [comment]
Closed the issue - The issue was related to DNS and has been resolved by changing the serviceAddr on the O to point to individual IP.
