### ISSUE TITLE
Add "segment transcode" endpoint to DMS API

### ISSUE THREAD

**Issue by thomshutt** [livepeer/go-livepeer#2552]
This ticket covers making the new API endpoint defined in https://www.notion.so/livepeer/Technical-Design-Transcode-Upload-of-VOD-Recorded-Segments-3208507a9816449393e067b7b507d083 

Making the endpoint's functionality is covered by a separate ticket, so the output of this one should be 
1. A domain object representing the JSON that the API receives
2. A domain object representing the callback JSON
3. A new endpoint that (for now) just returns "OK" or similar
4. Unit tests around the new endpoint
5. (Optional) A test framework for the callback - we can have the endpoint just fire a callback every time it's called for now, but this will mean we have a stub "Studio" server in the tests that's ready to use for when we do the real implementation of this endpoint

**Comment by AlexKordic** [comment]
PR created https://github.com/livepeer/catalyst-api/pull/17
