### ISSUE TITLE
CLI interface to set broadcasting profiles doesn't accept multiple profiles

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#257]
Open `livepeer_cli` and choose option 15 for setting broadcast config. You are asked which profiles you would like, and should probably supply something like a comma separated list of integers to choose multiple. But right now it forces you to enter a single integer.

Not the highest priority, but worth fixing unless we have another interface for setting this.

**Comment by dob** [comment]
This looks fixed in the latest release, right? I was able to submit comma separated profiles.

**Comment by ericxtang** [comment]
Yep.  Closing.
