### ISSUE TITLE
remote Transcoders fail to register to Orchestrator

### ISSUE THREAD

**Issue by joegraviton** [livepeer/go-livepeer#2579]
**Describe the bug**
We have 1 node running as both O and T (Ubuntu 22.04,  go-livepeer v0.5.34), and seems working well.
However, when running additional remote Transcoders for this O, we keep seeing following errors in logs:

```
/usr/local/bin/livepeer -transcoder -nvidia all -orchSecret ./orchSecret.txt -orchAddr livepeer.<example>.xyz:8935 -maxSessions 15 -monitor -v 6
...
I0904 22:57:17.313977  103509 ot_rpc.go:58] Registering transcoder to livepeer.<example>.xyz:8935
I0904 22:57:18.546843  103509 ot_rpc.go:128] End of stream receive cycle because of err="rpc error: code = Unimplemented desc = unknown service net.Transcoder", waiting for running transcode jobs to complete
I0904 22:57:18.547064  103509 ot_rpc.go:60] Unregistering transcoder: rpc error: code = Unimplemented desc = unknown service net.Transcoder
...
```
Above error is happening for livepeer T with v0.5.34 on both Windows 11 and Ubuntu 22.04.

**To Reproduce**

1. Run a node as both O and T
2. Start another remote T and tries to transcode for above O
3. See error

**Expected behavior**
We are expecting the remote T should also starting transcode for the O.

**Screenshots**
![livepeer-transcoder-err](https://user-images.githubusercontent.com/1306111/188310225-16d6accc-a05c-426f-bb40-08a62f23fbf4.png)

**Environment:**
 - OS: Ubuntu 22.04
 - Livepeer Version : v5.0.34
 - Transcoder GPU: Nvidia 3090 on windows 11 & 3070 Ti on Ubuntu 22.04.

**Additional context**
None.

**Comment by joegraviton** [comment]
For an Orchestrator, is it supported to run local and remote Transcoders at the same time ? 

From this doc: https://docs.livepeer.org/video-miners/core-concepts/architecture
It mentioned following 2 architectures:

- Combined orchestrator and transcoder
- Split orchestrator and transcoder

However, we are doing a mix of above 2.

**Comment by AuthorityNull** [comment]
> 

Yes, a mix should work. Are you running proxy in front of Livepeer or anything like that?

**Comment by AuthorityNull** [comment]
Oh hang on, you can't run an O/T combo and connect a T to it. You have to split the O/T. T's cannot connect to a combined orchestrator.

**Comment by joegraviton** [comment]
@AuthorityNull   I see, thank you for the information.
