### ISSUE TITLE
docker image with incorrect entrypoint

### ISSUE THREAD

**Issue by ghost** [livepeer/go-livepeer#2633]
**Describe the bug**
Image version 0.5.35 (DIGEST:sha256:874e1a4bd1bc2a3f01dec42610707351f0acfab544225f84ebeea0982d5bcbd6)

Their is a problem on the image, the binary path changed from 
`/usr/bin/livepeer`
 to 
`/usr/local/bin/livepeer`
But the entrypoint is still the old one.

v0.5.34
![image](https://user-images.githubusercontent.com/115943219/197392987-0f3869ab-3c12-4d5f-8290-895d0ea231bd.png)
v0.5.35
![image](https://user-images.githubusercontent.com/115943219/197392990-fc3aad09-498a-4521-97c4-f63b5b4bd14a.png)

**Comment by iameli** [comment]
@hjpotter92, could you take a look?

**Comment by hjpotter92** [comment]
Fixed with #2635
