### ISSUE TITLE
Transferrable ownership of an O (reversable)

### ISSUE THREAD

**Issue by RyanC92** [livepeer/go-livepeer#2648]
**Is your feature request related to a problem? Please describe.**
With a few O's being hacked on their O wallets it puts the O in a position where they have to abandon the orchestrator completely and start over. This has happened to O's such as myself and a few others. 

**Describe the solution you'd like**
I would like to propose that ownership of the registered O is tokenized into an NFT which can be transferrable (similar to ENS ownership) or just transferrable (like contract #18 transferBond) and apply a 7 day reversable cooldown similar to the unstaking function. 

**Describe alternatives you've considered**
- Generate an NFT signaling ownership of the O that can be transferred.
- Implement a contract function to transfer ownership with a locking period that can be reversable (similar to the withdraw stake locking mechanism)

**Comment by leszko** [comment]
Thanks @RyanC92. That's a really nice feature request. Since it's a big one and related to the protocol changes, how about creating a post on the [Livepeer Forum](https://forum.livepeer.org/). There we can discuss, create LIP and follow up on this topic.
