### ISSUE TITLE
Fix fast verification fails for some segments, when B is using both Nvidia and CPU O+Ts

### ISSUE THREAD

**Issue by cyberj0g** [livepeer/go-livepeer#2654]
### Problem

Fast verification fails for some segments, when the Broadcaster uses both Orchestrators with Nvidia hardware, and Orchestrators, which transcode on CPUs. We want to:
- investigate the reason of such fails
- measure the failure rate in a test environment
- make failure rate lower than 1%, as per Fast Verification acceptance criteria.

### Findings
1. Fast verification fails on perceptual hash [comparison](https://github.com/livepeer/go-livepeer/blob/eb4f023ca93df62e32e136afeafbe1f7e8097232/server/broadcast.go#L550), when CPU O ends up as trusted, and Nvidia O as untrusted, or vice versa.
2. The issue was reproduced with 360p renditions of segments `source_002.ts` and `source_003.ts` of [test asset](https://storage.googleapis.com/lp_testharness_assets/bbb_1080p_30fps_1min_2sec_hls.tar.gz).
3. We already have a [similar test](https://github.com/livepeer/lpms/blob/71a9089bf76013aec5e44bdcb1392ff308ed7669/ffmpeg/sign_nvidia_test.go#L11), but it doesn't fail on a test video.
4. [Original paper](https://static1.squarespace.com/static/5c96595ca5682794a1eb2fa8/t/5cb6170cf9619acd0cf644b4/1555437327308/MPEG-7_Video_Signature_Author_Version.pdf) on MPEG-7 signatures mention false negative (hashes do not match for matching videos) rate of 4%, which is acceptable when the goal is to detect similar videos, but less acceptable if we need to reliably prove otherwise, as in fast verification case.
5. Rendition produced with Nvidia transcoder have a slight inter-frame visual glitch, presumably, caused by bi-linear interpolation implementation in `scale_cuda` filter - see attached side by side video.

https://user-images.githubusercontent.com/12607647/202463733-860ca7ae-5169-4df3-a9d1-8d3c7a368183.mp4

**Comment by cyberj0g** [comment]
### Solution
1. Add a [unit test](https://github.com/livepeer/lpms/pull/357) to ensure an actual FP/FN rate, at least for a multi-segment test asset.
2. [Tune](https://github.com/livepeer/FFmpeg/pull/30) signature comparison function, so that above test passes.
3. Ongoing monitoring of fast verification fail rate on staging and production

**Comment by hthillman** [comment]
@cyberj0g where can I monitor fast verification fail rate?

**Comment by cyberj0g** [comment]
The monitoring currently reports almost zero fail rate on staging, I believe this issue is fixed.
