### ISSUE TITLE
Bootstrap process should be async

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#266]
Currently the network bootstrapping process blocks until all connections are made.

This should happen in the background.

**Comment by j0sh** [comment]
What should happen if the connection to the bootstrap node fails?

**Comment by j0sh** [comment]
If this is about speeding up the process of bringing up a node:

The slowest point when starting a transcoder is establishing a new IPFS node, which always seems to take exactly 5 seconds. https://github.com/livepeer/go-livepeer/blob/master/ipfs/node.go#L55

However, making that async is tricky until we figure our how to handle errors arising from that.

**Comment by ericxtang** [comment]
No a problem anymore because we don't connect to cached neighbors anymore.
