### ISSUE TITLE
Transcoder State 

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#269]
Currently the transcoder loses all states when stopped (either crashed or quit).  We should record the state (at least the transcoded claims) so during restart, on-chain actions can be carried out based on the previous state.

**Comment by ericxtang** [comment]
Another thing the transcoder should resume when restarting is the actual transcoding.  Currently, if a broadcast is going on and the transcoder restarts, the viewers who are viewing the transcoded streams will never be able to continue the stream.  (This causes the issue we saw when the stream sometimes dies when we restart the transcoder)

**Comment by j0sh** [comment]
Given the discussions in https://github.com/livepeer/go-livepeer-basicnet/issues/21 and https://github.com/livepeer/go-livepeer/issues/316 , this would require changes to the broadcaster as well, if the broadcaster is the one initiating the direct connection to the transcoder in order for the transcoder to set up the subscription. The broadcaster needs a retry mechanism.

**Comment by j0sh** [comment]
Closed via https://github.com/livepeer/go-livepeer/pull/358
