### ISSUE TITLE
PRG test server 89.187.188.246 closes connection before listening response (broken pipe issue)

### ISSUE THREAD

**Issue by boratuncer** [livepeer/go-livepeer#2700]
**Describe the bug**
I believe PRG test server "89.187.188.246" closes connection before clients response them. This causes broken pipe on client side. But this server "212.102.38.92" is working quite good.

**To Reproduce**
I started to see this issue 3-4 days ago and whenever I got test streams from "89.187.188.246" broken pipe always happens. But if I got test streams from "212.102.38.92", there is no problem. (My orchestrator's round trip time is around 0.54 to "89.187.188.246" when it happens. Before it starts to happen Prague was my top score.)

My version of livepeer is V0.5.35. And I can download transcoded video and watch on my laptop. Also this problem happens only on test streams, not on any other streams

`
Dec 22 08:08:31 bema-m livepeer[811]: E1222 08:08:31.447250     811 player.go:179] Error writting response /stream/6f28d01d/P576p30fps16x9/13.ts: write tcp 192.168.1.4:8935->89.187.188.246:35290: write: broken pipe
`

In screenshot streams at 12/21/2022 15:07:49 was from "212.102.38.92" and others are from "89.187.188.246"

This problem occur in the middle of sequences, generally 2th, 5th and 11th of the segments. (see BrokenPipe.txt)

[BrokePipe.txt](https://github.com/livepeer/go-livepeer/files/10291180/BrokePipe.txt)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version Ubuntu 22.04.1 LTS

** Screenshots **
![image](https://user-images.githubusercontent.com/19672389/209247824-d759f400-513b-4991-9511-d7a99226a134.png)

**Comment by leszko** [comment]
@boratuncer Thanks for reporting the issue.

I wonder, does it happen frequently? I checked some Os they had `60/60`. Could you write how often you see this issue?

**Comment by boratuncer** [comment]
Hi @leszko ,

It started to happen from PRG servers 5 days ago (at least I realized it) and on every test stream from 89.187.188.246 I have the problem. Before mine was also 60/60 and yes some OS has 60/60 but which server are they receiving segments ?

In my case if I got them from "212.102.38.92" then there is no pb.

**Comment by leszko** [comment]
> Hi @leszko ,
> 
> It started to happen from PRG servers 5 days ago (at least I realized it) and on every test stream from 89.187.188.246 I have the problem. Before mine was also 60/60 and yes some OS has 60/60 but which server are they receiving segments ?
> 
> In my case if I got them from "212.102.38.92" then there is no pb.

I see. And if you hover over the error in the dashboard, what is the error message? I checked again other Os and they look good with `60/60`, so not sure why your O is getting errors.

**Comment by boratuncer** [comment]
Hi, It says [{"error_code":"NoOrchestraors","count": 2}, {"error_code":"Download", "count": 2}]

Count changes 2, 4, 7 etc..

**Comment by boratuncer** [comment]
By the book definition; a 'Broken pipe' message happens when you write to a stream where the other end has been closed.

So I believe something like "ClientAliveInterval" (which I always use on SSH servers) is too short on 89.187.188.246.

**Comment by leszko** [comment]
I think the timeout is set high enough (`8s`), so it should be ok.

The error ` [{"error_code":"NoOrchestraors","count": 2}, {"error_code":"Download", "count": 2}]` means Broadcaster in our infra cannot connect to your Orchestrator during the "transcoding" or "download results" phase. That would probably indicate some latency issues. Where is your server located? Could you check the RTT from PRG region to your server?

**Comment by boratuncer** [comment]
If I'm not mistaken you display that error if transcoded results are not received back, right ? 

Because on my side, I get job from "89.187.188.246", transcode it and get failure when writing back. I even can download the transcoded video into my PC and watch it.

My server is located in Istanbul and this issue started to happen a couple of days ago. I don't know if I always get test streams from "89.187.188.246" before that I was OK. Maybe at that time I was getting test streams from "212.102.38.92"



--- 89.187.188.246 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9013ms
rtt min/avg/max/mdev = 46.235/46.747/47.231/0.288 ms


--- 212.102.38.92 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9012ms
rtt min/avg/max/mdev = 41.652/42.242/42.474/0.237 ms

**Comment by boratuncer** [comment]
One additional info, as you could see my orch. score is not good with SAO but I don't get broken pipe errors from it. I even got [{"error_code":"NoOrchestraors","count": 1}, {"error_code":"DeadlineExceeded", "count": 2}] from it.

**Comment by boratuncer** [comment]
One more additional info, IPv6 is closed on both my router and my node

**Comment by boratuncer** [comment]
Please find new logs in attachment.

[BrokenPipe.txt](https://github.com/livepeer/go-livepeer/files/10333216/BrokenPipe.txt)

**Comment by boratuncer** [comment]
Hi @leszko ,

I got evidences that this problem is related with my ISP so I'm going to fix with them.

On the other hand I don't know any reason why 212.102.38.92 was working without any error but I'm going to close the ticket.
