### ISSUE TITLE
T does not automatically connect to O after restart or crash .35 and .36

### ISSUE THREAD

**Issue by AuthorityNull** [livepeer/go-livepeer#2704]
**Describe the bug**
This is potentially related to issue [#2702](https://github.com/livepeer/go-livepeer/issues/2702#issue-1512478847).

T's are getting stuck trying to reconnect to an O after a restart or crash. This does not happen 100% of the time, but most commonly occurs when an O restarts incorrectly/crashes.

The T must be manually restarted before it can connect to the O again, or else it just hangs here:

```
Dec 29 23:30:18 fortuna livepeer[299586]: I1229 23:30:18.319760  299586 ot_rpc.go:141] End of stream receive cycle because of err="rpc error: code = Unavailable desc = error reading from server: EOF", waiting for running transcode jobs to complete
```

Thanks to Marco, we may have narrowed down the section of code where the issue is occurring:
https://github.com/livepeer/go-livepeer/blob/e2c46a1e30ca3c5aafcc1a4f11f55523235da871/server/ot_rpc.go#L124-L143

**To Reproduce**
1. Launch an O and T
2. Restart the O, or simulate a crash.
3. Observe T's logs.

**Expected behavior**
T should automatically connect back to an O regardless of how an O restarts.

**Desktop (please complete the following information):**
 - OS: Linux/Ubuntu
 - Version .35 and .36

**Comment by stronk-dev** [comment]
Yea, my thinking is the bug got introduced in this commit: https://github.com/livepeer/go-livepeer/commit/a1fb761474685ae0679e26349e27f19012d95a75#diff-0db7e4513a2e3eb16dedb22ed6a0920e6648e62733004c11dc0ed8a19f314464

Seems to me like the wait group can have more `wg.Add(1)` than `wg.Done()` calls when it enters the if statement where it calls `EndTranscodingSession`

Currently testing if moving the `wg.Add(1)` into the else statement fixes the issue...
