### ISSUE TITLE
Fix segment data locking on O "Session ended" notification 

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#2762]
I think it's like
1. Some stream ends via timeout. Any stream on the B, doesn't have to be the one in question. <https://github.com/livepeer/go-livepeer/blob/e7e1183c05f80c30d52a0b9db874effb3b297b13/server/mediaserver.go#L930>
2. `removeRTMPStream` grabs the global connectionLock <https://github.com/livepeer/go-livepeer/blob/e7e1183c05f80c30d52a0b9db874effb3b297b13/server/mediaserver.go#L609>
3. A few layers deeper within that call, we notify the O that the session has ended. This is an async call involving a round-trip to an O that can fail for any number of reasons, ephemeral network errors and whatnot <https://github.com/livepeer/go-livepeer/blob/e7e1183c05f80c30d52a0b9db874effb3b297b13/server/rpc.go#L269>
4. Meanwhile, more segments for _other_ streams are coming in, and they all queue up behind the locked `s.connectionLock` on this line <https://github.com/livepeer/go-livepeer/blob/e7e1183c05f80c30d52a0b9db874effb3b297b13/server/mediaserver.go#L837>
5. Finally the O end-session request either succeeds or times out, unlocking the lock, resulting in the big burst of transcodes that we see back up here <https://github.com/livepeer/go-livepeer/blob/e7e1183c05f80c30d52a0b9db874effb3b297b13/server/mediaserver.go#L837>

And then we get the big burst of segment transcodes that we've been seeing.

**Comment by Thulinma** [comment]
Knowing nothing of Go: would it make sense to just add that O end-session notification to a queue and handle that queue on a separate thread? I assume that notification need not happen with any active lock, anyway. 🤔

**Comment by iameli** [comment]
@Thulinma Starting a new goroutine to do the O updating will have essentially that effect, yeah.

**Comment by cyberj0g** [comment]
Interesting, does the timeout of 3 sec set [here](https://github.com/livepeer/go-livepeer/blob/d8ad5c7c9683bdf0569c1c3601416af360967840/server/rpc.go#L293) cause the issue? It should apply to all gRPC calls.

**Comment by iameli** [comment]
@cyberj0g I don't think that would _cause_ the issue, in fact I suspect that timeout is causing the issue to be not as bad as it could be by capping the "everything is frozen" state to <= 3sec. The real problem is a cascading effect like

* Session closes
* 3 seconds of blocking for a stuck O
* Lots of segments try and transcode, can't, retry
* Those livestreams time out
* Those sessions close
* Each one of those blocks for 3 sec

And so on. The issue was really hard to find because it only shows up when there's a "stuck" orchestrator in there somewhere that blackholes gRPC calls.

**Comment by cyberj0g** [comment]
Makes sense. The retries are caused by the fact that timeout is larger than segment length.
So the options are: 
* reduce the gRPC timeout to, say, 0.5 sec as a quick fix - an O with latency this large won't be selected for transcoding anyway
* make `EndTranscodingSession()` call async - at first glance it should work fine, but I'm not totally sure that won't cause a race condition somewhere else

**Comment by iameli** [comment]
I'd be nervous about blocking _all_ new segments on even a 0.5s timeout, would prefer to go the async route. Or if we can redesign the call to not lock `connectionLock`, that would be fine too. (cc @mjh1)

**Comment by iameli** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/2764
