### ISSUE TITLE
Client should compute pending stake and fees offchain

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#278]
Right now the client uses the `pendingStake` and `pendingFees` functions in the BondingManager contract to retrieve a delegator's stake + pending rewards and a delegator's collected fees + pending fees. Though these are read only functions that don't modify contract state thus not actually having any real cost, they are still subject to the gas limit since they are executed locally. As a result, it is possible for the computation to take a long time or get stuck. We should instead just calculate these values by retrieving the rewards/fees available for each round since a delegator's last claim round and then compute the pending stake and pending fees off chain with that data

**Comment by ericxtang** [comment]
Theoretically this would be nice, but I'm worried about the duplication of logic.  Since we are relying on Infura, maybe we can re-visit this later?

**Comment by ericxtang** [comment]
Not sure if this is a good idea anymore. Closing.
