### ISSUE TITLE
Default ports cause clashes when running >1 of Broadcaster / Orchestrator / Transcoder

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#2797]
# Summary of the issue

When attempting to run >1 of the Broadcaster, Orchestrator, Transcoder services on a single host, there are port clashes by default.

While this is resolvable, it does introduce greater complexity to getting a full Livepeer stack operation, for example in a development environment.

This issue seeks to remove this complexity, in order to make it easier to get started with developing with go-livepeer.

## cliAddr port

Currently, when you start `livepeer` binary in any of the modes B, O, or T), they all try to use port `7935` for the default `cliAddr`.

## httpAddr port

Currently, when you start `livepeer` binary in any of the modes B or O, they all try to use port `8935` for the default `httpAddr`.

# Proposed solution

Proposal is to introduce consistency across the piece, and avoid port clashes when starting all three BOT services with default port configuration

## As is

| Port | B    | O    | T    |
|------|------|------|------|
| cli  | 7935 | 7935 | 7935 |
| http | 8935 | 8935 | N/A  |
| rtmp | 1935 | N/A  | N/A  |

### Invariants

The main invariant in this, is that most Orchestrators on Livepeer Public Transcoding Network use `8935` for their http port. Changing this would be painful, so too would changing any ports used by the O. So, let's keep all the O's ports exactly the same.

Another invariant is that `1935` is the global default port for `rtmp`, which is how the Broadcaster ingests content. So, let's keep the B's rtmp ingest port the same.

## Proposal

Proposed changes in _italics_, and invariants in **bold**:

| Port | B    | O    | T    |
|------|------|------|------|
| cli  | _5935_ | **7935** | _6935_ |
| http | _9935_ | **8935** | N/A  |
| rtmp | **1935** | N/A  | N/A  |

For connecting to a `cli` using `livepeer_cli`, a user can then use `./livepeer_cli -http 5935` for the B, and `./livepeer_cli -http 6935` for the T.

This way, no ports will clash when running services with default configuration, thus reducing the overall complexity for "getting started" with go-livepeer. All ports would still be of the form *935.

**Comment by leszko** [comment]
I like the idea. I think we should change the default port, so that you can run all the services with default parameters locally.

**Comment by thomshutt** [comment]
+1 to this being a good idea. If the community is able to put together a PR then we'll be happy to accept it

**Comment by chrishobcroft** [comment]
> I like the idea. I think we should change the default port, so that you can run all the services with default parameters locally.

@leszko WDYM by "the default port"? The default port for which service? I'm not clear what you are proposing.

**Comment by chrishobcroft** [comment]
@thomshutt please remove the "community working on it" label as it is misleading.

It implies that someone is doing something about it, when to my knowledge, nobody is doing anything about it.

Such a label will dissuade anyone from picking this up, because they will think that someone is doing something on it, which isn't true.

Result: nobody does anything on it.

Further, I would propose to either remove the "community working on it" label altogether, partly because it implies that employees of Livepeer Inc. are not part of Livepeer Community, and this creates divisions between us, when as far as I'm concerned, we're all working on this together. Propose to re-label issues to "help wanted".

**Comment by leszko** [comment]
> @leszko WDYM by "the default port"? The default port for which service? I'm not clear what you are proposing.

I just meant that I liked your idea 🙃

**Comment by eliteprox** [comment]
@chrishobcroft This issue should have auto-closed with #2850. Can we close it now?

**Comment by chrishobcroft** [comment]
Verified as working! Nice job. Now all we have to do is remember that the B serves content at 9935 not 8935 :))
