### ISSUE TITLE
Setting Broadcaster specific price segfault

### ISSUE THREAD

**Issue by stronk-dev** [livepeer/go-livepeer#2819]
It works well in general, but when specifying 3 or more B's using CMD flags the program segfaults. This is caused due to an error being thrown in the `ReadFromFile` function, where `os.Stat(s)` returns an error which was not being covered by `os.IsNotExist(err)`. After that `info.IsDir()` is called but `info` is undefined at that point

https://github.com/livepeer/go-livepeer/blob/8bd65fb984ab611e1343df713bae231b8119090a/cmd/livepeer/starter/starter.go#L1413

https://github.com/livepeer/go-livepeer/blob/8bd65fb984ab611e1343df713bae231b8119090a/common/readfromfile.go#L12-L19

Entire segfault:
```
I0701 09:42:34.148159       1 db.go:458] Closing DB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1a087b2]
goroutine 26 [running]:
github.com/livepeer/go-livepeer/common.ReadFromFile({0x7ffc84ab8acc, 0x131})
	/common/readfromfile.go:19 +0x72
github.com/livepeer/go-livepeer/cmd/livepeer/starter.getBroadcasterPrices({0x7ffc84ab8acc, 0x131})
	/cmd/livepeer/starter/starter.go:1444 +0x49
github.com/livepeer/go-livepeer/cmd/livepeer/starter.StartLivepeer({_, _}, {0xc00052e2f0, 0xc00052e300, 0xc00052e310, 0xc00052e320, 0xc00052e330, 0xc00052e340, 0xc00052e350, 0xc00052e410, ...})
	/cmd/livepeer/starter/starter.go:766 +0x3fb3
main.main.func1()
	/cmd/livepeer/livepeer.go:97 +0x58
created by main.main
	/cmd/livepeer/livepeer.go:96 +0xca5
```

Proposed solution is to return the string as-is if the `ReadFromFile` errors

Edit: this issue probably only occurs when using CMD flags to

**Comment by ad-astra-video** [comment]
Just curious, what is the input string length max? Also, the max length is the file path?

**Comment by stronk-dev** [comment]
> Just curious, what is the input string length max?

Not sure, somewhere between specifying 2 and 3 broadcaster prices :p 
`OS.Stat` returns an error after some point where the input string is too long to be a file path/directory. A nice edge case which wasn't being checked for or covered by unit tests

Edit: basically what happened is `os.Stat(s)` returns an error which was not being covered by `os.IsNotExist(err)`. After that `info.IsDir()` is called but `info` is undefined at that point
