### ISSUE TITLE
Ungodly number of eth_getLogs for the same unbond event.

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#2858]
**Describe the bug**
My Livepeer node seems to make an ungodly (1M in a day) amount of `eth_getLogs` requests to my web3 provider, Alchemy in this case. 

It always tries to request the same `Unbond` event. 
The only difference in each request is the block hash. It seems to be trying this request on each block. 

We can confirm that this is indeed the `Unbond` event, as the first topic is the event signature hash. To confirm we can use `forge cast sig-event <EVENT STRING>`
```sh
cast sig-event "event Unbond(
        address indexed delegate,
        address indexed delegator,
        uint256 unbondingLockId,
        uint256 amount,
        uint256 withdrawRound
    )"
    // 0x2d5d98d189bee5496a08db2a5948cb7e5e786f09d17d0c3f228eb41776c24a06
```

```json
{
  "jsonrpc": "2.0",
  "id": 7281,
  "method": "eth_getLogs",
  "params": [
    {
      "address": null,
      "blockHash": "0x0c871f92d0f79b29bc4f84e71be80af22cce9e06dba1c13a936c8e00d59c951b",
      "topics": [
        [
          "0x2d5d98d189bee5496a08db2a5948cb7e5e786f09d17d0c3f228eb41776c24a06",
          "0x9f5b64cc71e1e26ff178caaa7877a04d8ce66fde989251870e80e6fbee690c17",
          "0x1340f1a8f3d456a649e1a12071dfa15655e3d09252131d0f980c3b405cc8dd2e",
          "0x22f2fc17c5daf07db2379b3a03a8ef20a183f761097a58fce219c8a14619e786",
          "0x5159e237d952190e68d5215430f305831be7c9c8776d1377c7667"
        ]
      ]
    }
  ]
}
```

**To Reproduce**
Unsure 
Repo and branch: https://github.com/kyriediculous/go-livepool/tree/nv/arb-update

**Expected behavior**
Stop querying this event 

**Screenshots**
<img width="919" alt="image" src="https://github.com/livepeer/go-livepeer/assets/22256858/03769a51-e25d-441d-8f08-d7ffc595ae5e">

**Additional Context**
Livepeer version 0.5.28

**Comment by leszko** [comment]
That's very weird, we didn't experience it. Also, I don't think go-livepeer even makes the query for the topics you mentioned. The only `eth_getLogs` query should be executed for these topics:

https://github.com/livepeer/go-livepeer/blob/6629fc28ed37b75ddfc0e14950d8498622921b8c/eth/watchers/topics.go#L8-L22

**Comment by kyriediculous** [comment]
> "Unbond(address,address,uint256,uint256,uint256)"

Is the event in these logs.

`forge cast` ignores parameter names.

It's indeed very weird because by block polling interval is set to 30s, and the UnbondingWatcher shouldn't be making RPC queries.

**Comment by leszko** [comment]
Yes, but there are more topics in the request you shared. Shouldn't they all show up?

**Comment by kyriediculous** [comment]
Sorry my bad, yes you're right. 

I believe the reason why I'm seeing so many requests is because I still had https://github.com/livepeer/go-livepeer/blob/4a4a956f3c9c8779bc4d94f9ff51cd70b7a28c42/eth/blockwatch/block_watcher.go#L23 set to 60. 

Not entirely sure why Alchemy doesn't show the full topic list linked in your comment.

Anyway, I will monitor if my update helps reducing my amount of RPC requests.
