### ISSUE TITLE
go-livepeer: Dynamically changing price casues streams drop

### ISSUE THREAD

**Issue by Tibia2000** [livepeer/go-livepeer#2903]
**Describe the bug**
Transcoding jobs are dropped after price is changed dynamically.

**To Reproduce**
1. Wait for stream at price 10
2. Change price from 10 to 200 while transcoding 
3. Streams are dropped

**Expected behavior**
After recent PR it should not drop the work when price is dynamically changed during work.
It started happenning Today around 10:00 Berlin Time, probably latest changes were implemented 

Tested on latest build:
https://build.livepeer.live/go-livepeer/0.7.1-dcc3250d/livepeer-linux-gpu-amd64.tar.gz

**Comment by leszko** [comment]
@Tibia2000 Thanks for raising the issue.

Could you share some more info? In particular:
1. Did it happen once or do you experience it every time you change the price?
2. How did you change the O's price? Using Livpeeer CLI?
3. Could you check in your logs if you have the following line? And if yes, then please share it
```
Setting fixed price=
```

**Comment by Tibia2000** [comment]
1. It happened each time I changed the price, I was checking it thoroughly. 
2. I am using python script with following function: `eu_url = f'{eu_base_url}:{port}/setOrchestratorConfig'
            try:
                response = requests.post(eu_url, data={'pixelsPerUnit': '1', 'pricePerUnit': new_price_eu})`
3. Yes I can see `20:46:56.251142 1978263 orchestrator.go:147] Setting fixed price=250/1 for session=fd3ac511
` in the logs

**Comment by leszko** [comment]
Thanks for the details. I'll look into the issue.

**Comment by Tibia2000** [comment]
I made another dive into logs and I can see:
``ct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.567168 1978263 segment_rpc.go:94] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Received segment dur=1.02s
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.567216 1978263 census.go:1149] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Logging SegmentEmerged... duration=1.02
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.567518 1978263 orchestrator.go:147] Setting fixed price=250/1 for session=5bc73cbf
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.567595 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.567928 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.568249 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.568570 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.568886 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.569197 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.569513 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.569829 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.570136 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.570450 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.570761 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.571093 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.571408 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.571727 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.572044 1978263 orchestrator.go:181] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Receiving ticket sessionID=5bc73cbf faceValue=0.012 ETH winProb=0.0000000833 ev=1000000000.00
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.939816 1978263 segment_rpc.go:134] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Downloaded segment dur=367.337683ms
Oct 30 21:22:38 x sudo[1978263]: I1030 21:22:38.940445 1978263 census.go:1211] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Logging SegmentDownloaded... dur=367.337683ms
Oct 30 21:22:39 x sudo[1978263]: I1030 21:22:39.016622 1978263 orchestrator.go:498] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Starting to transcode segment
Oct 30 21:22:39 x sudo[1978263]: I1030 21:22:39.016652 1978263 orchestrator.go:486] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Creating new segment chan
Oct 30 21:22:39 x sudo[1978263]: I1030 21:22:39.016672 1978263 orchestrator.go:634] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E clientIP=195.181.174.186 Starting transcode segment loop for manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 sessionID=5bc73cbf
Oct 30 21:22:39 x sudo[1978263]: I1030 21:22:39.016700 1978263 orchestrator.go:507] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Submitted segment to transcode loop
Oct 30 21:22:39 x sudo[1978263]: I1030 21:22:39.024624 1978263 lb.go:106] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E LB: Creating transcode session for job=5bc73cbf
Oct 30 21:22:39 x sudo[1978263]: I1030 21:22:39.024698 1978263 lb.go:154] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E LB: Created transcode session for key=5bc73cbf_0
Oct 30 21:22:39 x sudo[1978263]: I1030 21:22:39.024710 1978263 lb.go:240] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E LB: Transcode submitted for key=5bc73cbf_0
Oct 30 21:22:40 x sudo[1978263]: I1030 21:22:40.831314 1978263 orchestrator.go:593] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Transcoding of segment took=1.806691953s
Oct 30 21:22:40 x sudo[1978263]: I1030 21:22:40.831346 1978263 census.go:1334] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Logging SegmentTranscode nonce=0 seqNo=126 dur=1.806691953s trusted=true verified=true
Oct 30 21:22:40 x sudo[1978263]: I1030 21:22:40.831366 1978263 orchestrator.go:612] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Transcoded segment profile=480p bytes=1282724
Oct 30 21:22:40 x sudo[1978263]: I1030 21:22:40.843004 1978263 orchestrator.go:612] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Transcoded segment profile=720p bytes=4572912
Oct 30 21:22:40 x sudo[1978263]: I1030 21:22:40.969758 1978263 player.go:105] LPMS got HTTP request @ /stream/5bc73cbf/720p/126.ts
Oct 30 21:22:40 x sudo[1978263]: I1030 21:22:40.974572 1978263 player.go:105] LPMS got HTTP request @ /stream/5bc73cbf/480p/126.ts
Oct 30 21:22:49 x sudo[1978263]: I1030 21:22:49.802775 1978263 block_watcher.go:454] Polling blocks from=145513841 to=145513889
Oct 30 21:23:04 x sudo[1978263]: I1030 21:23:04.803563 1978263 block_watcher.go:454] Polling blocks from=145513890 to=145513938
Oct 30 21:23:19 x sudo[1978263]: I1030 21:23:19.797359 1978263 block_watcher.go:454] Polling blocks from=145513939 to=145513987
Oct 30 21:23:34 x sudo[1978263]: I1030 21:23:34.785349 1978263 block_watcher.go:454] Polling blocks from=145513988 to=145514039
Oct 30 21:23:49 x sudo[1978263]: I1030 21:23:49.792947 1978263 block_watcher.go:454] Polling blocks from=145514040 to=145514089
Oct 30 21:23:50 x sudo[1978263]: I1030 21:23:50.832340 1978263 lb.go:212] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E LB: Transcode loop timed out for key=5bc73cbf_0
Oct 30 21:23:50 x sudo[1978263]: I1030 21:23:50.878593 1978263 orchestrator.go:662] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf clientIP=195.181.174.186 sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E Segment loop timed out; closing
Oct 30 21:23:50 x sudo[1978263]: I1030 21:23:50.878664 1978263 orchestrator.go:720] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E clientIP=195.181.174.186 Transcoding session ended by the Broadcaster for sessionID=5bc73cbf
Oct 30 21:23:50 x sudo[1978263]: I1030 21:23:50.918958 1978263 lb.go:146] manifestID=a5d05713-4b9a-4723-930d-09a6374a85a1 seqNo=126 orchSessionID=5bc73cbf sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E clientIP=195.181.174.186 LB: Deleted transcode session for key=5bc73cbf_0
``
There is a session incoming, fixed price is set for it, then it just does 1 segment and sessions is ended by broadcaster. I Found 3 sessions like this with different sessionID and now the question is if it is just a coincidence and I got 3 corrupted segments or it was dropping legit sessions. I will do more tests soon.

**Comment by Tibia2000** [comment]
Another Update: 
1. set a price to 0 pp > Getting stream without fixed price set to it: `Price per pixel set to 0 wei for 1 pixels
Oct 30 14:48:16 london sudo[2121167]: I1030 14:48:16.355975 2121167 segment_rpc.go:94] manifestID=31b3f879-32a3-4e16-b836-a9c920a8c879 seqNo=1 orchSessionID=93bfc3cc sender=0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E clientIP=89.187.181.249 Received segment dur=2s`
2. then i set price to 400 and I have this in logs: `14:58:03.289617 2121167 handlers.go:504] Price per pixel set to 400 wei for 1 pixels`
3. Stream is eneded by broadcaster
4. Set new price to 250 wei : `Price per pixel set to 250 wei for 1 pixels`
5. I am getting new stream with fixed price: `Setting fixed price=250/1 for session=acb45364`

looks like initial 0 ppp was not cached and glued to the following streams?

**Comment by leszko** [comment]
Ok, I looked into the issue. I think it only affects the initial price `0`. Could you try if it works for you in the case when the initial price is > 0?

When the price is set to `0`, then the tickets are not sent, because you provide a free transcoding service. So, I think that from the O's perspective is good that if it it increases the price, then the session is dropped. Otherwise, you'd cover the session all the time for free.

**Comment by Tibia2000** [comment]
Should it not work like this: set 0 all the following streams which come in are priced as 0, then I change price and I want to keep those streams for free and new streams should be transcoded for the new price. Well to me it does not really matter but logically it should behave in a similar way for all price ranges even for 0. I will test now with initial price > 0. Changing price should not drop any streams even those worked for free imho. It will prevent streams from being swapped for no reason. I may also want to use my free compute and set 0 price for other B and when my session limit is reached I would like to raise the price to prevent myself being overloaded without dropping streams. (This is just imaginary, but probably could be materialized when we want to help attract other B with 0 price with our resources not being used at the time. So I think sooner or later it will become a problem. But easy workaround is to just raise a price to 1 wei, but it should be known by all Os)
