### ISSUE TITLE
Improve `livepeer_value_redeemed` metric implementation

### ISSUE THREAD

**Issue by rickstaa** [livepeer/go-livepeer#2917]
**Improved Bug Report**

**Describe the Bug**

The current implementation of the `ValueRedeemed` metric in the `go-livepeer` codebase exhibits behaviour where the metric is exposed only upon invoking the `redeem winning ticket` method (see [these lines of code](https://github.com/rickstaa/go-livepeer/blob/5d9bcaa325d8caa18151b42f50f4f78bf76834d7/pm/sendermonitor.go#L433-L437)). The issue arises from the fact that the metric counter is not published when the `go-livepeer` client is restarted, as observed in the [redeemed value panel](https://dashboards.transcode.ninja/public-dashboards/57f9500cea134a548e139179228a70c4?orgId=1&refresh=30s) of my orchestrator dashboard.

**To Reproduce**

1. Start the `go-livepeer` binary with the `-monitor` flag.
2. Visit http://localhost:7936/metrics and note the absence of the `livepeer_value_redeemed` metric.
3. Check [the redeemed value panel](https://dashboards.transcode.ninja/public-dashboards/57f9500cea134a548e139179228a70c4?orgId=1&refresh=30s) in my orchestrator dashboard, confirming the metric is published only when a ticket is redeemed.

**Expected Behavior**

The `livepeer_value_redeemed` metric should function as a counter, initiating at 0. This adjustment ensures compatibility with Prometheus's [increase](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) method, enabling the metric to persist through binary restarts.

**Screenshots**

![image](https://github.com/livepeer/go-livepeer/assets/17570430/8969d9f7-c128-4d55-aa0d-5b280d87a634)

**Desktop (Additional Information):**

 - OS: Ubuntu 22.04
 - Version: a9a4b00580ad4d6b37f4435240359c861cfef287

**Comment by leszko** [comment]
@rickstaa Thanks for raising the GH Issue!

I think it makes sense. Would you like to send a PR with the update?

**Comment by rickstaa** [comment]
@leszko This issue was fixed by @stronk-dev in https://github.com/livepeer/go-livepeer/pull/2916. As a result, it should not be present anymore on the main branch. I will test it out and close this issue 👍🏻.

**Comment by rickstaa** [comment]
I am closing this since the issue has been fixed.
