### ISSUE TITLE
Feature Request: Live Viewer Metrics

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#295]
I want to be able to see how many people are watching right now.

Also, I want all the people watching to see how many people are watching :)

As a later thing, I want to be able to see the total number of unique viewers who watched, and when they watched.

Then I want to be able to run some crazy-complex algorithms using Artificial Intelligence, to work out what people like to watch, and what turns people off (or rather, what causes them to turn off).

**Comment by dob** [comment]
Good requests, but these are app level features that won't be addressed in the Livepeer node or protocol. Closing here, but feel free to re-open in the [tv repo](https://github.com/livepeer/tv) or in the project-proposals dashboard: https://github.com/livepeer/project-management/projects/1
