### ISSUE TITLE
Error getting LivepeerToken address: no contract code at given address

### ISSUE THREAD

**Issue by Grwflcd** [livepeer/go-livepeer#2969]
Does anyone know how to solve this problem? I'm just beginning to learn about LPT 🤣

XXX bin % livepeer \                                                              
    -network arbitrum-one-mainnet \
    -ethUrl wss://goerli.infura.io/ws/v3/XXXXX \
    -orchestrator \
    -transcoder

*--------------*---------------------------------------------------------------*
| Network      | arbitrum-one-mainnet                                          |
| Orchestrator | true                                                          |
| Transcoder   | true                                                          |
| EthUrl       | wss://goerli.infura.io/ws/v3/XXXXXXX |
*--------------*---------------------------------------------------------------*
I0228 00:34:08.926361   76139 starter.go:388] ***Livepeer is running on the arbitrum-one-mainnet network: XXXX***
I0228 00:34:10.252088   76139 accountmanager.go:80] Using Ethereum account: XXXXX
I0228 00:34:10.709012   76139 accountmanager.go:114] Unlocked ETH account: XXXXX
E0228 00:34:11.145646   76139 client.go:199] Error getting LivepeerToken address: no contract code at given address
E0228 00:34:11.145748   76139 starter.go:635] Failed to set gas info on Livepeer Ethereum Client: no contract code at given address

**Comment by leszko** [comment]
The ETH URL you're trying to use is the Goerli testnet `wss://goerli.infura.io/ws/v3/XXXXX`, you need to specify the arbitrum mainnet.
