### ISSUE TITLE
PixelMixmatch error on broadcaster node when transcoding with 0.7.3

### ISSUE THREAD

**Issue by eliteprox** [livepeer/go-livepeer#2990]
**Describe the bug**
After upgrading my transcoder nodes, I've been consistently seeing a `PixelMixmatch` error on the broadcaster side when sending any streams.

```
E0330 03:17:31.466937  273447 broadcast.go:1339] Error verifying nonce=454213449037876007 manifestID=friday2 seqNo=4 err="PixelMismatch"
I0330 03:17:31.466960  273447 broadcast.go:221] [PublicLogs] Reusing Orchestrator, reason=performance: no segments in flight, latency score of 0.224847192 < 1
I0330 03:17:31.466967  273447 broadcast.go:347] Removing orch=https://10.10.10.10:8933 from manifestID=friday2 session list
I0330 03:17:31.466971  273447 broadcast.go:348] [PublicLogs] Removing orch=https://10.10.10.10:8933 from manifestID=friday2 session list
I0330 03:17:31.466975  273447 broadcast.go:1046] No sessions available for segment
```

**To Reproduce**
1. Install CUDA 12.x from: https://developer.nvidia.com/cuda-12-1-1-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=runfile_local
2. `sudo apt-get install -y nvidia-container-toolkit`
3. `sudo nvidia-ctk runtime configure --runtime=docker`
4. Run livepeer docker image `ghcr.io/livepeer/go-livepeer/build:v0.7.3`

**Expected behavior**
Transcode without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version 0.7.3

**Additional context**
The O/T nodes do not log any errors. Rolling back to 0.7.2 fixed it. I was running CUDA 12.3 and tried downgrading to 12.1 on a test box, but that didn't help.

**Comment by leszko** [comment]
This is most probably related not the CUDA update, but to the ffmpeg update. We plan to roll back the ffmpeg and make a new go-livepeer release. I'll keep you posted and then ask you to try again.

**Comment by leszko** [comment]
Ok, the go-livepeer v0.7.4 is out. Could you check if it fixed the issue?

**Comment by eliteprox** [comment]
That fixed it, closing issue
