### ISSUE TITLE
Release 0.1.12 gives a library error on OS X

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#302]
Downloaded livepeer_darwin release and tried to run it, and got the following error. 

```
junkyard-dog:bin dob$ livepeer -testnet
dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Users/dob/bin/livepeer
  Reason: Incompatible library version: livepeer requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
Abort trap: 6
```

**Comment by j0sh** [comment]
Curious, what version of macOS was this run with?

lzma isn't listed as a direct dependency, but it's pulled in transitively as part of the Security framework [1]. This was compiled on 10.13  (High Sierra), and what's also interesting is that this error reflects a non-standard install path; was lzma pulled in via Homebrew or something?

I'll see about disabling (the auto-detected) securetransport and re-build for now.

**Comment by dob** [comment]
Just adding a note that this was debugged through gitter, but it was OS X High Sierra 10.13.3. I think we can potentially close as per the latest test binary that seems to be free of this issue?

**Comment by j0sh** [comment]
Yes, looks to be fixed with https://github.com/livepeer/go-livepeer/pull/301, thanks.
