### ISSUE TITLE
Sometimes A New Eth Address Is generated?

### ISSUE THREAD

**Issue by rayj00** [livepeer/go-livepeer#304]
From all I know about Livepeer, I assume once you generate an Eth address, it's yours forever, barring issues with the node.

So, normally I have had the same eth address for quite a long time, until recently, in which at 3 different times in the last month, a new eth address was generated when I ran ./livepeer -testnet -v 6

One time I looked at the keystore and found 3 different eth addresses with 3 separate dates. 

So here us the livepeer console:
`root@localhost:~/livepeer_linux# ./livepeer -testnet -v 6
I0220 10:40:48.993701   15503 livepeer.go:138] Monitor is set to 'true' by default.  If you want to disable it, use -monitor=false when starting Livepeer.
I0220 10:40:48.996342   15503 network_node.go:80] Created node: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 at [/ip4/127.0.0.1/tcp/15000 /ip4/23.239.31.177/tcp/15000 /ip6/::1/tcp/15000 /ip6/2600:3c00::f03c:91ff:fef9:5ee7/tcp/15000]
I0220 10:40:48.997395   15503 basic_network.go:105] Connecting to cached peer: {<peer.ID XeYaU3> [/ip4/127.0.0.1/tcp/15000 /ip4/172.31.35.77/tcp/15000 /ip4/52.15.174.204/tcp/15000 /ip6/::1/tcp/15000]}
I0220 10:40:49.215207   15503 basic_notifiee.go:34] Notifiee - Connected.  Local: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 - Remote: 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0220 10:40:49.215512   15503 basic_notifiee.go:57] Notifiee - OpenedStream: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 - 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0220 10:40:49.215728   15503 basic_notifiee.go:57] Notifiee - OpenedStream: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 - 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0220 10:40:49.215821   15503 basic_notifiee.go:57] Notifiee - OpenedStream: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 - 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0220 10:40:49.215980   15503 basic_notifiee.go:57] Notifiee - OpenedStream: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 - 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0220 10:40:49.287469   15503 basic_notifiee.go:62] Notifiee - ClosedStream: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 - 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0220 10:40:49.288635   15503 basic_notifiee.go:62] Notifiee - ClosedStream: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 - 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0220 10:40:49.288762   15503 basic_network.go:455]

Setting up protocol: /livepeer_video/0.0.1
I0220 10:40:49.288858   15503 livepeernode.go:86] Connecting to 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01 /ip4/52.15.174.204/tcp/15000
I0220 10:40:49.288956   15503 livepeer.go:240] Setting up client...
I0220 10:40:49.320803   15503 basic_notifiee.go:62] Notifiee - ClosedStream: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 - 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0220 10:40:49.322376   15503 basic_notifiee.go:62] Notifiee - ClosedStream: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 - 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0220 10:40:49.444881   15503 accountmanager.go:40] **Please create a new ETH account**
Passphrase:
Repeat passphrase:
I0220 10:41:06.803254   15503 accountmanager.go:57] Using ETH account: 0xE095d87481A0Bc5DcC68Ca5A2a70A4B27810a6d5
I0220 10:41:08.351975   15503 accountmanager.go:75] Passphrase required to unlock ETH account
Passphrase:
I0220 10:41:17.129757   15503 accountmanager.go:86] ETH account 0xE095d87481A0Bc5DcC68Ca5A2a70A4B27810a6d5 unlocked
I0220 10:41:17.130523   15503 client.go:182] Controller: 0x460e655583C1808D09445645700F4e3bF9740aC0
I0220 10:41:17.167744   15503 client.go:203] LivepeerToken: 0x124894eB716E2fF63e3fBb8EFbd6647786A150A2
I0220 10:41:17.205427   15503 client.go:224] BondingManager: 0x4Bb510AaF8acaA7879A0a4650CF21731bB8B072c
I0220 10:41:17.247633   15503 client.go:245] JobsManager: 0x64517c4779D7092A03D9323148821809Cae50194
I0220 10:41:17.285112   15503 client.go:266] RoundsManager: 0x67bf06E497Bfe200f2419B20B59DAe2deB2ECf4d
I0220 10:41:17.322188   15503 client.go:287] Minter: 0xeb4d00216FA6967f76278aAC4afEBC007fadB776
I0220 10:41:17.359934   15503 client.go:308] Verifier: 0x3224c0D3758D8b8cbf03E97005D87F0a8e09E29E
I0220 10:41:17.396810   15503 client.go:329] LivepeerTokenFaucet: 0xA402E294aE679De4Cce59032E5390c8152cB9A44
I0220 10:41:17.397119   15503 mediaserver.go:84] Transcode Job Price: 1, Transcode Job Type: [{P240p30fps16x9 600k 30 426x240 16:9} {P360p30fps16x9 1200k 30 640x360 16:9}]
I0220 10:41:17.397256   15503 lpms.go:56] HTTP Server listening on :8935
I0220 10:41:17.397434   15503 lpms.go:52] LPMS Server listening on :1935
I0220 10:46:21.610450   15503 webserver.go:492] Depositing: 1
I0220 10:46:59.953482   15503 webserver.go:877] Requesting tokens from faucet`

**Comment by rayj00** [comment]
Just checked the keystore:
root@localhost:~# cd .lpData
root@localhost:~/.lpData# ls
conn  keys.json  keystore
root@localhost:~/.lpData# ls keystore
UTC--2018-01-01T20-08-58.517741846Z--2256862563d922483c3d698e17e239344b487c86
UTC--2018-02-08T23-46-18.536141859Z--bbbf11f4aa3602c6868d91acab4112d45556d61e
UTC--2018-02-11T14-08-16.075642403Z--7d0d2de2923d25d16ccfc6792bfbb1d6af17e41f
UTC--2018-02-20T16-41-05.254075767Z--e095d87481a0bc5dcc68ca5a2a70a4b27810a6d5
root@localhost:~/.lpData#

**Comment by rayj00** [comment]
I don't know why the lines are there?

**Comment by dob** [comment]
Thanks for filing, and yes this seems like a bug in which Livepeer for some reason is ignoring the existing key file and deciding to generate a new one.

**Comment by rayj00** [comment]
Perhaps create a backup keystore file?   At least that way I can copy over the correct eth adr.

**Comment by dob** [comment]
Have we seen this happen lately? Or can we mark as closed?
