### ISSUE TITLE
Playlist lvpr.tv

### ISSUE THREAD

**Issue by llyppi** [livepeer/go-livepeer#3091]
Using https://lvpr.tv/?url=
I have many paths on my bucket/root/video1...video2/transcode
On root/...  need create playlist.m3u8, to redirect sequence list videos

So be playlist,but lvpr.tv not support  
https://lvpr.tv/?url=https://link.storjshare.io/raw/jvdxlfvsgr5xe7fk3pge5snbzzda/mybkt/public/playlist.m3u8

https://lvpr.tv/?url=https://link.storjshare.io/raw/jvdxlfvsgr5xe7fk3pge5snbzzda/mybkt/public/DJI_0050/indexFHD.m3u8
https://lvpr.tv/?url=https://link.storjshare.io/raw/jvdxlfvsgr5xe7fk3pge5snbzzda/mybkt/public/DJI_0051/indexFHD.m3u8

**Comment by thomshutt** [comment]
@llyppi is this valid HLS syntax?

**Comment by llyppi** [comment]
> @llyppi is this valid HLS syntax?

Its default m3u used all players
Link playlist.m3u8 is public to read
Maybe file is wrong syntax,i not sure
