### ISSUE TITLE
ai_ prometheus metrics produced with inconsistent `pipeline` tag

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [livepeer/go-livepeer#3185]
It's maybe not a bug but an inconvenience resulting in multiple similar tags being produced. 
* `pipeline` value produced in 
[monitor.AIProcessingError(err.Error(), pipeline, ...](https://github.com/livepeer/go-livepeer/blob/ai-video/server/ai_http.go#L368) is equal to `text-to-image`, `image-to-image`, `upscale`, `image-to-video`, `audio-to-text`, `segment-anything-2` - lowercased with `-` as a separator.
* In [submitSegmentAnything2](https://github.com/livepeer/go-livepeer/blob/ai-video/server/ai_process.go#L635-L702) it's produced as `segment anything 2` (lower case, space separated).
* [`no orchestrators available...`](https://github.com/livepeer/go-livepeer/blob/ai-video/server/ai_process.go#L1058-L1098) errors are produced using `capName` resulting in `Text to image`, `Image to image`, `Image to video`, `Upscale`, `Audio to text`, `Segment anything 2` (First letter uppercase, space separated).

And because of that when trying to filter based on `pipeline` on Grafana we get "duplicates":
![Screenshot 2024-09-27 at 15 52 02](https://github.com/user-attachments/assets/9de8482e-703b-4eee-b1f8-c7c0accf3d3c)

We need some unification.

**Comment by ad-astra-video** [comment]
This is a good find! Thank you for bringing this forward!

Could we use the `PipelineToCapability` function to make them all use the capability name?  The `PipelineToCapability` function was introduced with the `maxPricePerCapability` addition to parse the pipelines input into the json pricing input to capabilities to try and avoid another a long switch statement to manually assign the capabilities based on the text input (see handleAIRequest as an example).

Open to alternative implementations of the `PipelineToCapability` function to make it less brittle. Maybe should remove the string parsing and just put in a switch statement in `PipelineToCapability` to assign the capabilities more directly? Other ideas welcomed here! An example of the brittle nature of this function is I provided incorrect advice to rename the `Large Language Model` capability description added with LLMs to `Large language model` in review of that PR.  I think it should instead be `Llm` to correctly find the capability for the `llm` pipeline in the `PipelineToCapability` function.

**Comment by pwilczynskiclearcode** [comment]
I already posted a [PR](https://github.com/livepeer/go-livepeer/pull/3191/files) trying to transform capability to pipeline name (pipeline names aren't defined globally by any `const`).
The prometheus tag/label is called [`pipeline`](https://github.com/livepeer/go-livepeer/blob/ai-video/monitor/census.go#L273) so I wanted to produce it in "pipeline" format, not capability.

**Comment by rickstaa** [comment]
This was fixed when https://github.com/livepeer/go-livepeer/pull/3191/files was merged thanks @pwilczynskiclearcode 🙏🏻.
