### ISSUE TITLE
Error with socket connection to remote ETH node due to too many open files

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#326]
Related to basicnet peerCache error with too many open files

```
E0308 01:08:36.309845   27924 eventmonitor.go:238] Error with header callback: EOF
E0308 01:08:36.309867   27924 eventmonitor.go:246] Error with header subscription: EOF
I0308 01:08:36.309874   27924 eventmonitor.go:172] Trying to resubscribe for NewRound
E0308 01:08:46.313355   27924 eventmonitor.go:176] dial tcp: lookup rinkeby.infura.io on 172.31.0.2:53: dial udp 172.31.0.2:53: socket: too many open files
E0308 01:09:29.967740   27924 peerCache.go:79] Error writing connection to file system: open /home/ubuntu/.lpData/conn: too many open files
```

**Comment by ericxtang** [comment]
I'm guessing this was on a transcoder node?  If that's the case, I think it's related to IPFS setting the files to 2048 by default.  We should raise that limit manually by changing limits.conf.

See this [thread](https://github.com/ipfs/go-ipfs/issues/3792) for more details.

**Comment by ericxtang** [comment]
Added instruction to https://github.com/livepeer/docs/blob/master/docs/source/transcoding.md#faq
