### ISSUE TITLE
Livepeer fails to process streams with <4 frames-per-second

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#328]
I've been testing Livepeer nodes by streaming RTMP content with different FPS.

For frame-rates between 4 and 29.97, Livepeer node functions as normal.

However, at lower frame-rates, the following behaviour was observed:

1. stream seems to take much longer to become visible

2. while the initially just showing a blank dark grey screen (see below) and *with audio content*

For frame rates 3 and below, the stream fails with a Segmenter Timeout:

```
E0312 23:12:51.876989    7232 lpms.go:138] Error segmenting stream: SegmenterTimeout
I0312 23:12:51.877042    7232 basic_broadcaster.go:49] Broadcasting finish
E0312 23:12:51.877057    7232 basic_broadcaster.go:51] Error broadcasting finish: ErrOutStream
```

Blank dark grey screen:

![image](https://user-images.githubusercontent.com/2212651/37312080-eebe2e34-2649-11e8-86b3-6db54c0fcd57.png)

**Comment by j0sh** [comment]
Most likely related to https://github.com/livepeer/lpms/issues/60

**Comment by ericxtang** [comment]
Closing because it's an outdated report.
