### ISSUE TITLE
ERROR: logging before flag.Parse: E0315 17:09:41.474184    2033 wizard_broadcast.go:168] Error reading manifest ID: <nil>

### ISSUE THREAD

**Issue by devsullo** [livepeer/go-livepeer#333]
I have LPT Balance, ETH Balance and running: Broadcast video in CLI which returns this error: 

**ERROR: logging before flag.Parse: E0315 17:09:41.474184    2033 wizard_broadcast.go:168] Error reading manifest ID: <nil>**

Full log: 

+-----------+
|NODE STATS|
+-----------+
*-----------------------------*----------------------------------------------------------------------*
|                     Node ID | 1220ca7c7aa7044b8b625913ce6ba84d813e8829a73cf82525a95c54205eed94252f |
*-----------------------------*----------------------------------------------------------------------*
|                   Node Addr |                        /ip6/::1/tcp/15000, /ip4/127.0.0.1/tcp/15000, |
|                             |                                          /ip4/192.168.8.69/tcp/15000 |
*-----------------------------*----------------------------------------------------------------------*
|                   RTMP Port |                                                                 1935 |
*-----------------------------*----------------------------------------------------------------------*
|                   HTTP Port |                                                                 8935 |
*-----------------------------*----------------------------------------------------------------------*
|          Controller Address |                           0x37dC71366Ec655093b9930bc816E16e6b587F968 |
*-----------------------------*----------------------------------------------------------------------*
|       LivepeerToken Address |                           0x24f56eF2fED379421BEE64Ecafc2bC744f72522b |
*-----------------------------*----------------------------------------------------------------------*
| LivepeerTokenFaucet Address |                           0xD69A2eC8f2F83267CE82A6d01837045BaE0EB9Bc |
*-----------------------------*----------------------------------------------------------------------*
|                 ETH Account |                           0xdC3c9189ce95c70aD761Ffcc0D810087B4302985 |
*-----------------------------*----------------------------------------------------------------------*
|                 LPT Balance |                                                 10000000000000000000 |
*-----------------------------*----------------------------------------------------------------------*
|                 ETH Balance |                                                      415351999900000 |
*-----------------------------*----------------------------------------------------------------------*
+-----------------+
|BROADCASTER STATS|
+-----------------+
*-------------------------------*-------------------------------*
|                       Deposit |                        100000 |
*-------------------------------*-------------------------------*
|   Broadcast Price Per Segment |                             1 |
*-------------------------------*-------------------------------*
| Broadcast Transcoding Options | P240p30fps16x9,P360p30fps16x9 |
*-------------------------------*-------------------------------*
+---------------+
|DELEGATOR STATS|
+---------------+
*------------------*--------------------------------------------*
|           Status |                                   Unbonded |
*------------------*--------------------------------------------*
|            Stake |                                          0 |
*------------------*--------------------------------------------*
|   Collected Fees |                                          0 |
*------------------*--------------------------------------------*
|    Pending Stake |                                          0 |
*------------------*--------------------------------------------*
|     Pending Fees |                                          0 |
*------------------*--------------------------------------------*
|  Delegated Stake |                                          0 |
*------------------*--------------------------------------------*
| Delegate Address | 0x0000000000000000000000000000000000000000 |
*------------------*--------------------------------------------*
| Last Claim Round |                                          0 |
*------------------*--------------------------------------------*
|      Start Round |                                          0 |
*------------------*--------------------------------------------*
|   Withdraw Round |                                          0 |
*------------------*--------------------------------------------*
CURRENT ROUND: 38732

What would you like to do? (default = stats)
 1. Get node status
 2. View protocol parameters
 3. Initialize round
 4. Bond
 5. Unbond
 6. Withdraw stake (LPT)
 7. Withdraw fees (ETH)
 8. Claim rewards and fees
 9. Transfer LPT
 10. Get test LPT
 11. Get test ETH
 12. List registered transcoders
 13. Deposit (ETH)
 14. Withdraw deposit (ETH)
 15. Broadcast video
 16. Stream video
 17. Set broadcast config
> 15

Current RTMP setting: http://localhost:1935/streams
Current HTTP setting: http://localhost:8935/streams
Keep it? (Y/n) > y
Now broadcasting - 
ERROR: logging before flag.Parse: E0315 17:09:41.474184    2033 wizard_broadcast.go:168] Error reading manifest ID: <nil>

**Comment by ericxtang** [comment]
@devsullo Thanks for testing out the node. I think it's either your local `ffmpeg` setup, or something with the Livepeer media server. Can you broadcast with OBS? http://livepeer.readthedocs.io/en/latest/broadcasting.html#broadcasting-using-obs

**Comment by devsullo** [comment]
Broadcasting with OBS is okay. So it's `ffmpeg` setup?

**Comment by ericxtang** [comment]
Yeah most likely.

**Comment by ericxtang** [comment]
Closing this issue because we removed the CLI ffmpeg broadcast option.  Currently OBS is the best option to broadcast into Livepeer.
