### ISSUE TITLE
Should we stop transcoding when the broadcaster runs out of deposit?

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#335]
Currently, the node keeps doing the transcoding even when the broadcaster runs out of deposit.  This can be used by the broadcaster to "get free work done"

**Comment by j0sh** [comment]
Yes.

Should we also ensure that the broadcaster has enough deposited to cover the period the job is supposed to be active, at least within a reasonable range? Say for the next 30 minutes worth of claims, or so.

This wouldn't prevent broadcasters from creating a job then transferring money out. But if we can monitor blockchain events for a specific account (the broadcaster's) then the transcoder could detect whether the deposit falls under a particular threshold, and halt accordingly.

**Comment by dob** [comment]
Yah, I agree that's the right implementation. I could see the threshold
potentially being a flag if they'd like to override the default. Eventually
we could make things like this, automatic price adjustments, and other
logic extensible via custom "strategies" for which they provide their own
implemenation.

**Comment by j0sh** [comment]
The transcoder now keeps track of the broadcaster's remaining balance and will reject the segment if the balance is too low.
