### ISSUE TITLE
Handle Chain Reorg For Transcoder

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#336]
An event in the log can be removed from a chain reorg - in which case, a new job transaction can be invalid (and therefore the event is removed).

The Log struct has a `Removed` field.  We should check that and stop a transcoding job if the event is removed.

**Comment by j0sh** [comment]
Is an event emitted for this, or do we have to rescan the log?

**Comment by ericxtang** [comment]
Event is emitted with `Removed=true` - in which case we'll revert the action.  I think the only thing we need to worry about now is NewJob - have the transcoder stop the job if it's removed.  (NewBlock and NewRound seem less important).

We should probably also resubmit the Job transaction for the broadcaster.  But we can capture that in another ticket.

**Comment by dob** [comment]
Yah we've long known that chain re-orgs are going to screw things up a bit.
My initial thoughts are that, as Eric suggested, if a current transcoder
sees this removed=true event then they coudl stop transcoding.

But then the job transaction presumably gets included in a new block, and
when the newly assigned transcoder sees this, they woudl automatically pick
up the job. Hopefully there haven't been any intermediate actions before
the reorg that would lead to a slashing condition. I can't think of any.
But for example if a transcoder tries to claim work on a job, and they are
not actually assigned to it, I think we just throw.

**Comment by dob** [comment]
If the broadcaster has constructured their ABS manifest already from a
transcode response from the original transcoder, they'd also need to be
able to update the manifest after receiving a second response from the new
transcoder.

FWIW, we'll eventually need to smoothly handle this, but I also don't think
it's our highest prioirity issues necessarily.

**Comment by ericxtang** [comment]
Closing because it's an outdated report
