### ISSUE TITLE
Player is playing old segments during stream

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#337]
I am streaming into ingest1 and I just experienced the following strange behaviour:

1. Load the stream to start viewing content

2. Watch content from 17hr 51mins into the stream

3. This freezes after watching approximately 10 seconds of content

4. I refresh the page and it plays the same 10 seconds of content. I repeat this several times, and it plays the same 10 seconds of content again each time. I think it's broken.

5. But... I wait some time, refresh the player again, and now it has moved on to 17hrs 58mins. At time of writing, the stream is still going at 18hrs 08mins.

There were no additional transactions generated during this time on the Blockchain, implying that there was no automatic reconnection.

Perhaps there is something about the configuration of the CDN and the player?

**Comment by ericxtang** [comment]
Is this still happening?  We changed the CDN settings - hopefully this is fixed now.

**Comment by chrishobcroft** [comment]
I haven't seen this again.
