### ISSUE TITLE
possible scenario: long GOPs cheat and unfair segment weight

### ISSUE THREAD

**Issue by f1l1b0x** [livepeer/go-livepeer#339]
possible scenario: long GOPs cheat and unfair segment weight

**long GOPs cheat:**
since the price in livepeer is per segment it gives an incentive to "cheat" by sending in a stream that was encoded with a keyframe frequency that is longer than the default segment length.

It will result ffmpeg to create chunks that are longer as we expect as it only can create the start of chunks at keyframe positions.

In my tests sending in streams with various gop sizes created playlist with variating target durations in the m3u8 lists and also actual segment/chunk length
#EXT-X-TARGETDURATION:9
#EXT-X-TARGETDURATION:6
#EXTINF:5.016,
#EXTINF:8.283
etc...

but they all cost the same if you process them.

**unfair segment weight**

The current price per segment is kind of unfair as 1080p60 segment processing costs are the same as for 360p30 segments. I call this unfair segment weight as the needed resources to encode the 1080p stream compared to 360p is about 9 times more CPU heavy at p30 and 18 times for p60

The unclear segment length and the unfair segment weight are both unpredictable factors in a resource consumption calculation.

This is going to make it really hard to do the following:

- estimate what income you will generate with you transcoder 
- estimate what transcoding job fits in which transcoder 
- advance transcoding with variable gops 
- do benchmarks
- fair payment for how heavy the transcoding job was 

**possible solution** (for both the gop cheat and the unfair segment weight):

do not offer a fixed price per segment but do a more detailed calculation to estimate the real resources needed for a transcoding job.

**framesize(width*height) * framerate(frames per second) * chunklength(seconds) = processing estimation score (PES)**

take a 4 second 1080p60 chunk:

1920*1080 * 60 * 4
= 497.664.000 PES

against a 2 second chunk with 360p30

640*360 * 30 * 2
= 13.824.000 PES

The score (PES) would be always pretty much linear to the CPU demands for encoding if calculated like the above and would not be "cheatable" as easy and way more fair for transcoder participators.
Since it directly relates to cpu (and later gpu) usage benchmarking is getting easier and you will know if a transcoder can handle a job before it applies for it. 
Miners will also be able to predict what income they can generate which usually is a must have.

the possibility for diversing the chunklength also allows better quality encoding features in the future but we would need a economic system that does not rely on fixed gop structures/chunklength to even begin with. 

How PES could be used instead of segment counts and its possible network effect:

The PES structure can be used to identify transcoders that are able to process your request independent from knowledge about the actual transcoding task details.

If a broadcaster would want to do a 3 quality encoding his program would calculate his PES across all encodings and per second:

720p30 = (1280 * 720 * 30) = 27648000 PES
360p30 = (640 * 360 * 30) = 6912000 PES
255p30 = (512 * 255 * 30) = 3916800 PES

sums to = 38476800 total PES

With it, it should search for transcoders that advertise more PES resources and only choose these to do the processing to avoid transcoders that do not have the capacity.

transcoders could take multiple transcoding jobs without risking overwhelming the cpu since a benchmark allows them to advertise their total PES and they can shuffle in multiple encoding jobs as long as they do not exceed their total PES limit. 

The price can also depend on the "PES per second" algoritm since then it does not matter how long segments are or what their weight is, it is going to be fair and hard to cheat. 

Stakers would direct their token to transcoders that advertise high PES values since those are the servers that will perform the best for the customer´s livestream. Currently stakers have no idea how well transcoders perform and without a PES value they can not automate delagation/bonding as well. 

PES performance measured over time can also help identify fraudulent or bad-performing participators programmatically.

**Comment by nicolasburtey** [comment]
Excellent point.

Also, I believe are important to take into the calculation:
- codec, obviously. 
- profile. a high profile is a lot more CPU intensive per pixel than a baseline profile, as it typically CABAC and B frames for instances. Maybe this is not so common in live encoding though.
- preset. So far the broadcast can't choose whether it wants to use x264 presets of "ultrafast" or "superfast" or any other method, but this is highly correlated to CPU usage. It's also related to the profile.

**Comment by f1l1b0x** [comment]
I  agree about the complexity/preset of the encoding and decoding also plays a role that shouldn't be underestimated.

A transcoder who would want to encode a 360p30 version of a 2160p60 would still have to be able to decode 2160p60

resource management ideally works without human intervention so we have to invent ways how broadcaster jobs find matching transcoders capacities

**Comment by nicolasburtey** [comment]
how about :

processing estimation score (PES) = 
framesize(width*height) * 
framerate(frames per second) * 
chunklength(seconds) *
bitrate(kbps) * bitrateRatio *
presetIndex

whereas:
presetIndex = 1 if preset==ultrafast
presetIndex = 2.1 if preset==superfast
presetIndex = 3.6 if preset==veryfast
presetIndex = 6.4 if preset==faster
presetIndex = 12.7 if preset==fast
presetIndex = 16.7 if preset==medium
presetIndex = 37.6 if preset==slow

The presetIndex factors are just derived from http://www.videoquality.pl/preset-settings-x264-quality-compression-speed-test/
bitrateRatio is a bit more complex to calculate as it's not linear, as it can be seen here: https://trac.ffmpeg.org/wiki/Encode/H.264

Also, I guess the preset choice would by default automatically determine the profile. 

Those calculations are related to x264, but other encoders would have other profile in term of CPU/Watt usage. I don't know to what extent it would generalize.

**Comment by nicolasburtey** [comment]
Very quick solver calculation leads to a formula of ln(1.6941+0.00013*bitrate) for the bitrate.
Calculation is here: www.transfernow.net/764fk7w7dsgr
It might sure be overfitted with such a little dataset!

**Comment by f1l1b0x** [comment]
Your calculations for the presets difficulty factor seem to be right but I guess benchmarks will tell.

The Bitrate should get its own estimation score (BES?) since it can variate too much within the same encoding parameters and it also does not really add to CPU usage if you use more or less for an encoding.

A user might choose to create a ABR set that has multiple 1080p and 720p versions with different bitrates like

1080p30@8000kbit
1080p30@6400kbit
1080p30@4800kbit
720p30@3600kbit
720p30@2600kbit
720p30@1800kbits
480p30@1200kbits
360p30@800 Kbits 
255p30@512kbits


The cpu usage on the different 1080p encodings would be pretty much the same. so they would result in the same PES for each encoding.
The bitrate variates a lot more and comes also from a different resource bucket which isnt the CPU but the network connection.

All qualities above together round to about 30.000kbits that are needed for the upload after transcoding. You need 50% bandwidth overhead for live transmission cause of tcp congestion, so a node would have to provide/reserve about 45.000kbit upload capacities for this transcoding job.

If the bitrate would now be part of the PES it would be hard to manage it across mutliple transcoder instances and hard to know by the PES values if there is enough bandwidth at the transcoder.

If you make it a different value a  BandwidthEstimationScore it would work

a transcoder would have to fullfil both demands for the PES and the BES seperately 

if you have the cpu but not the bandwidth it doesnt help or vice versa :)

thanks for the conversation this is really exciting stuff cant wait for doug and eric to comment

**Comment by dob** [comment]
Yah this is a perfect start to the design for what we've been referring to as "gas accounting", modeled off of Ethereum's gas accounting. PES and BES seem like great encapsulations of the video specific features that will factor into this accounting.

See the caption below the chart which mentions "gas" in this Livepeer Whitepaper section: https://github.com/livepeer/wiki/blob/master/WHITEPAPER.md#transcoder-transaction

See also the "Tributary Phase" which is the next scheduled protocol update https://medium.com/livepeer-blog/livepeer-network-phases-b196ab42264b. (This post is in the right spirit, but is a little .outdated, so don't take the full roadmap as written in stone).

As far as where to have this discussion, here is fine for now. Now that the protocol is frozen for mainnet deployment, we're considering a Livepeer Improvement Proposals (LIPs) process similar to Ethereum Improvment Proposals (EIPs), where potential protocol updates are designed, proposed, debated, reviewed, and then eventually merged if they are green-lighted for implementation. I would see this as being a definite candidate for implementation as soon as we get the design right, as the system really isn't fairly priced without it :)

**Comment by j0sh** [comment]
Great start. One thing other thing to take into consideration: encoders are not fungible for certain classes of users. For example, professional broadcasters would prefer to pay more for a x264-encoded stream, while others would be okay with a lower quality NVENC stream, all other basic settings being the same.

While the mechanics of specifying (or excluding) transcoders could be left to a separate negotiation step, it's useful to decouple the concept of 'gas accounting' from the actual costs of that gas. Each transcoder might have different ways to price each unit of work.

Eventually we should be able to configure audio (or the lack thereof), and other video codecs (HEVC? VP9? AV1?), each with their own accounting particulars.

**Comment by ericxtang** [comment]
This should be addressed by per-pixel accounting.  Let's close?

**Comment by yondonfu** [comment]
Perhaps we should keep this open until pixel based accounting details are finalized?

**Comment by yondonfu** [comment]
This should largely be addressed by pixel based accounting. That feature will need some more improvements including considering other factors such as the codec used which can be tracked separately.
