### ISSUE TITLE
Get Livepeer and restream.io working together

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#348]
Today I have been experimenting with restream.io, which is a service to allow you to stream to multiple different services at the same time.

My ambition was to be able to stream to Livepeer as well as YouTube / Facebook etc. to be able to help people start to migrate their streaming away from YouTube / Facebook and onto Livepeer, using restream.io.

Also, I will be speaking at an event in Amsterdam on Wednesday 4 April - they will be livestreaming onto YouTube, and I would like to try to get it livestreamed also on livepeer.tv

The result of the experiments are:

1. Configuring restream.io to stream to YouTube worked seamlessly - a simple case of allowing restream to log in to YouTube and granting rights to manage the account.

2. Configuring a "custom streaming server" required subscription to a paid service ($14.99 / month), which I was kindly able to get a free trial on to test and debug and configure, after talking to Randy (@Exuviax) on their support team.

3. I was able to configure ingest1 as a streaming server to be the same as the settings I use in OBS.

4. When I started streaming into restream.io, I could see that they were successfully connecting to ingest1, as it created a transaction on rinkeby: https://rinkeby.etherscan.io/address/0x0ddb225031ccb58ff42866f82d907f7766899014

5. However, the stream didn't show up on http://media.livepeer.org/channels/0x0dDB225031cCB58fF42866f82D907F7766899014

6. I tested again using OBS to connect directly to Livepeer, and this _**did**_ work (exactly the same RTMP settings).

7. restream.io's developers had a look at the live stream on their system, and as far as they were concerned, they were correctly sending RTMP into ingest1.

8. They suggested talking to Livepeer's developers to see if they can see anything awry on the stream coming from restream.

Please can I request some help from someone in the core dev team to help debug this?

@ericxtang or @j0sh or @dob perhaps?

**Comment by chrishobcroft** [comment]
Specific feedback provided by @Exuviax is:

> Our developers have checked on our end and it seems that we are sending the stream out to Livepeers servers using the settings you provided. Maybe they would be able to provide more information on what the cause may be.

**Comment by Bradymck** [comment]
Would love to know more about this as well. I use Restream quite a bit.

**Comment by chrishobcroft** [comment]
OK, further recent experiments on this show that restream is able to successfully stream to livepeer.

![image](https://user-images.githubusercontent.com/2212651/45554046-bdafe980-b835-11e8-99ad-80f0d74d063b.png)

This test was performed using OBS to stream to restream, and then configuring restream to stream to livepeer (ingest2).

**Comment by chrishobcroft** [comment]
Proof-of-restream:

![image](https://user-images.githubusercontent.com/2212651/45562873-ee028280-b84b-11e8-8ee2-e429bd305c1e.png)

Streaming from [__OBS__](https://obsproject.com) on __Ubuntu__ at `2560x1440`, `10fps`, `1000kbps` into [__restream.io__](https://restream.io/)

[__restream.io__](https://restream.io/) restreaming content to the following livestreaming infrastructure platforms:

- [__Livepeer (open-source infrastructure)__](http://livepeer.org) - being played at [Livepeer 3](https://media.livepeer.org/channels/0xA14f8740d6aF9E4Ad1a37b74F94D733CAF601c1E), streaming into the securely hosted ingest node provided by @ericxtang @j0sh @yondonfu @dob 

and simultaneously to:

- [_YouTube (closed-source infrastructure)_](www.youtube.com) - via [Livepeer TV's YouTube Channel](https://www.youtube.com/watch?v=s8-MXBPMyGo)

This provides a way for broadcasters to stream to Livepeer's open-source video infrastructure, and also to a closed-source alternative.

This should be interesting for @Souptacular and @mauricevg for `#devcon4`. I recommend you connect with @Exuviax from [__restream.io__](https://restream.io/). I don't believe they accept payment in Ethereum though - at least, not _yet_.

Also cc: @Bradymck - it's working!

And bravo to the Livepeer Core Devs for the recent major upgrade - the [Tributary Release](https://medium.com/livepeer-blog/livepeers-tributary-release-335c9270f9da), which is beginning to feel more and more robust and comfortable, for a broadcaster of content looking to test alternatives to YouTube.

Looking forward to seeing what the future holds for Livepeer.

@f1l1b0x @RaffiSapire @Randy1Burrell @darkdarkdragon @adamsoffer @leos @jozanza @blake41

**Comment by Bradymck** [comment]
Oh man, thanks for the ping! This is awesome!
