### ISSUE TITLE
Password management

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#35]
Need a better way to handle the eth password.  Take a look at unlock account in Geth.

**Comment by ericxtang** [comment]
Proposed solution:
* If the node is started in on-chain mode, check the ethPassword flag when launching the node
* If ethPassword is not set, ask the user to type in the password when starting a node
* If the password is incorrect, the node launch fails
* The account is unlocked indefinitely within the context of the Livepeer node

This means the user always has to enter a password in on-chain mode, even if it's an empty string.

**Comment by yondonfu** [comment]
Closed by #249
