### ISSUE TITLE
HLS chunklist show only a single ts file

### ISSUE THREAD

**Issue by f1l1b0x** [livepeer/go-livepeer#361]
Following the HLS specs https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-8

Currently in a livepeer chunklists I always only find a single .ts file instead of the default of 3 .ts files as in the specs. This forces the player to operate in a too small time window and timing issues with propagation times become bigger. 

Currently:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:649
#EXT-X-TARGETDURATION:4
#EXTINF:3.960,
122024e79da23598727044784476421f255c248acd6f4a968dfc14d006dd43b5eac843e607143ccac33365bc3d5fbca7b0946fa9418591048175497133c2de769c51P240p30fps16x9_649.ts

As a solution make the number of segments kept in a chunklist a parameter I can set. (default 3)

wanted:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:647
#EXT-X-TARGETDURATION:4
#EXTINF:3.960,
122024e79da23598727044784476421f255c248acd6f4a968dfc14d006dd43b5eac843e607143ccac33365bc3d5fbca7b0946fa9418591048175497133c2de769c51P240p30fps16x9_647.ts
#EXTINF:3.960,
122024e79da23598727044784476421f255c248acd6f4a968dfc14d006dd43b5eac843e607143ccac33365bc3d5fbca7b0946fa9418591048175497133c2de769c51P240p30fps16x9_648.ts
#EXTINF:3.960,
122024e79da23598727044784476421f255c248acd6f4a968dfc14d006dd43b5eac843e607143ccac33365bc3d5fbca7b0946fa9418591048175497133c2de769c51P240p30fps16x9_649.ts

**Comment by ericxtang** [comment]
@f1l1b0x currently, we make the stream available as soon as the gateway node receives a single segment.  As more segments arrive, we keep up to 10 segments in the playlist.

Of course we can enforce there to always be 3 segments on the gateway. This means we will wait for longer during the initial buffering, and not keep as many segments as we currently do.  Is this something that we should do?

**Comment by f1l1b0x** [comment]
Yes, I think most of the stalls might be timing issues related and more segments just mean more time to catch up as with as single chunk in the chunklists. In my tests I never saw more than a single ts file in the m3u8, please let me know if that is not a default state

**Comment by ericxtang** [comment]
Not sure if the HLS standard specifies the number of segments per video. Since the node doesn't have the behavior of "always containing a single segment", should we close this issue?

**Comment by ericxtang** [comment]
Closing because it's an outdated report
