### ISSUE TITLE
Interim Solution To Scale p2p Network

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#362]
We originally wanted to scale the p2p network by [changing the networking protocol](https://github.com/livepeer/go-livepeer-basicnet/issues/29).  However, because of the libp2p compatibility issue, we are unable to merge the change in 'basicnet'.  In preparation to the network launch, it'll be nice to have an interim solution to at least provide a little boost to the scalability to our p2p network.

My simple proposal is the following:
* Have multiple bootnodes (I propose 5)
* When a transcoding node starts, it connects to all of the bootnodes
* When a gateway node starts, it connects to all of the bootnodes
* When a broadcasting node starts, it connects to the bootnode that has the closest NodeID to itself

Under the current networking protocol, when a `transcoder` gets a new job, it will send the `Sub` request to the neighbor node with the closest ID to the `StreamID`.  Under the proposed network formation, as long as the connections are successful, we guarantee the routing from `transcoder` to `broadcaster` through the `bootnode`.

The nice thing about this proposal is that it requires very little code change.  Of course it doesn't scale infinitely, but it props up the network for the very short term until we get to a more scalable architecture.

**Comment by f1l1b0x** [comment]
I am not a expert in network topology but the recent scaling debate between BTC(LN) and BCH brought up some discussions that I find quite plausible.

https://en.wikipedia.org/wiki/Small-world_network 

while a meshed network will work, it might still leave room for unoptimized pathfinding of a file in a network. A small world network would make sure not only to be connected to the neighbors (usually neighbors are determined based on relative latency.) but also to more distant nodes that have a higher chance on having a different state than your neighbors.

Your bootnodes concept seem to be quite linear with the hub-model in the small world networks,  correct?

**Comment by ericxtang** [comment]
Merged
