### ISSUE TITLE
Network Upgradability Proposal

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#367]
The p2p networking protocol for Livepeer has consistently gone through changes in the past 12 months, and will likely continue to change after launch.  It's important for us to be able to upgrade the protocol without breaking backward compatibility.  What we want:

* For nodes to be backward compatible
* To be able to move fast with our software releases
* Satisfy the following examples.  Assume `N1` contains networking protocol v1, `N2` and `N3` contains v1+v2
    * N1 should be able to communicate with N2 via v1
    * N2 should be able to communicate with N3 via v2

To achieve this, we need to:

* Lock down the current `ProtocolID` as v0.0.1 (described in `basic_network.go → Protocol`). This means no more changes to this version.
* Keep a record of `map[NodeID]ProtocolID`
* For each new connection, we exchange a capability list.
    * If there is an overlap, pick the highest version and put into the map
    * If no overlap, terminate the connection.  If this is in a node startup sequence, report the error and terminate the node.
* `GetOutStream` looks into the map to determine the protocol version for the new libp2p stream.
* The implementation details of the new protocol is undetermined - but we will likely have some kind of triage logic for methods like `SendTranscoderResponse`, `UpdateMasterPlaylist`, etc.

The only change that needs to happen before the launch is the capability exchange. Everything else can wait because nodes that can speak multiple versions can always talk with nodes that can only speak a single version.

**Comment by j0sh** [comment]
As long as the `ProtocolID` follows a predictably increasing sequence, and we specify that future versions are compatible with earlier versions, then I think we can avoid the capability exchange; all we need is the protocol ID during stream establishment (which I believe is sent out already?). From there the node that receives the stream can match up based on `min(my_protocol, their_protocol)` .

We would have to add another message that replies with the minimum protocol version, or we could simplify and enforce that `my_protocol >= their_protocol` on the *initial connection*. This would also encourage bootnodes, relays, etc to be on the latest version of a protocol. Subscribers could lag behind.

We will have to be very, very careful about code reuse / sharing if supporting multiple versions of a protocol, and take care that semantic changes to newer versions don't inadvertently "trickle down" and break older clients.

Maybe we should make a distinction between backwards compatible protocol changes which require a version bump, and changes that break protocol compatibility entirely (eg, a network hardfork). Hardforks would be needed if the network evolves to support a capability that can't be expressed through the old protocol. Not sure if we should make such breakage explicit, eg with a semver numbering scheme, or via more "social" means. Similar to Bitcoin's: "at round X, we'll enable a feature; if you aren't at least on protocol version Y by then, you'll be left with a broken client."

**Comment by ericxtang** [comment]
@j0sh ok - I think this touches on the issue of whether we want support different versions of protocols talking to each other.  My initial reaction says no, because it's just easier to think about versions in that way.  It may lead to more duplication in code, but I'd rather do that than having to reason about multiple versions of the protocol talking to each other.

Currently in libp2p, the `protocol.ID` is simply a unique string (I don't think it comes with version comparison out of the box).  So we'd have to build custom code to make the comparison work (haven't done the research to learn how to do that).

Any reason you'd want to avoid the capability exchange?

**Comment by j0sh** [comment]
> whether we want support different versions of protocols talking to each other

Don't think it's a good idea either.

>  in libp2p, the protocol.ID is simply a unique string (I don't think it comes with version comparison out of the box)

We could cast "0.1" to a float and do the comparison that way? Or split / parse as needed, see semver. Doesn't really matter as long as there's a number in a consistent place somewhere.

> Any reason you'd want to avoid the capability exchange?

That method of versioning implies we might have a "branchy" evolution of the protocol, with the exchange being akin to selecting common feature flags. That seems unwieldy. With a linear development progression (which we currently practice) and a backwards compatibility rule for official clients, capability exchange is also unnecessary. We do still need a reply/ack containing `min(my_protocol, their_protocol)` if we choose to allow `my_protocol < their_protocol`. The reply is also where we can signal an incompatible protocol.

We can engage in capability negotiation for specific features within the protocol (eg, transcoding specifications) but that should't be baked into the protocol version itself IMO.

**Comment by ericxtang** [comment]
Ahh I see what you mean.  Just did some more digging in libp2p - seems like there is a native implementation about this.

https://github.com/libp2p/go-libp2p-host/blob/acf01b322989cf731f66ce70b1ed7c41fe007798/match.go#L34

An example can be found here:
https://github.com/libp2p/go-libp2p/blob/master/p2p/host/basic/basic_host_test.go#L112

Basically, you can have a libp2p stream that speaks multiple protocol versions, and set a `MultistreamSemverMatcher`.  As long as the major version is equal and the minor version is >= other client, the connection succeeds.

This seems like a good enough solution for now.  Now we'll have to think about what it means to upgrade major versions that breaks backward compatibility.  Bitcoin-style hardfork works.  For example - we can do a switch at a specific Eth blocknumber.  If that's the case, I don't think we need to make any changes at this point.

**Comment by j0sh** [comment]
> As long as the major version is equal and the minor version is >= other client, the connection succeeds.

Cool. Right now, it doesn't seem like there is explicit feedback to the connecting client that there's a protocol version mismatch; should we add that in? https://github.com/libp2p/go-libp2p/blob/master/p2p/host/basic/basic_host_test.go#L173-L190

> Now we'll have to think about what it means to upgrade major versions that breaks backward compatibility. Bitcoin-style hardfork works.

Yes, Bitcoin style hardfork works, and you're right no need for changes at this point.

Semver doesn't really map cleanly to Bitcoin style hardforks but it doesn't really matter since it's just a convention. Normally you would have to use the same major version forever (otherwise how to phase in changes?), but looking at the libp2p tests, we can pass in multiple versions of a protocol -- which is actually nice, we can add a new major version along the old version, and eventually drop old versions completely. Can't do that by simply checking the minor version alone.
