### ISSUE TITLE
ClaimEarnings doesn't complete for large ranges

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#368]
This might be more of an issue in devenv where rounds go by quickly.

Suppose we have to claim over an large range of rounds, say 10,000+. We do this from the CLI. A few things happen:

* When a transcoder initializes a new round, checking the tx for the in-progress claim seems to fail. Not sure why, and **this might be the real problem here**.

```
I0420 00:25:04.936664   11974 client.go:462] Claimed rewards and fees from round 11947 through 11967
I0420 00:25:06.017730   11974 roundservice.go:95] New round - preparing to initialize round to join active set
E0420 00:25:08.941745   11974 client.go:458] Unable to check tx for round 11987; tx 0xbd0ffd9a7ac0a2af0dd675119d8b9fb41b668f18940d2ca1b13088a0b625b2d5 failed
I0420 00:25:10.020527   11974 roundservice.go:126] Initialized round 26080
I0420 00:25:14.014364   11974 rewardservice.go:94] Called reward for round 26080 - 0 LPTU rewards minted
I0420 00:25:26.958358   11974 client.go:462] Claimed rewards and fees from round 11967 through 11987
```

* After each failure, the retry counter [here](https://github.com/livepeer/go-livepeer/blob/master/server/webserver.go#L497) is incremented.

* After maxing out the retries, the whole process stops and we have to manually restart the claiming process from the CLI.

**Comment by ericxtang** [comment]
Yeah I think it's because of the new rounds - we can't claim when the round is uninitialized, but the round is ALWAYS uninitialized during the first block of the round.  So if there is a claim transaction in that first block, it'll fail...

**Comment by j0sh** [comment]
Shouldn't we still be able to claim for previous rounds even if the current round is uninitialized?

**Comment by yondonfu** [comment]
At the moment you can't claim earnings for previous rounds if the current round is not initialized. Tracking fix here: https://github.com/livepeer/protocol/issues/215

**Comment by ericxtang** [comment]
Talked with @yondonfu offline about this - filed an issue.  https://github.com/livepeer/protocol/issues/216

**Comment by j0sh** [comment]
Closing since we don't have any more earnings to claim with Streamflow.
