### ISSUE TITLE
Prevent creating an on-chain job when the round is not initialized

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#379]
When a round has not been initialized, the on-chain data structure managing the list of active transcoders for a new round will be empty. If a transcoder node receives a new job event at this point it will check if it is assigned to the job: https://github.com/livepeer/go-livepeer/blob/master/eth/eventservices/jobservice.go#L67 However, the returned assigned address will be the null address because the on-chain list of active transcoders will be empty. As a result, the transcoder node will consider itself as not assigned to the job and skip it. The implication here is that any job created in a new round before it is initialized will never be picked up by a transcoder node.

Since the JobsManager contract currently allows new jobs to be created even when a round is not initialized, another fix for this would be for the node to check if the current round is initialized before allowing a new job to be created by a broadcaster.

**Comment by j0sh** [comment]
Fixed in https://github.com/livepeer/go-livepeer/pull/380
