### ISSUE TITLE
Transcoder doesn't stop when broadcaster has low balance

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#384]
When the broadcaster has low balance, the transcoder automatically claims.  However, it doesn't stop doing the transcoding.  It just keeps doing new claims for every new segment.

```
I0426 17:57:44.353099   31544 livepeernode.go:214] Broadcaster does not have enough funds. Claiming work.
```

**Comment by j0sh** [comment]
Should be fixed by now; the transcoder will reject segments if the broadcaster's balance is too low.
