### ISSUE TITLE
Potential Integer Overflow

### ISSUE THREAD

**Issue by ksloven** [livepeer/go-livepeer#401]
Hi, the contract address here : https://etherscan.io/token/0x58b6a8a3302369daec383334672404ee733ab239
is potentially vulnerable to integer overflow:

==== Integer Overflow  ====
Type: Warning
Contract: 0x58b6a8a3302369daec383334672404ee733ab239
Function name: _function_0xd73dd623
PC address: 3368
A possible integer overflow exists in the function `_function_0xd73dd623`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------

**Comment by yondonfu** [comment]
Hey @ksloven what tool did you use to generate this warning? The message looks similar to the output generated by Mythril.

**Comment by ksloven** [comment]
hey @yondonfu indeed, it is mythril. But based on another report from another project, we looked abit deeper at teh code and at the issues of the scan output and it appeared those were false positives (2 integer overflows and 1 underflow). So this overflow issue could be tentative (false positive)

**Comment by yondonfu** [comment]
Got it. I just ran Mythril on the deployed contract address and I do see that same warning - I think this is a false positive as the `assert` guards in the SafeMath library being used here should prevent an overflow: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/StandardToken.sol#L73 

I'm going to close this issue for now, but if you do end up believing that the warning is valid, please do keep us posted and let the OpenZeppelin community know as well given that the warning is generated by the OpenZeppelin standard token implementation.
