### ISSUE TITLE
Refactor Event Subscription

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#411]
There is currently a lot of duplicated subscriptions. For example, every time we call `SubscribeNewBlock`, we send a new subscription request to the remote provider (could explain why our sub connection is unstable).  

Instead, we should be sending a sub request per event type, and having multiple local listeners on the same event.  

Related to this - a lot of the db updates should be happening at the global event subscription level instead of on the local event listener level.

**Comment by yondonfu** [comment]
This might also be a good opportunity to replace the custom defined event subscription functions such as this: https://github.com/livepeer/go-livepeer/blob/master/eth/eventmonitor.go#L117 with the new auto-generated event subscription functions in a contract binding such as this: https://github.com/livepeer/go-livepeer/blob/master/eth/contracts/jobsManager.go#L1752 The auto-generated event subscription functions in contracts bindings were included after the last time we updated the checked in contract bindings created by a recent update for the `abigen` tool.

**Comment by j0sh** [comment]
The auto-generated subscriptions look quite nice. I can't tell whether multiple watchers will generate multiple subscriptions (hence we'd have manage local listeners ourselves), or is that built-in?

**Comment by yondonfu** [comment]
I think each auto-generated `Watch{EventName}` function will create a new subscription and forward parsed events to the consumer via the `sink` channel so it would be on us to create a single subscription for a particular event and set up local listeners to use the event values passed down the `sink` channel

**Comment by ericxtang** [comment]
Closing this issue.  Code has been refactored.
