### ISSUE TITLE
Delayed Broadcasting Implementation

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#415]
A couple things. 

* Broadcasters need to listen for their own jobs, the same way transcoders do. Seems like a good opportunity to put https://github.com/livepeer/go-livepeer/issues/411#issuecomment-386362364 into practice, any thoughts?

* Should broadcasters reuse the `jobs` DB schema [1] ? Or should we keep that separate for transcoders, and have a dedicated `broadcasts` table for broadcasters? Most (if not all) of the fields would be exactly the same. Or we could add a 'type' field to the table (for broadcaster/transcoder).  I'm inclined to keep them separate, to avoid confusion (especially when users may be testing and switching between broadcasting/transcoding) and give the tables room to diverge later on.

[1] https://github.com/livepeer/go-livepeer/blob/b08a108896cef796637c15a60708e9a191249c48/common/db.go#L51-L63

**Comment by j0sh** [comment]
We enforce a minimum validity period, currently 10 minutes, in https://github.com/livepeer/go-livepeer/pull/428 . If the job will expire in sooner than 10 minutes, we create a new one. Any thoughts?

**Comment by yondonfu** [comment]
> Broadcasters need to listen for their own jobs, the same way transcoders do. Seems like a good opportunity to put #411 (comment) into practice, any thoughts?

👍 

> Should broadcasters reuse the jobs DB schema [1] ? Or should we keep that separate for transcoders, and have a dedicated broadcasts table for broadcasters?

I agree that to avoid confusion and in the interest of accommodating potential future divergences in the requirement for job data between a broadcaster and transcoder that it makes sense to maintain separate tables.

> If the job will expire in sooner than 10 minutes, we create a new one.

Seems reasonable. Perhaps this could also be configurable later by the user.

**Comment by j0sh** [comment]
Merged in https://github.com/livepeer/go-livepeer/commit/2e9b5dacb961d2027d189c7603bdf07220dce121
