### ISSUE TITLE
Configurable gas price

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#420]
This is a proposal to allow `gasPrice` to be configurable so that node operators can change this for both individual txns and for long running default.

- [ ] gasPrice defaults to 4 gwei
- [ ] Add `--gasPrice` flag that allows user to pass in a decimal value interpreted in gwei. `2` == 2 gwei. `3.1` == 3.1 gwei.
- [ ] Add cli option to adjust gasPrice
- [ ] Bonus points for gasPrice being stored (in the sqlite db?) so that it's value is maintained across restarts.
- [ ] Bonus points for the http interface exposing a method to set this value, so that people could script against a gas oracle to have it set intelligently for them.

**Comment by yondonfu** [comment]
There already is a `-gasPrice` flag that allows the user to pass in a custom gas price (denominated in wei) and it defaults to 4 gwei https://github.com/livepeer/go-livepeer/blob/master/cmd/livepeer/livepeer.go#L88

Some options for using a gas price oracle
- ETHGasStation published this script last year https://github.com/ethgasstation/gasstation-express-oracle/blob/master/gasExpress.py I think some the features here were absorbed into the Geth gas price oracle helper though
- Geth (and maybe Parity) offers a gas price oracle helper that can be queried via an RPC call https://github.com/ethereum/go-ethereum/wiki/Gas-Price-Oracle 
- Etherchain has an API https://www.etherchain.org/tools/gasPriceOracle
- I'm not sure if ETHGasStation has an officially supported production API

Looking into the Geth gas price oracle helper seems like a good first start as an optional configuration for users

**Comment by ericxtang** [comment]
Turns out you can use the gas oracle if you set the gas price to nil.

**Comment by dob** [comment]
Does this mean that if you start the livepeer node with `--gasPrice 0` then it will automatically use the oracle?
