### ISSUE TITLE
Running transcoder not able to get job data to begin transcoding

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#422]
I created a job: https://etherscan.io/tx/0x669793245c746723e636d8947bb76aee985e76e2932f8a099bbe4119a22521d9

It got assigned to the transcoder I was running: 
`Job: 3, Price: 180000000000, Broadcaster: 0x2Ca085879d9EDDcD51c4FC4f88fE2D77eDdDc272, Transcoder: 0xFb9849b0B53F66B747Bfa47396964a3FA22400A0`

I was watching the logs on the transcoder:

```
E0508 20:42:44.225081     875 jobservice.go:56] Got empty job for id:3. Should try again.
E0508 20:42:47.144078     875 eventmonitor.go:243] Error with log subscription for RoundInitialized: EOF
E0508 20:42:47.144079     875 eventmonitor.go:272] Error with header subscription for BlockWatcher: EOF
E0508 20:42:47.144279     875 client.go:734] Error getting block by number 5579796: EOF. retrying...
E0508 20:42:48.426241     875 client.go:734] Error getting block by number 5579796: not found. retrying...
E0508 20:42:49.440250     875 client.go:734] Error getting block by number 5579796: not found. retrying...
E0508 20:42:50.846732     875 client.go:734] Error getting block by number 5579796: not found. retrying...
E0508 20:42:50.846756     875 client.go:741] BlockByNumber failed: not found
E0508 20:42:50.846765     875 jobservice.go:69] Error checking for assignment: not found
E0508 20:42:50.846774     875 eventmonitor.go:235] Error with log callback: not found
I0508 20:42:50.846781     875 eventmonitor.go:239] Done watching for logs
```

It looks like it was aware that job id 3 occurred, but that it couldn't get information about it. This node was talking to Infura.

**Comment by j0sh** [comment]
We also need to be checking for `err != nil` and/or `job == nil` here, since this issue is also causing crashes for some users.

https://github.com/livepeer/go-livepeer/blob/master/eth/eventservices/jobservice.go#L54-L58
