### ISSUE TITLE
Node not serving master playlist/manifest after a certain amount of time, despite individual renditions still playing

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#431]
On Rinkeby start a broadcast job. Start consuming the stream at media.livepeer.org.

After awhile, the stream will no longer be requestable - it will say "this broadcaster is currently offline" - on new requests. However players who happen to already have identified the particular rendition stream that they are requesting will be able to continue requesting segments. It's only new requests, that are requesting the manifest, which will receive a 404.

It's not clear to me whether this is a cloudfront issue, or an issue with the node itself. @jozanza and I observed this yesterday on crypto.livepeer.tv and @ericxtang found and confirmed the bug. So feel free to add any context which I missed.

**Comment by jozanza** [comment]
Good summary @dob. I'll just add that using `curl` is pretty helpful for identifying/debugging this problem. You can also "copy as curl" from the "Network" tab in Chrome devtools, which makes it even easier to see if browser headers have anything to do with the network response.

**Comment by ericxtang** [comment]
This is no longer an issue.  Closing.
