### ISSUE TITLE
Remove the need for a -publicIP variable when running livepeer as transcoder

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#449]
**Is your feature request related to a problem? Please describe.**

Isn't one of the main points about this kind of decentralised system to get rid of the need to bind stuff to IP addresses? So when I run a node, I've got to check what the publicIP address is, and enter this, and this is constantly changing on many devices these days, so why still have this attachment of two things?

**Describe the solution you'd like**

I want to be able to run livepeer as a transcoder more easily. And having to put in stuff like "-publicIP" doesn't fill me with a huge amount of confidence that the networking on this video streaming network is actually robust. Sorry :(

**Describe alternatives you've considered**

I consider an option where we continue to require a public IP address to bind to (which limits people running multiple nodes in one publicIP) cripples us. I don't know how the code works, but I would definitely love to understand more about why it still needs an IP? Is it for Cloudfront or something?

**Additional context**

Nothing more to add, except to say "Go Livepeer!"

**Comment by j0sh** [comment]
While we could add facilities to auto-discover the IP and avoid the need to specify `-publicIP`, we can't escape the Internet's underlying routing infrastructure, which runs on IPs, ports, etc. See all the hard-coded addresses we have here:

https://github.com/livepeer/go-livepeer/blob/fac0393950e821f16555a17eb460b8abe74f6ada/cmd/livepeer/livepeer.go#L51-L54

Having a public IP for transcoders is a reliability measure to facilitate direct connections between the transcoder and broadcaster. In a sense, that's also even more decentralized: there's no need for intermediate bootnodes or relay networks, which was the cause of much of our instability.

> So when I run a node, I've got to check what the publicIP address is, and enter this, and this is constantly changing on many devices these days

A transcoder (server) address really should not be constantly changing on many devices. They need to be locatable and reliably connected to the network. With https://github.com/livepeer/LIPs/issues/6 you should only need to set the IP (or DNS name) once, but if that needs to be changed often, it's a bit suspect. Also see https://github.com/livepeer/go-livepeer/issues/442

**Comment by chrishobcroft** [comment]
For clarity, this issue is motivated by a desire to simplify the process for running a transcoder node.

There would be great power in being able to tell people that it really is as easy as:

a) download a zip file
b) unzip it
c) run `./livepeer -transcoder`

After this, the transcoder setup process could all be managed through the protocol explorer.

Any extra "required" arguments like -publicIP (which may be easier for some to surmount than others) just adds to the friction and complexity of getting more nodes running in the network.

**Comment by f1l1b0x** [comment]
i created the feature request #470 to deal with this and other problems related to IPs

**Comment by j0sh** [comment]
The public IP is no longer required to be set via CLI, however transcoders must be public and registered on-chain (we have facilities to help auto-discover your public IP for you, to make this process easier).
