### ISSUE TITLE
Transcoder Registry

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#451]
**Is your feature request related to a problem? Please describe.**
In the [new networking scheme](https://github.com/livepeer/go-livepeer/issues/430), transcoders need to make their connection information public. There has been a [LIP](https://github.com/livepeer/LIPs/issues/6) for transcoder metadata registry, however, since this is a blocking issue for the new networking scheme, I'd like to proposal to fast-track the transcoder registry implementation.

**Describe the solution you'd like**
The easiest way I see is to create a vanilla smart contract only for writing / looking up information, and register it with the controller.  I think this can be done fairly quickly because it doesn't interact with other parts of the smart contract system.

**Describe alternatives you've considered**
DHT-based solution - but it feels unstable and we don't understand the domain well enough.

**Comment by j0sh** [comment]
Blockchain registry implemented in https://github.com/livepeer/go-livepeer/commit/94d8edca933350d9587e76ef5a83066dccfcfd05
