### ISSUE TITLE
Networking v2 Back Compat

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#462]
There's a question of whether we need to be concerned with back compatibility for the broadcaster-transcoder part of the networking flow.

Since the network is still relatively small, I'd be okay with breaking compatibility, but this should be communicated to our users, eg the requirement to set ServiceURI. For thoroughness, here is what it would entail to preserve compatibility:

1. Need to an additional protocol version in basicnet; say `livepeer_video/1.0.0` in addition to the current `livepeer_video/0.0.1` (We can indicate support for both protocols when making a direct connection.)
2. Transcoders continue to send `TranscodeSub` requests
3. Existing basicnet broadcasters will need to be modified to ignore TranscodeSub subscriptions if the flow between the broadcaster-transcoder supports `1.0.0` .
    * If the broadcaster-transcoder connection only supports `0.0.1` , then the transcoder is outdated, and the broadcaster uses the old `0.0.1` protocol.
4. If the direct connection from broadcaster to transcoder fails, then the flow is over `0.0.1`
    * May happen if transcoder hasn't set a ServiceURI yet
5. Broadcasters still on `0.0.1` will continue to work.

The "breaking compatibility" part affects broadcasters more, and entails this:

1. No changes needed to basicnet
2. Transcoders no longer send `TranscodeSub` requests
3. Transcoders must set ServiceURI in order to process any jobs.
    * New slashing condition?
4. Older broadcasters will not be able to have transcode jobs done due to missing `TranscodeSub`
5. Newer broadcasters will still be able to have jobs processed by older transcoders

Thoughts?

**Comment by f1l1b0x** [comment]
I vote for no backwards compatibility till we consider us stable as a v0.1 we should be as josh say on like v0.0.1.27
our "v2 beta" might become v0.0.2?

**Comment by j0sh** [comment]
> till we consider us stable as a v0.1 we should be as josh say on like v0.0.1.27

Haha -- there's actually a typo in the writeup, we probably want to increase the major version, so it'd be `1.0.0` or something instead. Libp2p follows semver and will reject connections that don't have a matching major version, but we can pass in both `1.0.0` and `0.0.1` to indicate support for both versions of the networking protocol. That way, old clients can still be served, while transcoders that receive connections bearing the new protocol string can use that instead. Updated the writeup for clarity.

**Comment by dob** [comment]
I believe that it is acceptable to break backwards compatibility at this point. The vast majority of interactions with Livepeer are currently executed through the protocol smart contracts and not the p2p network, so better to move quickly and get the network into a state where it can be reliable and robust than to complicate the code and logic to support multiple protocols.
