### ISSUE TITLE
Error on "Get node status"

### ISSUE THREAD

**Issue by ghost** [livepeer/go-livepeer#465]
I am getting this error on "Get node status", even after restarting the transcoder:

>>>>>>>
+-----------+
|NODE STATS|
+-----------+
*-----------------------------*----------------------------------------------------------------------*
|                     Node ID | 12209065dc738d05ed4f5350cb2e0de70bf526ff3ad30bb7a7145dec19bbe189db8b |
*-----------------------------*----------------------------------------------------------------------*
|                   Node Addr |              [/ip4/127.0.0.1/tcp/15000 /ip4/10.129.10.152/tcp/15000] |
*-----------------------------*----------------------------------------------------------------------*
|                   HTTP Port |                                                                 8935 |
*-----------------------------*----------------------------------------------------------------------*
|          Controller Address |                           0xF96D54E490317c557A967ABfA5d6e33006BE69b3 |
*-----------------------------*----------------------------------------------------------------------*
|       LivepeerToken Address |                           0x58b6A8A3302369DAEc383334672404Ee733aB239 |
*-----------------------------*----------------------------------------------------------------------*
| LivepeerTokenFaucet Address |                           0x0000000000000000000000000000000000000000 |
*-----------------------------*----------------------------------------------------------------------*
|                 ETH Account |                           0x12345678 |
*-----------------------------*----------------------------------------------------------------------*
|                 LPT Balance |                                                              Unknown |
*-----------------------------*----------------------------------------------------------------------*
|                 ETH Balance |                                                              Unknown |
*-----------------------------*----------------------------------------------------------------------*
ERROR: logging before flag.Parse: E0614 10:17:21.343472   11923 wizard_stats.go:153] Error getting transcoder info: unexpected end of JSON input
+------------------------------+
|TRANSCODER EVENT SUBSCRIPTIONS|
+------------------------------+
*--------------------------------*-------*
|     Watching for new rounds to | false |
|                     initialize |       |
*--------------------------------*-------*
|       Watching for initialized |  true |
|          rounds to call reward |       |
*--------------------------------*-------*
|          Watching for new jobs |  true |
*--------------------------------*-------*
ERROR: logging before flag.Parse: E0614 10:17:21.344880   11923 wizard_stats.go:218] Error getting delegator info: unexpected end of JSON input
CURRENT ROUND: 
<<<<<<<<

I am running the latest software version (0.2.3) on Ubuntu. I haven't seen this happening before over the last weeks.

**Comment by yondonfu** [comment]
Could you provide any logs from the node itself at the time that you used the CLI to invoke the "Get node status" option?

Also, how are you connecting to the ETH network? Are you using the default setup (no additional options passed in when booting up the node such that it will use Infura) or are you using running a full/light ETH client locally?

**Comment by ghost** [comment]
[livepeer_transcoder.log](https://github.com/livepeer/go-livepeer/files/2102714/livepeer_transcoder.log)

When it failed I was using a local light ETH client and when I switched to the default setup things started to work.

**Comment by yondonfu** [comment]
Based on the logs and the fact that you are using a local light ETH client, it seems like your light client is not being served by any full node peers at the time of these operations. Unfortunately, there is no guarantee that a light client will be served by full node peers at the time of a request (full nodes currently do not serve light clients by default - they have to explicitly choose to do so). 

If you are running into a lot of trouble with finding peers with a light client, another alternative besides using the default setup which relies on Infura is to run a full ETH client. It could run on a separate machine and you could even setup the proper security groups such that only the machine that your Livepeer node is running on can access it

**Comment by ghost** [comment]
I see, thank you for looking into it!
