### ISSUE TITLE
need DNS instead of IP for load balancing and ddos protection

### ISSUE THREAD

**Issue by f1l1b0x** [livepeer/go-livepeer#470]
Problem:
Since the IP of a transcoder (orchestrator in v2) is exposed in our smart contract, an attacker could ddos his competing transcoders to 

*make them fail transcode a stream 
an attacker would monitor the job assignment and would start to ddos the publicIP of the elected transcoder.

*harm their reputation
failing the transcodings / uptime will harm their reputation making them lose their delegators trust.

*shut down the entire livepeer network
by ddosing all available nodes 

Solution:
allow DNS instead of IP to be used

* a DNS is easier to protect as an IP address against DDOS attacks. 
* a DNS allows you to switch the network at any time without any smart contract interactions (allow DSL users to work arround their forced disconnects)
* a DNS allows you to balance between mutliple servers on your own for high availability or a bigger geo footprint
 

examples: 

users could use dyndns.org as a service to switch their node´s dns entry to a new IP address each time their dsl config changes without the node changing anything.

a user could use cloudflare or similar to protect his network from DDOS attacks +

a user could use googles or similar DNS balancing services to run multiple nodes behind the same DNS and have the dns balancer decide on which user is being routed to which server

**Comment by j0sh** [comment]
DNS host names are usable in the v2 networking scheme without any additional work. This was an explicit goal, for many of the reasons that you mention.

**Comment by f1l1b0x** [comment]
cool! close then?
