### ISSUE TITLE
Transcoder Object Store with S3

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#472]
**Is your feature request related to a problem? Please describe.**
Transcoder brings write the transcoding results to an S3 bucket, and share the location to the broadcaster.

**Describe the solution you'd like**
The transcoder should be able to set an S3 bucket as an object store, and write the transcoding result into the S3 bucket (including the playlists).  We should test and see if the playlist updates quickly enough for live streaming.  We should also look into solutions for permissions, so only the broadcaster can access the stream.

**Describe alternatives you've considered**
We can also allow the broadcaster to specify an object store location.  This could be something we work on in the future.

**Comment by j0sh** [comment]
OS merged in https://github.com/livepeer/go-livepeer/pull/562
