### ISSUE TITLE
Cleanup dead code

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#477]
**Is your feature request related to a problem? Please describe.**
There are a few places in the codebase where we have dead code.  Let's clean it up!

**Describe the solution you'd like**
Just delete them.  Any maybe add tests.

**Additional context**
Feel free to add more locations.

Dead code location:
* `jobservice.go -> RestartTranscoder` (early return)
* `livepeernode.go -> TranscodeAndBroadacst` (entirely deprecated)

**Comment by j0sh** [comment]
Yanked a bunch of stuff out https://github.com/livepeer/go-livepeer/pull/478 , including the `/transcoder` endpoint in webserver.go and a few supporting functions that were only used within the larger removed stuff.
 
As mentioned, we really could use some more replacement tests.

**Comment by j0sh** [comment]
Fixed in https://github.com/livepeer/go-livepeer/pull/478/commits/330cf64282b5d8eabe1d3e762feb06aa06b4a4c7
