### ISSUE TITLE
Mediaserver State Refactor

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#480]
**Is your feature request related to a problem? Please describe.**
The state management code in `mediaserver.go` is getting unwieldy and a bit error-prone. It could use some refactoring.

**Describe the solution you'd like**

Much of the state management in mediaserver.go is 'column based' ; that is, we have many fields indexed by StreamID. These are:

```
VideoNonce
rtmpStreams
hlsSubTimer
broadcastRtmpToHLSMap
broadcastRtmpToManifestMap
```

We should consolidate these into a 'row' based scheme where all related fields are bundled in the same struct so they can be accessed and managed once, safely. Such a state could look something like:

```
struct RTMPPublishState {
  StreamID string
  VideoNonce string
  HLSStreamID string
  ManifestID string
}
```

There are two ways to accomplish this:

### Within LPMS

The first way involves changing LPMS and relieves the API user of concurrency concerns, but is a bit more invasive.

Stateful LPMs procedures that rely on callbacks, eg HandleRTMPPublish and HandleHLSPlay, can be updated to take an opaque state at the beginning, and propagate that state during the lifetime of the procedure. This typically reduces the per-state bookkeeping that is required outside those APIs, including manual mutex management. (Most of these fields are not currently concurrent safe, with the exception of `VideoNonce` .)

For example the current API of,

```
func (self *VidListener) HandleRTMPPublish(
	makeStreamID func(url *url.URL) (strmID string),
	gotStream func(url *url.URL, rtmpStrm stream.RTMPVideoStream) error,
	endStream func(url *url.URL, rtmpStrm stream.RTMPVideoStream) error) {
```

becomes

```
type RTMPStreamContainer interface {}
func (self *VidListener) HandleRTMPPublish(
	makeStreamContainer func(url *url.URL) (container RTMPStreamContainer),
	gotStream func(url *url.URL, rtmpStrm stream.RTMPVideoStream, container RTMPStreamContainer) error,
	endStream func(url *url.URL, rtmpStrm stream.RTMPVideoStream, container RTMPStreamContainer) error)
```

Then the `RTMPPublishState` struct can be defined within mediaserver and returned within its implementation of `makeStreamContainer`.  State propagation within LPMS is then 'straight through' with no per-connection bookkeeping or locking required within `mediaserver` or `LPMS.vidlistener`.

Similar could be done for eg, `HandleHLSPlay` which depends on `hlsSubTimer`.

Managing a list of `rtmpStreams` (and exposing accessor APIs, eg to check the length) should also be done within LPMS vidlistener, but note that careless list manipulation could still introduce concurrency problems.

**Describe alternatives you've considered**

The other way avoids changes in LPMS. We still consolidate all the mediaserver state into a single struct, and map that to StreamIDs ourselves. The disadvantage here is that the set-up and tear-down within the map still needs to be done manually, and we still need to be careful of concurrency when handling the map.

**Comment by AlexKordic** [comment]
@hthillman closing this issue as outdated
