### ISSUE TITLE
Object Store

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#483]
**Is your feature request related to a problem? Please describe.**

Object Storage (OS) is a necessary component of a robust transcoding system. OS provides persistent access to transcoded data outside of the transient context of live-streaming, and is foundational for use cases such as VOD.

**Describe the solution you'd like**

Refer to the [networking spec](https://github.com/livepeer/go-livepeer/blob/bcf4a0db62f4565bab4cdeabe667855d1b70c2bb/doc/networking.md) for details on the flow between the broadcaster, transcoder and orchestrator.

Note that the following is a sketch of a solution; significantly more detail (eg, on required fields and contents) will be added to the networking spec once the implementation nears completion.

## Four OS Options

There are two places where OS can be used: for segment inputs (the original source prior to transcoding), or outputs (the results after transcoding). Either can be owned by the orchestrator or broadcaster, giving us four options for OS.

### Broadcaster Supplied Input OS

Broadcaster uploads source segments to its own OS. In the POST `/segment` when submitting a segment for transcoding, the content-type can be set to a special value, eg `livepeer/objectstore`. The body then contains the URI where the segment can be downloaded from.

The rest of the headers (Authorization / Credentials / Livepeer-Segment) should remain as-is.

We may add more specific content types for particular storage providers if the situation calls for it; however, for the act of submitting a **publicly readable URL**, this is all that's needed.

### Orchestrator Supplied Input

Orchestrator provides info and broadcaster uploads prior to submitting the segment for transcoding.

The necessary info (paths, credentials) to be used for uploads is sent via the `TranscoderInfo` response after the broadcaster makes a `TranscodeRequest` . After the segment has been uploaded by the broadcaster, submission proceeds in the same way as Broadcaster Supplied Input, with the URL set to an orchestrator-provided OS.

The following diagram is a representative flow of an orchestrator-owned object store, with the same OS being used for both inputs and outputs.

![network v2_ object store interoperability](https://user-images.githubusercontent.com/292510/40022308-68921d20-577c-11e8-8779-42b4efd3a582.png)
[Sequence diagram source](https://sequencediagram.org/index.html#initialData=C4S2BsFMAIDlOAdwPYCcDW0BuAmAXNAPIBGAVpAMbDQDKwaMAkgHbCSrIAO7AhsSODABPAFAjOPVKAogJrIqgoALSAGdgqHvVQiAQhx4ATCj3XtoAWgB8C5Wo1a00AgClkxAEqQAjiMKKVdU1tS2tofWQjEzNUZ1pIAHMAW0h5ABVNZlUKZEN2ABpaAGZoEGYAM2QxcGQuOGhQFNUxCKjTNlRrGiKCAB1mfugABUIaNOKAfRpElNYJgFUPRhFui2tW43b2AhaDTZjrDJ4snLzUPuZoeOTU6hBVaC1J6Zu5xeWRI5Pc8zDuggA4gBRcbdKYzW4LJZibqhKxfbI-c67SL7DoAHjWCNO2yIAGloE4gagODoRKlDEA)

### Broadcaster Supplied Output OS

Broadcaster provides credentials for transcoder to upload segments after transcoding.

In this case, we need to submit some additional information with the initial request to `/segment` such as the upload paths and any credentials. In order to preserve compatibility with the current method of submitting segments, we'll likely set a `Content-Type: multipart/mixed` field in the request. One part contains the upload information, while the other part contains the submitted segment itself, either a blob or an URI that's been uploaded to an input OS. For example:

```
Content-Type: multipart/mixed; boundary=frontier

This is a message with multiple parts in MIME format.
--frontier
Content-Type: livepeer/s3-upload

<S3 upload information here for transcoding results>
--frontier
Content-Type: livepeer/videoblob
Content-Length: 1400000

<raw mpegts segment here>
--frontier--
```

After uploading the segments, the transcoder returns the output URLs in the response to `/segment` along with an appropriate Content-Type header. The transcoder *may* return multiple URLs per transcoded profile, for example `[{name: 720p30fps, uris: [ local storage, IPFS]}]`.

### Orchestrator Supplied Output OS

Transcoder uploads to orchestrator-owned object store, and returns the output URL in the response to `/segment`. The permissions around the URL should be such that the broadcaster is able to retrieve the segment without further authentication.

Output segments using an orchestrator-provided OS must remain available until the segments in question have been claimed and validated; however, we have no way of enforcing this behavior.

### Signaling, Choice and Configuration:

The broadcaster has full discretion over which object store to use (or not to use one at all) for source uploads. Ideally it follows the path of least cost: the broadcaster should prefer to use an orchestrator-owned object store if direct uploads are not possible. This mitigates certain classes of concerns, eg an orchestrator's internal topology imposing much higher request and bandwidth costs, eg due to transcoder races.

Likewise, the transcoder ultimately chooses what to use if faced with a choice between broadcaster and transcoder OS. However, the transcoder should prefer the broadcaster's storage if support is indicated within the `/segment` request. Otherwise use own storage if available.

We may want to consider adding explicit signaling to indicate which upload mechanisms are supported, preferred or disabled. This would allow granular control over output locations, eg a list of mandatory outputs, or even to disable certain locations. For example, if IPFS was made a default output option, some broadcasters might elect not to have their content publicly available that way.

Signaling also allows various implementations to add (or defer or disable) support for various OS providers without coordinating among all implementations, beyond the initial definition of the provider's interface. However, at this stage of the network, that concern may be a bit premature, and we can likely add in such signaling support later (eg, via headers) without breaking compatibility. This may be better reserved for a separate job negotiation step.

There is a question of how we handle multiple jobs. Specifically, do we track OS preferences on a per-job basis, or globally on a per-node basis?  Simplest to use the node's current preferences and maintain a single configuration for all jobs. This allows us to reconfigure OS preferences for jobs even after starting them. However, the drawback is we can't have different preferences per job, and changes mid-job may lead to unexpected behavior in some situations.

## Object Store Providers

We should take the opportunity to build OS support for several 'providers' at once. This allows us to converge on an optimal design for the internal goclient API sooner, and avoid excessive refactoring in the future as we add support for additional providers with diverse upload mechanisms.

### Local Storage

Local storage refers to segments that are served from the orchestrator node itself.

Useful for making transcoded results available, especially for VOD. Works out of the box without anyone needing to set up a third-party system.

This is already working to serve live video. However, we will need to rework the HTTP endpoint to serve segments on a different port than the CLI, to minimize the exposure of CLI commands. The question is whether to reuse the RPC port, or serve HTTP segments on a different port to give operators flexibility. Or offer both. Reusing the RPC port is simplest, configuration-wise.

### S3

Use a S3 POST policy with AWS Signature v4 scheme. Likely requires a number of fields; Policy, Signature, URL prefix, and so forth. 

### IPFS

Since IPFS is permissionless, nodes can simply make content available via IPFS. Send the resulting IPFS URI within the `/segment` request or response.

Note that IPFS typically has a propagation delay of 10+ minutes before content is visible throughout the network. Additionally, the node originating the content must remain online to seed the network. In most cases, where no external object store is available, it is more reasonable for the orchestrator to serve segments from its local storage. The exception is if the broadcaster plans to mirror VOD-style content for the long term specifically over IPFS. In that case, having the transcoder upload to IPFS would save the broadcaster from a separate download + publish step.

We already post to IPFS for validation, so the work required to support IPFS out-of-the-box should be minimal.

## Compatibility

This proposal is fully backwards compatible with the v2 networking system; clients that haven't upgraded to support OS will continue to work.

Object store does not preclude p2p streaming; segments are expected to remain available on a live-streaming basis via the relay network even if OS is being used.

**Comment by yondonfu** [comment]
> The necessary info (paths, credentials) to be used for uploads is sent via the TranscoderInfo response after the broadcaster makes a TranscodeRequest 

This might vary depending on the provider, but what options does the orchestrator (in the case of it supplying an input OS) and the broadcaster (in the case of it supplying an output OS) have if credentials are leaked to multiple third parties that spam the object store (lets say S3 is the provider) thereby jacking up the orchestrator/broadcaster's bills? Blacklisting IPs?

> There is a question of how we handle multiple jobs. Specifically, do we track OS preferences on a per-job basis, or globally on a per-node basis? Simplest to use the node's current preferences and maintain a single configuration for all jobs. 

Maybe we start with OS preferences on a per node basis and consider switching to OS preferences on a per job basis with the inclusion of signaling allowing broadcasters and orchestrators to come to agreement on the OS preferences to be used for a particular job before beginning the work.

> We should take the opportunity to build OS support for several 'providers' at once. This allows us to converge on an optimal design for the internal goclient API sooner, and avoid excessive refactoring in the future as we add support for additional providers with diverse upload mechanisms.

This sounds great - perhaps a simple unified interface i.e. 2 methods `put` and `get` backed by modules for each of the storage providers that also adhere to a standard storage provider module interface. Blockstack calls these drivers within their [Gaia](https://github.com/blockstack/gaia) storage system.

**Comment by j0sh** [comment]
> This might vary depending on the provider, but what options does the orchestrator (in the case of it supplying an input OS) and the broadcaster (in the case of it supplying an output OS) have if credentials are leaked to multiple third parties that spam the object store (lets say S3 is the provider) thereby jacking up the orchestrator/broadcaster's bills? Blacklisting IPs?

I actually don't know enough about S3 if you can blacklist IPs from there. But rogue uploads are certainly a risk, since you're essentially creating a [policy](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html) to allow multiple uploads towards a particular directory. If it's any consolation, POST policies have an expiration date, the content-type and various other things can be restricted. Will look into this issue as I'm working on the implementation.

One trick (which we will use for VOD) is that well-formed mpegts segments can be concatenated arbitrarily, so we could theoretically [upload all segments as the same S3 object](https://aws.amazon.com/blogs/aws/amazon-s3-multipart-upload/) (one per profile), and limit the damage to just that one object using a presigned URL rather than a generic policy.  This might secure against someone dumping a million files within a bucket, but might be an idiosyncratic design decision that not everyone is expecting, and wouldn't work for all types of containers.

I think this might be a situation where reputational risk is more appropriate, especially for the transcoder. For most cases, I'd say that orchestrators themselves are better off just taking uploads directly via the existing POST mechanism, rather than using an object store. There are only a few exceptions, eg a transcoder race architecture.

**Comment by yondonfu** [comment]
> For most cases, I'd say that orchestrators themselves are better off just taking uploads directly via the existing POST mechanism, rather than using an object store.

Yeah unless there is a good way to defend against the attack vector of malicious OS uploads due to leaked credentials it seems like at least for broadcaster and orchestrator interactions, broadcasters should really only choose to provide an input OS (if it is providing an OS at all) such that orchestrators can only fetch files and orchestrators should really only choose to provide an output OS (if it is providing an OS at all) such that broadcasters can only fetch files. This would at least isolate the issues pertaining to the malicious OS upload attack vector to interactions between an orchestrator and its transcoders.

**Comment by j0sh** [comment]
There are risks with both reads and writes, eg a transcoder might not want its OS to be used as the focal point for mass distribution from a broadcaster, and certain transcoder behaviors may lead to higher read costs for broadcaster-owned OSes, eg races.

Ultimately, proper credentials management is a reflection of opsec, and for a transcoder this could mean losing delegates due to a loss of trust. Broadcasters or transcoders should not be using object stores if they cannot monitor its usage or limit access to credentials.

Although there are a few things we could be doing to help them mitigate that, such as packaging the node up to run as a proper service user, access control on keys and the DB, etc. Just needs someone to pick up [this ticket](https://github.com/livepeer/go-livepeer/issues/321).

For what it's worth, uploading to a customer-owned OS is a common feature for various transcoding services. This usually involves the customer creating an IAM user / policy specifically for the service. I'm not sure if that would be entirely appropriate here, or at what granularity (eg, a transcoder probably does not want to give all broadcasters the same creds).

**Comment by yondonfu** [comment]
> There are risks with both reads and writes, eg a transcoder might not want its OS to be used as the focal point for mass distribution from a broadcaster, and certain transcoder behaviors may lead to higher read costs for broadcaster-owned OSes, eg races.

Good point - I just wanted to highlight what I believe to be potentially more harmful consequences with writes.

> Ultimately, proper credentials management is a reflection of opsec, and for a transcoder this could mean losing delegates due to a loss of trust. Broadcasters or transcoders should not be using object stores if they cannot monitor its usage or limit access to credentials.

Agreed on the point about orchestrators/transcoders being responsible for their own opsec. I just think limiting access to credentials is a very difficult task for broadcasters/orchestrators in a permissionless setting - once you give the credentials to a counterparty they can do whatever they want with them and disappear afterwords.

> For what it's worth, uploading to a customer-owned OS is a common feature for various transcoding services. This usually involves the customer creating an IAM user / policy specifically for the service. 

But in this scenario, there is a real world business with real world reputation on the line such that if they did anything malicious with their access to the customer owned OS there would be drastic consequences for them i.e. legal action, falling stock price for a public company, etc.

**Comment by dob** [comment]
I had been thinking that for the S3 driver, orchestrators would provide temporary credentials (with expiration) to the broadcasters or transcoders such that only they could read/write to the folder for the duration of the job, plus expiry SLA.

The trickiest scenario here though seems to be orchestrator provided output store for VOD. In this case, what is the expectation...

* that the orchestrator pays all the bandwidth costs for public access to the output encodings? 
* that the broadcaster needs to download the outputs and store them on their own CDN for distribution?
* that the orchestrator is expected to seed the output to a CDN on behalf of the broadcaster, but not serve greater than N requests in total?

In centralized cloud transcode proudcts, does the company usually offer to host and serve the output encodings indefinitely or for some fixed period of time? Do they charge the broadcaster for storage, bandwidth, or both?

**Comment by j0sh** [comment]
> once you give the credentials to a counterparty they can do whatever they want with them and disappear afterwords.

This is certainly true for broadcasters, which is one reason why having broadcasters upload to an orchestrator-owned OS is usually inappropriate. Orchestrators however, are not anonymous and do have reputational risk on the line when it comes to handling broadcaster credentials.

Note that broadcaster creds also have an expiration, which can be set very short (just a few minutes) since we can refresh upload creds after each segment anyway. This should work well for live video, which is where a direct upload to a broadcaster-managed OS would be the most useful to avoid repeated handling of latency-sensitive video. However, I'm not sure what the typical propagation latency bounds are for a new object, given S3's consistency model.

 VOD would need longer expirations and probably even the credentials saved on disk.

**Comment by j0sh** [comment]
> The trickiest scenario here though seems to be orchestrator provided output store for VOD

In general, whoever's hosting the object store would be expected to cover the cost of using that. If the orchestrator is hosting, the broadcaster would certainly be expected to recover the results within a reasonable time frame.

> that the orchestrator is expected to seed the output to a CDN on behalf of the broadcaster, but not serve greater than N requests in total?

We could do that, although I imagine we'd probably need to integrate each CDN's API specifically to configure the orchestrator as an origin on behalf of the broadcaster. After that, it shouldn't be much different than the orchestrator hosting the files themselves for a limited amount of time, eg within the SLA.

>In centralized cloud transcode proudcts, does the company usually offer to host and serve the output encodings indefinitely or for some fixed period of time?

After some quick googling:

* **Elastic Transcoder**: Looks like it requires a S3 bucket. I think that their live encoder also offers direct Cloudfront integration which is nice. https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/gs-2-create-s3-buckets.html
* **Zencoder**: will host outputs for up to 24 hours in addition to the typical integrations: https://support.brightcove.com/zencoder-output-settings
* **Coconut**: only supports outputting to customer-provided destinations: http://coconut.co/docs/output-urls
* **encoding.com** seems to require a customer-provided output destination, but their "batteries included" vid.ly product will store and distribute it for a fee. See, http://help.encoding.com/faq/,  "What’s the difference between Encoding.com and Vid.ly?"

**Comment by dob** [comment]
Sounds like for VOD, broadcaster supplied object store is almost a requirement for centralized services. Can get around this if you use IPFS driver (though you still may need to retrieve then seed yourself). 

What do you think about the simple SLA for orchestrator provided output is that they store and serve the file for the duration of the verification window (verificationPeriod + slashingPeriod)? This equals 200 blocks, or approximately 50 minutes. This way in a live use case a broadcaster who doesn't have an object store will certainly have the output segments available for someone to buffer and consume the segments live with *minutes* of latency, but if they want to do VOD or record the content they need to provide their own store, or retrieve the files and write to a store of their own, or use another adapter like IPFS?

Looking out even further, perhaps "extended storage", is a capability that orchestrators can advertise and factor into the price/segment for that capability. So ~30 day storage is a capability that broadcasters can opt in to, just like choosing your region and encoding profiles, and it just adds to the price.

**Comment by j0sh** [comment]
> What do you think about the simple SLA for orchestrator provided output is that they store and serve the file for the duration of the verification window (verificationPeriod + slashingPeriod)?

The files probably should be held the length of the job, or until verification/slashing is complete, whichever comes second. But we have no way to enforce that behavior to the extent that a SLA may imply. In fact, we're leaning pretty heavily on trust across various aspects of the object store, eg credentials, availability, access patterns, etc.

> if they want to do VOD or record the content they need to provide their own store, or retrieve the files and write to a store of their own, or use another adapter like IPFS

Once we have job negotiation in, the orchestrator could set their own policies and decline jobs without a broadcaster-provided store. For now, a minimum requirement may just be that the orchestrator serves the files themselves. They could use IPFS but that's essentially a layer of indirection when the orchestrator is the one seeding the file anyway.

> Looking out even further, perhaps "extended storage"

Cool idea, I like that. Very easy to do with job negotiation as long as we're not strict about enforcing availability. With state channels there's even the notion of rents.

**Comment by ericxtang** [comment]
I think a broadcaster would want to provide an input OS for VOD - in which cases, they can make it read-only (or even just provide a direct URL).  Hard for me to see this use case for Live.

What are the cases when a broadcaster would want the orchestrator to write into its OS instead of loading it from the orchestrator's OS?  This feels like a problem-prone path - B's OS can be down, inaccessible, etc.  If the orchestrator cannot write the file, the result will be lost.  Technically it's not the orchestrator's fault, but it feels like an unhappy situation.  We can avoid this situation completely by simply now allowing it.  (and saving us some work)

**Comment by ericxtang** [comment]
Another potential issue for orchestrator-provided OS is bandwidth abuse. Imagine if a broadcaster use the OS url as a broadcast URL for millions of viewers. One possible solution is to require read authentication, and remove the authentication if bandwidth abuse is discovered.  How long the content will stay around is kinda up to the orchestrator, but it would be nice if the orchestrator can provide ttl for it.

**Comment by ericxtang** [comment]
> Output segments using an orchestrator-provided OS must remain available until the segments in question have been claimed and validated; however, we have no way of enforcing this behavior.

Not sure if we should have any expectations of how long the segments should be around based on claims and validations.  Instead, orchestrators can specify ttl for segments, which establishes how long the segments will be around for the broadcaster to use.  It feels like we shouldn't rely on OS for claims/validations, since there can be cases where orchestrators don't provide OS, but still need to do claims/validations.

**Comment by j0sh** [comment]
> What are the cases when a broadcaster would want the orchestrator to write into its OS instead of loading it from the orchestrator's OS

It's a very common feature with other transcoding services, and actually looks like the primary method of delivering outputs. Depositing the results directly where the broadcaster wants them saves a few steps where the broadcaster has to fetch the results, then put them where it wants. This also saves some uncertainty over how long an orchestrator is expected to keep results available, and mitigates orchestrator concerns over unfair access patterns (eg, using the orchestrator OS as the distribution point for millions of viewers).

All this depends on who our audience is going to be here. Individual broadcasters are not going to have an object store, while developers are much more likely to. 

> B's OS can be down, inaccessible, etc. If the orchestrator cannot write the file, the result will be lost

Note that we'd have the same set of issue with transcoder owned OSes, so this is something we should handle  anyway (eg, retrying uploads).

Also, we can have multiple output destinations; a transcoder could still serve results out of its own OS (or itself) as a default or fallback. However, if a broadcaster requests that their own OS also be used, then transcoders should try their best to do so.

**Comment by j0sh** [comment]
> It feels like we shouldn't rely on OS for claims/validations

Since the orchestrator is generally expected to keep segments available until validation passes, that seems like a natural boundary for a SLA. However, this probably should also be kept available for the duration of the job itself (but I just realized, maybe not if the job expiry is really far into the future).

> Instead, orchestrators can specify ttl for segments

Good thought, we can do that by optionally adding it to the segment response (eg, it wouldn't be needed after uploads to broadcaster owned OSes), as a hint to the broadcaster for how long the segment may be available.

**Comment by j0sh** [comment]
> I think a broadcaster would want to provide an input OS for VOD - in which cases, they can make it read-only (or even just provide a direct URL). Hard for me to see this use case for Live.

Agreed, it might not be the typical flow for live, but there are a few cases where this may be useful:
* Simultaneously store your content to your OS for later review, archival or compliance.
* Distribute your content to other places, in addition to the transcoder. Saves bandwidth (and latency) by only uploading once.
* Just-in-time transcoding for your content, which might not necessarily be live video

**Comment by j0sh** [comment]
OS merged in https://github.com/livepeer/go-livepeer/pull/562
