### ISSUE TITLE
Initial Partial Unbonding CLI Support

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#484]
**Is your feature request related to a problem? Please describe.**

[LIP-8](https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-8.md) introduces the concept of partial unbonding to the protocol allowing delegators to unbond a portion of their bonded stake which can be withdrawn after the unbonding period. These unbonding tokens are managed by an "unbonding lock" structure which can also be used to rebond towards a delegator's current delegate prior to the unbonding lock's withdraw round. This is particularly helpful for transcoders (since they are delegators delegated towards themselves) that would like to withdraw earned tokens without completely exiting the registered transcoder pool. As the primary tool used by a transcoder node operator, the node CLI should support this partial unbonding workflow. The rest of this issues describes an initial pass at partial unbonding CLI support with the objective of enabling the feature for transcoder node operators while punting edge cases off to be dealt with separately.

**Describe the solution you'd like**

**Database**

Create a DB table for `unbondingLocks` that keeps track of the ID, amount and withdraw round for each unbonding lock created by the node's account.

**HTTP API**

Update the `/unbond` HTTP endpoint:
- Accept an `amount` parameter
- Executes the contract `unbond()` function and waits for the `Unbond()` event which will include the new unbonding lock ID. The node will store the unbonding lock fields in the local DB.

Update the `/withdrawStake` HTTP endpoint:
- Accept an `unbondingLockId` parameter
- Executes the contract `withdrawStake()` function. Once the transaction confirms, delete the unbonding lock from the local DB.

Add an `/rebond` HTTP endpoint:
- Accept an `unbondingLockId` parameter
- Accept an optional `to` parameter
- If the `to` parameter is provided, executes the contract function `rebondFromUnbonded()` function. If the `to` parameter is not provided, execute the contract function `rebond()`. Once the transaction confirms, delete the unbonding lock from the local DB.

Add an `/unbondingLocks` HTTP endpoint:
- Queries the DB for all unbonding locks

**CLI**

Update the `unbond` option
- Prompt the user to enter an amount (must be <= current bonded amount)
- Send a request to the `/unbond` HTTP endpoint with the user's provided amount

Update the `withdraw` option
- Send a request to the `/unbondingLocks` HTTP endpoint to retrieve a list of all withdrawable unbonding locks. Display all unbonding locks with a withdraw round <= current round in a table with ID, amount and withdraw round. If there are no unbonding locks with a withdraw round <= current round, tell the user that there are no withdrawable unbonding locks
- Prompt the user to enter the ID of a withdrawable unbonding lock
- Send a request to the `/withdrawStake` endpoint with the user's provided unbonding lock ID

Add a `rebond` option
- Send a request to the `/unbondingLocks` HTTP endpoint to retrieve a list of all active unbonding locks. Display all unbonding locks in a table with ID, amount and withdraw round. If there are no active unbonding locks, tell the user that there are no active unbonding locks
- Prompt the user to enter the ID of an unbonding lock
- If the user is currently unbonded, show the user a list of registered transcoders and prompt the user to enter the ID of a registered transcoder. Else, go to the next step.
- Send a request to the `/rebond` endpoint with the user's provided unbonding lock ID. If the user is unbonded, also include the address of the new delegate.

Note: These changes do not handle the case where a node operator exports the key used by the node and uses it in another application (such as the explorer) to unbond. In this case, it is possible for the local node DB to become out of sync with the state of unbonding locks on-chain. In the future, we can include the ability to index the chain to refresh the local node DB to make sure it is in sync with the state of unbonding locks on-chain.

**Comment by yondonfu** [comment]
An additional option is to kick off a unbonding lock event watching service when a node boots up that will update the local DB every time an unbonding lock is created or deleted (via the `Unbond()`, `Rebond()` and `WithdrawStake()` events). The service would filter for events starting from the node's last seen block (stored in the local DB).

**Comment by dob** [comment]
Yah, echoing that I don't believe we can rely on the local DB to be updated solely via the invocation of the txns themselves, since the user may move their key to another machine and lose their local DB. Instead, we either have to update the DB via Logs (which we can optimize by only filtering for logs since the last DB update), or we need to query the blockchain to loop through all the potential unbondinglocks.

**Comment by j0sh** [comment]
Just for clarification: is the use of the local DB here a convenience to avoid re-scanning the blockchain for unbonding locks?

Although the explorer is being deferred for now, are there any thoughts towards handling that? Is there anything we might be able to preemptively build in here?

**Comment by dob** [comment]
Yes, the purpose of the DB is to avoid having to loop through all indexes between 0 and `nextUnbondingLockID` and doing blockchain reads in order to find ones that are active. (Or looping through all Log events to constructruct this every time). 

Certainly optional, but probably a worthwhile optimization if we already have a pattern in place for simple log watching loops.

**Comment by j0sh** [comment]
Implemented in https://github.com/livepeer/go-livepeer/pull/486 , merged in https://github.com/livepeer/go-livepeer/commit/2e9b5dacb961d2027d189c7603bdf07220dce121
