### ISSUE TITLE
Video on Demand

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#485]
Here is a proposed transcoding flow for VOD

![image](https://user-images.githubusercontent.com/292510/48181442-54e86900-e2dc-11e8-819e-7c2fdae86209.png)

[VOD Flow Diagram Source](https://sequencediagram.org/index.html#initialData=C4S2BsFMAIDUHkAi0Bi4D2B3AUNgDgIYBOoAxiIQHbDTxGkAWkAzsEQcOkbgEJHoEAJqQKtIRALQA+OoxZsOXAFwAVdpWal0gyACVIARwB00ABQqAnnkhK4SAJS5sspq3adJ0vgOGjg41XVNbXFoAElKADN0Xn4hETFJKTUCDS0dIlsABXgAZRVoAHoAN21sFLSQzylveL8A2gBpaC5oADl0YFwAc34AVzxoDHRBgG0+6hBwaC0AWzwofwBdcqD08WkpUwBme3gAIwArSFIaXI8bOBAdGOZCUhgJADZsWt9E6QrgjNsAcV0sgBhOyIfRsECQYqQVapb4bLxxd7+TIg-TMPrgYDMbCQSiCWI+BLI6QHY6naDnLiXFCQYCMK43V6IoniAA8EgkpJOZwutlg10g6CAA)

### GRPC `TranscoderReq`, `TranscoderInfo`

This is the same request that live broadcasters make to get transcoder information from the orchestrator. We may add a ‘job type’ parameter for VOD, to give orchestrators an opportunity to distinguish from live jobs and make preparations accordingly. However, there doesn’t seem to be a present need for any special VOD preparations during the TranscoderReq call.

## POST `/vod`

The broadcaster bulk-uploads the segment content (or a URL pointing to the segments) to the orchestrator's HTTP `/vod` endpoint, alongside signatures for each segment.

Required Headers:

* `Credentials` From TranscoderInfo
* `Authorization` From TranscoderInfo
`Livepeer-Segment` : Contains `SegData` following live but with altered semantics.

```proto
message SegData {
    // Total number of sequences in this VOD upload
    int64 seq = 1;

    // Hash of the concatenation of the segment hashes, eg
    // hash = H(H(seg_1)|...|H(seg_seq))
    bytes hash = 2;
    
    // Broadcaster signature across all segment hashes. Same derivation as live:
    // sig = Sig(streamID | seqNo | hash)
    bytes sig = 3;
    
    // Information for any broadcaster-provided OS
    repeated OSInfo storage = 4;
}
```

Headers must also contain any `Credentials` and `Authorization` fields as supplied by the `TranscoderInfo` RPC call.

Body is of `multipart/mixed` content type. Each part is a segment, in original sequence order. Each part has its own `Livepeer-Segment` header containing a SegData populated with the fields appropriate for the segment. The `SegData.storage` field must be unset for each segment's SegData header. The Content-Type of each part matches live: it must either be `video/MP2T` or `application/vnd+livepeer.uri` .

Recognizing that the transcode may take some time to complete for long content, and to avoid issues with long-lived but idle HTTP connections, the transcoder can immediately preprocess the job (confirming the header signatures and that the deposit is enough to cover the job) and return an acknowledgement for `/vod` as soon the preprocessing is complete. Perhaps an expected completion time could be returned as well, if there was a way to benchmark system performance and current load.

### GRPC `VODCheck`

**GRPC Definition**
```proto
rpc VODCheck(VODCheckReq) returns (VODResults);

message VODCheckReq {

    string credentials = 1;
    
    bytes authorization = 2;

    // Start of the sequence number range which should be returned. Default: 0
    int seq_start
    
    // End of the sequence number range which should be returned. Default: last known sequence 
    int seq_end
}

```

After the acknowledgement from `/vod`, the broadcaster can periodically poll the transcoder with a gRPC `VODCheck` call. If the transcoder has completed the work, it returns URLs containing the master playlist manifest. From there, the broadcaster can then download the results to its own disk.

While HTTP POST will be used for `/vod` due to message size, GRPC works better for most other messages, including `VODCheck`.

Alternatively, the `credentials` and `authorization` fields could go into gRPC metadata (headers), following how HTTP auth handling is done elsewhere within the RPC protocol.

**Response Format**

```proto
message VODResults {
  // 'status' can be a progress indicator or some other message
  string status = 1;
  
  // List of transcoded results
  repeated TranscodeResult = 2;
}
```

The `VODCheck` response returns a `VODResults` message which consists of a list of `TranscodeResult` structs that fall within the sequence range specified by `VODCheck`. If the full range of the sequence cannot be returned, as many as possible are returned. Results must be in ascending sequence number order. The orchestrator may also opt to populate the `status` field with an error or informational message.

### Contiguous Files

We can use a characteristic of MPEG transport streams to de-clutter the filesystem a bit. Valid segments can be arbitrarily concatenated (or split apart as long as it is done on proper packet boundaries). Hence, we only need to mux and upload a single file as opposed to hundreds of individual segments. When doing so, we note the segment offsets within the list of signatures that is posted to the transcoder. This would be equivalent to a local HLS byte-range lookup, which is also supported with fMP4.

### Multipart Uploads
Content uploaded directly to the transcoder or S3 probably should be multipart-uploaded for speed and resiliency. For now, single-blob uploads will be enough, however if there is a problem mid-upload, we cannot restart where we left off.

Here is S3’s explanation of [multipart uploads](https://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html)

### Offline Processing

Later on we can make this an “offline” process; that is, VOD jobs are queued and processed appropriately when transcoder’s load allows for it (eg, prioritizing live traffic). Scheduling VOD jobs allows for lower costs over live encoding. However, distinguishing VOD and live jobs likely requires smart contract changes or an off-chain job negotiation step. Until either of those are implemented, VOD jobs will be processed just-in-time as live jobs are.

### Results Webhook

Developers building on top of Livepeer may opt to be notified of results by submitting a webhook rather than polling `VODCheck` . However, in the interests of keeping the broadcast node self-contained, this will be left for future improvement.

### Basicnet p2p Relay

Making the results available over the basicnet p2p relay might be useful for some people, but could require significant plumbing work. For decentralized VOD distribution, IPFS may be better.

**Comment by ericxtang** [comment]
Maybe we can also return a progress indicator in `vod_results`.

**Comment by f1l1b0x** [comment]
nice start and it fits in todays protocol. I think we should aim for a grouped transcoding in which multiple transcoders split the work a job among each other. a single vod transcoder would be taking much longer to process and might fail if the transcoder fails. as a first design we can start like this but for v2 we need the distributed encoding approach

**Comment by dob** [comment]
Excellent.

The one thing that came to mind for me was how this would fit with the "transcoder races" concept. It seems like the broadcaster is serving content to one transcoder in this flow, but the idea of an orchestrator coordinating many transcoders to race to encode the VOD content would create redundancy, reliability, speed, and distributed processing seems powerful. It seems like the orchestrator would play the role of communicating with the transcoders moreso than the broadcaster in that scenario. But perhaps that's V2.

**Comment by j0sh** [comment]
Yeah, what happens on the transcoder side is an implementation detail that's hidden from the broadcaster. The work could be done in parallel, or sequentially, assigned to a pool of trusted transcoders, raced among untrusted transcoders, and so forth. Whatever works best for the orchestrator. This strong decoupling was one of the design goals with the v2 networking model, and also applies to live video.

**Comment by f1l1b0x** [comment]
great job as always!

**Comment by j0sh** [comment]
Updated with details on the message format
