### ISSUE TITLE
Metrics Enhancement

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#490]
**Is your feature request related to a problem? Please describe.**
Metrics for the Livepeer network currently can be viewed at http://metrics.livepeer.org/videos.  

You can turn on event logging by starting the Livepeer node with `-monitor`.  Events can be logged (see [this example](https://github.com/livepeer/go-livepeer/blob/5d0e059b215843a4279180522c9f6879a3d6870c/server/mediaserver.go#L187)) by sending to a centralized logging server.  The logging server runs a [nodejs daemon](https://github.com/livepeer/livepeer-metrics) that connects to a cloud-hosted Mongo.  The daemon returns the metrics for us to see - currently it returns a list of past video streams (and if these videos have failed).  

This system can use a lot of improvement. 

**Describe the solution you'd like**

We can add a table to show the data (we can use something like [react table](https://react-table.js.org/#/story/readme))
* Add a table view so `/video` data can be viewed in a table.
* Add pagination + sorting
* Differentiate between Rinkeby and Mainnet
* Add picker for different metrics

We can add more metrics:
* Time between the previous segment and the current segment (eg, when the segment emerges from LPMS)
* Time it takes to upload a segment
* Time it takes to transcode (approx)
* End-to-end transcode time (upload + transcode) for successful transcodes
* Any errors during the upload or transcode (eg, timeout, transcoder busy, etc)
* Sequence number difference when transcode succeeds or fails (detects scheduling issues)
* Number of segments pending "in flight" when the transcode succeeds or fails (approximates the backlog)

**Comment by j0sh** [comment]
If it helps, here is a script that I've been using to extract some of these metrics from the broadcaster log: https://gist.github.com/j0sh/ea6624d55e519d5146e6568637582140

**Comment by j0sh** [comment]
Implemented in https://github.com/livepeer/go-livepeer/pull/501 and https://github.com/livepeer/livepeer-metrics/pull/3 ; OK to close this?

**Comment by ericxtang** [comment]
No longer valid after moving to new metrics system.
