### ISSUE TITLE
Tracking: Out of Order Segment Uploads

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#491]
**Describe the bug**
In the v2 networking system, the broadcaster starts a new goroutine each time a segment is submitted for transcoding in order to avoid blocking the production of new segments. Under certain circumstances (eg, a upload backlog) this may lead to out-of-order segments arriving at the transcoder, since we don't do any queuing or scheduling of uploads.

https://github.com/livepeer/go-livepeer/blob/690d41eef081afb7bb2c21f1ffb8786cfae6a1e1/server/mediaserver.go#L311

**To Reproduce**

This behavior hasn't been observed, even when testing under poor network conditions. However, it is a logical possibility, so we should monitor it.

**Expected behavior**
Ideally, only one segment should be in-flight at a given time.

**Additional context**

Practically speaking, if there is more than one segment in-flight between a broadcaster and a transcoder, then the network cannot keep up with the incoming stream. Either the broadcaster or transcoder needs to fix their network, or the broadcaster needs to reduce the bitrate of the video that's being submitted.

**Comment by ericxtang** [comment]
Want to confirm here, but I don't think this is an issue anymore right?

**Comment by j0sh** [comment]
Technically, I think this is still an issue. We've seen it show up if video is segmented faster than realtime - https://github.com/livepeer/go-livepeer/issues/750

The multi-O work [1] from @angyangie should satisfy the preferred solution to this issue by ensuring there is only one segment in-flight for any given O. With that, we can probably close this issue.

[1] https://github.com/livepeer/go-livepeer/pull/806
