### ISSUE TITLE
Create livepeer plugin for embark-framework

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#505]
**Describe the solution you'd like**

To have a plugin for livepeer within embark-framework, to make it easier for developers using embark to integrate with livepeer, and stream more easily.

**Additional context**

@embark-framework has plugins for e.g.

"storage on IPFS"
"naming on ENS"
"ethereum on Geth"

It would open up livepeer to a new set of developers using embark if there was a plugin for:

"livestreaming on livepeer" or "trasnscoding on livepeer"

**Comment by ericxtang** [comment]
Are we still pursuing this?
