### ISSUE TITLE
building the cmd/livepeer after git clone fails 

### ISSUE THREAD

**Issue by girishramnani** [livepeer/go-livepeer#509]
**Describe the bug**
When building the `cmd/livepeer` package after cloning the issue, this error occurs

```
../../vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go:25:2: cannot find package "github.com/ericxtang/m3u8" in any of:
	/Users/gramnani/GoProjects/src/github.com/livepeer/go-livepeer/vendor/github.com/ericxtang/m3u8 (vendor tree)
	/usr/local/Cellar/go/1.10/libexec/src/github.com/ericxtang/m3u8 (from $GOROOT)
	/Users/gramnani/GoProjects/src/github.com/ericxtang/m3u8 (from $GOPATH)
livepeer.go:32:2: cannot find package "github.com/golang/glog" in any of:
	/Users/gramnani/GoProjects/src/github.com/livepeer/go-livepeer/vendor/github.com/golang/glog (vendor tree)
	/usr/local/Cellar/go/1.10/libexec/src/github.com/golang/glog (from $GOROOT)
	/Users/gramnani/GoProjects/src/github.com/golang/glog (from $GOPATH)
```

**To Reproduce**

1. `mkdir -p $GOPATH/src/github.com/livepeer`
2. `cd $GOPATH/src/github.com/livepeer`
3. `git clone git@github.com:livepeer/go-livepeer.git`
4. `cd go-livepeer/cmd/livepeer`
5. `go build .`

**Expected behavior**
The livepeer cmd should be been built in the folder

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS High Sierra

**Comment by j0sh** [comment]
Typically for golang, it is encouraged to use `go get` rather than a direct git clone, since `go get` also fetches deps. In the case when cloning from git, a second `go get ./...` step needs to be run prior to building.

**Comment by girishramnani** [comment]
But that approach will fetch the master branches of the unvendored packages
which could break stuff if the there are changes in those packages.

**Comment by j0sh** [comment]
If a package is prone to breaking compatibility, we can vendor it. However, due to vgo, golang is starting to lean into the convention that imports under a certain path need to remain backwards compatible forever. To make breaking changes, a version number in the import path should to be bumped. Hopefully that will mitigate the need to vendor literally everything.
