### ISSUE TITLE
Reusable jobs feature is reusing jobs even though new broadcasting options are used

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#519]
**Describe the bug**
I started a broadcast with certain broadcasting options (price, encoding options), and then stopped that stream and restarted my node. I then started a new stream with different broadcasting options. But rather than create a new job on chain with these new options, it reused the existing job with the old options.

**Comment by j0sh** [comment]
Ah yeah. Good catch. This was mentioned as a requirement here https://github.com/livepeer/go-livepeer/issues/316#issuecomment-387623814 but never got implemented.
