### ISSUE TITLE
Transcoder Video Validation

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#52]
Transcoders should be able to validate they are running the correct version of FFMPEG, and the output is "to-spec" with the protocol.

The naive strategy here would be to have a few test video segment input/output pairs as "gold standard", and the transcoders would run transcoding on those to make sure they are using the right software.

This is NOT a bullet-proof solution.  I'm interested in hearing other ideas.

**Comment by dob** [comment]
What about an md5 hash of the ffmpeg binary?

**Comment by ericxtang** [comment]
No longer relevant because we now directly integrate with libav.
