### ISSUE TITLE
Unchecked signatures in transcode results

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#523]
**Describe the bug**

Signatures attached to the transcode results received by a broadcaster are not checked.

**Expected behavior**

The broadcaster client to check signatures attached to the transcode results.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.02

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/569
