### ISSUE TITLE
Better Broadcaster Solution For When Transcoder Fails

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#530]
**Is your feature request related to a problem? Please describe.**
In the current protocol version, the broadcaster stream stability can easily be affected by transcoder failures.  Consider the following scenario:
1. B creates a job for T with the default setting (720p, 360p, 240p), starts streaming.
2. T starts doing transcoding, sends video back.
3. T gets too many jobs and crashes.

Now B still has all 3 streams in the master playlist, but only the 720p stream works (because it's the original stream).  If a player is playing the 360p/240p stream, it will have a broken experience.

**Describe the solution you'd like**
Considering offchain job negotiation is still being worked on, we should have a stop-gap solution that mitigates the broken experience.  I propose to have the broadcaster do the following:
* Remove all transcoded playlists (but leave the original stream) when more than 3 out of the last 5 segments fail to transcode. 
* Create a new job.  Use that new job to do the transcoding.
* Stop creating new jobs after 3 tries.

Given the current token staking distribution, the 1st place transcoder will get around 25% of the jobs.  This heuristic also serves as a control mechanism that doesn't further overwhelm a node that's already overwhelmed.

**Describe alternatives you've considered**
We can continue to create new jobs, but we can potentially run into the situation where all of the popular transcoders are overwhelmed and broadcasters are stuck creating new jobs over and over, which would drain the Eth in the broadcaster's account.

**Comment by j0sh** [comment]
We probably need to be careful to distinguish legitimate transcoder unavailability from other types of errors. Some examples errors that shouldn't count towards the failure count:

* Transcoder may not see the job on-chain yet (in the case of newly created jobs)
* Errors within the broadcaster's stream itself (malformed or too-long segment)
* Networking issues with the broadcaster itself, eg slow uploads

Also, 3 out of 5 might be a bit touchy; maybe ~10 failures out of 15 would work better.

This brings up an interesting aspect though. Transcoders are incentivized to retain jobs as much as possible. A specially configured transcoder could have an 'overload mode' where it attempts to short-circuit certain jobs by refusing to do them or to return misleading error messages. Transcoders could use this type of strategy to mask availability/responsiveness during transient peaks in demand. However it's not likely to be a huge risk in the near term, before offchain job negotiation.

**Comment by ericxtang** [comment]
Agree that transcoder unavailability is different from broadcast mistakes. Maybe we should look into these issues separately. 

However, I think the broadcaster should still have a graceful-fallback strategy to deal with situations where it thinks transcoding has failed.

I think we can also add some logic to the transcoder to start rejecting jobs when it's overloaded, let's capture that in another issue.

**Comment by j0sh** [comment]
We have failover now so I think we can close this issue.
