### ISSUE TITLE
Job service does not set working flag

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#535]
**Describe the bug**

The job service does not set the working flag to true when it is running. As a result, the service starts running in the background, but when the CLI queries the web server to check if the service is running it will think that the service is not running because the working flag is still false.

**To Reproduce**
1. Start a transcoder node
2. Go to the CLI, load the node stats and observe the event subscriptions section

**Expected behavior**

If the job service is running in the background, the working flag should be true and the CLI should display that information to the user.

**Desktop (please complete the following information):**
 - Version 0.3.0

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/579
