### ISSUE TITLE
Separate database files for different Ethereum networks

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#537]
**Is your feature request related to a problem? Please describe.**

At the moment, the node uses the same SQLite database (defaults to `~/.lpData/lp.sqlite`) whether it is connected to mainnet or Rinkeby. This is problematic in that if the node switches between networks certain values stored in the database could be overwritten. For example, the `LastSeenBlock` could be 100 while connected to mainnet, but would be overwritten with 60 once the node connects to Rinkeby. Additionally, the node could store transcode receipts that are valid on one network, but invalid on another.

**Describe the solution you'd like**

The node should maintain a separate SQLite database corresponding to each network. There could be a database file `~/.lpData/rinkeby/lp.sqlite` for Rinkeby related data and `~/.lpData/mainnet/lp.sqlite` for mainnet related data. If the node needs to run in off-chain mode we can consider having a separate file for that as well.

**Comment by j0sh** [comment]
Extending this a bit further, it would probably be good to store all generated files under each network's folder -- sqlite DBs, key files, .ts segments, etc.

**Comment by ericxtang** [comment]
I like @j0sh's idea.  Would make it easier to switch between the different networks.

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/578
