### ISSUE TITLE
livepeer_cli deposit not decreasing?

### ISSUE THREAD

**Issue by rayj00** [livepeer/go-livepeer#539]
**Describe the bug**
livepeer v0.3.0
I have been experiencing "Insufficient Deposit" on the livepeer console and no longer see the "Successful Transcode"  messages when this happens.  The livepeer_cli displays the deposit, however it never decreases.  I am assuming it should decrease over time?
**To Reproduce**
Supply a low value of Deposit.
Stream until you receive the "Insufficient deposit"  message.
Check the cli for deposit.  It will be the same as it was initially.

**Expected behavior**
I would expect the cli Deposit display to decrease?  I could be wrong.   If so, close this ticket.

**Screenshots**
I0824 12:57:58.351295    1698 events.go:140] Logging SegmentUploaded...
E0824 12:57:58.352246    1698 rpc.go:477] Transcode failed for segment 525: Insufficient deposit
I0824 12:57:58.352400    1698 events.go:180] Logging Transcode
I0824 12:58:01.827197    1698 events.go:113] Logging SegmentEmerged...
I0824 12:58:01.827257    1698 db.go:726] db: Setting segment count for job 3427 to 526

**Comment by rayj00** [comment]
![image](https://user-images.githubusercontent.com/6609523/44597514-e8120800-a79d-11e8-9511-cf0e14786527.png)

**Comment by rayj00** [comment]
I am getting the Insufficient Deposit when I am broadcasting in spite of the above screen capture.

**Comment by rayj00** [comment]
Is seems that the .ts segments are still being generated in the .lpData directory?

**Comment by j0sh** [comment]
The `Deposit` amount in the CLI reflects what is currently recognized on the blockchain. Only when a transcoder successfully claims the work will your deposited amount decrease.

To avoid overdrawing the deposited limit, transcoders do local bookeeping on your stream and will reject segments if there is no longer sufficient Eth deposited to cover the cost of transcoding the stream. This is why your streams seem to work for the first few moments of a stream, only to max out your deposit.

Perhaps we could also do some local bookeeping on the broadcast node to keep track of pending charges. We might be able to give better error feedback to the user that way, eg via the CLI.

**Comment by ericxtang** [comment]
Closing this issue.
