### ISSUE TITLE
ServiceURI from RPC call seems to return different result from registered URI

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#541]
**Describe the bug**
Reported by @dob 

During a transcoding job, the job is created successfully, and the RPC connection seems to be successful as well, but the video segment is being sent to a different URI - 
```
I0824 14:48:46.029748   38955 broadcaster.go:115] Created broadcast job. Id: 31, Price: 200000000006, Transcoder:0x4FF088AC5422f994486663FF903b040692797168, Type: 5ecf4b5293c717e7
I0824 14:48:46.100563   38955 rpc.go:366] Connecting RPC to https://18.222.22.113:8935
I0824 14:48:50.088536   38955 mediaserver.go:361] starting to submit segment 11
I0824 14:48:50.091867   38955 rpc.go:423] Submitting segment 11 : 615700 bytes
E0824 14:48:50.091906   38955 rpc.go:428] Unable to submit segment 11 Post http://127.0.0.1:8935/segment: http2: unsupported scheme
I0824 14:48:54.620624   38955 mediaserver.go:361] starting to submit segment 12
I0824 14:48:54.623116   38955 rpc.go:423] Submitting segment 12 : 613820 bytes
E0824 14:48:54.623155   38955 rpc.go:428] Unable to submit segment 12 Post http://127.0.0.1:8935/segment: http2: unsupported scheme
```

This is because we expect the transcoders to restart their node after setting the `ServiceURI`.

Let's change it so we update the local `ServiceURI` after the transaction has gone through.

**To Reproduce**
I haven't able to reproduce it.

**Expected behavior**
The URI for video segment should be the same as the ServiceURI registered onchain.

**Comment by j0sh** [comment]
My guess is that the 0x4FF08 transcoder didn't actually restart their node after setting the on-chain service URI.

The orchestrator's internal ServiceURI is set once (at start-up time), and if an on-chain ServiceURI is not found, the default is `http://127.0.0.1:8935` 

https://github.com/livepeer/go-livepeer/blob/cf67256880bf31bfec8c77bc077557a92503a913/cmd/livepeer/livepeer.go#L349-L358

 We can probably work around this case by resetting `LivepeerNode.ServiceURI` within webserver.go after setting the on-chain service URI.

https://github.com/livepeer/go-livepeer/blob/cf67256880bf31bfec8c77bc077557a92503a913/server/webserver.go#L281-L296

**Comment by dob** [comment]
Oof, yah I definitely did not tell transcoders that they needed to restart their node after setting `serviceURI`

**Comment by ericxtang** [comment]
@j0sh good idea about automatically updating the local `ServiceURI` after the transaction goes through.  I updated this issue to reflect that.
