### ISSUE TITLE
When creating an unbonding lock, livepeer_cli guides users to enter amount as a float, but expects big integer

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#545]
**Describe the bug**

During the process of creating an unbonding lock, the livepeer_cli provides information which guides the user to enter an amount in the wrong format.

**To Reproduce**

1. Run `./livepeer` in `-transcoder` mode, with an account which has bonded stake
2. Run `./livepeer_cli`
3. Choose option `7. Invoke "unbond"`
4. See that the `livepeer_cli` tells the user the Current Bonded Amount **in LPT** (this is the confusing bit).

`Current Bonded Amount: 17471.404866149158765313 LPT`

5. Type `n` and press return

`Would you like to fully unbond? (y/n) - > n`

6. Enter the amount to partially unbond in LPT (mirroring the information provided).

`Enter unbond amount - > 1471.404866149158765313`

7. See an error:

`ERROR[08-27|18:41:04] Invalid input, expected big integer      err="failed to parse big integer"`

**Expected behaviour**

I would expect that the information provided as a guide to the user should be in the same units as the expected input.

For example:

```
Current Bonded Amount: 17471.404866149158765313 LPT
Current Delegate: 0xa20416801ac2eacf2372e825b4a90ef52490c2bb
Would you like to fully unbond? (y/n) - > n
Enter unbond amount in LPT - > 1471.404866149158765313
```
or
```
Current Bonded Amount: 17471404866149158765313 LPTU
Current Delegate: 0xa20416801ac2eacf2372e825b4a90ef52490c2bb
Would you like to fully unbond? (y/n) - > n
Enter unbond amount in LPTU - > 1471404866149158765313
```

**Screenshots**

![screenshot from 2018-08-29 10-17-28](https://user-images.githubusercontent.com/2212651/44774975-c4bbd400-ab74-11e8-8532-fccce8520fd3.png)

**Comment by ericxtang** [comment]
Fixed.
