### ISSUE TITLE
cli: Merge 'Become a Transcoder' and 'Set Transcoder Config'

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#548]
**Is your feature request related to a problem? Please describe.**
When you're already a transcoder, in the CLI you want to "Set Transcoder Config" in order to change your transcoder parameters. The "Become a Transcoder" option is a no-op. And vice versa.

**Describe the solution you'd like**
Have a single option that intelligently registers the transcoder if needed, or simply sets the config.

**Describe alternatives you've considered**

**Additional context**
```
What would you like to do? (default = stats)
...
14. Invoke multi-step "become a transcoder"
15. Set transcoder config
```

**Comment by ericxtang** [comment]
Maybe we can intelligently display the option (when transcoder is not registered, expose the "become a transcoder" option.  When transcoder is registered, expose the "set transcoder config" option)
