### ISSUE TITLE
go-livepeer Doesn't punch through NATs

### ISSUE THREAD

**Issue by ya7ya** [livepeer/go-livepeer#558]
**Describe the bug**
If `go-livepeer` node is running behind a firewall or a VPN, it's not able to get the external IP , it should be able to do so in order to broadcast and communicate with other peers in the network.

**To Reproduce**
1. run a VPN
2. run Livepeer node
3. stream some rtmp to `rtmp://localhost:1935`
4. try loading that stream anyway within localhost
5. try the same on a different machine that isn't within the VPN.
6. see error.

**Expected behavior**
the node should be able to figure out the external IP, we could probably use a simple signaling server, this method is used in WebRTC to signal peers and establish a connection.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 16.04

**Additional context**

cc @ericxtang

**Comment by j0sh** [comment]
Can you elaborate on what the use case would be for this?

This could be useful for P2P but in that case I think we'd need to consider a number of other things alongside that if/when we design a P2P delivery system for the goclient. Eg, any integration with the Novage P2P effort should imply using a library with proper NAT traversal support, which is essential for WebRTC.

Anyhow, NAT hole punching is rather uncommon for TCP, and doesn't work for symmetric NATs. We also can't use it for CDNs or playback with standard (non-Livepeer) media players. For those reasons, the node really should be exposed if the video is intended to be consumed outside the network. Transcoders already have a requirement to be public.

We do attempt to self-discover the IP address, but the method has limited usefulness for determining public ports. WebRTC uses STUN.

https://github.com/livepeer/go-livepeer/blob/b26253aa6996b2069722ec658222f230ee81d847/cmd/livepeer/livepeer.go#L331-L340

**Comment by j0sh** [comment]
This is not in scope anymore and won't be for the foreseeable future. We can open another issue if it ever becomes a requirement again.
