### ISSUE TITLE
Orchestrator / Transcoder Flag

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#567]
**Is your feature request related to a problem? Please describe.**
With the upcoming O/T split, we need a way to distinguish "transcoding mode" from "orchestrating mode" , and to support a combined mode where O/T are running on the same instance (as it is done now).

Note that we can run without a combined O/T mode under the expectation that Os would be obligated to run the transcoder separately, but this doesn't seem like the best UX at this early stage of the network.

**Describe the solution you'd like**

Leave "-transcoder" as is; this initializes an orchestrator+transcoder instance, which is unchanged from the current behavior. Add "-orchestrator" for an orchestrator-only instance. Standalone transcoders will need to specify the orchestrator address + shared secret anyway, so those flags (eg, `-orchAddress`, `-orchSecret`) could implicitly create a standalone transcoder.

**Describe alternatives you've considered**

* Add an "-orchestrator" flag for orchestrators only, and re-purpose the "-transcoder" flag to enable transcoding (whether in conjunction with "-orchestrator" or standalone). We would probably need a deprecation / grace period for this though, since it'd be a breaking a change to the current behavior.

* Keep the "-transcoder" flag behavior for now, and add "-orchestrator" with a default for the O to do transcoding. Add a "-disableTranscoder" flag to disable O's default transcoding behavior. Eventually repurpose the "-transcoder" flag (by making it mutually exclusive with "-orchestrator") to support standalone transcoding.

* A separate livepeer_transcoder executable. This maintains the separation of concerns a little better, but we'd probably have to still wire in "transcoder mode" on the orchestrator.

Any other ideas or thoughts?

**Comment by darkdarkdragon** [comment]
@j0sh  Seems reasonable. Do you want to add flags before doing actual split?

**Comment by dob** [comment]
I'm not yet up to speed enough on the entire proposal for T/O split. But I think that in the first iteration keeping O's as T's by default will be helpful, since there's no default pool implementation or supply side for T's out of the box.

**Comment by j0sh** [comment]
@darkdarkdragon If we change the behavior of the existing "-transcoder" flag then it would be better to introduce the "-orchestrator" flag in a backwards-compatible manner and give users time to migrate over, before we actually break compatibility.

Another possibility is: leave "-transcoder" as is; this initializes an orchestrator+transcoder instance, which is unchanged from the current behavior. Add "-orchestrator" for an orchestrator-only instance. Standalone transcoders will need to specify the orchestrator address + shared secret anyway, so those flags (eg, "-orchAddress", "-orchSecret") would implicitly create a standalone transcoder.  I actually like this the best so far; updated the ticket.

**Comment by yondonfu** [comment]
Something that might be worth keeping mind with how the flags are used is how the O/T split lines up timing wise with the introduction of new terminology to transcoder operators in communication. The concept of an orchestrator will be completely foreign to many users, so if the default flag that a user has to enable is `-orchestrator` then we'll also have to prepare the right story in the communication once that update hits the node.

If the default flag to enable is instead still `-transcoder` which initializes an orchestrator + transcoder together, then there is less of a need to have the full user story of what orchestrators are immediately prior to having a complete story around V2. But perhaps there is argument for a more iterative introduction of orchestrators before the full V2 story as well

**Comment by j0sh** [comment]
O/T split has been merged, so closing this one
