### ISSUE TITLE
Kick Off New Go Routines For Transcoding Task in Transcode Loop 

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#570]
**Is your feature request related to a problem? Please describe.**
A single "stuck" segment currently can block the transcoding of an entire video stream due to our current transcoding loop design.  

**Describe the solution you'd like**
We should 
1. Kick off a new go-routine for each segment transcoding [here](https://github.com/livepeer/go-livepeer/blob/cd4fe0d650a3e7a36bfdb59a51c8d9465b2bea64/core/orchestrator.go#L337).  
2. Add a context so we time-scope this go-routine.  I think 6s is a good start (since we have 4s segments now).  
3. Log the error whenever a transcode routine gets killed for going past the time scope.

**Describe alternatives you've considered**
We can keep thing as is - but the broadcaster will have a sub-par experience.  I think it's reasonable to expect segments to fail or hang once-in-a-while.  But we don't want this to stop the entire stream from being transcoded.

**Comment by j0sh** [comment]
> Add a context so we time-scope this go-routine. I think 6s is a good start

We'll need ensure that operations within the goroutine are cleaned up properly, eg ffmpeg. Otherwise resources will be leaked when the goroutine is killed.

**Comment by ericxtang** [comment]
Transcoders now time out at default of 8s.
