### ISSUE TITLE
New Video Streams Cannot Be Transcoded Until All Past Jobs Are Received

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#571]
**Describe the bug**
Sometimes transcoders get "stuck" for different reasons.  For example, the local Geth node crashes.  When this happens, it can miss many jobs.  When the transcoder is restarted, it has to go back and reload all the old jobs before processing current jobs (and this process can take a LONG time).

Quote from @j0sh - 
> the transcoder wouldn't get events for recent jobs until it receives all the old ones first. Also, it seems that the block watcher is not started until all this is complete

> So we wouldn't have a up-to-date "current block" number until the job service finished processing historical jobs. I'm not quite sure if it's safe to do the historical processing asynchronously, need to look into it

**To Reproduce**
1. Run a transcoder with a local Geth node
2. Kill the Geth node, and create a bunch of jobs in over some period of time
3. Restart the Geth node (and restart the transcoder)
4. Now the transcoder has to reload all of the old jobs before being able to process new ones.

**Expected behavior**
Transcoder starts to process new jobs right after the restart.  This is because old jobs are likely no longer active.

**Comment by j0sh** [comment]
Should be fixed by https://github.com/livepeer/go-livepeer/pull/568
