### ISSUE TITLE
Research Automated Build Process

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#573]
**Is your feature request related to a problem? Please describe.**
We should have an automated build process so new builds are automatically created and uploaded to S3.  

**Open Questions**
* How do we address automated building for OSX and Windows?
* Should we integrate with Hubot?

**Comment by darkdarkdragon** [comment]
- CircleCI has macOS VM
 - for windows there is https://www.appveyor.com - and it's free for open source projects

**Comment by eladmallel** [comment]
@ericxtang how important is it that we build for windows? - if it's really important, I'd like to throw Travis into the options hat, since they support windows machines and are incredibly popular. They also have a "free for open source" thing, so it might end up being cheaper than Circle.

wdyt?

**Comment by BlinkyStitt** [comment]
For docker, it should be easy to have automated builds at http://hub.docker.com/

I forked this repo and setup https://hub.docker.com/r/bwstitt/go-livepeer to use `Dockerfile.alpine` and it seems to work. It looks like https://hub.docker.com/u/livepeer already exists, so this should just be a couple clicks to setup.

**Comment by ericxtang** [comment]
@darkdarkdragon has done some of this.  Can we close?

**Comment by BlinkyStitt** [comment]
https://hub.docker.com/r/livepeer/go-livepeer/ looks good to me. I think this can be closed.
