### ISSUE TITLE
Better Versioning

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#574]
**Is your feature request related to a problem? Please describe.**
Release versioning should have git commit hashes included.

Proposal: `v0.3.1-cd4fe0d`

**Comment by yondonfu** [comment]
Github releases already have Git commit hashes attached to the release which can be viewed on a project's release page. An alternative instead of coupling the Git commit hash with the versioning scheme would be to modify the `version` command used with the binary to print out additional information about a binary including the Git commit hash (in addition to things like what version of Go was used used for the build, what architecture was the build executed on). For example, this is the output from `geth version`:

```
Geth
Version: 1.8.3-stable
Git Commit: 329ac18ef617d0238f71637bffe78f028b0f13f7
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: darwin
GOPATH=/Users/yondonfu/Development/go
GOROOT=/Users/travis/.gimme/versions/go1.10.darwin.amd64
```

**Comment by darkdarkdragon** [comment]
@ericxtang @j0sh @yondonfu 
I want to include this into M1 - it will help troubleshoot problems with deployed nodes.
My suggestion is to use git to generate version. This should be included into build process like this
`go build -v -ldflags="-X core.LivepeerVersion=$(git describe --always --long --dirty)"` 
This would require us to set tags in git, such as `0.3.1` for current version. Plust we should create two new branches for releases - `rinkeby` and `mainnet`, and configure CI to build and publish new binaries when code is push to these branches.
This will give more clarity for us and for the community from which code our releases are built.

**Comment by darkdarkdragon** [comment]
Plus for every release we should build and push docker image with official Livepeer binary.

**Comment by j0sh** [comment]
The `ldflags="-X` trick is really cool!

I'm in favor of this approach. Not sure we'll make an official release before M1, but we can certainly put most of this into the Makefile. Then perhaps a `make release` target or script for when we're ready to make releases which can prompt for a tag name, etc.

This worked for me:

```diff
diff --git a/Makefile b/Makefile
index 6e0acdc3..d35f1d12 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,10 @@
-all: net/lp_rpc.pb.go
+all: net/lp_rpc.pb.go livepeer
+
+version=0.3.1
+
+.PHONY: livepeer
+livepeer:
+       go build -ldflags="-X github.com/livepeer/go-livepeer/core.LivepeerVersion=$(version)-$(shell git describe --always --long --dirty)" cmd/livepeer/*.go
 
 net/lp_rpc.pb.go: net/lp_rpc.proto
        protoc -I=. --go_out=plugins=grpc:. $^
diff --git a/core/livepeernode.go b/core/livepeernode.go
index 17538c99..53375ffc 100644
--- a/core/livepeernode.go
+++ b/core/livepeernode.go
@@ -26,9 +26,9 @@ import (
        "github.com/livepeer/go-livepeer/net"
 )
 
+var LivepeerVersion string // set at compile time
 var ErrTranscoderAvail = errors.New("ErrTranscoderUnavailable")
 var ErrTranscode = errors.New("ErrTranscode")
-var LivepeerVersion = "0.3.1-unstable"
 
 type NodeType int
 
```

**Comment by darkdarkdragon** [comment]
> +version=0.3.1

We could set tag on current master branch right now, so this would not be needed, and git will be single source of version number.

**Comment by darkdarkdragon** [comment]
> Not sure we'll make an official release before M1

Yes, probably we won't release anything at least before we will deploy new contracts to rinkeby, but I want to have new version numbers in the builds we deploy to Google Cloud - this should help in troubleshooting.
