### ISSUE TITLE
Geth compat for Golang 1.11

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#583]
**Describe the bug**
Our vendored geth is apparently incompatible with the latest version of golang, 1.11. See https://github.com/ethereum/go-ethereum/issues/17751

**To Reproduce**
1. Install go 1.11
2. Try to build the goclient

**Expected behavior**
Goclient should build

**Additional context**
We probably need to rebase our [go-ethereum](https://github.com/livepeer/go-ethereum) changes on top of a more recent release. Not sure if this would also require regenerating the smart-contract code.

**Comment by angyangie** [comment]
Thanks for filing this @j0sh ! To add, the latest version of go Geth worked with locally was `go1.10`. Does not even work with `go1.10.4`
