### ISSUE TITLE
Should be able to create a stream without a deposit

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#584]
**Is your feature request related to a problem? Please describe.**
A broadcast node currently cannot create a viewable stream without having deposited Eth.  This is an artificial constraint.  Even though they won't be able to pay for the transcoding without a deposit, they should still be able to creating a viewable stream (from the incoming stream).

**Describe the solution you'd like**
If the deposit is 0, an incoming RTMP stream should create the viewable stream, but not create a transcoding job.

**Describe alternatives you've considered**
This theoretically can also be done via LPMS, but since the Livepeer node is used more, we should enable it here.

**Additional context**
Brought to my attention at the #cryptolife hackathon.

**Comment by j0sh** [comment]
There's a few considerations here:

There is offchain mode if the user has no intention of transcoding. That should permit view only streams.

For onchain mode (where the intent is to transcode), halting the stream here is useful as a feedback mechanism for the same reason we don't allow creating streams if a round is uninitialized: it brings to the user's attention that something is amiss and needs to be corrected. See https://github.com/livepeer/go-livepeer/pull/380#issuecomment-384465091

Without the explicit feedback, issue diagnosis becomes more indirect (eg, why is my transcode job not starting?). There is not enough visibility into transcode status right now, and often things get lost in the logs, so I'm erring towards failing fast as the better option for now.

Note that once a user makes a deposit, they would still need to restart the stream, unless we add in (one-off) support for reacting to that specific scenario.

A better long-term option would be to have improved UX around the status of transcode jobs, and to move away from implicit job creation towards more explicit job configuration and addressing. Also see https://github.com/livepeer/go-livepeer/issues/429 and https://github.com/livepeer/go-livepeer/issues/481

**Comment by j0sh** [comment]
Looks like we resolved this in https://github.com/livepeer/go-livepeer/issues/694 by requiring a deposit for onchain mode. Please re-open this ticket if the behavior still needs discussion.
