### ISSUE TITLE
VOD Fire and Forget

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#592]
**Is your feature request related to a problem? Please describe.**
The ideal flow for VOD would be a "fire and forget" model: that is, the broadcaster submits a job and its contents in bulk to an orchestrator, then comes back some time later to retrieve the results. The orchestrator can then schedule the work as appropriate, yielding lower costs through more efficient allocation of transcoding resources.

Fire-and-forget exposes two facets of the fair exchange / data availability problem:
1. How to ensure the orchestrator gets paid for the work
2. How to ensure the broadcaster is able to retrieve the work

Pre-authorizing VOD work up front solves issue 1, but not issue 2. 

I'd like to propose retaining fire-and-forget, and ignoring issue 2 until we build a more specialized payments flow for VOD. The reasoning is:

1. Orchestrators have more to lose than broadcasters, since they are incentivized to form long-lasting relationships in order to obtain repeat work.
2. The amounts involved are likely to be quite small (cents per hour). Losing a few cents in order to determine a reliable orchestrator may be an acceptable cost of doing business.
3. For tickets with larger face values, the broadcaster can 'shop around' as necessary, without yielding a winning ticket.
4. We can build mechanisms that trickle VOD work as a risk mitigation measure, eg in 15 minute increments.
5. This places more weight on an orchestrator's reputation. A stricter reputational system will only benefit honest orchestrators.
6. We may see social defenses emerge for this, such as a shared blacklist.

**Comment by eladmallel** [comment]
How does this work in the world of PM, in which IIUC we are reducing the scope of a job to a single ticket? - if we want to allow B to go offline for a while after submitting the video, it means we should provide some payment safeguards *before* we allow B to go offline.

Sounds like this use case can't fully enjoy the benefits of PM and perhaps needs its own payment scheme - do we already have some ideas on how this payment flow should work?

**Comment by j0sh** [comment]
The broadcaster would be submitting multiple tickets up front (or a single ticket with an equivalent `winProb`) to cover the anticipated cost of doing the VOD job.

Correct that PM doesn't provide watertight safeguards with regards to data availability for B. The proposal here is to accept this drawback until we have the opportunity to address VOD-specific payments.

@yondonfu had a sketch of a VOD-specific payments scheme, although I can't seem to find it.

**Comment by f1l1b0x** [comment]
a set and forget option that allows a B to fire and go offline would always include some trust with the O doing the work after being paid already. 
however can B always request proof for the work after the job was accomplished? 
is it coming with an amount of time that O has to do the job? 
since it isnt a segment by segment payment, can the O refund B in case it finds the files it received not transcodeable?
