### ISSUE TITLE
Bug When B and O Both Provide Local Storage

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#595]
**Describe the bug**
According to acceptance test [#3](https://docs.google.com/document/d/1QKCEwYQexX0XlmS7uOqReWbcDkEz8bKRt611FmTZadA/edit#), when B and O both provide local storage, only B should be storing the results to its local.  

However, currently, both B and O store video segments to local disk. 

**To Reproduce**
1. Launch B with local storage (make sure datadir is empty)
2. Launch O with local storage (make sure datadir is empty)
3. Start streaming to B
4. B's datadir and O's datadir both have segments

**Expected behavior**
Only B's datadir should have segments

**Comment by j0sh** [comment]
Note that we don't actually have on-disk OS, only in-memory.

That being said, the orchestrator writes to disk here for two reasons:
1. The source segment needs to be locally available for verification via IPFS. This is going away with Streamflow.
2. Intermediate storage for transcode results. These are deleted immediately after the results are processed.
