### ISSUE TITLE
Bug When Only O Provides S3 Storage

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#596]
**Describe the bug**
According to acceptance test [#5](https://docs.google.com/document/d/1QKCEwYQexX0XlmS7uOqReWbcDkEz8bKRt611FmTZadA/edit#) When only O provides S3 storage, O should write the video segments to S3.  However, currently O writes the video segments to both S3 AND local storage.

**To Reproduce**
1. Start B with local storage
2. Start O with S3 storage (make sure datadir is empty)
3. Start streaming to B
4. O's S3 AND datadir both contain segments

**Expected behavior**
O should ONLY write to S3.

**Comment by j0sh** [comment]
See https://github.com/livepeer/go-livepeer/issues/595#issuecomment-437647566 ; O's datadir contains segments for the same reasons.

**Comment by ericxtang** [comment]
Closing
