### ISSUE TITLE
Update networking.md With New Section

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#598]
**Is your feature request related to a problem? Please describe.**
The `networking.md` doc specifies how the networking protocol works today, but it doesn't capture the design principles we used to create the protocol.

**Describe the solution you'd like**
Add a `Design Considerations` section to discuss some of the considerations like:
* gRPC doesn't do a good job handling large data. [discussion link](https://developers.google.com/protocol-buffers/docs/techniques#large-data)
* gRPC upgrade path. [doc link](https://developers.google.com/protocol-buffers/docs/proto#updating) [discussion link](https://groups.google.com/forum/#!topic/grpc-io/LPsPg5ctQd4)

Essentially, it would be good to move some of the discussion points from the google docs thread [here](https://docs.google.com/document/d/1BnQ6BVgj50IZOip0A97ZT9R-r4lklDg7uhpJAgZbWUI/edit?disco=AAAACWbHq7I) to this doc so anyone who wants to work on networking related stuff can understand how to design their changes.

**Describe alternatives you've considered**
We could also start a new doc, but feels like an overkill now.

**Comment by j0sh** [comment]
Also needs updating for the new Ping command.

**Comment by j0sh** [comment]
Fixed in https://github.com/livepeer/go-livepeer/pull/604
