### ISSUE TITLE
O should respond with an InsufficientCapacity when B attempts a new job/segment negotiation and O is at max capacity

### ISSUE THREAD

**Issue by eladmallel** [livepeer/go-livepeer#603]
**Is your feature request related to a problem? Please describe.**
As we are thinking about off-chain negotiation messages between B and O, in a naive implementation we would not be able to tell apart Os that are offline/unresponsive vs responsive Os that are aware they are at max capacity and cannot take on additional work.

It seems important to tell these scenarios apart, to allow the good Os to maintain a strong reputation and avoid seeming offline when they are not.

**Describe the solution you'd like**
B and O should both support the handling of an `InsufficientCapacity` response O can send B when they are negotiating work. Perhaps in future version this message could also include some heuristic prediction by O of when some capacity should free up.

Suggested naive implementation: the node operator can set a max concurrent streams flag, as mentioned in #706 .

**Describe alternatives you've considered**
The naive alternative is described above - O simply does not respond and B needs to have some timeout and then try other Os.

**Additional context**
None to add.

**Comment by dob** [comment]
I'd like to add support to the notion that this sort of message is only a benevolent message than can help B if provided from an honest and upstanding O, but that B should never expect to receive this message in order to operate correctly.
