### ISSUE TITLE
Offchain Mode

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#609]
**Is your feature request related to a problem? Please describe.**
We've had an `-offchain` mode for some time. This mode was originally intended for basicnet (bootnodes, gateways), but was also useful for viewing ingest RTMP or segmented streams without any accompanying transcoding.

There are still advantages to having such an offchain mode:

* Allows to run independently of the smart-contract protocol or payments mechanism. Useful for running a private network, and testing of the standalone broadcasting/transcoding flow.
* Fewer moving parts to handle when a user's interest is in testing the video flow, since they don't need Docker or a VM, and can avoid the steps needed to initialize the smart-contract protocol, make deposits, register orchestrators, etc. The Ethereum setup in devenv is extremely unstable right now.
* Maintaining a clear separation between the Ethereum and non-Ethereum code may also allow an easier path for integrating other blockchains or settlement systems in the future.

There's been a bit of rot because the `-offchain` mode hasn't been consistently tested or maintained. In particular, here are the things that will currently break with `-offchain` mode:

* Orchestrator connectivity self-check
* Discovery (incorporates the Ethereum address)
* Segment signing and checking

**Describe the solution you'd like**

Special-case and skip anything involving sigs or the eth address. We already do this check nearly everywhere the `LivepeerNode.Eth` object is used, but the handling needs to be improved in a few places.

The concern with this approach is that we're skipping over more code that probably ought to be checked / run regularly to minimize the risk of divergence between onchain and offchain mode.

**Describe alternatives you've considered**

Use a local eth account without the features that require an active connection to an Ethereum node such as block watchers, on-chain lookups, txn submission, etc. We can still perform local operations such as signing and verifying messages.

The concern with this approach is that we don't want to create a situation where a user may have "authorized" something in offchain mode, leading to undesirable consequences onchain. We can maintain a separate offchain keystore to help mitigate that, but it doesn't help if a user is explicit about sharing their keystore path between both modes.

**Related**
https://github.com/livepeer/go-livepeer/issues/555

**Comment by ericxtang** [comment]
Do we need to bypass the Eth address to enable `-offchain`?  In the context of segment signing, the Eth address can simply be used as a keypair.

I'm in favor of maintaining the `-offchain` path, and it feels like a maintenance task - maybe even a small re-architecture, to make sure there is a working code path without using the blockchain.  Also in favor of using `-orchAddr` in this flow, so a B can talk to a O without the blockchain.

**Comment by j0sh** [comment]
> In the context of segment signing, the Eth address can simply be used as a keypair.

Yeah, that was the suggested alternative. It's a bit more work right now, because the Eth address is pretty closely tied to the Eth backend, for example, it's part of the `Eth` struct, which means we need to move the keys and signing outside of `Eth` or redo most of our `Eth != nil` checks for offchain mode.

Another option is to create an "stub offchain" implementation of the Eth client so we don't need to explicitly skip any code if Eth is not present. That would allow us to generate fresh keypairs for offchain mode. That likely requires a more work though, to ensure the "offchain defaults" continue to work well with the present flow.

> I'm in favor of maintaining the -offchain path, and it feels like a maintenance task - maybe even a small re-architecture, to make sure there is a working code path without using the blockchain.

Luckily, the separation is pretty good already; it was only a few tweaks to get this working along with O Discovery. https://github.com/livepeer/go-livepeer/pull/610

The overall separation could certainly be cleaner (eg, the stub Eth module to avoid explicit offchain checks) but I think this is enough to get us going for now.

**Comment by ericxtang** [comment]
> Another option is to create an "stub offchain" implementation of the Eth client so we don't need to explicitly skip any code if Eth is not present. That would allow us to generate fresh keypairs for offchain mode. That likely requires a more work though, to ensure the "offchain defaults" continue to work well with the present flow.

Another consideration is whether `-offchain` mode is only used for testing. I now agree with no Eth addr because if you just want to use the Livepeer software without the blockchain for transcoding / live streaming, you probably don't want a B->O->T architecture (instead, you just want a node to do the transcoding and give you the response).

In any case, I'm on board with no Eth addr / signatures for `-offchain`. When O receives videos with no signatures, it'll assume offchain, and will only do the work if it's also started with `-offchain` (same goes for T).

**Comment by j0sh** [comment]
Fixed in https://github.com/livepeer/go-livepeer/pull/610 and https://github.com/livepeer/go-livepeer/pull/604
