### ISSUE TITLE
CDN-based Video Broadcasting 

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#61]
Make sure videos can be consumed from a centralized gateway node / page

Open source the player page so anyone can run a gateway node / page

Add a paragraph in the tutorial on how to set up a gateway node / page

**Comment by dob** [comment]
Mentioning @buildog to this issue as it's possible that the "player page" could just be the same content as in the desktop app. Right now we just have some static HTML + JS.

**Comment by ericxtang** [comment]
@buildog Oh yeah - right now it's the world's simplest webpage. It points to a Cloudfront url that serves the  video `var videoURL = "https://d3v4kunrmk4k0a.cloudfront.net/stream/" + activeVideo + '.m3u8'`, and uses hls.js to play the video. The Cloudfront stack gets the video from gateway1.livepeer.org. 

It's all in the [livepeer-gateway](https://github.com/livepeer/livepeer-gateway) repo.

**Comment by ericxtang** [comment]
We should make the web player match the desktop app experience.  I'll create a new issue for this.
