### ISSUE TITLE
On-Chain Orchestrator Discovery

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#616]
**Is your feature request related to a problem? Please describe.**
The next task in orchestrator discovery is to use on-chain information to discover active orchestrators. This can be broken up into a few steps.

**Describe the solution you'd like**
- [ ] Modify [`offchainOrchestrator`](https://github.com/livepeer/go-livepeer/blob/a8362ac3655062328d95be07976d5f90ccbc136f/discovery/discovery.go#L13) to store a list of URIs, rather than a single URI
  * Perhaps `offchainOrchestrator` should be renamed `offchainOrchestrators` or something else entirely.
- [ ] Modify CLI arguments to accept a list of orchestrators.
  * Perhaps via multiple `-orchAddrs` flags, or a single comma-separated `-orchAddr` flag.
  * Long term, it'd be good to clean up the CLI flags processing and/or implement a config file with a 1-to-1 correspondence to the CLI flags -- similar to Bitcoin and Bitcoin-dervied nodes
  * This is an "addition" to the Orchestrator Discovery RP but still seems useful.
- [ ] In the `discovery.GetOrchestrators` function (invoked at the beginning of the broadcast): parallel invoke `rpc.GetOrchestrator` for all orchestrators (or first N, perhaps N=10). Gather replies. If there are still pending requests after M seconds (say, M=3), time out the remaining requests and return all valid responses.
  * The job will use the first valid entry in the list returned from `discovery.GetOrchestrators`. Ensure list is constructed in the order that responses are received.
  * Modulo goroutine scheduling, this should generally approximate the lowest latency connection.
  * Pricing information is not really relevant for MVS so we won't incorporate it for now.
- [ ] If no orchestrator(s) specified via flags, invoke `eth.RegisteredTranscoders` at node startup time, and populate `offchainOrchestrator` list with resulting transcoders. This could be implemented as another constructor that returns an `offchainOrchestrator` instance. Perhaps it can be called  `NewOffchainOrchestratorFromOnchainList` but I'm open to anything less verbose.

**Describe alternatives you've considered**
* Omit specifying a list of orchestrators via CLI and **only** take the list from the blockchain.
* Define a separate struct rather than reusing/modifying `offchainOrchestrator`
* Only return the first response rather than waiting up to M seconds.
* Perhaps randomize the list of O at `GetOrchestrators` invocation time to mitigate any bias introduced by goroutine scheduling. Eg, although we invoke `rpc.getOrchestrator` in parallel for all Os in the `offchainOrchestrator`` list, responses may still tend to follow the original order of the list, putting weight on the first few Os.
* Construct the list of on-chain Os via `reward` calls rather than the existing `eth.RegisteredTranscoders` function. This is probably best left for a later step.

**Additional Context**
See the O Discovery RP and https://github.com/livepeer/go-livepeer/pull/604 for further details.

**Comment by eladmallel** [comment]
I'm not sure it's worth it, but you could measure the roundtrip time in each goroutine and sort Os by roundtrip time, thus mitigating the risk of bias towards goroutine scheduling.

wdyt?

**Comment by j0sh** [comment]
Implemented by https://github.com/livepeer/go-livepeer/pull/619
