### ISSUE TITLE
TicketBroker Interface

### ISSUE THREAD

**Issue by eladmallel** [livepeer/go-livepeer#626]
**Is your feature request related to a problem? Please describe.**
As part of the PM implementation, both B and O need to communicate with the on-chain TicketBroker contract to manage and read deposits and penalty escrows, redeem tickets, etc.

**Describe the solution you'd like**
Create an `TicketBroker` interface that exposes the following functionality:

- fundDeposit
- fundPenanltyEscrow
- approveSigners
- requestSignersRevocation
- redeemWinningTicket
- unlock & cancelUnlock
- withdraw

This interface will be provided as a dependency to both the `Sender` and `Receiver` structs that represent both sides of a PM exchange. The real implementation use our Eth client. For testing purposes we can provide a mocked implementation of `TicketBroker`.

**Describe alternatives you've considered**
We considered just using Eth client, but felt the interface is a minor addition that improves testability.

**Additional context**
For additional context on TicketBroker, check out the smart contract [here](https://github.com/livepeer/protocol/blob/pm/contracts/pm/TicketBroker.sol).

**Comment by dob** [comment]
I was thinking that a convenience method might be helpful:

`function fund(uint depositAmount)`

It requires that `depositAmount` <= `msg.value` and then just splits the deposited eth into the deposit and penaltyEscrow according to the specified depositAmount. This would allow B to re-up both balances in one txn.

**Comment by yondonfu** [comment]
@dob We have a wrapper function in the contract (https://github.com/livepeer/protocol/blob/pm/contracts/pm/TicketBroker.sol#L117) to do this.
