### ISSUE TITLE
pm: Common ticket data structures and interfaces

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#627]
**Is your feature request related to a problem? Please describe.**

As a part of MVS PM, there will be common code required by both a ticket sender and recipient:

- Ticket data structure
- Ticket validation and construction

Both a ticket sender and recipient will also need a common interface for interacting with interacting with a third party that processes ticket related operations on behalf of the sender and recipient (the implementation will call to an ETH smart contract).

**Describe the solution you'd like**

- Add a `Ticket` data structure in the `pm` package
- Add functions for ticket validation and construction (using the `Ticket` data structure)
- Add a `TicketBroker` interface in the `pm` package. This will eventually be implemented via the ETH client, but initially we can use a simple stub implementation when writing unit tests.

**Comment by yondonfu** [comment]
Oops, duplicate of #628 #626

**Comment by eladmallel** [comment]
It was my oops @yondonfu !
