### ISSUE TITLE
Possible job metadata use case for broadcaster in future

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#64]
At the moment, a broadcaster does not have much use for job metadata once it creates a job. Could there be any actions that can be taken by the broadcaster based on this metadata?

**Comment by dob** [comment]
Can you explain what exactly you mean by "Job Metadata"? They need to observe the `transcoderAddress`.

**Comment by yondonfu** [comment]
Hm I think this can be closed for now as it is not specific to anything
