### ISSUE TITLE
Out-of-band Orchestrator Discovery and Caching

### ISSUE THREAD

**Issue by angyangie** [livepeer/go-livepeer#641]
**Is your feature request related to a problem? Please describe.**
This last phase of Orchestrator discovery is to use out-of-band processes to gather information from all Os in the service registry, so broadcasters don’t need to do discovery in real-time when a new stream is created. This can be broken up into a few steps:

**Describe the solution you'd like**
- [x] Build DB schema for caching with the following fields, to start with (Include DB indexes for more efficient lookups ). We'll add pricing information once it's available, if necessary. 

> id INTEGER PRIMARY KEY
> createdAt STRING DEFAULT CURRENT_TIMESTAMP
> updatedAt STRING DEFAULT CURRENT_TIMESTAMP
> serviceURI string
> ethereumAddr string (or varbinary)
> PRIMARY KEY(id, ethereumAddress)

- [x] Cache refreshing:  check for updates from the blockchain every hour. Scan all the rows in that table, and compare them to the refresh. If any rows are missing, add them (no rows will be deleted). Once list is refreshed from the blockchain, we can combine updating the table and inputing new rows for new orchestrators on the list as an "upsert", that is, check for the existence of a row, update it if necessary, otherwise insert

- [x] Integrate GetOrchestrator with DB cache

- [x] Add unit test cases for DB-backed orchestrator selection

**Describe alternatives you've considered**
When thinking about refreshing the table, we could drop in the full table, but not something we want to do in the long run, because it could be that we have good work history with specific orchestrator that's not on the list anymore. Broadcaster should still have access to them.

Future Optimizations/Questions to think about (from @j0sh):
- Only rows that haven't been updated in +24 hours will be updated. 
- At some point we'll also want to query GetOrchestratorInfo to get things like pricing information, but since we aren't storing that in the DB right now it can wait. 
- We could update records in the DB one-by-one and check the results in the DB. We'd need to fetch all Os from the blockchain, then filter out Os that already exist in the DB but aren't due for an update, then call GetOrchestrator for each and populate the DB with the values received from OrchestratorInfo. It's more of a concern when the list of orchestrators grows really large, and we don't need to be pinging them so frequently for data (faceValue/winProb) that changes less frequently. 

**Additional context**
See the O Discovery RP, https://github.com/livepeer/go-livepeer/pull/604, and https://github.com/livepeer/go-livepeer/pull/619 for further details.

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/642
