### ISSUE TITLE
Smart Contract Deployment Automation

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#65]
The deployment of Livepeer smart contracts should be automated.  We pretty much already have it captured in `eth/helpers.go`, just need a way to invoke the right thing + a way to do upgrades.

**Comment by dob** [comment]
I think truffle deploy might do this automatically if you're running a node on the chain you want to deploy to, have eth, and an unlocked account.

________________________________

**Comment by yondonfu** [comment]
Truffle can handle this and allows for custom config to target specific networks i.e. main net, test net, private test nets. The deployment functions in `eth/helpers.go` are primarily to facilitate testing the client in Go setting, but when we actually deploy our contracts to a network I think it will be best to use Truffle for deployment and then provide the deployed contract addresses to the client (right now the client just needs the `LivepeerProtocol` and `LivepeerToken` contract addresses)

**Comment by ericxtang** [comment]
Great.  I'll close this issue for now.
