### ISSUE TITLE
pm: support ETH call and transaction submission retries in Broker implementation

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#654]
**Is your feature request related to a problem? Please describe.**

Errors from ETH calls and/or transaction submission when interacting with the TicketBroker contract can be housed in a single place such that users of the Broker interface implementation i.e. recipient and sender do not each have to handle these types of errors and retry.

EDIT: We could also include tx replacements for existing txs that sit pending for a long time.

**Describe the solution you'd like**

One option is that the Broker interface implementation functions can retry for these types of errors for a certain period of time and then only return an error if there is a fairly high chance that something is definitely wrong with the ETH connection i.e. the Ethereum node is not online or cannot support the request.

Another option is that the RPC client used to send requests to Ethereum nodes can implement the retries for these types of errors.

EDIT: For existing txs that sit pending for a long time, we could automatically submit replacement txs with bumped gas prices (within some acceptable range so we don't bid in a gas price auction endlessly).

**Describe alternatives you've considered**

If we don't handle retries for these types of errors in a single location we could end up with duplicated retry code in a bunch of areas of the codebase. Handling these types of errors in a single location can also relieve callers of the burden of trying to recover from these types of errors because the callers will know that something is actually wrong with the ETH connection when they receive an error.

**Comment by eladmallel** [comment]
@yondonfu perhaps it's a good idea to give some specific examples of errors that should be auto-retried, versus the kind of errors we won't want to retry?
