### ISSUE TITLE
Configure mining node

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#66]
We need a reliable node running that is mining the private Ethereum chain for the testnet soft launch.

**Comment by dob** [comment]
Ideally with ~15-20 second blocktimes. It's also possible we could use the Proof of Authority consensus supported by Puppeth, and then one of the bootnodes could just produce a block every 15 seconds, rather than having to actually mine with 100% CPU.

**Comment by ericxtang** [comment]
Done through Clique PoA
