### ISSUE TITLE
DB WinningTickets should have a createdAt column

### ISSUE THREAD

**Issue by eladmallel** [livepeer/go-livepeer#661]
**Is your feature request related to a problem? Please describe.**
For forensics purposes we want `winningTickets` records to have a `createdAt` column, set with the timestamp of when the ticket was stored in the DB.

**Describe the solution you'd like**
A DB column named `createdAt` with the default value of `CURRENT_TIMESTAMP`.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/725
