### ISSUE TITLE
Alerting instrumentation for node operators

### ISSUE THREAD

**Issue by eladmallel** [livepeer/go-livepeer#671]
**Is your feature request related to a problem? Please describe.**
Node operators could benefit from connecting their Livepeer nodes to any monitoring system they prefer to use, mainly to receive alerts that require action, but also for reporting data collection.

Examples of events node operators might wish to get alerts for:

- **Low deposit balance**: this one is especially tricky with PM, since the node might predict an upcoming balance concern even before it's known on-chain, if Os defer ticket redemption while updating B they received a winning ticket.
- **Double spend detected**: this is true for both B and O operators; B might want to take corrective action; O might want to block B or protect themselves in other means.
- **Max capacity reached**: also true for both B and O, as they might want to learn the fluctuations of supply and demand and adjust their setup accordingly.

**Describe the solution you'd like**

- A Livepeer node should accept a "Monitoring Webhook" URL, to which it will send HTTP requests containing the event details.
- At first it can support a strict format, e.g. JSON over POST with hard-coded fields
- Further versions could support GET requests with URL params, custom Golang hooks for further instrumentation, etc.

**Describe alternatives you've considered**

[Collectd](https://collectd.org/) with a [custom plugin](https://collectd.org/wiki/index.php/Plugin:Exec). I believe collectd is widely used, but I think a webhook provides an easier path to hooking up this monitoring solution to services like PagerDuty, or even directly to a Twilio SMS.

**Additional context**
Thinking about this as a long-term UX improvement for node operators.

**Comment by eladmallel** [comment]
My proposed standard to integrate with:
https://graphiteapp.org/

Also great:
https://collectd.org/

**Comment by j0sh** [comment]
For completeness, also want to mention we have our in-house metrics system for event reporting. That could be used to receive and alert on problematic events.

I don't really have a thought one way or another on which approach would be better suited, only to say that we'd ideally standardize on a single system rather than maintaining several, each with a slightly different purpose.

**Comment by darkdarkdragon** [comment]
This actually pretty specific events. If we think node operators would want to have them without installing full fledged monitoring service (like `collectd`), then we should support both variants:
1. Send them to specified webhook, so operator can direct them into, say, PagerDuty
2. Send them to internal monitoring system, if enabled.
