### ISSUE TITLE
IPFS support for inputs to verifications

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#68]
When a segment is up for verification, the input data needs to be available on IPFS. This requires

1. Running an IPFS node
2. Writing the segment to be verified to IPFS
3. Pinning it and keeping it available through the verificaiton period.

Systems like Swear and Filecoin can eliminate some of the burden on the transcoder at a cost, but for now we need the nodes to do this.

Also, we have to make a small change to the protocol, where the broadcast segment includes the SHA2-256 content addressed hash rather than the Keccak256 hash. Will track that in the protocol.

**Comment by yondonfu** [comment]
Done - IPFS node is now embedded and the protocol accepts the IPFS storage hash for segment data during the verification flow
