### ISSUE TITLE
Set a minimum deposit and/or penalty escrow for O

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#682]
**Is your feature request related to a problem? Please describe.**
O does not have a way to specify or enforce a minimum deposit and penalty escrow.

**Describe the solution you'd like**
O to have the capability to specify a minimum deposit / penalty escrow.

When O has a minimum deposit / penalty escrow specified, reject jobs that do not meet the criteria. This checking should be done both via GetOrchestrator and SubmitSegment.

Perhaps have a reasonable default if no minimum is set.

**Comment by yondonfu** [comment]
The orchestrator defines the [minimum reserve for a broadcaster as its desired ticket EV](https://github.com/livepeer/go-livepeer/blob/master/pm/recipient.go#L236). If the broadcaster's reserve is less than the desired ticket EV, then the orchestrator will return an insufficient sender reserve error.

> This checking should be done both via GetOrchestrator and SubmitSegment.

A check happens in `GetOrchestrator()` via a call to [TicketParams()](https://github.com/livepeer/go-livepeer/blob/master/server/rpc.go#L253).

A check also happens in `ServeSegment()` via a call to to [ProcessPayment()](https://github.com/livepeer/go-livepeer/blob/master/server/segment_rpc.go#L65) which will execute the check [whenever a new ticket is received](https://github.com/livepeer/go-livepeer/blob/master/core/orchestrator.go#L165).
