### ISSUE TITLE
Broadcaster does not verify orchestrator's signature

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#685]
**Describe the bug**

A broadcaster currently does not verify an orchestrator's signature over the hash of the concatenated transcoded segment hashes. 

See: https://github.com/livepeer/go-livepeer/blob/c45d7e33e6ae22ac08260085e379cfd6bb56e7d3/server/mediaserver.go#L409

**To Reproduce**
1. See commented out code in above link.

**Expected behavior**

A broadcaster should verify the orchestrator's signature over transcoded results. 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 1b65ae0

**Comment by j0sh** [comment]
Note that the sig + hash `Sig_O(H(H(Rendition_1) | ... | H(Rendition_N)))` also needs to be generated on the O side first.

The hash was formerly generated by the claimmanager but was never re-implemented after the claimmanager was removed.

**Comment by j0sh** [comment]
Addressed by https://github.com/livepeer/go-livepeer/pull/702
