### ISSUE TITLE
Transcoding Result Contains Incorrect URL

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#691]
**Describe the bug**
The transcoding result contains incorrect URL when using a newly registered O. This seems to be because the OS.SaveData in `rpc.go->ServeSegment` is giving back the old URI.

**To Reproduce**
1. Start a new O.
2. Register the O onchain (make sure it's the only O)
3. Start streaming to B
4. You'll see errors described below
5. Stop Stream, restart O
6. The error goes away.

**Expected behavior**
O should automatically update the ServiceURI with the new URI without needed a restart.

**Screenshots**
```
E0117 21:24:22.813874       1 player.go:163] Error getting segment /stream/85eb7484/P240p30fps16x9/0.ts: ErrNotFound
E0117 21:24:22.813901       1 player.go:163] Error getting segment /stream/85eb7484/P360p30fps16x9/0.ts: ErrNotFound
E0117 21:24:22.814074       1 drivers.go:75] Non-200 response 500 Internal Server Error
E0117 21:24:22.814102       1 broadcast.go:158] Download error with segment 0: 500 Internal Server Error (URL: http://127.0.0.1:8935/stream/85eb7484/P360p30fps16x9/0.ts)
E0117 21:24:22.814150       1 drivers.go:75] Non-200 response 500 Internal Server Error
E0117 21:24:22.814179       1 broadcast.go:158] Download error with segment 0: 500 Internal Server Error (URL: http://127.0.0.1:8935/stream/85eb7484/P240p30fps16x9/0.ts)
I0117 21:24:24.166130       1 rpc.go:530] Submitting segment 1 : 567008 bytes
I0117 21:24:24.179402       1 rpc.go:553] Uploaded segment 1
```

**Comment by j0sh** [comment]
Ah nice catch. Easy way to fix this would be to make the memory driver's `baseURI` a pointer reference, rather than a string value.

https://github.com/livepeer/go-livepeer/blob/90c10193860999497cef5f1031fec4890bb9f19e/drivers/local.go#L27-L33
