### ISSUE TITLE
Background buzzing noise in audio of transcoded video

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#701]
**Describe the bug**

The audio of transcoded video contains a buzzing noise in the background that is not present in the original input video.

**To Reproduce**
1. Use https://github.com/livepeer/test-harness to set up a private network with 1 B and 1 O
2. Make sure that O is registered on-chain with the correct service URI
3. Restart both O and B.
4. In the `test-harness` directory run `./test-harness stream dist/test123/docker-compose.yml` to stream a static file into B. By default, if you run `npm install` in the `test-harness` directory, the Big Buck Bunny video should be downloaded and placed in the `assets` folder - this will be the static file streamed into B.
5. Use the `transcode_demo.sh` script in this project to play the input video and transcoded videos. Since we did not set specific transcoding options for B, the default profiles should be used (https://github.com/livepeer/go-livepeer/blob/master/server/mediaserver.go#L55): P240p30fps4x3 and P360p30fps16x9.
6. Listen to the audio in the original input video.
7. Listen to the audio in the transcoded video for both P240p30fps4x3 and P360p30fps16x9. Notice that there is a buzzing noise in the background that was not present in the original input video.

**Expected behavior**

The audio of transcoded video should not contain background buzzing noise or any sounds not present in the original input video.

**Desktop (please complete the following information):**
 - OS: OSX
 - Version: f023c29

**Additional context**

This behavior was confirmed by @angyangie on her machine as well.

**Comment by j0sh** [comment]
Fixed in https://github.com/livepeer/go-livepeer/pull/726
