### ISSUE TITLE
Webhooks: Events

### ISSUE THREAD

**Issue by eladmallel** [livepeer/go-livepeer#704]
**Is your feature request related to a problem? Please describe.**

Allow customers to consume events related to their streams processed by Livepeer. Such events can include: stream start, stream end, mid-stream error, etc.

**Describe the solution you'd like**

- Have the `webhookURL` CLI config value, as described in #703 
- POST a request to `webhookURL` with a body containing the event info
- The body format should be in JSON
- The request should be retried until the webhook server responds with HTTP 200 (optional: use exponential backoff)

**Describe alternatives you've considered**
The main alternative we considered was to expose a REST API so customers can fetch stats and events. We might still take this approach as well, but we're starting with the simpler solution of webhooks for now.

**Additional context**
None at the moment.

**Comment by j0sh** [comment]
> The request should be retried until the webhook server responds with HTTP 200 (optional: use exponential backoff)

Perhaps retry up until a certain point; we probably don't want to retry forever for informational events, especially if it leads to a significant backlog on the node. Also need to consider whether events potentially arriving out-of-order is an issue under retries (we could simply include a timestamp and document that events are not guaranteed to be ordered).

**Comment by eladmallel** [comment]
@j0sh great points!

> Perhaps retry up until a certain point

Do you already have a thought on how to define this point? e.g. should it be up to 24 hours after the event was generated?
Btw, we could employ a more robust approach, where the node would store all failed events in its local DB, and once the webhook server is responsive again (requires further definition), it can kick off a background task to retry all those events again. I think this might be an overkill but wanted to put it on the table to get more thoughts.

> we could simply include a timestamp and document that events are not guaranteed to be ordered

I really like this approach and think that's how we should start this feature.

Once again, if we "go crazier" and persist failed events to DB, we could potentially guarantee order, as long as we implement it such that we always retry from the oldest event onward.

any additional thoughts @j0sh @darkdarkdragon ?

**Comment by eladmallel** [comment]
Another dilemma I wanted to discuss is the relationship between sending these events to the webhook and our current `monitor` package:

Should updating the webhook on these events happen *inside* the monitoring service?

I like this idea because these two concepts seem so similar that it would be mostly duplication to implement an entirely new mechanism for webhook events. To be clear, I'm referring to "FYI-type events", which do not include the webhook call to authorize ManifestIDs.

@darkdarkdragon @j0sh what do you think?

**Comment by darkdarkdragon** [comment]
@eladmallel do we really need this? I don't remember us discussing this one.

**Comment by eladmallel** [comment]
@darkdarkdragon I remember this requirement coming from @ericxtang or @f1l1b0x - maybe they can shed more light on this need?

**Comment by ericxtang** [comment]
I think sending the events back to `webhookURL` will make it easier for a user to manage their streams.  It also makes the webhook approach more powerful (for example, it's easy for a user to implement logic that kicks of another process upon receiving the `StreamStarted` event).  

Whether to use the `monitor` package feels like a decision for the implementer.  On first glance, I prefer the DRY principle, and think it makes sense to use the `monitor` package.

**Comment by eladmallel** [comment]
@ericxtang can you share more of your thoughts on whether this task should be in the scope of M2 or not? @f1l1b0x as well?

**Comment by j0sh** [comment]
Just wanted to mention there feels like some conceptual overlap with https://github.com/livepeer/go-livepeer/issues/671 . At the very least, most of the events a node operator might want to subscribe to would probably also be useful for instrumentation.

I think it's certainly a good exercise to consider:
* coherence with our existing metrics system, which feels very close to what we want already
* composability with respect to various notification systems
* customization based on application-specific requirements

Whether this is actually needed for M2 is a separate question; I'd say this is another area where we could use more customer development to drive priorities. Curious what others think.

**Comment by darkdarkdragon** [comment]
Looks like we need another discussion about scope of M2.
I would vote for now to implement only `RTMP approval` part, and postpone everything else till we have some feedback from real customers.

**Comment by ericxtang** [comment]
This is finished.
