### ISSUE TITLE
RTMP Auth Webhook: Documentation

### ISSUE THREAD

**Issue by eladmallel** [livepeer/go-livepeer#705]
**Is your feature request related to a problem? Please describe.**

Customers who wish to integrate with our test service will require some documentation on the integration architecture, what they should implement (e.g. webhooks), what is the format of various requests and responses, etc.

This documentation is an important part of their overall integration UX, so we want it to be sufficiently clear and usable.

**Describe the solution you'd like**

- Decide where this documentation should live: readthedocs? github?
- Document the entire integration flow, along with example requests and responses
- Ask another dev on our team to follow the docs to the letter and provide feedback

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by j0sh** [comment]
For a long-form intro to the auth webhook, I'm thinking that readthedocs would be a good place for it. We should describe:

* Setting the CLI flag
* Request format
* Response format
* ManifestID limitations. Technically anything will work except for a backslash which will be split during playback, so returned MIDs should not contain a backslash [1].
* Maybe have simple examples of a callback webhook in a couple languages (Ruby with Sinatra, Python with Flask?).

[1] Could be improved via https://github.com/livepeer/go-livepeer/issues/764
