### ISSUE TITLE
Use abigen contract binding with ABIEncoderV2 support for struct function params

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#707]
**Is your feature request related to a problem? Please describe.**

The abigen generated contract binding for the LivepeerETHTicketBroker contract is currently based off a modified version of the contract that does not use the ABIEncoderV2 flag which enables the use of structs in function parameters. As a result, the modified version of the contract forces the caller to pass in all the individual fields of a ticket struct separately for `redeemWinningTicket()`.

Using an abigen generated contract binding for LivepeerETHTicketBroker has the following benefits:
- The original version of the contract can be used with the ABIEncoderV2 flag enabled
- The contract interface becomes cleaner because a single ticket struct can be passed into `redeemWinningTicket()`
- The contract calling Go code becomes cleaner because a single ticket struct can be used as a parameter

Note: Solidity will also eventually enable the ABIEncoderV2 flag by default. See: https://twitter.com/ethchris/status/1085960010012782592

**Describe the solution you'd like**

- Once abigen supports generating contract bindings that use the ABIEncoderV2 flag in order to enable struct function params, create a new contract binding for LivepeerETHTicketBroker. 
- At this point, we can also directly pass in a ticket struct when calling `redeemWinningTicket()` from Go code.
- We might want to update the vendored go-ethereum code that contains the necessary dependencies to invoke the contract binding functions

**Describe alternatives you've considered**

We could choose not to use struct params for `redeemWinningTicket()`, but this results in a more cumbersome to use contract API.

**Comment by eladmallel** [comment]
@yondonfu cool! do you have any sense of when abigen will support v2 by default?

**Comment by yondonfu** [comment]
Closed by #881
