### ISSUE TITLE
Document CLI Flags

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#708]
**Is your feature request related to a problem? Please describe.**
The command line flags are under-documented.

**Describe the solution you'd like**
Document the flags more thoroughly, including with examples. Ideally we would keep the documentation "close to the code", eg somewhere in `docs` where they can be easily referenced offline and updated as the code changes.

**Describe alternatives you've considered**
We could place the docs somewhere in readthedocs. However, a link from readthedocs to the in-node docs might suffice.

**Comment by yondonfu** [comment]
@j0sh Do you think it would be sufficient to just update the descriptions that are passed in as flag parameters in [livepeer.go](https://github.com/livepeer/go-livepeer/blob/master/cmd/livepeer/livepeer.go#L90)? Then, the documentation could just live with the flag code itself and we could just dump the output of `livepeer -help` into a file in `docs` if needed.

**Comment by j0sh** [comment]
@yondonfu The inline CLI documentation is typically terse. It would be nice to have expanded descriptions for most options - context around the option itself, the B/O/T modes they apply to, any interactions with other options (some are mutually exclusive), examples of usage, etc etc.
