### ISSUE TITLE
Send metrics to metrics server by default

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#71]
We should do this for the testing period so we can get better insights into the network.

**Comment by dob** [comment]
Yah agreed. Can we add a clear log message though that says "Metric Data being collected during testnet softlaunch. Disable this by starting with `<flag>` if you would not like your node data shared." or something like that.

**Comment by ericxtang** [comment]
Yep.

**Comment by ericxtang** [comment]
Done
