### ISSUE TITLE
Mediaplayer is broken for demo purposes

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#712]
**Is your feature request related to a problem? Please describe.**
The media player used to be able to play ANY stream in the test network because of a p2p relay network.  Unfortunately it was unstable and we had to take it out.  Now we have a broken media player.

**Comment by ericxtang** [comment]
Change the readthedocs page to make sure users know how to use the "source" param in the mediaplayer.

**Comment by j0sh** [comment]
Also would be good to update https://media.livepeer.org/ to avoid the impression that the player will work for any ETH address

**Comment by j0sh** [comment]
Mediaplayer is in good shape now thanks to @iameli and the readthedocs site has been updated. Woot!
