### ISSUE TITLE
Clean up lengthy functions in our code base

### ISSUE THREAD

**Issue by angyangie** [livepeer/go-livepeer#714]
**Is your feature request related to a problem? Please describe.**
Break functions up in places where they are more than 100 lines long. Here are a few examples:
- RPC.go ServeSegment (over 100 lines), SubmitSegment
- Main.go function in livepeer.go (450 lines long)

**Describe the solution you'd like**
Break functions up into separate distinct functions that do specific tasks. It improves code readability.

**Additional context**
I will add more context here later.

**Comment by ericxtang** [comment]
Done.  Closing.
