### ISSUE TITLE
Video segments get piled up on disk 

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#716]
**Is your feature request related to a problem? Please describe.**
The transcoder writes transcoded segments to local disk, but we don't clean them up after.  There should be a cleanup policy.

**Comment by j0sh** [comment]
Transcoders should clean up segments immediately -- if not there is a bug.

Broadcasters do pile up segments until the stream ends (and if the stream doesn't end cleanly then they stay on disk forever). Related: https://github.com/livepeer/go-livepeer/issues/352

**Comment by ericxtang** [comment]
Correction - it is the broadcaster

**Comment by ericxtang** [comment]
Related to https://github.com/livepeer/lpms/issues/57.  @j0sh will look into this (also on the transcoder side)
