### ISSUE TITLE
Package refactoring mainly to create Livepeer-agnostic libraries and helpers

### ISSUE THREAD

**Issue by eladmallel** [livepeer/go-livepeer#717]
**Is your feature request related to a problem? Please describe.**
Seems like some of our packages can be refactored such that we achieve:
- More reuse
- Smaller odds of running into cyclic imports
- Easier answer to "where should I put this?"

**Describe the solution you'd like**
We should ideally run a dependency analysis that outputs a graph, such that we can reason on this visually.
For now some thoughts are:
- Break apart `eth` into two packages: (1) Livepeer-agnostic helpers, and (2) Livepeer-specific integration with the protocol
- Break apart `common`, such that `common` does not include any DB-related code

Does anyone have additional thoughts?

**Describe alternatives you've considered**
Leaving things as-is is always an option!

**Additional context**
As we were working on the `pm` package implementation we bumped into some cyclic dependency issues.

**Comment by angyangie** [comment]
Just wanted to include a [link](https://github.com/livepeer/go-livepeer/pull/702/files/824d0bdb163c2caa5dfb93517f6c49635405af65#diff-cecc27bfe2b6b19181ce443733dfba57R221) to our initial discussion on the topic here, so it's not lost in the flurry of PR's. 

Thanks for creating this issue @eladmallel !

**Comment by hthillman** [comment]
closing for now but we'd like to address in the future - need more specific issues
