### ISSUE TITLE
Dependency management in go-livepeer

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#719]
**Is your feature request related to a problem? Please describe.**
We vendor packages because of legacy reasons - when we started the repo, golang doesn't have good version management in dependency tools.  But from my understanding, this has changed.  It would be good to use a modern tool to manage our dependencies.

**Comment by mk-livepeer** [comment]
I believe that we've resolved this with the move to `go.mod` ...  We can probably close this.  @ericxtang ?

**Comment by ericxtang** [comment]
Yep.  Closing.
