### ISSUE TITLE
Agree on a consistent format for tests

### ISSUE THREAD

**Issue by angyangie** [livepeer/go-livepeer#721]
**Is your feature request related to a problem? Please describe.**
( In the spirit of transferring important/meaningful discussions on PR's to issues, adding our discussion on test formatting here)

Our tests are being written in several different formats. It would be nice to come up with a "standard" way to write tests, and have consistency across all of our test files (though we'd have old tests that wouldn't comply to the new test writing style until we make a deliberate attempt to transition them). 

The debate centers on whether we should have smaller test functions with specific naming [in three parts: the code under test (usually a function name), the scenario, the expected result separated by an underscore], or, continue doing testing as we have in the past (longer functions that encompass multiple test cases and reduce set-up code repetition). The recent addition of `stretchr/testify/assert` and `stretchr/testify/require` could also be discussed here, though it seems we might have reached consensus that it's generally a good addition to our tests. 

**Describe the solution you'd like**
This is an ongoing discussion that would benefit from everyone's input. So far, some opinions:

@eladmallel : taking the approach of smaller functions and the specific naming paradigm nudges us to think more carefully about all the cases we want to cover. Long test functions with comments along the way harder to parse than the shorter functions I've been trying out. See this recent example: https://github.com/livepeer/go-livepeer/pull/655/files#diff-c20584ae20b069ed08dc6769a1c19e77. Of course one of the downsides could be repetitive setup code, but that can be mitigated with some solid helper functions. 

@j0sh: I'll go out on a limb here and say that I don't find the "surgical" approach to help readability or understanding the code flow for a few reasons:
- The method names are really long, which takes conscious effort to mentally parse and understand. Even if retaining the surgical approach, I'd really prefer more concise method names, and elaborating on the scenario/expected result as a comment.
- It generates a large amount of boilerplate, which we'd still have with helper functions.
- Separating each test case into its own function, we lose the benefit of code locality. It's harder to quickly scan the tests and reason about the various conditions that are covered (or might not be covered). Here, I was able to quickly see that we were missing nil/empty checks. Also, the progression here can logically be followed: testing empty case, testing one case, testing multiple cases. Splitting that up doesn't improve the readability.
- Related to code locality, one pattern I've used is to check for various conditions following the implementation. This makes it easier to scan the implementation and identify the test case that's covering it. For example, if a function checks and early-exits for conditions A, B, C, we'll have a unit-test checking for A, B, C. The RPC tests have a bunch of these, eg https://github.com/livepeer/go-livepeer/blob/master/server/rpc.go#L176 and https://github.com/livepeer/go-livepeer/blob/master/server/rpc_test.go#L147 (admittedly the checks here aren't quite in the proper order; that could be improved.)

**Additional context**

[Original discussion](https://github.com/livepeer/go-livepeer/pull/642#discussion-diff-244993868L120)

**Comment by yondonfu** [comment]
Another point worth discussing is our approach for mocks & stubs. After the introduction of the `testify` package, we have started to use the `testify/mock` package in order to set up pre-test expectations (which allow us to mock method return values) which some might dislike from a style stand point (perhaps partly due to the API exposed by the `testify/mock` package). See this [comment](https://github.com/livepeer/go-livepeer/pull/696#discussion_r249225064) for more details.
