### ISSUE TITLE
Demo network topology for O/B

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#736]
* Two Os
* Two Bs
* Geth?

**Comment by j0sh** [comment]
Are we settled on the setup as outlined here? https://github.com/livepeer/test-harness/commit/caea8357f540a97acb53e7bdd688f35354f1dc01

**Comment by darkdarkdragon** [comment]
@j0sh 
yes, same setup running for seven days now and handling six stream with failure rates up to (sometimes) 3%. So it will handle five streams without problem.
