### ISSUE TITLE
Remove PID-file requirement

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#74]
We should remove the PID file for now.  It doesn't get removed correctly when the node crashes, and that prevents you from restarting the node (unless you manually delete the pid file).

We COULD recover from the panic, but I think right now, it's good to see the panics so we can address these bugs.  At some point (when the network goes LIVE), we'll add panic recovery so the node wouldn't crash when unexpected panics happen.

I'll add an issue to Testnet Launch to make sure we remember.

**Comment by yondonfu** [comment]
Closed by #97
