### ISSUE TITLE
Transcoder-only node is single-queued

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#748]
**Describe the bug**
Orchestrator creates transcoder loop for each stream. These loops runs in parallel. When orchestrator node works as a transcoder too, it transcodes segments in each loop by itself, thus using every CPU core that is available. When orchestrator uses separate transcoder, it sends transcode tasks form all transcode loops into one transcoder, and that transcoder processes them one-by-one, thus limiting cpu usage to only one core.

**Expected behavior**
Transcoder should behave same as orchestrator - process all streams in parallel.

**Comment by j0sh** [comment]
This would be addressed as part of the multi-T project that @angyangie is working on. Orchestrators would be responsible for tracking available capacity and scheduling work among its connected Ts.

**Comment by darkdarkdragon** [comment]
No, it won't be addressed, unless way transcoder works will be changed. In current way, it will require to run multiple transcoders instances on one machine to utilize all the resources - certainly not the best user experience.

**Comment by j0sh** [comment]
> No, it won't be addressed, unless way transcoder works will be changed.

Why wouldn't we be able to change it?

**Comment by darkdarkdragon** [comment]
Will we change it? My mistake, from your answer I've assumed that we won't. If we do, then this issue should be closed.
