### ISSUE TITLE
Segfault when trying to start broadcast

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#761]
**Describe the bug**
When I try and start a local offchain broadcast [with the 0.4.0 beta release](https://github.com/livepeer/go-livepeer/releases/tag/0.4.0), the broadcaster is crashing with this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4a66b4c]

goroutine 99 [running]:
github.com/livepeer/go-livepeer/server.processSegment.func1(0xc000138000, 0xc000036125, 0xb, 0xc000280200, 0xf00f2d0edddb10e, 0x57f65c0, 0xc000246240, 0xc0002463c0, 0x57f4a00, 0xc0000ba640)
	/Users/ericxtang/Code/Livepeer/lpdev-data/go/src/github.com/livepeer/go-livepeer/server/broadcast.go:221 +0x4ac
created by github.com/livepeer/go-livepeer/server.processSegment
	/Users/ericxtang/Code/Livepeer/lpdev-data/go/src/github.com/livepeer/go-livepeer/server/broadcast.go:124 +0x5e9
```

[Full logs from the broadcaster and transcoder are here.](https://gist.github.com/iameli/8efbac98c85d3bb7812291017f278133)

**To Reproduce**
I ran an broadcaster like so:

```
./livepeer \
  -offchain \
  -datadir ~/.lpData/broadcaster \
  -orchAddr 127.0.0.1:8936 \
  -currentManifest \
  -v 99 2>&1 | tee broadcaster.log
```

And a transcoder/orchestrator like so: 

```
./livepeer \
  -datadir ~/.lpData/transcoder \
  -cliAddr ":7936" \
  -serviceAddr "127.0.0.1:8936" \
  -offchain \
  -v 99 -orchestrator -transcoder 2>&1 | tee transcoder.log
```

Then I booted up OBS, configured it to stream to `rtmp://127.0.0.1/movie` with a stream key of `stream`. Set to 1080p output, 1000kbps, `ultrafast` x264 settings.

**Expected behavior**
No crashy

**Comment by j0sh** [comment]
Does this happen on master? Should have been fixed in https://github.com/livepeer/go-livepeer/commit/e75958f0cbe2f63dbb7b82374284d19c301788ab

**Comment by iameli** [comment]
Ah, right you are. Thanks!
