### ISSUE TITLE
-ethPassword Change

### ISSUE THREAD

**Issue by rayj00** [livepeer/go-livepeer#763]
**Is your feature request related to a problem? Please describe.**
If a -ethPassword becomes public knowledge,  anyone with knowledge of the server can use or abuse the
livepeer infrastructure.
Accidentally revealed the -ethPassword
**Describe the solution you'd like**
The ability to change the password:  OldPW: xxxxxx  NewPW: xxxxxxx
**Describe alternatives you've considered**
No alternative attempted, however if there is an alternative, it should be documented in detail.
**Additional context**

**Comment by darkdarkdragon** [comment]
Livepeer stores private key in standard Geth format, so you can change password using Geth as outlined [here](https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts#account-update)
