### ISSUE TITLE
Custom Stream Keys via Auth Webhook

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#764]
**Is your feature request related to a problem? Please describe.**
Playback of RTMP ingest streams is protected by a stream key, but there is no programmatic way to discover this key for playback from other elements on the network, or to control the generation of the key.

**Describe the solution you'd like**
Currently, the RTMP auth webhook has a limitation that any backslashes from the returned manifestID will be incorrectly parsed during playback as being part of the rendition, based on the playback path convention of `manifestID/rendition/seqNo`.

Looking at the first backslash in the manifestID returned from the webhook would be a useful way to incorporate the RTMP stream key, which is conditionally autogenerated. So, if the manifestID contains a slash, we consider it a manifestid+streamkey (eg, fully formed RTMP StreamID), and this can be used for RTMP playback from other elements of the broadcaster's infrastructure.

Note that subsequent slashes after the first can be considered part of the stream key, without any issue.

**Describe alternatives you've considered**

An alternative is to set this as separate fields in the response, eg: `{"manifestID": mid, "streamKey": key}`. However, we would likely still have to scan the manifestID and terminate the stream if any invalid characters (currently just a backslash) are found.

We could also implement an API for explicit RTMP stream aliases, but that seems unwieldy compared to the webhooks approach.

**Comment by darkdarkdragon** [comment]
Looks like I don't know RTMP infrastructure well. What does this means `Playback of RTMP ingest streams is protected by a stream key`?
And what this means `this can be used for RTMP playback from other elements of the broadcaster's infrastructure.`?

**Comment by j0sh** [comment]
If you look at `createRTMPStreamIDHandler`  then you'll notice that the RTMP playback URL (which FFMpeg uses for segmenting) looks something like `rtmp://localhost/manifestID/streamKey` where the streamKey part is randomly generated.

The stream key protects the RTMP stream from "drive-by playbacks" where knowing the RTMP ingest URL also allows you to pull the RTMP stream. Providers may not necessarily want their users to pull incoming RTMP streams or act as the origin point for further distribution.

https://github.com/livepeer/go-livepeer/blob/15d70f06f2f4b6184838360aa19a15774a2d6d81/server/mediaserver.go#L188-L190

Since the streamKey is randomly generated, there's no way for anyone outside the node pull the RTMP stream. Returning the streamKey as part of the webhook response gives providers the flexibility of making the RTMP stream available for processing outside the Livepeer node.

**Comment by darkdarkdragon** [comment]
OK, thanks - wasn't aware that RTMP stream ingested in node is available to be consumed from same node. Pretty unexpected. We should clearly state this in documentation.

**Comment by j0sh** [comment]
> wasn't aware that RTMP stream ingested in node is available to be consumed from same node

Currently the stream keys prevent the RTMP from being consuming outside the goclient. But you are right, once we make it easy for users to consume RTMP outside the goclient, then it needs to be documented.
