### ISSUE TITLE
Can't build Docker images

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#766]
**Describe the bug**
`docker build -f Dockerfile.debian -t livepeerbinary:debian .` results in a variety of `can't load package` errors, [full log here](https://gist.github.com/iameli/13cc4a780cef5d3aac3caf6a5d51ecc2).

**To Reproduce**
`docker build -f Dockerfile.debian -t livepeerbinary:debian .`

**Expected behavior**
A working Docker build

`docker version`:

```
▶ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by iameli** [comment]
Hrmph, just worked for me when I tried again just now. No idea. Closing for now.

**Comment by darkdarkdragon** [comment]
@iameli This #769 should fix it.
