### ISSUE TITLE
Task breakdown for multi-T

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#775]

**Comment by angyangie** [comment]
Added to end of this [doc](https://docs.google.com/document/d/1KfEWm0z3svw10TrFH9hiMImkXocl3ba_S-8vmX94HNc/edit?userstoinvite=josh@livepeer.org&ts=5c647762&actionButton=1#)

**Step 1: Track remote transcoder capacity**

1. Add an option for Ts to specify their capacity via CLI, eg livepeer -transCap 5. As a rule of thumb, each T will be able to handle one segment per core (though capacity advertised is up to each T to determine).

- add `transCap` to `server.RunTranscoder` (in livepeer.go), `runTranscoder` (ot_rpc.go), `RegisterTranscoder`, `orch.node.serveTranscoder` (in orchestrator.go), `orch.ServeTranscoder`, `serveTranscoder`, `NewRemoteTranscoder`
- add `transCap` to `TranscoderClient.RegisterTranscoder` in lp_rpc.proto

2. Build the RemoteTranscoder struct, which will keep track of remote transcoder capacity, and implements the existing Transcoder interface:

```golang
type RT struct {
	capacity int
}

func NewRemoteTranscoder(capacity int) *RT {
  return &RT{ capacity: capacity }
}

func (r *RT) Transcode() {
}

func (r *RT) Capacity() int {
	return r.capacity
} 
```

**Step 2: Add multiple remote transcoder management**

3. Implement the `RemoteTranscoderManager` struct and its corresponding `Register` (not to be confused with the `lphttp.Register` method), `Unregister` and `Transcode` methods.

```golang
type RTManager struct {
	remotes []*RT
}

func (m *RTManager) Register(t *RT) {
	for i := 0; i < t.Capacity(); i++ {
		m.remotes = append(m.remotes, t)
	}
}

func (m *RTManager) Unregister(t *RT) {
	var remotes []*RT
	for _, v := range m.remotes {
		if v == t {
			continue
		}
		remotes = append(remotes, v)
	}
	m.remotes = remotes
}

func (m *RTManager) Transcode() {
	t, remotes := m.remotes[0], m.remotes[1:]
	m.remotes = remotes
	t.Transcode()
	m.remotes = append(m.remotes, t)
}
```

3. Add RemoteTranscoderManager to LivepeerNode (`Transcoder` interface is already a part of it).

```golang
type LivepeerNode struct {
         ...
	RTManager    *RTManager
	Transcoder     Transcoder
}
```

4. Add `n.RTmanager`, `n.Transcoder`, `RTManager.Register` and `RTManager.Unregister` to `serveTranscoder` method:

```golang
func (n *Node) serveTranscoder(capacity int) {
	if n.RTmanager == nil || n.Transcoder == nil {
	       manager := RTManager{}
                n.RTmanager = manager
                n.Transcoder = manager
	}
	t := NewRemoteTranscoder(capacity)
	n.RTmanager.Register(t)
	defer n.RTmanager.Unregister(t)
	// ... do rest ...
}
```

**Comment by j0sh** [comment]
> Add an option for Ts to specify their capacity via CLI, eg livepeer -transCap 5

We already have `-maxSessions` that is used for B and O, perhaps we could use the same flag for T, just for consistency.

> Add multiple remote transcoder management

Note that we'll eventually need to consider cases where a T is removed from the list while there is another segment in-flight to the same T. Under the list-management algorithm posted, the T would be re-added to the list each time. To fix this, we probably should maintain a separate set for "live Ts" and check T liveness before re-adding it to the list.

Also, the code posted is generally pseudocode; there should of course be bounds checking where appropriate.

> Add n.RTmanager, n.Transcoder, RTManager.Register and RTManager.Unregister to serveTranscoder method

```golang
func (n *Node) serveTranscoder(capacity int) {
	if n.RTmanager == nil || n.Transcoder == nil {
	       manager := RTManager{}
                n.RTmanager = manager
                n.Transcoder = manager
	}
```
The assignment and initialization of the manager / transcoder probably should happen earlier, perhaps during the server initialization phase that's kicked off from `livepeer.go`, rather than when a transcoder first connects.

As @darkdarkdragon noted in https://github.com/livepeer/go-livepeer/issues/748 , the T can currently only handle one job. But this looks to be a straightforward modification by making the [relevant parts](https://github.com/livepeer/go-livepeer/blob/e3af71c64385a5073fe8d0b43b235d151fbdae5b/server/ot_rpc.go#L86) in `ot_rpc.go` async.

**Comment by angyangie** [comment]
> We already have -`maxSessions` that is used for B and O, perhaps we could use the same flag for T, just for consistency.

Interesting idea! That would work. I initially thought that might interfere with `createRTMPStreamIDHandler` in mediaserver.go, which uses `maxSessions` to check for max rtmpConnections, but after some exploration, I see that a remote transcoder would never have to touch that code. Therefore, using `maxSessions` would be fine. 

> Note that we'll eventually need to consider cases where a T is removed from the list while there is another segment in-flight to the same T. Under the list-management algorithm posted, the T would be re-added to the list each time. To fix this, we probably should maintain a separate set for "live Ts" and check T liveness before re-adding it to the list.

Good observation. So, what you mean, is that `defer n.RTmanager.Unregister(t)` gets called, but, turns out that `t.Transcode()` is being called for a segment slightly before that, and therefore, `m.remotes = append(m.remotes, t)` adds the transcoder back on the list? 

> The assignment and initialization of the manager / transcoder probably should happen earlier, perhaps during the server initialization phase that's kicked off from livepeer.go, rather than when a transcoder first connects.

Yes, I thought about that too. Seems like a good move.

> ...straightforward modification by making the relevant parts in ot_rpc.go async.

I'll include in the next iteration of the plan!

**Comment by j0sh** [comment]
>  I see that a remote transcoder would never have to touch that code. Therefore, using maxSessions would be fine.

We can still set a different variable in standalone T to hold the capacity; just the flag could be reused in `livepeer.go`.

> So, what you mean, is that defer n.RTmanager.Unregister(t) gets called, but, turns out that t.Transcode() is being called for a segment slightly before that, and therefore, m.remotes = append(m.remotes, t) adds the transcoder back on the list?

Correct.

**Comment by angyangie** [comment]
This is done. Will close
