### ISSUE TITLE
Task breakdown for multi-O

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#776]

**Comment by angyangie** [comment]
(added to end of this [doc](https://docs.google.com/document/d/1KfEWm0z3svw10TrFH9hiMImkXocl3ba_S-8vmX94HNc/edit?userstoinvite=josh@livepeer.org&ts=5c647762&actionButton=1#))

1. Build BroadcastSessionManager struct:

```
type BroadcastSessionManager struct {
	broadcastSessions []*BroadcastSession
}
```

2. Edit `selectOrchestrator` to build and return `[]*BroadcastSessions`, not just a `BroadcastSession`. This will also involve changing how a single `BroadcastSession` will be stored/created in `startSession` and in `rtmpConnection` struct (`BroadcastSessionManager` will be stored instead of a single `BroadcastSession` . Below is a shortened version of `selectOrchestrator` changes to be made:

```golang
func selectOrchestrator(n *core.LivepeerNode, numOrhcs int) ([]*BroadcastSession, error) {
	// edit selectOrchestrator to return []*BroadcastSession
	
	orchInfos, err := n.OrchestratorPool.GetOrchestrators(numOrchs)
	
	var sessions *BroadcastSession
	
	for _, info := range orchInfos {
		session = &BroadcastSession{OrchestratorInfo: info ....}
		sessions = append(sessions, session)
	}
	
	return sessions 
}
```

3. Build out rest of the `BroadcastSessionManager` struct methods, including `CheckStatusOfList` helper method.

```golang
func (bsm *BroadcastSessionManager) SelectFromList(numOrchs int) (*BroadcastSession) {
	sessions := CheckStatusOfList(numOrchs, bsm.broadcastSessions)
	bsm.broadcastSessions = sessions
	
	sess, sessions := bsm.broadcastSessions[0], bsm.broadcastSessions[1:]
	bsm.broadcastSessions = sessions
	
	return &sess
}

func (bsm *BroadcastSessionManager) AddToList(sess) {
	bsm.broadcastSessions = append(bsm.broadcastSessions, sess)
}

func CheckStatusOfList(numOrchs int, broadcastSessions BSM.broadcastSessions) (BSM.broadcastSessions) {
    	reqLengthOfList := numOrchs*2
    	if len(broadcastSessions) < numOrchs {
        	orchInfos, err := selectOrchestrator(reqLengthOfList)
    	} else {
		return BSM.broadcastSessions
	}
	
	var sessions *BroadcastSession
	for _, info := range orchInfos {
		session = &BroadcastSession{OrchestratorInfo: info}
		sessions = append(sessions, session)
	}
	
	return sessions
}
```

4. Integrate `SelectFromList` and `AddToList` to processSegment, which will select session to use in `SubmitSegment` and beyond.

```golang
func processSegment(cxn *rtmpConnection, seg string, numOrchs int) {
	sess = cxn.BroadcastSessionsManager.SelectFromList(numOrchs)
    	res, err := SubmitSegment(sess, o, seg, nonce)
    
	if err == nil {
        	       cxn.BroadcastSessionsManager.AddToList(sess)
    	}
}
```

**Comment by j0sh** [comment]
```func CheckStatusOfList(numOrchs int, broadcastSessions BSM.broadcastSessions) (BSM.broadcastSessions) {
 ...
	var sessions *BroadcastSession
	for _, info := range orchInfos {
		session = &BroadcastSession{OrchestratorInfo: info}
		sessions = append(sessions, session)
	}
```

Not quite clear on what this last bit does; don't we already have a list of BroadcastSessions from `selectOrchestrator` ?

Note that any refresh via `selectOrchestrator` should be done async, and we should still return an O if any are available for processing the current segment.

Also we might want to consider what might happen if we're capacity constrained on the network; do we want to re-request a session from Os that we are currently using? Under the current scheme, this runs the risk of hitting the orchestrator's cap and excluding the O from subsequent segments (even though we have been using it successfully).

Lastly, there is a issue when B-supplied OS is in the picture. Since segment paths are predictable, competing Os could attempt to "front run" or overwrite other Os by inserting bogus data for segments they aren't assigned to. This is possible because B currently creates a single OS session with just the manifestID as the path. To fix this, we might want to generate a fresh **external** OS session for each O using a prefix such as "manifestID/$randomPrefixPerOrch" to avoid these types of issues. This can be referenced using the existing `BroadcastSession.BroadcasterOS` field; we'll need to remove any references to `GetOSSession` from the current playlist. This is only applicable for **external** OS; for in-memory OS we'll still need a single OS session shared among all O (we don't have the same concerns with in-memory OS because O doesn't have access to it).

**Comment by angyangie** [comment]
> Not quite clear on what this last bit does; don't we already have a list of BroadcastSessions from selectOrchestrator ?

Ah yesss. I meant to remove that!

> Note that any refresh via selectOrchestrator should be done async, and we should still return an O if any are available for processing the current segment.

What do you mean by " we should still return an O if any are available for processing the current segment"? In what scenario?

> Also we might want to consider what might happen if we're capacity constrained on the network; do we want to re-request a session from Os that we are currently using? Under the current scheme, this runs the risk of hitting the orchestrator's cap and excluding the O from subsequent segments (even though we have been using it successfully).

We could just add additional Orchs to the list, keeping the ones we on the list. For example, if `reqLengthOfList` = 6, and we're working with 3 Os, we take the response from `GetOrchestrators` and add 3 O's (filtering out for those that are already on our list). We'd need a "live orchestrators" list for that to work, similar to T's.

> Lastly, there is an issue when B-supplied OS is in the picture...

Good catch. Is this something you think we should build for this initial MVP version?

**Comment by j0sh** [comment]
> What do you mean by " we should still return an O if any are available for processing the current segment"?

If any Os are available in the list, those should be used rather than waiting for the list refresh to complete.

Simplified example - add in the appropriate locking, bounds checking, etc:

```golang
func (bsm *BroadcastSessionManager) SelectFromList(...) {
 sz = len(bsm.broadcastSessions)
  if (sz < numOrchs) {
    // this is run async and resets bsm.broadcastSessions.
    go refreshList()
  }
  if sz <= 0 {
    // no orchestrators avail so return early
    return nil
  }
  // we have at least one session available
  sess, bsm.broadcastSessions = bsm.broadcastSessions[0], bsm.broadcastSessions[1:]
  return &sess
}
```

> Good catch. Is this something you think we should build for this initial MVP version?

Yes. It can be done separately, but we shouldn't ship without the fix.

**Comment by ericxtang** [comment]
Seems like this is done (considering we are mostly done with the engineering already).  Can we close?

**Comment by angyangie** [comment]
Yep! We're done with this
