### ISSUE TITLE
Merge API Documentation

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#778]
Let's use the readthedoc for this.

I think we should include the information from the [demo script](https://hackmd.io/YtCHagQeTUC6svkmrSNsRQ?view) and the [1-pager](https://www.notion.so/ericxtang/Livepeer-Transcoding-API-95db927400634992a31e89034f8e6b54).  Maybe using the 1-pager as the "Intro", and demo script as the "Getting Started Guide".

**Comment by j0sh** [comment]
Is this resolved by https://github.com/livepeer/docs/blob/master/docs/source/demo.md ?
