### ISSUE TITLE
Endpoint to Delete Stream

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#782]
@f1l1b0x had suggested to create an endpoint that allows users to delete a running stream based on the ManifestID. This endpoint will give the user the ability to shut access to a certain user (imagine you are Twitch, and you want to stop a specific stream based on an ingest URL you generated).

**Comment by j0sh** [comment]
We could add a CLI endpoint to stop a stream.

That wouldn't really shut off access if a user wants to retry the stream, but it seems that's a concern best handled outside the goclient itself (eg, reject via the auth webhook).
