### ISSUE TITLE
Metrics: redundancy rate

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#785]
Redundancy rate - how much duplicate transcoding work is done

**Comment by j0sh** [comment]
Assuming we even do redundancy -- wouldn't this be a fixed number?

**Comment by darkdarkdragon** [comment]
yes, but it can be different per deployment, so overall rate will not be constant.
plus, if in future we will implement some SLA (which actually will set redundancy level) in pricing menu for B to choose from - then it will be even more dynamic.

**Comment by j0sh** [comment]
> yes, but it can be different per deployment, so overall rate will not be constant.

Will the rate change during the lifetime of the deployment?

Also, are we tracking multiple deployments with the same Prometheus? There were issues with this idea last time we discussed it.

**Comment by darkdarkdragon** [comment]
> Will the rate change during the lifetime of the deployment?

Right now no, but if in future B will be able to select this param?

> Also, are we tracking multiple deployments with the same Prometheus?

That was idea?

>  There were issues with this idea last time we discussed it.

What ones? I don't recall.
