### ISSUE TITLE
Structured Ingest URL Paths

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#791]
**Is your feature request related to a problem? Please describe.**
Currently, our ingest URLs are relatively unstructured. The manifestID is passed in as an optional query string parameter, with the path ignored:

```
rtmp://ingest-host/path/is/ignored?manifestID=mid
```

There is some concern about the use of "special characters" to form the query string. Additionally, it would be nice to make the RTMP URL more consistent with the HLS playback URL, which is of the form:

```
http://ingest-host/stream/<manifestID>.m3u8
http://ingest-host/stream/<manifestID>/<rendition>.m3u8
http://ingest-host/stream/<manifestID>/<rendition>/<num>.ts
```

**Describe the solution you'd like**

We can use the first part of the RTMP path as the manifestID and the rest as the stream key. For example:

```
# manifest ID = "streamName"
# stream key = "secretStreamKey"
rtmp://host/streamName/secretStreamKey

# manifest ID = "streamName"
# stream key = "secret/stream/key"
rtmp://host/streamName/secret/stream/key

# manifest ID = "streamName"
# Stream key = randomized
rtmp://host/streamName

# manifest ID = randomized
# Stream key = randomized
rtmp://host
```

**Additional context**

Because of how we parse URLs for HLS playback [1], the manifestID cannot have slashes in it. This is the reason the streamKey could end up being `secret/stream/key` in the URL `rtmp://host/streamName/secret/stream/key` .

[1] http://host/stream/<manifestID>/<rendition>/<num>.ts

**Comment by f1l1b0x** [comment]
we should follow the same naming like anyone else is

rtmp://host/application-name/streamname


the hls url should result in this format

http://host/application-name/streamname/playlist.m3u8


We also should offer an alternate playlist next to it:

http://host/application-name/alternate-streamname/playlist.m3u8

it is important that the alternate-streamname is not revealing the original streamname to improve the security for the missing flash auth.

We should deny the use of special chars in the application and streamname since many encoders out there will choke on them. 

Next to allowing any application and streamname to be used we should allow a way to configure LPMS that only app and streamnames pre-created by the admin would be valid to use and connections to non existing stream endpoints that receive a stream should revoke it.

**Comment by j0sh** [comment]
>we should follow the same naming like anyone else is
>rtmp://host/application-name/streamname

Here I'm going to refer to the `streamname` as the "manifest ID" since that is Livepeer's name for the thing.

Note the primary reason for this convention is because most RTMP media servers were able to serve multiple applications, and used the path to route the stream into the correct application. Most real-world services don't expose more than one application, so for most services, the `application-name` part of the path prefix ends up being a constant (and hence, relatively redundant). It's a server implementation detail that's leaking through to the user.

Here, Livepeer doesn't have any other RTMP applications, so I'm curious exactly how we should handle this `application-name/streamname` breakdown. Specifically, what would the `application-name` part be? And how would Livepeer users benefit from us following this?

> the hls url should result in this format
> http://host/application-name/streamname/playlist.m3u8

For HTTP, we have a `/stream/` prefix for historical reasons; this is how we identify the stream as being routed to LPMS, and in earlier days it was planned to build other features around different prefixes (eg, `/vod/` for the full playlist).

If you feel strongly about naming consistency, we can incorporate the following scheme:

```
Ingest rtmp://host/stream/<manifestID>
Output http://host/stream/<manifestID>.3u8
```

where the `/stream/` becomes a fixed part of the RTMP path. However, I'd veer towards making this optional (eg, by stripping out the `/stream/` part) since it doesn't serve a concrete purpose other than satisfying a taste for consistency.

> We also should offer an alternate playlist next to it:

The manifest ID can be decoupled from the  RTMP URL entirely if you're using a webhook, so there doesn't need to be any correspondence between the RTMP and HLS addresses. For example:

```
Ingest: rtmp://host/any/path
--> (Invoke webhook to authenticate stream. Return ManifestID from webhook) -->
Output: http://host/stream/manifestID.m3u8
```

What does adding an alternate playlist give us over the webhook setup? How is the alternate playlist configured and how do users discover it?

> it is important that the alternate-streamname is not revealing the original streamname to improve the security for the missing flash auth.

We have stream keys to protect RTMP playback, and webhooks to protect HLS playback. Aside from the alternate playlist, is flash auth still needed?

I can see maybe adding programmatic support for stream-name aliases but it wouldn't be for security reasons.

> We should deny the use of special chars in the application and streamname since many encoders out there will choke on them.

I'm not sure what there is to deny. We have never required any specific RTMP URL structure beyond the URL being well-formed. This proposal is about introducing a few conventions around how we interpret the URL path *by default* to avoid using a query parameter to specify the manifest ID.

If a user introduces auth webhooks into their flow, then how the URL path is interpreted becomes user-defined. If a RTMP client connects with a URL that contains query-string parameters, why can't those parameters be carried through to webhook auth? The client has already connected with a well-formed URL. What is there to deny?

> Next to allowing any application and streamname to be used we should allow a way to configure LPMS that only app and streamnames pre-created by the admin would be valid to use and connections to non existing stream endpoints that receive a stream should revoke it.

Webhooks again solve this issue.

**Comment by darkdarkdragon** [comment]
@j0sh 
>  so I'm curious exactly how we should handle this application-name/streamname breakdown. Specifically, what would the application-name part be? And how would Livepeer users benefit from us following this?

When we was discussing authentication for Transcode API, we came to idea of prefixing users manifests like this: `companyName_manifestID` and to authenticate based on first part of the manifest id. Urls like `rtmp://host/companyName/streamname` would naturally look much better, but will require some changes on our side. Simplest way is just to declare that manifest id is always consist from two non-empty parts.

**Comment by j0sh** [comment]
> When we was discussing authentication for Transcode API, we came to idea of prefixing users manifests like this: companyName_manifestID and to authenticate based on first part of the manifest id. Urls like rtmp://host/companyName/streamname would naturally look much bette

In that thread it was also mentioned that type of breakdown is also quite specific to the business logic. In this case, the `companyName/streamName` would have been Livepeer-specific. We shouldn't assume most broadcasters would want to follow this type of "multi-tenant" scheme; some might just need a stream name (with the 'application name' or 'company name' becoming an unused appendage). One could plausibly seeing broadcasters also wanting a three-level breakdown, and so forth.

> Simplest way is just to declare that manifest id is always consist from two non-empty parts.

While we currently have a technical reason for manifest IDs being restricted to one level of the address path (URL parsing), enforcing further breakdowns end up being arbitrary. And I'm not so sure that it really matters for users anyway. How do users benefit?

For what it's worth, I can maybe see a technical path towards supporting arbitrary depth manifest IDs. But I'm not sure that we actually *need* that feature, and we shouldn't enforce any special rules unless there's a good reason for it.
