### ISSUE TITLE
Invoking Claim Rewards (ClaimEarnings) Fails

### ISSUE THREAD

**Issue by natemiller1** [livepeer/go-livepeer#795]
**Description**
When invoking claim rewards via the cli (option 10), the transaction does not complete. I receive the same error each time:
```
Invoking transaction: "claimEarnings".  Params: [20]
Transaction Failed: failed to estimate gas needed: gas required exceeds allowance or always failing transaction
```

**Summary**
I joined as a transcoder in round 1265. 
I've verified I have sufficient gas/ether. I'm also running a geth light client. 
I've restarted both geth and livepeer multiple times with the same result. 
Everything else appears to function normally, I can set my transcoder config and manually call rewards if necessary.
Last Claim round is listed at 0 on my node stats
Start Round is listed at 1265
Speaking with other transcoders, I've seen that when they claim rewards, the round they claim goes into Params (e.g. [1278])
Everytime, no matter what round I attempt to claim, params is always [20] (I've tried 1265, 1270, 1276, 1277, 20, and 100)
This isn't an emergent problem at the time since I'm compounding rewards anyway.

My livepeer config:
```
ExecStart=/path/livepeer -datadir /path/.lpData -ipfsPath /path/livepeer -log_dir /path/logs -transcoder -ethUrl ws://127.0.0.1:8546 -publicIP ip.address. -ethPassword PASSWD
```

**Desktop**
Running geth and livepeer in systemd
Ubuntu 18.04, AWS VPS

**Comment by yondonfu** [comment]
@natemiller1 What release version of the Livepeer node are you using?

**Comment by natemiller1** [comment]
Yep, that was it... Not sure how I managed to install an earlier version, believe I was running 0.2.4. Updated to 3.2 and it was fixed. [Insert embarrassed face emoji]

**Comment by yondonfu** [comment]
Great! Glad to hear it was fixed by updating the node version.
