### ISSUE TITLE
Support IPC/RPC Calls

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#80]
The Livepeer node should support RPC calls.  Geth gives an example of how it can be implemented.

Take a look at `rpc/ipc.go` as an example.
Also look at: 
https://github.com/nolash/go-ethereum-p2p-demo/blob/master/B1_RPC.go
https://github.com/nolash/go-ethereum-p2p-demo/blob/master/B2_Method.go
https://github.com/nolash/go-ethereum-p2p-demo/blob/master/B3_Message.go

**Comment by eladmallel** [comment]
@ericxtang what kinds of RPC calls did you have in mind under this issue? Is this still relevant?

**Comment by j0sh** [comment]
My guess is that the CLI webserver falls under RPC here. @ericxtang should we close this issue?

**Comment by ericxtang** [comment]
No longer relevant.
