### ISSUE TITLE
Transcoder node reward call output showing incorrect LPT amount

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#802]
**Describe the bug**
When the transcoder node calls reward it outputs the txn hash and a success message indicating how many LPT were generated. The number of LPT shown seems incorrect. See:

```
******************************Eth Transaction******************************

Invoking transaction: "reward".  Hash: "0x3c3d08b923333dc8b781eb1683507eee93580b0b771dd064bdb2317397c5f9f5".  Params: []

***************************************************************************
I0327 02:02:53.645488   30853 rewardservice.go:146] Called reward for round 1293 - 594.186376801240537347 LPT rewards minted
```

When viewing that txn hash it shows 635 LPT generated: https://etherscan.io/tx/0x3c3d08b923333dc8b781eb1683507eee93580b0b771dd064bdb2317397c5f9f5

But the CLI output shows 594.

**To Reproduce**
1. Observe reward call output from a running txn node and compare it to the txn on etherscan.

**Expected behavior**
The correct amount should be output

**Comment by yondonfu** [comment]
After the [earnings distribution contract accounting bug fix](https://forum.livepeer.org/t/protocol-accounting-bug-fix-retrospective/391), the BondingManager contract started splitting up inflationary rewards minted by a transcoder into a reward pool for delegators and a reward pool for the transcoder. As a result, if a client queries only for the delegator reward pool, the returned value will not reflect the total inflationary rewards minted by a transcoder during a round. The node currently does this - see this [logging statement](https://github.com/livepeer/go-livepeer/blob/master/eth/eventservices/rewardservice.go#L146).

We can fix this issue by summing together the delegator reward pool and transcoder reward pool to calculate the total inflationary rewards.

**Comment by ericxtang** [comment]
@yondonfu is there a fix we can add to the `go-livepeer` node so we can add the 2 reward pools together?

**Comment by yondonfu** [comment]
Yep, but I actually think an easier alternative fix would be for the node to query for the `Reward` event which should include the total inflationary rewards minted after the `reward` transaction is mined.
