### ISSUE TITLE
The Hosted API Node

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#812]
Place holder for eng tasks in [this release proposal](https://docs.google.com/document/d/1gDNiuRu3r2i-yICc3iChh7ItlY6l3jfHLb5ZzMpoaVk/edit)

**Comment by iameli** [comment]
Closed in favor of the API issues on LivepeerJS https://github.com/livepeer/livepeerjs/issues?q=is%3Aissue+is%3Aopen+label%3A%22API+Node+Prototype%22
