### ISSUE TITLE
Step 1: Track remote transcoder capacity

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#817]
1. Add an option for Ts to specify their capacity via CLI, through maxSessions. As a rule of thumb, each T will be able to handle one segment per core (though capacity advertised is up to each T to determine).
* add `maxSessions` to `server.RunTranscoder` (in livepeer.go), `runTranscoder` (ot_rpc.go), `RegisterTranscoder`, `orch.node.serveTranscoder` (in orchestrator.go), `orch.ServeTranscoder`, `serveTranscoder`, `NewRemoteTranscoder`
* add `MaxSessions` to `TranscoderClient.RegisterTranscoder` in `lp_rpc.proto`

2. Build the RemoteTranscoder struct, which will keep track of remote transcoder capacity, and implements the existing Transcoder interface:
```
type RT struct {
	capacity int
}

func NewRemoteTranscoder(capacity int) *RT {
  return &RT{ capacity: capacity }
}

func (r *RT) Transcode() {
}

func (r *RT) Capacity() int {
	return r.capacity
}
```

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/833/commits/378e9f4ee5b7d046fb97562e9c92023c10ea834b
