### ISSUE TITLE
Step 2: Add multiple remote transcoder management

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#818]
Implement the `RemoteTranscoderManager` struct and its corresponding Register (not to be confused with the `lphttp.Register` method), `Unregister` and `Transcode` methods.
* Keep in mind that we'll eventually need to consider cases where a T is removed from the list while there is another segment in-flight to the same T. Under the list-management algorithm posted, the T would be re-added to the list each time. We can maintain a "live Ts" list and check T liveness before re-adding it to the list (not pictured below). (more details: https://hackmd.io/XrK4nA95TGqwNX8FnHXaiQ) 
```
type RTManager struct {
	remotes []*RT
}

func (m *RTManager) Register(t *RT) {
	for i := 0; i < t.Capacity(); i++ {
		m.remotes = append(m.remotes, t)
	}
}

func (m *RTManager) Unregister(t *RT) {
	var remotes []*RT
	for _, v := range m.remotes {
		if v == t {
			continue
		}
		remotes = append(remotes, v)
	}
	m.remotes = remotes
}

func (m *RTManager) Transcode() {
	t, remotes := m.remotes[0], m.remotes[1:]
	m.remotes = remotes
	t.Transcode()
	m.remotes = append(m.remotes, t)
}
```

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/833/commits/24b949e5f7af099158109059e05854f26ba7ac00
