### ISSUE TITLE
Step 3: Add Trasncoder Management Logic to livepeer.go

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#819]
Add `RemoteTranscoderManager` to `LivepeerNode` (`Transcoder` interface is already a part of it).
```
type LivepeerNode struct {
         ...
	RTManager    *RTManager
	Transcoder     Transcoder
}
```

Add `n.RTmanager`, `n.Transcoder`, `RTManager.Register` and `RTManager.Unregister` to livepeer.go:
```
	if n.RTmanager == nil || n.Transcoder == nil {
	       manager := RTManager{}
                n.RTmanager = manager
                n.Transcoder = manager
	}

```

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/833/commits/20932449408ec2089d57bf023325b5a170766147
