### ISSUE TITLE
Step 5: Multi-T Acceptance Testing

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#821]
**Multi-T Tests:**

T is able to advertise its capacity at startup. Once T is connected to any O, it will be sent that number of segments to Transcode from the O, all one after the other, until the T is handling one segment per core advertised through its capacity flag. We don't allow Ts to have more than one segment in flight per core, which will mitigate back logging.

**Note**: For all acceptance tests below, make sure that output stream is coming back with ordered segments!

1. Stream with 3 Ts each with a capacity of 2, all connected to a single Orchestrator:
- Send any number of streams for transcoding to O - O should send first two segments to the first T, next two segments to the next T, next two segments to the last T, then circle back to the first T… so on and so forth.

2. Stream with 5 Ts each with a capacity of 5, all connected to a single Orchestrator:
- Send any number of streams for transcoding to O - O should send first 5 segments to the first T, next 5 segments to the next T, next 5 segments to the next T…  until the last T has been sent 5 segments, then circle back to the first T… so on and so forth.

3. O starts out with one registered T1, capacity of 3:
- T2 connects to same O, capacity of 4. Once T1’s advertised capacity has been reached (i.e. once T1 has received 3 segments in a row for transcoding), T2 receives 4 segments in a row for transcoding. T1 is then sent 3 segments for transcoding… so on and so forth.
- T3 connects to the O with a capacity of 2. Once T1 and T2’s advertised capacity has been reached, T3 is sent two segments in a row for transcoding. The rest of the rotation remains the same.

4. O starts out with 3 registered Ts, all with capacity of 3. All three Ts are being sent 3 segments in a row before O moves on to send segments to another T: 
- T1 disconnects from O. No segments are sent to T1, and rotation continues as before, with T2 and T3.
- [IF we implement retries, otherwise ignore letter a] - If segment fails to be transcoded, it is sent to the next transcoder on the list and is transcoded correctly.
- T2 disconnects from O. No segments are sent to T2, and rotation continues as before, with T3.

**Other areas to test:**
- Latency
- Additional uploads/downloads
- Remote v. local transcoders
- Specific transcoder errors

**Comment by j0sh** [comment]
Do we consider this part done?

**Comment by ericxtang** [comment]
I remember @angyangie wrote down the acceptance tests.  Angie?

**Comment by angyangie** [comment]
Yes these are done! I tested locally. What's remaining is test-harness benchmarking.

I'll close this issue.
