### ISSUE TITLE
FFMPEG Test Video Causes Transcoding Issue

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#840]
**Describe the bug**
This ffmpeg test video command causes some transcoding issues: 
```
ffmpeg -re -f lavfi -i testsrc=size=1280x720:rate=30 -f lavfi -i sine -vf drawtext="text='%{localtime\:%X}':fontsize=20:fontcolor=white:x=7:y=7" -vcodec libx264 -vb 2000k -preset ultrafast -x264-params keyint=60 -acodec aac -f flv rtmp://localhost:1935/stream/test1
```

The video is suppose to look like:

<img width="1680" alt="Screen Shot 2019-04-25 at 7 18 03 PM" src="https://user-images.githubusercontent.com/345743/56774034-e1a1b900-678e-11e9-91cd-093d936ff5b1.png">

But every few segments, it looks like:
<img width="1680" alt="Screen Shot 2019-04-25 at 7 18 06 PM" src="https://user-images.githubusercontent.com/345743/56774039-e4041300-678e-11e9-986b-0fcb43735798.png">

**To Reproduce**
1. Set up a local B/O/T setup
2. Run the ffmpeg command
3. Watch in Safari

**Expected behavior**
Video transcoding to be successful

**Comment by j0sh** [comment]
Haven't been able to reproduce this in Safari or ffplay [1].

One thing I've noticed is that using a keyframe interval of 60 at 30fps regularly produces segments longer than 2 seconds, which has a higher likelihood of impacting playback. It might help to tighten the keyframe interval to 30 and maybe set a closed GOP, eg: `-x264-params keyint=30:min-keyint=30  -flags cgop`. Using ffmpeg native flags, the equivalent would be `-g 30 -keyint_min 30 -flags cgop`

Some other questions:

* Anything else particular about the environment?
* What version of ffmpeg is this? For what it's worth, my HEAD here is `399c8e8` but the `n4.1.1` tag we use for goclient should also work.
* Does ffplay or other players show artifacts? Or is it just Safari? 
* Does this occur with specific media playlists? Source and/or transcoded?
* Does the original RTMP also show artifacts? [2]

[1] Had to build a ffmpeg with the drawtext filter enabled and tweak the CLI flags but I don't think drawtext really makes a difference for this test case:

```
ffmpeg -re -f lavfi -i testsrc=size=1280x720:rate=30 -f lavfi -i sine -vf drawtext="fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf:text='%{localtime\:%X}':fontsize=20:fontcolor=white:x=7:y=7" -vcodec libx264 -vb 2000k -preset ultrafast -x264-params keyint=60 -acodec aac -f flv rtmp://localhost/test1
```

[2]  If you get stuck with the stream key, recall can be set by ingesting to `rtmp://host/manifestID/streamKey`, and played back with the exact same URL.
