### ISSUE TITLE
Test-harness instances stop receiving streams after certain # of streams sent to it

### ISSUE THREAD

**Issue by angyangie** [livepeer/go-livepeer#843]
**Describe the bug**

When streaming 5 streams into the test-harness (3 from twitch, one from OBS, one from test-harness BBB video), using [this](https://gist.github.com/angyangie/7bedeffd53e1b50e99b24b4a5fb9c00a) `multigroup.js` configuration (20 Ts, 20 Os, 1 B), all orchestrators seem to go offline periodically, for 3-5 minutes at a time. Transcoding rate goes down to 0%, we get `NoOrchestrators` and `ReadBody` errors from all O's, and ultimately discovery errors of  `caller=rpc.go:181 msg="Did not connect: context deadline exceeded"` and `"Discovery error=Could not get orchestrator: rpc error: code = Unknown desc = Invalid orchestrator request (OrchestratorCapped)"`. 

See dashboard here: http://34.74.10.88:3001/d/ZsZv-B3iz/livepeer-overview?orgId=1&from=1556313277185&to=1556314656952

**To Reproduce**

1. Use [this](https://gist.github.com/angyangie/7bedeffd53e1b50e99b24b4a5fb9c00a) `multigroup.js` to set up test-harness (run `node examples/multigroup.js`)
2. Stream using OBS to whatever RTMP port is output at the end of that file ^. Ex: rtmp://34.74.248.47:2548
3. Use the steps below and repeat 3 times to run 3 twitch live streams through our system. 

* Go to twitch, select any top channel
* Use youtube-dl, run youtube-dl -g <twitch_url>
* You should get a manifest URL
* Use ffmpeg: ffmpeg -re -i <manifest_url> -c:v copy -c:a aac -f flv <ingest_url>

4. Use ` ./test-harness stream angie-multigroup` with your own deployed test-harness name, to stream BBB.
5. Watch one of the streams using `ffplay http://34.74.248.47:2548/stream/current.m3u8` (insert your own IP address and port number)
6. Watch all transcoding cease

**Expected behavior**
Transcoding should remain at 100%.

**Screenshots**

<img width="1328" alt="Screen Shot 2019-04-26 at 5 23 24 PM" src="https://user-images.githubusercontent.com/16169518/56838313-8bdf1680-684b-11e9-90a8-26c380bd0381.png">

<img width="1680" alt="Screen Shot 2019-04-26 at 5 28 42 PM" src="https://user-images.githubusercontent.com/16169518/56838327-94375180-684b-11e9-80ff-41b310b37c8e.png">

<img width="1680" alt="Screen Shot 2019-04-26 at 5 29 01 PM" src="https://user-images.githubusercontent.com/16169518/56838340-9bf6f600-684b-11e9-8d37-4f60d2c1c253.png">

<img width="1680" alt="Screen Shot 2019-04-26 at 5 30 27 PM" src="https://user-images.githubusercontent.com/16169518/56838397-ce085800-684b-11e9-9650-9d25f8ba0d8e.png">

**Comment by angyangie** [comment]
@darkdarkdragon @ya7ya @j0sh this is happening ... will continue looking into it Monday. If you see anything on your end, feel free to discuss here.

**Comment by j0sh** [comment]
Just to clarify, does this seem more like an issue with the goclient or the test harness? From a quick glance it appears there are connectivity issues between B/O.

**Comment by angyangie** [comment]
Yes, I do think you're right. The issue persists even with 2 streams being streamed simultaneously. That shouldn't be the case. I've tested that scenario locally, and all works well

**Comment by ericxtang** [comment]
Another way to test it is manually deploy on GCP and see if we can reproduce.

**Comment by angyangie** [comment]
**Update:** 

**Another way to reproduce:**
- Deploy 12 instances, 10 Os and 1 B
- Run `./test-harness stream -m 20 <name of your deployment>`
- See in grafana that  "Concurrent Streams" in Grafana = 12 (or another number), not 20 as expected
- Most importantly, curling `curl http://<ip_address>/stream/current.m3u8` will be left hanging. No response
- Stop the stream multiplier, and the  "Concurrent Streams" in Grafana still remains at 12, though all graphs have stopped showing streams coming in (this number varies)
- Try to stream a single stream into that ... no streams are "accepted" anymore. No more transcoding happens. 

**Thoughts on what could be happening:** 


- Neither the FFMPEG command to run streams, nor the stream simulator seem to be the problem. 
- When running ` go run -race cmd/livepeer/livepeer.go -broadcaster`, we see a lot of potential race conditions in LPMS. See logs here: [logs.txt](https://github.com/livepeer/go-livepeer/files/3159349/logs.txt)
- Potential issue with grpc:

```
Starting session refresh
I0508 19:51:13.734985       1 rpc.go:175] Connecting RPC to https://o_a_9:8935
I0508 19:51:13.735041       1 rpc.go:175] Connecting RPC to https://o_a_1:8935
I0508 19:51:13.735113       1 rpc.go:175] Connecting RPC to https://o_a_4:8935
I0508 19:51:13.735168       1 rpc.go:175] Connecting RPC to https://o_a_7:8935
I0508 19:51:13.735243       1 rpc.go:175] Connecting RPC to https://o_a_5:8935
I0508 19:51:13.735336       1 rpc.go:175] Connecting RPC to https://o_a_3:8935
I0508 19:51:13.735359       1 rpc.go:175] Connecting RPC to https://o_a_2:8935
I0508 19:51:13.735386       1 rpc.go:175] Connecting RPC to https://o_a_8:8935
I0508 19:51:13.735414       1 rpc.go:175] Connecting RPC to https://o_a_6:8935
I0508 19:51:13.735464       1 rpc.go:175] Connecting RPC to https://o_a_0:8935
```
Rpc.go `startOrchestratorClient` is starting, but never seems to finish or timeout (there is supposed to be a 3 sec timeout during O refresh but we've seen weird things happen within golang HTTP handling
). Seems like `refreshSessions` or `selectOrchestrators` never finishes (both use `OrchestratorPool.GetOrchestrators` and ping O's to find their availability). O is up in all of those situations.

Currently, we're adding more logging to `startOrchestratorClient`and testing out in test-harness.
