### ISSUE TITLE
Feature: Webhook on B for managing O connection Info in Offchain mode

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#851]
**Is your feature request related to a problem? Please describe.**
An operator currently cannot control the O connection information on a B node dynamically (it can only be done on the command line).

**Describe the solution you'd like**
Add an API on B so the operator of a private offchain Livepeer deployment has the ability to:
* Query the orchAddr array on a B
* Dynamically add / remove orchAddr on a B

**Comment by iameli** [comment]
I kind of like the opposite approach @j0sh suggested - B's fire a webhook to their API node every time they need a list of orchestrators. I like that this causes there to be less state on the Bs and more on the APIs.

**Comment by j0sh** [comment]
Note that @darkdarkdragon has addressed the first part here by adding the orchestrator address list to the node's `/status` response, so the orchestrator list can be queried via CLI: https://github.com/livepeer/go-livepeer/pull/848/commits/ad31d59f83e8f7d2c096934f449afe3aa0f5324f

**Comment by iameli** [comment]
This would be good to have soon. I'm currently using a very silly trick to handle orchestrator auto-scaling in the MI prod cluster — specifying a large quantity of dummy orchestrators that I can grow into later with a Kubernetes StatefulSet:

```
-orchAddr=prod-transcoder-0.prod-transcoder.default.svc.cluster.local:8935,prod-transcoder-1.prod-transcoder.default.svc.cluster.local:8935,prod-transcoder-2.prod-transcoder.default.svc.cluster.local:8935,prod-transcoder-3.prod-transcoder.default.svc.cluster.local:8935,prod-transcoder-4.prod-transcoder.default.svc.cluster.local:8935,prod-transcoder-5.prod-transcoder.default.svc.cluster.local:8935,prod-transcoder-6.prod-transcoder.default.svc.cluster.local:8935,prod-transcoder-7.prod-transcoder.default.svc.cluster.local:8935,prod-transcoder-8.prod-transcoder.default.svc.cluster.local:8935,prod-transcoder-9.prod-transcoder.default.svc.cluster.local:8935
```

I've already got the active orchestrator list in the API, so I just need go-livepeer to ask for it via webhook.

Brief, vague proposal:

New flag: `--orchestrator-webhook-url=https://livepeer.live/api/orchestrator`
This endpoint is polled periodically for a JSON list of orchestrators. We shouldn't wait on a webhook response _every_ time we're utilizing a list of orchestrators — that's an area of the system where we want to move as quickly as possible, but we could poll every 5-20 seconds?

(Perhaps controllable via `--orchestrator-webhook-frequency=5s`?)

The webhook should return a JSON list of objects with "address" properties, like so:

```json
[
  {
    "address":"https://gke-eth-nodes-prod-k80-8afd2e1b-2mml.livepeer.live"
  },
  {
    "address":"https://orchestrator.iame.li"
  }
]
```

Then that becomes the internal list of orchestrators.

Open question: do we stop working with existing orchestrators if they're not on the new list?

**Comment by j0sh** [comment]
> This endpoint is polled periodically for a JSON list of orchestrators. We shouldn't wait on a webhook response every time we're utilizing a list of orchestrators

We can hit the webhook whenever the orchestrator list refreshes. This would only happen if the broadcaster senses it's running low on Os in the pool for a given stream.

This would be very straightforward to implement using the OrchestratorPool interface, then the system takes care of refreshing as appropriate.

> do we stop working with existing orchestrators if they're not on the new list?

If an O is still in the list when a refresh is called, it will remain in the list unless evicted. Eviction only happens if there's an error, a timeout, etc.

**Comment by angyangie** [comment]
I'm picking up this ticket. Some questions for you all. We already have an endpoint on the CLI that'll give us all `orchAdd` a B is working with. We also refresh the list of O's registered when the cached list becomes too small. 

- Where will this new list of O's, acquired from hitting `/status` endpoint on CLI  be used? 
- When we mention a new `--orchestrator-webhook-url=https://livepeer.live/api/orchestrator` flag, which node is that on? 
- When we say that then that becomes the internal list of orchestrators... internal to which node?
- Why would we need to Dynamically add / remove orchAddr on a B?

**Comment by j0sh** [comment]
> Where will this new list of O's, acquired from hitting /status endpoint on CLI be used?

This is list of O that is available from within the [OrchestratorPool](https://github.com/livepeer/go-livepeer/blob/f5106de234ff99f26916f6965a0f8fe41e789f25/net/interface.go#L9-L13) interface that the `discovery` module implements. Rather than populate the OrchestatorPool from DB, from on-chain lookup, or from CLI args, we populate it via webhook.

Not sure what you mean by "acquired from hitting `/status` endpoint on CLI" though. The status endpoint just lists the orchestrators that B has available in its pool, so those come from elsewhere (such as a webhook in this case).

> When we mention a new --orchestrator-webhook-url=https://livepeer.live/api/orchestrator flag, which node is that on?
>When we say that then that becomes the internal list of orchestrators... internal to which node?

This flag will be set on the broadcaster, and the list of orchestrators is internal to the broadcaster only.

> Why would we need to Dynamically add / remove orchAddr on a B?

Presumably this makes it easier to manage a long-running cluster of nodes without having to explicitly push out O address updates to each of them, especially offchain. @iameli can confirm the use case.

The utility here isn't limited to offchain though; a B operator could use this mechanism to provide a subset of 'preferred' onchain orchestrators. (We need to check that this type of onchain behavior actually works, but that's something for later.)

**Comment by angyangie** [comment]
From @iameli :

> When you say that then that becomes the internal list of orchestrators... internal to which node?
Why would we need to Dynamically add / remove orchAddr on a B?

The production infrastructure runs on a Kubernetes cluster that we can scale up and down. Currently, we're running three machines, with one B and one OT on each. However, let's say we suddenly have fifty streams coming in from users of the Wowza plugin. Without disturbing any of the existing infrastructure, we want to be able to spin up lots of new OTs, and have the Bs learn about them without having to restart the B. That's what the webhook is for — the B requests a new list of servers from the API node, which speaks Kubernetes and can tell it where to find all the new OTs.

> When you mention a new --orchestrator-webhook-url=https://livepeer.live/api/orchestrator flag, which node is that on? 

That list is provided by the API node. I haven't yet implemented the GET /api/orchestrator endpoint, but it will function almost identically to the existing GET /api/boradcaster endpoint: https://github.com/livepeer/livepeerjs/blob/eli/api-node-prototype/packages/api/src/controllers/broadcaster.js

> Where will this new list of O's, acquired from hitting /status endpoint on CLI  be used? 

Hmm, I don't think /status factors into this at all.

**Comment by angyangie** [comment]
>Without disturbing any of the existing infrastructure, we want to be able to spin up lots of new OTs, and have the Bs learn about them without having to restart the B. 

That makes a lot more sense to me now. Wasn't thinking about nodes in containerized environment.

>  Rather than populate the OrchestatorPool from DB, from on-chain lookup, or from CLI args, we populate it via webhook.

Sounds good. We'd ping `https://livepeer.live/api/orchestrator` for new O's when they were needed. 

> That's what the webhook is for — the B requests a new list of servers from the API node, which speaks Kubernetes and can tell it where to find all the new OTs.

How would we initially trigger the spinning up of new OT's? Would B's request to `https://livepeer.live/api/orchestrator` have any information on how many OT's it needed? Would pinging mean we spin up x number of them every time? Trying to figure out how kubernettes would know to scale up or down

**Comment by iameli** [comment]
Thanks for pasting my response, somehow couldn't find this issue when I was looking around yesterday 😃

> How would we initially trigger the spinning up of new OT's? Would B's request to `https://livepeer.live/api/orchestrator` have any information on how many OT's it needed? Would pinging mean we spin up x number of them every time? Trying to figure out how kubernettes would know to scale up or down

Right now it'd happen manually by scaling the instance group in GCP when we know more streams are going to be coming in. Eventually, we'll want to implement Kubernetes' [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) by hooking it into our Prometheus metrics and scaling up or down based on the number of running streams.

**Comment by angyangie** [comment]
> Eventually, we'll want to implement Kubernetes' Horizontal Pod Autoscaler by hooking it into our Prometheus metrics and scaling up or down based on the number of running streams

Very cool! That'll be a good day, friend.
