### ISSUE TITLE
Initialize Round Takes 10 Minutes

### ISSUE THREAD

**Issue by rayj00** [livepeer/go-livepeer#853]
**Describe the bug**
Initialize Round takes an extremely long time compared to a month or so ago.
**To Reproduce**
 1. Start livepeer as such:  livepeer -rinkeby -rtmpAddr 0.0.0.0:1935 -httpAddr 0.0.0.0:8935 -v 99
 2. Run  'livepeer_cli'
 3. Choose #5 to Invoke "Initialize  round"

**Expected behavior**
In the past, this used to complete rather quickly....1-2 minutes at most.

**Actual Behavior**
Initializing the round is now taking roughly 10 minutes to complete.

**Comment by j0sh** [comment]
* Gas estimation on Rinkeby can be a bit wonky. Check https://www.rinkeby.io/#stats and be sure the node is supplying enough (adjust `-gasLimit` and/or `-gasPrice` as necessary).
* Rounds on Rinkeby go by quickly. Rather than manually initialize rounds each time, run another node with the following flags to initialize rounds automatically: `-transcoder -initializeRound=true`.
* Pester one of us to restart the Rinkeby round initializer :)  cc @yondonfu

**Comment by rayj00** [comment]
Not sure what I'm supposed to be looking at on rinkeby.io/#stats?  
I set the Eth gas price to auto.  It was at 10000.  Not sure what to do with the gas limit?

**Comment by rayj00** [comment]
And apparently its not that easy running a transcoder: 
root@localhost:~/livepeer0.3.3/livepeer_linux# ./livepeer -rinkeby -transcoder -initializeRound=true .
I0509 19:14:58.909140   30750 livepeer.go:96] ***Livepeer is running on the Rinkeby test network: 0x37dc71366ec655093b9930bc816e16e6b587f968***
I0509 19:14:59.261524   30750 accountmanager.go:58] Using ETH account: 0x35e01199F8137077346FDD476191f1967A52BDb5
I0509 19:15:00.309850   30750 accountmanager.go:76] Passphrase required to unlock ETH account 0x35e01199F8137077346FDD476191f1967A52BDb5
Passphrase:
I0509 19:15:05.761502   30750 accountmanager.go:87] Unlocked ETH account: 0x35e01199F8137077346FDD476191f1967A52BDb5
I0509 19:15:06.306905   30750 livepeer.go:326] Transcoder 0x35e01199F8137077346FDD476191f1967A52BDb5 is inactive
E0509 19:15:06.659739   30750 livepeer.go:356] Could not parse service URI; transcoder may be unreachable
E0509 19:15:06.659778   30750 livepeer.go:360] Service address http://127.0.0.1:8935 did not match discovered address https://23.239.31.177:8935; set the correct address in livepeer_cli or use -serviceAddr
I0509 19:15:07.907035   30750 livepeer.go:378] Transcoder 0x35e01199F8137077346FDD476191f1967A52BDb5 will automatically initialize new rounds
I0509 19:15:08.503456   30750 livepeer.go:291] ***Livepeer Running in Transcoder Mode***
I0509 19:15:08.503614   30750 webserver.go:1223] CLI server listening on 127.0.0.1:7935
I0509 19:15:08.503707   30750 livepeer.go:309] CLI webserver shut down
I0509 19:15:08.503839   30750 cert.go:83] Private key and cert not found. Generating

It stopped output after "Generating".   Generating what?

**Comment by j0sh** [comment]
The node shuts down because it does an availability check using your public IP. (Otherwise transcoders would never be able to receive work.) As the log suggests, set `-serviceAddr http://127.0.0.1:8935 `.

**Comment by rayj00** [comment]
So running a broadcast node and a transcoder node on the same server doesn't seem valid?
Here is how I try to start them:
`livepeer -rinkeby -rtmpAddr 0.0.0.0:1935 -httpAddr 0.0.0.0:8935 -v 99`  This works.
`livepeer -rinkeby -transcoder -serviceAddr 127.0.0.1:8935`  Does not work and get this:
E0510 07:04:30.083361    4821 livepeer.go:356] Could not parse service URI; transcoder may be unreachable
I0510 07:04:32.050095    4821 livepeer.go:291] ***Livepeer Running in Transcoder Mode***
I0510 07:04:32.050248    4821 webserver.go:1223] CLI server listening on 127.0.0.1:7935
I0510 07:04:32.050312    4821 livepeer.go:309] CLI webserver shut down
I0510 07:04:32.050433    4821 cert.go:83] Private key and cert not found. Generating

?

**Comment by rayj00** [comment]
If I start like this:
root@localhost:~/livepeer0.3.3/livepeer_linux# ./livepeer -rinkeby -transcoder -serviceAddr 127.0.0.1:8935
I0510 13:29:35.305337    7741 livepeer.go:96] ***Livepeer is running on the Rinkeby test network: 0x37dc71366ec655093b9930bc816e16e6b587f968***
I0510 13:29:35.699740    7741 accountmanager.go:58] Using ETH account: 0x35e01199F8137077346FDD476191f1967A52BDb5
I0510 13:29:36.817171    7741 accountmanager.go:76] Passphrase required to unlock ETH account 0x35e01199F8137077346FDD476191f1967A52BDb5
Passphrase:
I0510 13:29:43.061896    7741 accountmanager.go:87] Unlocked ETH account: 0x35e01199F8137077346FDD476191f1967A52BDb5
I0510 13:29:43.855220    7741 livepeer.go:326] Transcoder 0x35e01199F8137077346FDD476191f1967A52BDb5 is inactive
E0510 13:29:43.915305    7741 livepeer.go:356] Could not parse service URI; transcoder may be unreachable
I0510 13:29:51.192812    7741 livepeer.go:291] ***Livepeer Running in Transcoder Mode***
I0510 13:29:51.193019    7741 webserver.go:1223] CLI server listening on 127.0.0.1:7935
I0510 13:29:51.193198    7741 cert.go:83] Private key and cert not found. Generating
I0510 13:29:51.196138    7741 cert.go:22] Generating cert for 127.0.0.1
I0510 13:29:51.196458    7741 rpc.go:345] Listening for RPC on :8935

Then the broadcast node will not start.  So it seems I need 2 separate servers...which is unrealistic.

**Comment by yondonfu** [comment]
The Rinkeby round initializer was down for a bit because the ETH node that it was using needed to be upgraded. It should be initializing rounds on Rinkeby now

**Comment by ericxtang** [comment]
Closing.
