### ISSUE TITLE
Benchmarking B from a streamer's perspective

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#856]
Understand performance of a SINGLE broadcast node on high CPU machines with 4 cores (from a streamer's perspective)
* Test segmenter without transcoding
* Measure from a streamer's perspective, including success in ingest and success in output.

**Make sure this is automated and repeatable**

**Comment by darkdarkdragon** [comment]
Results are here
https://docs.google.com/spreadsheets/d/1eChPNzG-VuitEFhK9IiJLc_UTNcY6rYu5oEzTEQ3OLQ/edit?pli=1#gid=72112262

`n1-highcpu-32` is able to handle **200** streams with 100% success rate (tested for 12 hours)
