### ISSUE TITLE
Job Watcher timeout exceeded; stopping

### ISSUE THREAD

**Issue by rayj00** [livepeer/go-livepeer#859]
**Describe the bug**
On rinkeby:
After ~10 minutes of steaming, the livepeer log is spewing error messages between the LastSeenBlock messages.

**To Reproduce**
1. Start a live stream
2. Verify "Logging SegmentEmerged" output messages on console log.
3. Continue streaming for at least 10 minutes.

**Expected behavior**
A clean console log with no error messages

**Screenshots**
I0511 06:50:00.098036   17680 db.go:456] db: Setting LastSeenBlock to 4363062
E0511 06:50:00.587692   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:02.652771   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:04.717774   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:06.827133   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:08.891349   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:10.955561   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:13.019918   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:15.087768   17680 client.go:1023] Job watcher timeout exceeded; stopping
I0511 06:50:15.098797   17680 db.go:456] db: Setting LastSeenBlock to 4363063
E0511 06:50:17.152124   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:19.216547   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:21.281041   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:23.345524   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:25.410248   17680 client.go:1023] Job watcher timeout exceeded; stopping
E0511 06:50:27.474390   17680 client.go:1023] Job watcher timeout exceeded; stopping

These messages continue, even after streaming is stopped!

**Additional context**
I have never seen this "Logging SegmentEmerged" message before?  Previously, the log showed
another output message for segments being recorded in the  .lpData directory.

**Comment by rayj00** [comment]
Restarting the stream works but the error messages continue.

**Comment by ericxtang** [comment]
Thanks @rayj00.  This is a deprecated issue that will go away when Streamflow is deployed (there won't be onchain jobs anymore).
