### ISSUE TITLE
Getting the manifestID?

### ISSUE THREAD

**Issue by rayj00** [livepeer/go-livepeer#860]
**Describe the bug**
I used to be able to retrieve the manifestID by doing a curl -s http://localhost:8935/mainfestID,
but for some reason it is not working.

**To Reproduce**
1. Run livepeer as a broadcaster
3. Create a stream using OBS
4. Confirm  the manifestID is shown on the console log 
5. Run this command on another console terminal:  curl -s http://localhost:8935/mainfestID
6. You will receive 404 error message.

**Expected behavior**
I uses to get back the manifestID?

**Screenshots**
I0512 11:02:48.855602   32750 mediaserver.go:435]

Video Created With ManifestID: 14236c1fe53206fde6c183efcaf36c8a9f7340a6fbb2ea689019347f82dc157a

I0512 11:02:48.855615   32750 mediaserver.go:436]

hlsStrmID: 14236c1fe53206fde6c183efcaf36c8a9f7340a6fbb2ea689019347f82dc157aP720p60fps16x9

I0512 11:02:48.855708   32750 lpms.go:143] Segment RTMP Req: rtmp://127.0.0.1:1935/stream/657334fe556310543e6f0c64bec0ad8ac235d678dcc3ba9e98dbebad83c79657RTMP
I0512 11:02:48.984037   32750 player.go:62] LPMS got RTMP request @ rtmp://127.0.0.1:1935/stream/657334fe556310543e6f0c64bec0ad8ac235d678dcc3ba9e98dbebad83c79657RTMP
I0512 11:02:49.218991   32750 base.go:207]
******************************Eth Transaction******************************

Invoking transaction: "job".  Hash: "0x0770c41bc7097668169cd77c61e64bd526edafa37bf748752bb56c4634a3e261".  Params: [14236c1fe53206fde6c183efcaf36c8a9f7340a6fbb2ea689019347f82dc157aP720p60fps16x9 93c717e7c0a6517a 1 4375593]

***************************************************************************
I0512 11:02:56.770945   32750 events.go:80] Logging StreamStarted...

**root@localhost:/tmp/LPdata# curl -s http://localhost:8935/manifestID
404 page not found
root@localhost:/tmp/LPdata# curl -s http://23.239.31.177:8935/manifestID
404 page not found**

Is it possible to save the current manifestID in an environment variable?
It kinda makes sense to me to do that.  Does it make sense to you?

**Comment by j0sh** [comment]
> I used to be able to retrieve the manifestID by doing a curl -s http://localhost:8935/mainfestID,

The CLI API is, by default, on port 7935 and has been for some time now. If there's documentation that points to this API on port 8935, let us know so we can correct it. See https://github.com/livepeer/go-livepeer#streaming .

Also there's a typo in the URL, it's `manifestID` rather than `mainfestID`.
