### ISSUE TITLE
Full Playlists

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#869]
**Is your feature request related to a problem? Please describe.**

There are a few features on the horizon that might require serving full playlists (rather than a rolling-window live playlist):

* VOD transcoding
* DVR / stream recording
* Time shifting

Supporting full playlists are straightforward (the m3u8 library does this), but the biggest unanswered product questions are around playlist management. In particular:

* How should playlists be named?
* How should collisions be handled?
* How should playlist discovery work?
* Policy for writing to storage?

Additionally there are smaller questions of whether full playlists should be enabled by default - which is a way to eat up disk space quickly. Should this also be configured per stream (eg, via webhook)?

## Playlist Naming

There are a few options to name playlists:

1. A simple way to name the playlist would be to follow the manifest ID, eg `<manifestID>.m3u8` 
2. Playlist name can be customized via auth webhook callback.
3. Randomly generated for each stream. Possibly with a structured suffix, eg `<manifestID>_<nonce>.m3u8`

These options are not mutually exclusive and can be combined. Eg, we can use the manifest ID along with a structured random suffix, such as `<manifestID>_<nonce>.m3u8`, and still support webhook callbacks to completely decouple the full name from the manifest ID.

## Playlist Collisions

When the name of a playlist collides with an existing playlist in the same OS location, we have a collision. There are a few options for handling collisions:

1. Append to an existing playlist if another exists in the same OS location.
2. Overwrite any existing playlists
3. Force a unique name, negating the possibility of a collision

Some further considerations that may affect the naming + collision strategy:
1. Are playlists associated with a RTMP connection, or attached to some other logical session?
2. Are they otherwise bounded on top of the session? Eg, a "RTMP connection + 5 minutes" implies two things: the playlist needs to persist and continue appending if the RTMP stream reconnects after 5 minutes, *and* a new, non-colliding playlist needs to be created if the RTMP stream reconnects after 5 minutes.

## Playlist Discovery

1. How should discovery work if we have multiple playlists for a given stream?
2. What is the access level for this discovery mechanism? Eg, CLI or plain HTTP/RPC ?
3. Will we need to store a reference to these full playlists on the node indefinitely, eg in the DB?

## Playlist Storage

Full playlists (especially for time-shifting or seeking in live streams) generally cannot be live-updated in external in OS given the typical [read-after-write](https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html) consistency models. 

To mitigate this, playlists need to be served locally for live streams. External OS can still be used if only written to when necessary (eg, at the end of stream). There are a few ways to handle full playlists locally:

1. The local playlists can be either in-memory (as is now). We don't have durability in this case - if the node crashes, pending changes are lost.

2. Can be written to disk, preferably using on-disk local storage https://github.com/livepeer/go-livepeer/issues/867 .

## Additional Technical Considerations

There's some concern around `m3u8.InsertSegment` because this may involves a search and a sort for each out-of-order insert. In pathological cases (eg, a VOD job where we receive all segments and insert them one-by-one) the runtime looks to be something like O(N^2logN). We should sanity check that the actual performance stays reasonable when handling long playlists under these conditions. (And if not, determine the most appropriate course of action.) See: https://github.com/ericxtang/m3u8/blob/master/writer.go#L377-L397

**Comment by darkdarkdragon** [comment]
> Full playlists (especially for time-shifting or seeking in live streams) generally cannot be live-updated in external in OS given the typical read-after-write consistency models.

Or we can just say that appropriate external service should be used, like [MediaStore](https://aws.amazon.com/mediastore/), and do not try to solve this by ourselves (probably any livestream deployment on AWS will use it anyway).

**Comment by iameli** [comment]
My proposal for resolving the manifest collisions adds a timestamp that continuously rolls over to the nonce and is discussed here https://github.com/livepeer/go-livepeer/issues/1565#issuecomment-656881503 and here https://github.com/livepeer/go-livepeer/issues/1565#issuecomment-657311571. It would look like:

```
<manifestID>_<timestamp>_<nonce>.m3u8
```

which means we can continuously upload the full playlist forever to an external OS. Playing it back involves reading through all the manifests and combining them, optionally with some caching.

Happy to continue that part of the conversation here if we think it'll be more organized.

**Comment by j0sh** [comment]
> which means we can continuously upload the full playlist forever to an external OS 

There would still be eventual consistency issue uploading full playlists to distributed storage, which would be problematic for a live, time-shifted stream. (Time shifting isn't necessarily a requirement *right now* but I think it shares a lot of the same issues we have with handling recordings or VOD, and if we can converge on something to solve all of these, the better.) And who's responsible for recombining the playlists during live? And / or who does the finalization, if multiple broadcasters are handling a given stream? When can things be finalized, since the settlement period is indefinite? 

It also makes less sense to write intermediate playlists for VOD transcodes.

In https://github.com/livepeer/go-livepeer/issues/1565#issuecomment-657737865 , one solution to accommodate broadcaster bouncing is to fix up the playlists / segments after the fact, but that's recording-specific.

Another is to have the node itself act as a canonical service for full playlists. This ensures we can handle things exactly the way we need it to - once - and allows for the playlist-handling architecture to evolve independently of the underlying object storage system, rather than being intimately coupled. This would also allow for easier handling of intermediate files vis-a-vis the finalized results. Eg, the primary (intermediate) storage mechanism could be on-disk, while finalized results could be in a customer's S3.

Storing and serving full playlists from the node itself is very simple. (My initial thought is this would be toggled via a CLI flag setting the playlist window length, with an option for a full playlist.) On top of that, there would be a few ways to run a "full playlist" or a recording service:

* An incoming stream triggers a single-shot pull via RTMP, HTTP, HLS, etc. The results can be transcoded, or not. The results are put into storage and finalized as needed after the stream terminates. Doesn't really help time shifted playback, unless in-progress playlists are written to something like a disk shared with a webserver.

Pulling is the simplest way to deal with VOD, and an incoming live stream could trigger a single-shot pull for recording (say, via webhook endpoint that spawns a task). This pull could also run a pre-fixup step in order to continue any incomplete recordings that were non-gracefully terminated.

* A listening node can serve as an object storage endpoint itself. This allows for the node itself to act as the source of ground truth for a given stream. The node can keep a persistent record of segments received for a given stream, generate manifests as needed, and perform any finalization. This could serve as the origin point for distribution. This scheme is the most attractive, because it allows us to maintain our fully distributed architecture without coalescing around a potential SPOF such as a cloud storage system. (Eg, different streams could utilize different node-storage instances.)

* Rather than a separate node that only functions as an object storage endpoint, the same could be done for a listening node that ingests RTMP, HTTP push, etc, if it's known that node is the only one handling a given stream. Serving a full playlist from these is trivial. Like the pull-flow, this would would work well for less distributed setups, eg typical node-first users.

On collisions:

Given all that's said above, my thinking towards collisions is the following:

* If a "full playlist" or "recording" service is responsible for a given stream, then:
* Each stream will have a certain amount of long-lived state on the node. ("Long-lived" being the typical stream timeout, say a minute or so, but configurable of course.) Anything that happens while this stream is active gets appended to the node's internal state.
* If a new stream comes in, where the name matches an expired stream - overwrite the expired stream. This keeps the node itself as stateless as possible.
* We could make "appendability" configurable later.
* We could offer an option to randomize output file names to prevent over-writing. But not sure if this should be the default because of predictability and "just-grab-it"-ness (described below).
* If we do want to prevent collisions by default, then we probably need "virtual" paths, like:
```
/manifestID/datetime/rendition/...
/manifestID_datetime.m3u8
```
And for a given active stream, `manifestID.m3u8` gets mapped to `manifestID_datetime.m3u8`. But this implies additional work on the user side to extract expired manifests from persistent storage, since they can't just grab `manifestID.m3u8`. The ease of "just grab it" is the reason I'm in favor of overwriting things.

**Comment by darkdarkdragon** [comment]
> Another is to have the node itself act as a canonical service for full playlists.

I don't see how this will have us with the streams that are scattered across multiple broadcasters?

**Comment by j0sh** [comment]
>>Another is to have the node itself act as a canonical service for full playlists.
>
> I don't see how this will have us with the streams that are scattered across multiple broadcasters?

@darkdarkdragon Probably the easiest way to is to adopt the "node-as-object-storage-endpoint" method, or pull + fixup.

One thing that came to mind though, is that with https://github.com/livepeer/go-livepeer/issues/695 in conjunction with proxy mode ( and the auth scheme described in https://github.com/livepeer/go-livepeer/issues/1569 ) then it's likely that the "stream index" (manifest id) across multiple proxy broadcasters will be different for the same logical stream. In that case, it might be better to just retain recording on the source only for the node-first flow. If we still want to do remote recording across multiple broadcaster proxies, then some other canonical stream id will need to be propagated among broadcasters.

**Comment by hthillman** [comment]
can reopen if we need full playlists

**Comment by h1k3rr** [comment]
Can we reopen this issue ? 
The concern that OS do not provide strong consistency is no longer true for multiple providers like s3, minio and filebase.
Also a playlist in json is currently recorded on OS but not the m3u8 playlist, I wonder why ?
I understand that the playlist can become very large and difficult to update too often, but could we simply have a first version with limited time window (few hours). There was an example with an extreme time window of 48 hours. Even youtube limits its DVR to 12 hours.

**Comment by yondonfu** [comment]
> Also a playlist in json is currently recorded on OS but not the m3u8 playlist, I wonder why ?

@iameli might have some insight here.

**Comment by joegraviton** [comment]
"Also a playlist in json is currently recorded on OS but not the m3u8 playlist, I wonder why ?"

I also noticed this.  I was about to write a script to convert the playlist json to m3u8 file myself.
Then luckily, I discovered that,   the m3u8 file will actually be built on the fly by livepeer.
You can test with something like this:
```
curl http://localhost:8935/recordings/<stream-id>/index.m3u8
```
This assumes your httpAddr is on :8935 and the stream is already recorded with `-recordStore`.
