### ISSUE TITLE
Integrate livepeer with Livepeer Aragon App

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#876]
### Problem Statement

Any Livepeer Transcoder which is governed by an Aragon DAO using the [Livepeer Aragon App](https://github.com/videoDAC/livepeer-aragon) calls smart contract functions on Livepeer's Protocol _**via**_ the [Livepeer Aragon App contract](https://github.com/videoDAC/livepeer-aragon/blob/master/livepeer-aragon-app/contracts/LivepeerAragonApp.sol).

The calling of `reward` is currently only possible manually, either through a Livepeer Aragon App installed in an Aragon DAO ([see this example, select the Transcoder tab](https://rinkeby.aragon.org/#/video.aragonid.eth/0x0069ee94a2c6964221c45a402d8b1ff0c45224b6)), or calling the contract, e.g. via a [oneclickdapp for a deployed instance of the Livepeer Aragon App](https://oneclickdapp.com/avenue-jargon/).

**_This manual requirement to call reward is the problem._**

Furthermore, as the Livepeer Aragon App evolves to allow other time-sensitive functions to be called on the protocol, the manual overhead would only increase.

### Proposed Solution

I would like to be able to run an instance of livepeer which calls `reward` on Livepeer's Protocol _**via**_ the [Livepeer Aragon App contract](https://github.com/videoDAC/livepeer-aragon/blob/master/livepeer-aragon-app/contracts/LivepeerAragonApp.sol).

Perhaps this could pass in an extra flag and an argument, such as:

```
./livepeer -transcoder -livepeerAragonAppAddress 0x0069ee94a2c6964221c45a402d8b1ff0c45224b6
```

Furthermore, this could be the reference implementation for other Livepeer protocol smart contract functions which may need to be called via the Livepeer Aragon App in future, such as `claimWork` or `verify`, or anything that comes up in the Streamflow release.

### Alternative Solutions

An alternative would be for the `reward` function to continue to need to be called manually. This maintains the obvious risks of manual error, and also the likelihood that the intervention required will only increase in future iterations of Livepeer's protocol.

Another alternative would be to create a separate watch / caller application which watches for new rounds of the protocol, and calls `reward`. This feels like duplication, and also would require extensive work to create additional logic for future time-sensitive function calls.

### Additional Context

AragonOS's Permissions system allows a DAO to assign roles on the Aragon Livepeer App to any entity represented by an Ethereum address.

For example, the REWARD_ROLE role can be granted to:

1. Any address, so that anyone or any thing can call `reward` on behalf of the DAO
2. A specific address, to call `reward` unilaterally on behalf of the DAO
3. the DAO's Voting app, so that the calling of `reward` can only be proposed by anyone with permission to do so, and must first pass a vote before it can happen.

For this example, we will only be considering options 1 or 2, although it is worth noting that it would be possible for the livepeer software to submit a transaction which creates a vote for the DAO to decide on. This could be useful for any function calls which could result in slashing, and which are time-sensitive, or require information held in the livepeer software's session.

**Comment by j0sh** [comment]
Maybe we can allow `reward` to be called on behalf of any address (rather than white listing or special-casing Aragon). Then anyone could call `reward` for a DAO-controlled contract, or their own transcoder. This would make it easier to automate `reward` calls via an external process, or invoke reward manually if necessary.

**Comment by chrishobcroft** [comment]
Makes sense to not have special cases. 

Would the approach you're suggesting effectively mean creating a role-based permissions system as part of Livepeer's protocol? If so, Aragon have already done a lot of work on this, so it's worth being aware of. 

For example, here's a link to [the permissions system for an instance of the Livepeer App in an Aragon DAO on Rinkeby](https://rinkeby.aragon.org/#/video.aragonid.eth/permissions?p=app.0x0069ee94a2c6964221c45a402d8b1ff0c45224b6), and screenshot below:

![Screenshot from 2019-05-18 18-21-46](https://user-images.githubusercontent.com/2212651/57973014-06f2a300-799a-11e9-99ed-f88dca0e2791.png)

**Comment by j0sh** [comment]
We are discussing validator contracts for other aspects of the protocol, see https://github.com/livepeer/protocol/issues/284 . But these don't seem necessary for `reward` calls, unless there's a reason you would not want someone else to call reward on your behalf.

**Comment by yondonfu** [comment]
> Maybe we can allow reward to be called on behalf of any address (rather than white listing or special-casing Aragon).

Yep this should be possible with a contract change.

> We are discussing validator contracts for other aspects of the protocol

livepeer/protocol#284 isn't really related to `reward` calls - however, it is relevant for an Aragon DAO backed orchestrator because the DAO will need to designate signers that are authorized to sign off-chain data on its behalf. While the Aragon app implements a [SignatureValidator](https://github.com/aragon/aragon-apps/blob/master/apps/agent/contracts/SignatureValidator.sol) interface, I don't think that it is safe to rely on the Aragon DAO itself for authenticating signatures in Livepeer's setting due to the possibility a signature invalidation attack (happy to elaborate further separately).

**Comment by chrishobcroft** [comment]
Related question: if I were to use the Livepeer Aragon App to register itself as a Transcoder (with address 0x123...) and set their ServiceURI to be the same as that of a running Livepeer Node (with address 0xabc...), what would happen when video was sent to the ServiceURI to be Transcoded?

Let's assume that 0xabc... is **not** part of the active set.

![image](https://user-images.githubusercontent.com/2212651/59054946-af56a180-888c-11e9-8525-24d5fe21906c.png)

**Comment by yondonfu** [comment]
Video would be sent to node 0xabc and it *should* only transcode the video if it is in the active set because only orchestrators in the active set would be paid. I don't think this is the behavior for the latest V1 release, but it should be the behavior in the Streamflow release.

**Comment by hthillman** [comment]
closing, can reopen if there's interest
