### ISSUE TITLE
Segmenter buffers small segments

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#885]
**Describe the bug**
If segments are small (in bytes), segmener buffers them internally and then spits outs them all at once, up to three segments together. 

**To Reproduce**
1. Generate test video
`ffmpeg -f lavfi -i sine=frequency=1000:duration=60 -c:a aac -f lavfi -i testsrc=duration=60:size=1280x720:rate=30 -g 60 output2-60-2.mp4`

2. Start broadcaster with one orchestrator.
3. Stream test video into broadcaster.
4. Observe segment two and three emerged at the same and not being transcoded.

**Expected behavior**
All segments should be transcoded with only one orchestrator, no matter the segment size.

**Additional context**
This is not a problem by itself, but it surfaces problems with orchestrator selection and distribution of work inside orchestrator.

**Comment by j0sh** [comment]
This seems like it may be an issue with segment lengths; do they all add up to less than the expected segment size (2sec)?

> All segments should be transcoded with only one orchestrator, no matter the segment size.

The rule right now is: we drop segments if there are no orchestrators available, and we only allow one segment in flight per O. (That explains the behavior you see with 'bunched' segments being dropped.) This approach does make it problematic for certain types of jobs, eg batch or VOD, but is a safer assumption in a decentralized, live context where latency tolerances are tight and Os themselves may be unreliable.

**Comment by darkdarkdragon** [comment]
> This seems like it may be an issue with segment lengths; do they all add up to less than the expected segment size (2sec)?

It is problem with byte size of segments. As you can see, I've generated test video, and it have perfect 1 second interval between key frames.

> The rule right now is: we drop segments if there are no orchestrators available, and we only allow one segment in flight per O. 

I know that, and this is thing needs to fixed. We aiming not only to decentralized use case, but for enterprises too. Imagine engineer in enterprise, evaluating our software - setting up broadcaster, orchestrator, streaming totally fine stream into it - and observes transcoding failures, despite the that hardware is totally capable to do transcoding. Probably at that point evaluation will end and our software will be dismissed.

**Comment by j0sh** [comment]
> I know that, and this is thing needs to fixed.

Dropping segments is no good, but I'd also argue that this particular report is atypical and not a normal case; it feels like something is wrong with the segmenter here if it's bunching up segments and dumping them all out at once. Also see https://github.com/livepeer/go-livepeer/issues/750 - you also said such behavior is not a target use case :)

> not only to decentralized use case, but for enterprises too

There are certainly some aspects that have been optimized for a decentralized environment, but a bigger part of this is more general : to ensure reliability and minimize latency during live transcoding. This points to the importance of documentation in this area, eg  https://github.com/livepeer/go-livepeer/issues/868 is important - so we all fully understand the design choices and the tradeoffs of those, which should help orient our conversations.

**Comment by darkdarkdragon** [comment]
> you also said such behavior is not a target use case :)

That was before I fully understood how our system works.

> to ensure reliability and minimize latency during live transcoding

And rule `one segment in flight` makes reliability worse. It was introduced to prevent backlogging on orchestrator, but now orchestrator has own mechanism to prevent overload, so that rule (`one segment in flight`) no longer needed.

Also, just overall feeling - our code depends on timing, and it just doesn't feel right and make our code fragile.
