### ISSUE TITLE
Gas Limit Assignment

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#89]
We run into the problem of exceeding gas limit using the default Geth setting - and the temporary solution now is to manually assign it (now it's 4700000).

We talked about a few potential solutions - one being manually running the estimator and assigning a fixed gas limit only when it exceeds the block gas limit.

**Comment by dob** [comment]
Which transaction exceeds the gas limit? Are you saying that we exceed the
block gas limit, or that we just don't provide enough for some transactions
because the estimator was wrong?

**Comment by ericxtang** [comment]
Duplicate to https://github.com/livepeer/go-livepeer/issues/25
