### ISSUE TITLE
Add a TranscodeReceipt message for reporting pixels processed in TranscodedSegmentData message

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#892]
Introduce a new TranscodeReceipt message.

```
message TranscodeReceipt {
    
    // Number of pixels processed to produce the transcoded data
    int64 pixels_processed = 1;
    
    // Price info used during transcoding
    PriceInfo price_info = 2;
}
```

In the short term, pixels_processed will just track output pixels, but in the future it could track input pixels as well.

Add a receipt field to the existing TranscodedSegmentData message.

```
message TranscodedSegmentData {

    // URL where the transcoded data can be downloaded from.
    string url = 1;
    
    // Transcoding receipt
    TranscodeReceipt receipt = 2;
}
```

**Comment by kyriediculous** [comment]
As discussed we will keep track of the pixel count per transcoded segment and let the broadcaster know his provisional credit balance. 

** This solution is not bulletproof if we ever remove the 'one segment in flight' constraint as a broadcaster might be basing his payments for the next segment on an outdated balance. 

1. Add pixel count to the `TranscodedSegmentData` message (repeated field)
```
// Individual transcoded segment data.
message TranscodedSegmentData {

    // URL where the transcoded data can be downloaded from.
    string url = 1;

   // Amount of pixels processed
   int64 pixels
}

// A set of transcoded segments following the profiles specified in the job.
message TranscodeData {

    // Transcoded data, in the order specified in the job options
    repeated TranscodedSegmentData segments = 1;

    // Signature of the hash of the concatenated hashes
    bytes sig = 2;
}
```

2. Add provisional balance for a manifestID to the `TranscodeResult` message

```
// Response that a transcoder sends after transcoding a segment.
message TranscodeResult {

    // Sequence number of the transcoded results.
    int64 seq = 1;

    // Result of transcoding can be an error, or successful with more info
    oneof result {
        string error = 2;
        TranscodeData data = 3;
    }
   
    // The remaining balance for a manifestID after debiting for transcoding work
    bytes balance = 4;

    // Used to notify a broadcaster of updated orchestrator information 
    OrchestratorInfo info = 16;
}
```

**Comment by yondonfu** [comment]
Upon further thought, I think we can omit `balance` from the `TranscodeResult` message for the following reasons:

- A reader might find the semantics of `balance` confusing if they are solely looking at the `TranscodeResult` message definition. While a comment can indicate that `balance` is associated with a specific manifestID, the message does not indicate a manifestID so it is up to the reader to sift through the Go code to figure out how `balance` is associated with a manifestID
- `balance` is transmitted over the wire as a `bytes` type which requires a separate encoding/decoding step to translate the field into a `big.Rat` type in the Go code. We can avoid this encoding/decoding step if we omit `balance`
- Including `balance` in the message does not reduce the computation that B must perform after receiving a `TranscodeResult` message. B still has to compute and debit the fee for the results from its local balance when it verifies the provisional balance sent by O. If we omit `balance` from the message, then B will need to compute and debit the fee for the results immediately upon receiving the message to update its local balance. When we include `balance` in the message, B asynchronously computes and debits the fee and when we omit `balance` from the message, B synchronously computes and debits the fee. While the latter case requires synchronous computation it also avoids a decoding step for `balance` so I don't think this should be much of a concern
- Including `balance` does not avoid issues involving discrepancies between B and O's local balances. If B and O's local balances become out of sync for whatever reason, the only difference between B relying on a provisional balance explicitly returned by O vs. deriving the provisional balance based on the pixels in the results is how the discrepancy is discovered - in the former scenario, B will detect the discrepancy when verifying the balance and in the latter scenario, O will detect the discrepancy when checking B's balance after receiving a segment

If we omit `balance` from the `TranscodeResult` message, then the only message update required for this issue would be:

```
message TranscodedSegmentData {
    string url = 1;
    int64 pixels = 2;
}
```

**Comment by kyriediculous** [comment]
The argumentation makes sense.

So In the case of omitting `balance` we are relying on B's check of the output pixel count as well as the expected price B sent to O for determining how many tickets to send to O with the next segment? 

And we are assuming bad behaviour of O (debiting too much) when the pixel counts from the `TranscodedSegmentData` message do not match B's local computation and thus a likely insufficient balance for the next segment sent. At which point B can decide to work with another O?

**Comment by yondonfu** [comment]
> So In the case of omitting balance we are relying on B's check of the output pixel count as well as the expected price B sent to O for determining how many tickets to send to O with the next segment?

B would synchronously:

1. Receive `TranscodeResult` message
2. Sum the values of the `pixels` field in each `TranscodedSegmentData` message nested in the `TranscodeResult` message as `totalPixels`
3. Compute the fee using `totalPixels` and the last known price for O
4. Debit the fee its local balance which can be used to determine the payment amount for the next segment

B would asynchronously verify that the pixels in the results matches the pixels reported in the `TranscodedSegmentData` messages.

> And we are assuming bad behaviour of O (debiting too much) when the pixel counts from the TranscodedSegmentData message do not match B's local computation and thus a likely insufficient balance for the next segment sent.

If the pixel count verification fails then B should stop working with that O (right now we would just remove the session for O, but we'll need to eventually prevent that O from being included in the session list again if we refresh the session list). If B sends a segment + payment based on its local balance and O responds with an insufficient balance error, B should also stop working with O - B should never encounter the insufficient balance error if it is honestly paying O since its local balance will always be based off O's pixel reports and O's last known price (if this is outdated then O should notify B and use the provided price during the grace period and then return an error after the grace period)
