### ISSUE TITLE
O creates price info for B based on a base price and payment redemption tx cost overhead

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#894]
**TxCostOverhead(addr)**

Should return the overhead (as a float) of payment redemption based on the transaction cost relative to the value of the payment. The overhead will be based on the current gas price. Additionally, when using PM, the overhead will be based on the `faceValue` used for tickets. Since the `faceValue` used for tickets can depend on a broadcaster's reserve, the value returned by this function can vary depending on the broadcaster which is why the function accepts the broadcaster's address as a paramter.

**PriceInfo(addr)**

Should return the price info for a broadcaster. An orchestrator will call this function in order to populate the `price_info` field in the `OrchestratorInfo` message returned to a broadcaster during discovery.

```
// BasePriceInfo returns the orchestrator's configured base price info
basePriceInfo = BasePriceInfo()
txCostOverhead = TxCostOverhead(addr)

basePricePerPixel = priceInfo.pricePerUnit / priceInfo.pixelsPerUnit
pricePerPixel = basePricePerPixel * (1 + txCostOverhead)

if pricePerPixel < 1 {
    // If price per pixel is less than 1 wei then set
    // the price per unit to 1 wei and pay for multiple pixels
    priceInfo.pricePerUnit = 1
    priceInfo.pixelsPerUnit = floor(1 / pricePerPixel)
} else {
    // If price per pixel is >= 1 wei then set
    // the price per unit to the price per pixel and
    // pay for a single pixel
    priceInfo.pricePerUnit = pricePerPixel
    priceInfo.pixelsPerUnit = 1
}

return priceInfo
```

The returned `PriceInfo` can be included in the `OrchestratorInfo` message.

**Comment by kyriediculous** [comment]
@yondonfu Is an O configuring BasePriceInfo part of the scope for this issue? 
Since I don't see an issue describing this separately I assume it is, but just wanted to make sure.

**Comment by yondonfu** [comment]
Yeah. I think O could specify the `-pricePerUnit` and `-pixelsPerUnit` flags. An alternative would be to have a single `-pricePerPixel` flag that accepts a float, but it might be preferable not to deal with floating point math if possible...

The default for `-pixelsPerUnit` could be 1, so typically a user that wants to adjust the price per pixel would only need to modify the value for `-pricePerUnit` (which would also have some default value).

Some rough implementation thoughts:

The [orchestrator](https://github.com/livepeer/go-livepeer/blob/master/core/orchestrator.go#L35) struct implementation in the `core` package could be updated to:

```
type orchestrator struct {
    address ethcommon.Address
    node *LivepeerNode
    basePriceInfo PriceInfo
}
```

where `PriceInfo` is defined as:

```
type PriceInfo struct {
    pricePerUnit int64
    pixelsPerUnit int64
}

func (info *PriceInfo) PricePerPixel()  float64 {
    return float64(info.pricePerUnit) / float64(info.pixelsPerUnit)
}
```

Then, the [Orchestrator](https://github.com/livepeer/go-livepeer/blob/master/server/rpc.go#L33) interface could expose the `PriceInfo()` method which is implemented by the `orchestrator` struct:

```
func (orch *orchestrator) PriceInfo(addr ethcommon.Address) PriceInfo {
    ...
}
```

Since #904 uses an integer `TxCostMultiplier` to compute the default face value of a ticket instead of a percentage overhead represented as a float, we'll need to adjust the formula for computing the price per pixel from (as defined in the OP of this issue):

```
// BasePriceInfo returns the orchestrator's configured base price info
basePriceInfo = BasePriceInfo()
txCostOverhead = TxCostOverhead(addr)

basePricePerPixel = priceInfo.pricePerUnit / priceInfo.pixelsPerUnit
pricePerPixel = basePricePerPixel * (1 + txCostOverhead)
```

to:

```
// BasePriceInfo returns the orchestrator's configured base price info
basePriceInfo = BasePriceInfo()
txCostMultiplier = TxCostMultiplier(addr)

basePricePerPixel = priceInfo.pricePerUnit / priceInfo.pixelsPerUnit
pricePerPixel = basePricePerPixel * (1 + 1 / txCostMultiplier)
```

We could expose a `TxCostMultiplier` method in the `pm.Recipient` interface used to compute the value for a given address.

**Comment by yondonfu** [comment]
Instead of defining a custom `PriceInfo` struct, we could use a [big.Rat](https://golang.org/pkg/math/big/#Rat) instead to store a rational number representing `pricePerUnit / pricePerPixel`. Usage would look something like the following:

```
type orchestrator struct {
    address ethcommon.Address
    node *LivepeerNode
    basePriceInfo *big.Rat
}

func (orch *orchestrator) PriceInfo(addr ethcommon.Address) *big.Rat {
    // Will need to export TxCostMultiplier on pm.Recipient
    multiplier := orch.node.Recipient.TxCostMultiplier(addr)
    // pricePerPixel = basePricePerPixel * (1 + 1 / txCostMultiplier)
    return new(big.Rat).Mul(orch.basePriceInfo, big.NewRat(multiplier + 1, multiplier))
}
```
