### ISSUE TITLE
go-livepeer build instructions are missing some dependency install steps

### ISSUE THREAD

**Issue by mk-livepeer** [livepeer/go-livepeer#910]
* Missing autotools dependency requirement (automake, autoconf, autoreconf)
* Missing GNUTLS dependency requirement

MacOS:
`brew install automake`
`brew install gnutls`

Linux:
(Debian-based, includes Ubuntu)
`apt-get install automake build-essential ssh`
(Redhat based, includes centos, fedora)
`yum install automake ssh`

**Comment by yondonfu** [comment]
#888 updated the build instructions to include some missing dependencies (mainly based on the ones used [here](https://github.com/livepeer/go-livepeer/blob/master/docker/Dockerfile#L7)). `automake` and `ssh` are the two dependencies mentioned here that are *not* included in the current documentation - I'm not sure that these are needed? The [documentation](https://github.com/livepeer/go-livepeer/blob/master/doc/install.md#option-2-build-from-source) also only includes installation instructions for Debian, but definitely feel free to open a PR to include the instructions for CentOS/Fedora as well!

**Comment by mk-livepeer** [comment]
I can run through a fedora / redhat / centos install at some point to double check the instructions, there....    Meanwhile, `automake` is indeed necessary, but `ssh` isn't necessarily needed.  `GNUTLS` is.  GNUTLS is achievable by installing a few different packages, but it will most definitely be installed with `ssh` , which is easier for most cases.

**Comment by j0sh** [comment]
`gnutls-dev` is the apt package that's needed for ffmpeg. In lean distros like Debian, `git`, `pkg-config` and friends might be needed as well.

This is what's in the CI config for LPMS: https://github.com/livepeer/lpms/blob/master/.circleci/config.yml#L26

**Comment by kyriediculous** [comment]
This should be resolved by #888 already @mk-livepeer , can you verify? 

NodeJS is also removed from the dependency install instructions by #935 

I'm closing this issue for now, but feel free to re-open.
