### ISSUE TITLE
devtool setup does not provide `pricePerUnit` argument

### ISSUE THREAD

**Issue by mkrufky** [livepeer/go-livepeer#918]
I've been setting up broadcasters and transcoders as follows:
```
docker run -d -p 8545:8545 -p 8546:8546 --name geth-dev darkdragon/geth-with-livepeer-protocol:pm
```
...and each of the following in separate sessions:
```
go run cmd/devtool/devtool.go setup broadcaster | sh 
```
```
go run cmd/devtool/devtool.go setup transcoder | sh
```
The scripts are missing the `pricePerUnit` argument - go-livepeer complains:
```
 livepeer.go:327] Price per unit of pixels must be greater than 0, provided 0 instead
```

**Comment by kyriediculous** [comment]
Ah yes this can be the case indeed.

This was introduced in #916 

We are demanding an orchestrator to set `pricePerUnit` explicitly to prevent free transcoding unknowingly. 
The value defaults to 0 but will also throw a fatal error when it is 0. 

Adding the flag and setting it to an arbitrary number greater than 0 should fix the issue. 

```
pricePerUnit := flag.Int("pricePerUnit", 0, "The price per 'pixelsPerUnit' amount pixels")


if *pricePerUnit <= 0 {
  // Prevent orchestrator from unknowingly provide free transcoding
  glog.Fatalf("Price per unit of pixels must be greater than 0, provided %d instead\n", *pricePerUnit)
  return
}
```

**Comment by kyriediculous** [comment]
Ah yes this can be the case indeed.

This was introduced in #916 

We are demanding an orchestrator to set `pricePerUnit` explicitly to prevent free transcoding unknowingly. 
The value defaults to 0 but will also throw a fatal error when it is 0. 

Adding the flag and setting it to an arbitrary number greater than 0 should fix the issue. 

```
pricePerUnit := flag.Int("pricePerUnit", 0, "The price per 'pixelsPerUnit' amount pixels")


if *pricePerUnit <= 0 {
  // Prevent orchestrator from unknowingly provide free transcoding
  glog.Fatalf("Price per unit of pixels must be greater than 0, provided %d instead\n", *pricePerUnit)
  return
}
```
