### ISSUE TITLE
B should be able to control how often it refreshes its O list

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#925]
**Is your feature request related to a problem? Please describe.**

At the moment, when running in on-chain mode, B will refresh its cached O list once every 1 hour which is a [hardcoded constant](https://github.com/livepeer/go-livepeer/blob/master/discovery/db_discovery.go#L15). The length of the refresh interval affects how often B will receive updated O info (such as prices) and also how often B will "see" newly registered Os. Higher refresh intervals slow O info update propagation to the B, but lower the number of network requests that B has to perform regularly. Lower refresh intervals increase O info update propagation to the B, but increase the number of network requests that B has to perform regularly. While the current hardcoded 1 hour refresh interval might suffice for many cases, some users might want to control the refresh interval.

**Describe the solution you'd like**

Allow B to specify a `-cacheRefreshInterval` (open to naming alternatives) that indicates in seconds how often its cached O list will be refreshed when running in on-chain mode. The default value would still be 1 hour.

**Describe alternatives you've considered**

We could stick with a hardcoded constant, but this reduces flexibility for a B operator.

**Additional context**

**Comment by j0sh** [comment]
Configuring the refresh interval seems harmless.

One thing I like about having an O cache (with periodic refreshing) is that it discourages pricing volatility. Highly volatile prices for transcoding just harms the end user experience IMO. I'd even be in favor of bumping up the default refresh interval to something longer, like 1 day.
