### ISSUE TITLE
Update DB cache to store Pricing information

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#934]
**Is your feature request related to a problem? Please describe.**
#906 allows broadcasters to optionally set a `MaxBroadcastPrice` to filter the orchestrators in the cached orchestratorpool based on an O's pricing info. 

This results`getOrchestratorInfo` call for every orchestrator in the cached `orchestratorPool` , which might result in a lot of requests being sent when there hundreds of orchestrators on the network. 

Rather than querying price for all orchestrators in the cached pool, we should do a quick first pass on orchestrators we know passed the pricing requirements for B before. 

Pricing information for all orchestrators will still be updated when the cache is refreshed 

**Describe the solution you'd like**

0. Refresh DB cache, insert orchestrator pricing info. 
    * update `cacheRegisteredTranscoders` in `db_discover.go` to include a flow/logic similar to initiating  `newOnchainOrchestratorPool` and calling `orchestratorPool.getOrchestrators` with the addition of including the ethereum address.
    * **CAVEAT**: `NewOnchainOrchestratorPool`/ `orchestratorPool.getOrchestrators` does not return the ethereum address for the orchestrator. So it seems it might be better to largely duplicate the logic from these two methods into `cacheRegisteredTranscoders` rather than changing `NewOrchestratorPool` to take in a struct of `{ServiceURI, EthAddress}` which implies reworking many tests as well. 

2. Stream comes in 

3. Filter eligible orchestrators from DB cache
    * Update` db.SelectOrchs` to take in a filter struct as argument if `filter == nil , ignore filter`
    * Update `selectOrchs query` or create a new SQL query in `common/db` to filter based on filter struct

5. Send `OrchestratorInfo` request to eligible orchestrators

6. Filter out eligble orchestrators from response
    * See #906

8. Use top-N eligible responses for orchestrator selection

**Describe alternatives you've considered**
A slightly different flow, that only stores eligble O's in DBcache to begin with. Omitting the need to alter `db.SelectOrchs` which would need access to `server.BroadcastPrice` resulting in a cyclical import. 

0. Refresh DB cache
  0.1 Fetch orchestrator info/pricing info for O's 
  0.2 Insert only eligible O's into DBcache 
2. Get O's from DBcache 
3. Send Orchestrator info request to O's in cache
4. Filter out eligble O's from response
5 Use top-N eligble responses for O selection

**Additional context**
For more context, please see the discussion and comment from Josh in #906 .

**Comment by yondonfu** [comment]
>  Omitting the need to alter db.SelectOrchs which would need access to server.BroadcastPrice resulting in a cyclical import.

We shouldn't need to access `server.BroadcastPrice` in `(*DB).SelectOrchs()` because we can either modify `(*DB).SelectOrchs()` to accept the max price as an argument or create a new method `(*DB).FilterOrchs()` that accepts a filter config struct that carries the max price (and potentially other filter requirements in the future). Under the hood, a simple approach could be to iterate through the results returned by the current [SQL query](https://github.com/livepeer/go-livepeer/blob/master/common/db.go#L141) and a more efficient approach could be to build a custom SQL query that allows us to use WHERE clauses with the filter requirements i.e. WHERE price < maxPrice.

> Refresh DB cache
> 0.1 Fetch orchestrator info/pricing info for O's
> 0.2 Insert only eligible O's into DBcache

I would prefer caching all of the Os because the definition of "eligible" could change between caching time and selection time i.e. B's max price could change

**Comment by kyriediculous** [comment]
> a more efficient approach could be to build a custom SQL query that allows us to use WHERE clauses with the filter requirements i.e. WHERE price < maxPrice.

Since we're storing `*big.Rat `as `[]byte` blobs  in SQL using `GobEncode/GobDecode` I'm not sure if we can do this in the SQL query itself ? Or are there better alternatives for storing?

**Comment by j0sh** [comment]
> we can either modify (*DB).SelectOrchs() to accept the max price as an argument

This would be preferable.

> Since we're storing *big.Rat as []byte blobs in SQL using GobEncode/GobDecode

I would not do this, because it makes interoperability with non-golang tooling harder. We could store the result of the division, maybe as an integer shifted up by some amount ([fixed point](https://en.wikipedia.org/wiki/Fixed-point_arithmetic)).

**Comment by kyriediculous** [comment]
That _could_ work since we're getting the `big.Rat` anyway when we refetch `OInfo` and merely using the value stored in SQL for comparison, you're right.

It would however mean that we'd also have to get the fixed point of the `BroadcastCfg.MaxPrice()` (not that big of a deal) but we'd lose some accuracy I think? We've started using `big.Rat`to avoid dealing with fixed points/floats in the first place. But I guess it's _okay_ in this isolated query context ? Wondering what @yondonfu thinks about as well.

**Comment by yondonfu** [comment]
Converting the price into a fixed point number and storing it as an integer sounds reasonable to me. If we use a scaling factor of 1000, we can still store prices as low as .001 wei per pixel and that are in increments of .001 wei per pixel without losing precision which seems ok. I think the question is: does .001 wei per pixel seem like a reasonable floor on how low an orchestrator can set its price and for the delta between prices? See below for an example of some estimated values to see if this is a reasonable floor:

```
# Estimate for a 2 second segment
# Renditions = 720p, 480p, 360p
outPixels = (1280 * 720 * 30 * 2) + (858 * 480 * 30 * 2) + (480 * 360 * 30 * 2) = 90374400
pricePerPixel = .001 wei
pricePerSegment = ourPixels * pricePerPixel = 90374.40000000001 wei
pricePerHour = pricePerSegment * 30 * 60 = 162673920.00000003 wei
# @ ETH/USD = 1000000000
# Using a gigantic number for the conversion rate to demonstrate
# that even at this extreme conversion rate, the price per hour
# ends up being quite low so at a more realistic conversion rate
# the price per hour would be even lower
pricePerHour = 0.16267392000000003
```

So, even at ETH/USD = 1000000000, the price for transcoding this hour long stream under the current accounting strategy would still be less than 20 cents (and this is before factoring in decoding costs as well). Thus, it feels like a floor of .001 wei per pixel should give an O a reasonable amount of flexibility to set low prices.
