### ISSUE TITLE
Latency Based O Selection

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#938]
**Is your feature request related to a problem? Please describe.**

The broadcaster's orchestrator selection algorithm currently works by popping [O off a stack](https://github.com/livepeer/go-livepeer/blob/master/server/broadcast.go#L52-L65). The [attached diagram](https://sequencediagram.org/index.html#initialData=C4S2BsFMAICECcD2BDAJgY2QZ2Je0B5edAC2gGVIp1REA7AKAYAdl5R0RW7hoAiBCgzZc8PtGzQsWJgwBGiAB7QoAM16JVUrAC5oAKn2VpIehWDJ0Aa0MAdOomIkAgvcelYsrK3QwAtADMTNJ+AHxEpM56lADmAIzySiqQ6tCa2noRJJ4M3pb+QblYYVmw0ZAx0ABMTArKahpa0jrBPgXBWNAAPH5+hE6w0OWVVdAASpDe9FiQtUkNaU26-R6t+dCBTFnOG2HaQxQV0HHjk8zTs3XJqenNKy72WXC5bRtB0huh9zvD0EFXC1uy1KL3WfgALEA) shows how this is suboptimal: here, orchB has a faster response time, but orchA is selected for the next segment anyway due to coming in later and being on top of the stack.

**Describe the solution you'd like**

We can fine tune this to select O based on a latency score. As a first approximation, the latency score for a given segment can be calculated as the transcode duration over the segment duration. We might also want to apply some form of hysteresis on this score over the life of the stream (eg, EWMA) but the appropriate parameters should be modeled first. Implementation can consist of replacing the O stack in the session manager with a heap.

Initial latency values for new Os should be 1. Os that tend to process faster than realtime will have scores <0 , while those slower than realtime will have scores > 1. This allows us to cycle through a set of orchestrators that may not be able to process segments faster than realtime, and settle on the top fastest few.

Selecting based on latency also gives orchestrators more incentive to complete the work quickly. Slow or over-subscribed Os may not receive additional segments beyond the first one, regardless of their initial place in the selection stack.

![image](https://user-images.githubusercontent.com/292510/60117565-21edcb00-972f-11e9-8526-c51c9bb7a470.png)
[Sequence Diagram Source](https://sequencediagram.org/index.html#initialData=C4S2BsFMAICECcD2BDAJgY2QZ2Je0B5edAC2gGVIp1REA7AKAYAdl5R0RW7hoAiBCgzZc8PtGzQsWJgwBGiAB7QoAM16JVUrAC5oAKn2VpIehWDJ0Aa0MAdOomIkAgvcelYsrK3QwAtADMTNJ+AHxEpM56lADmAIzySiqQ6tCa2noRJJ4M3pb+QblYYVmw0ZAx0ABMTArKahpa0jrBPgXBWNAAPH5+hE6w0OWVVdAASpDe9FiQtUkNaU26-R6t+dCBTFnOG2HaQxQV0HHjk8zTs3XJqenNKy72WXC5bRtB0huh9zvD0EFXC1uy1KL3WfgALEA)

**Comment by yondonfu** [comment]
In the diagram, should "Seg 2 Response" be returned by OrchB and not by OrchC?

**Comment by j0sh** [comment]
Ah yep - fixed

**Comment by yondonfu** [comment]
@j0sh With #1241 (stake/latency based O selection) merged, do you think we can close this issue? One thing mentioned in this issue that is *not* implemented right now is applying some form of hysteresis on the latency score (i.e. EWMA), but that is also being tracked by #1232

**Comment by j0sh** [comment]
Yep - closing.
