### ISSUE TITLE
pm: RoundsManager implementation that maintains a cache

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#946]
**Is your feature request related to a problem? Please describe.**

At the moment, both [pm.Sender](https://github.com/livepeer/go-livepeer/blob/master/pm/sender.go#L34) and [pm.Validator](https://github.com/livepeer/go-livepeer/blob/master/pm/validator.go#L35) rely on the `RoundsManager` interface in order to query the latest round and its associated block hash. This interface is currently implemented by [eth/client.go](https://github.com/livepeer/go-livepeer/blob/master/eth/client.go#L129) which will execute a RPC call against an ETH node in order to fetch the values. This is fine for preliminary testing, but is sub-optimal in a production setting because both senders and recipients of PM tickets will need to execute a RPC call for each ticket sent and received.

**Describe the solution you'd like**

We can add an implementation of the `RoundsManager` interface that maintains cached values for the current round and its associated block hash. The implementation could initialize the cache and then monitor contract events for new round and block hash values that would be used to update its cache.

**Describe alternatives you've considered**

We could run a Graph node in parallel with the Livepeer node which would handle the event monitoring. However, this adds additional devops overhead for a node operator.

**Additional context**

**Comment by j0sh** [comment]
> The implementation could initialize the cache and then monitor contract events for new round and block hash values that would be used to update its cache.

We have the [blockservice](https://github.com/livepeer/go-livepeer/blob/81ee4e9bb2a36a273f40544ea3ed08e6e1075a26/eth/eventservices/blockservice.go#L37-L40) that writes the last seen round to the DB; that could be updated to also store the hash in the `kv` DB table. If we go that direction, we can separate out the monitoring / caching from reading and returning the value.

But I'm unsure if there's still a benefit to making this data persistent, as opposed to retaining the value in memory.

(Don't quite recall why the round was written to disk in the first place though. It might have been for robustness at startup time when we had issues with reliable Eth node connections, or simply to avoid making the code aware of yet another interface  - since most code already had access to the DB, we invoked that directly).

**Comment by kyriediculous** [comment]
We can keep an in memory storage of the `last initialized round` and `blockhash for the last initialized round`. To do this we can create a new type `RoundsWatcher` 

We would update these values when a `NewRound(uint256 indexed round, bytes32 blockHash)`  event gets emitted. We can do this by subscribing to the event using the blockwatcher API introduced in https://github.com/livepeer/go-livepeer/pull/1037.
We would also need to decode the events using the contract ABI. 

Upon initiation we can use an RPC call to initially fetch the data

For `RoundsManager.BlockHashForRound(round)` we could still use an RPC call if `round != RoundsManager.LastInitializedRound` else read the value cached in memory. From a quick glance over the pm package it seems we only ever need the block hash for the last initialized round at the moment. 

To integrate the new `RoundWatcher` we'd have to replace the ethclient with the new watcher upon initiating `Sender` and `Validator`. 

```
type RoundsWatcher struct {
 lastInitializedRound *big.Int
 blockHashForRound [32]byte
 sub Event.Subscription
 quit chan struct{}
 // safe concurrent access 
 mu *sync.RWMutex
 // livepeer eth client
 eth *eth.LivepeerEthClient
 bw *eth.Watcher
 // initiated block watcher
}

// Constructor 
func NewRoundsWatcher(*eth.LivepeerEthClient, *eth.Watcher)

// Exported Methods
func (rw *RoundsWatcher) LastInitializedRound (*big.Int, error)
func (rw *RoundsWatcher) BlockHashForRound ([32]byte, error)
func (rw *RoundsWatcher) Listen() {
  // Fetch current round and hash through RPC call
  // Call setters
  // Create a subcribtion on blockwatcher listening for `NewRound events`
  // start listening for `NewRound logs on channel`
} 
func (rw *RoundsWatcher) Close() {
  // Unsubscribe from sub
  // Close quit channel
}

// Unexported Methods
func (rw *RoundsWatcher) setLastInitializedRound
func (rw *RoundsWatcher) setBlockHashForRound
```
