### ISSUE TITLE
Transcoder Setup Improvement

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#95]
Right now, if the you start the Livepeer node as a transcoder, and you don't have the proper on-chain state, the node will automatically walk you through the process of setting up as a transcoder.

After a discussion with @yondonfu, we decided to:
* Take out the check on the Livepeer node and the on-chain logic
* Add a check in RewardsManager to see if the node is an active transcoder (if not, don't call reward)
* Add proper instructions in the Getting Started guide for becoming a transcoder

**Comment by yondonfu** [comment]
Also feels like the creating an on-chain job should also move to the CLI wizard. Right now that logic lives in `mediaserver.go` and the media server's RTMP handler will create an on-chain job when a stream is received. Price and transcoding options are currently set by flags when booting up the node, so changing these values for future broadcasts would require rebooting the node. Instead, the CLI wizard broadcast command can accept price and transcoding options flags and make a call to a web server end point to create an on-chain job when a stream is started. The broadcaster could then leave the node running and just change the price and transcoding options flags whenever it starts a new broadcast

**Comment by yondonfu** [comment]
On second thought, if someone was broadcasting via something like OBS and not using the CLI wizard, we would still want to create the broadcaster to be able to create an on-chain job if they are broadcasting their stream through a Livepeer node. To address that case, perhaps the on-chain job creation logic should remain in `mediaserver.go`...but we could still use a web server end point to update a broadcaster's price and transcoding options for future broadcasts so a broadcaster does not have to boot up the node with different flag values for each broadcast

**Comment by yondonfu** [comment]
Closed by #100. On-chain job creation is still in `mediaserver.go`, but a broadcaster can use the CLI wizard to update its broadcast config
