### ISSUE TITLE
Include pricePerPixel in Payment message

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#954]
**Is your feature request related to a problem? Please describe.**

Currently, B expects to pay O's last known price when it submits a segment - B expects the fee debited from its balance for a transcoded result to be the # of pixels processed * O's last known price. However, this expectation can be left unfulfilled if O's `pricePerPixel` changes from the time that B receives the price to the time that O computes the fee to debit from B's balance. B should be able to indicate the `pricePerPixel` it expects to pay and if O chooses to transcode the segment then the fee debited from B's balance should be based on the `pricePerPixel` provided by B.

**Describe the solution you'd like**

B can include O's last known price with the `Payment` message passed over the wire.

We'll need to:

- Update the [Payment](https://github.com/livepeer/go-livepeer/blob/master/net/lp_rpc.proto#L245) RPC message, which is passed over the wire, to include a nested `PriceInfo` message
- Update the [genPayment()](https://github.com/livepeer/go-livepeer/blob/master/server/segment_rpc.go#L452) to include O's last known price in the `Payment` message to be serialized and passed over the wire

Changes to [(*orchestrator).ProcessPayment()](https://github.com/livepeer/go-livepeer/blob/master/core/orchestrator.go#L98) (i.e. actually validating the provided price) can be implemented separately.

**Describe alternatives you've considered**

B could skip providing any indication of the `pricePerPixel` that it expects to pay and O could just transcode a segment based on whatever its current `pricePerPixel` is. Then, when O returns a transcode receipt, B could use O's last known `pricePerPixel` to verify the balance. In this case, O's `pricePerPixel` could have legitimately changed resulting in the balance in the receipt appearing to be incorrect. As a result, B disconnects from O because it had no way to receive notifications of an updated `pricePerPixel` prior to receiving the transcoded result. Alternatively, B could derive the `pricePerPixel` used by computing the difference between its own view of its balance and the balance in the receipt - if the `pricePerPixel` is still below B's `maxPricePerPixel`, B would consider the balance in the receipt valid. However, the problem here is that if O knows B's `maxPricePerPixel`, it could advertise low `pricePerPixel` values, but when returning receipts always use B's `maxPricePerPixel - 1`.

Another design involves O including the `pricePerPixel` used in the receipt, but I think the implications would be the same as ones for the above design.

The proposed solution would allow B expect notifications for `pricePerPixel` updates earlier in the workflow allowing B to just disconnect if a transcode receipt includes a balance that does not reflect the `pricePerPixel` provided with the segment.

**See below for another approach for B to provide a pricePerPixel with segments**

B already includes segment metadata in the header of a segment so we can just have B add O's known price to this metadata payload.

We'll need to:

- Update [core.SegTranscodingMetadata](https://github.com/livepeer/go-livepeer/blob/master/core/streamdata.go#L25), which is flattened and signed by B, to include O's last known price represented by a `*big.Rat`
- Update the RPC message [SegData](https://github.com/livepeer/go-livepeer/blob/master/net/lp_rpc.proto#L105), which is passed over the wire, to include a nested `PriceInfo` message
- Update [genSegCreds()](https://github.com/livepeer/go-livepeer/blob/master/server/segment_rpc.go#L414) to include O's last known price in B's signature and to include O's last known price in the `SegData` message to be serialized and passed over the wire

Changes to [verifySegCreds()](https://github.com/livepeer/go-livepeer/blob/master/server/segment_rpc.go#L209) (i.e. actually validating the provided price) can be implemented separately.

**Additional context**

**Comment by j0sh** [comment]
Could we put this in the Payment struct rather than SegData? That seems like a better fit.

(Also, just noticed that the `Ticket` and `TicketParams` structs are nearly identical. We really should clean that up, or even flatten those params into the `Payment` struct entirely.)

https://github.com/livepeer/go-livepeer/blob/0dcd9bd30b377159801e4be4c6358c1812d1cccc/net/lp_rpc.proto#L242-L257

**Comment by yondonfu** [comment]
> Could we put this in the Payment struct rather than SegData? That seems like a better fit.

Yeah we can do that - I updated the OP accordingly. I was originally hesitant about putting the price in the `Payment` message because keeping it exclusively as a group of tickets seemed nice, but on second thought including the price in the `Payment` message essentially says: "this group of tickets pays for transcoding based on this expected price" which makes sense to me.

> Also, just noticed that the Ticket and TicketParams structs are nearly identical. We really should clean that up, or even flatten those params into the Payment struct entirely

Yep - we're actually not using the `Ticket` message at all anymore so we should be able to remove it completely.

**Comment by kyriediculous** [comment]
> "this group of tickets pays for transcoding based on this expected price"

Yeah I agree with that but you can make the same argument for putting it in the Segment Metadata 

> " I expect this segment to be transcoded in accordance with the specified price"

I like the second one better still but that's very, very opinionated.

And I very much like this property to not obfuscate the payment message 

> exclusively as a group of tickets

**Comment by yondonfu** [comment]
> you can make the same argument for putting it in the Segment Metadata

At the moment, the `SegData` message fields are primarily concerned with *how* the segment should be transcoded i.e. which profiles to use, what storage medium to use, etc. Adding the price into the message introduces payment concerns into a message that is currently solely focused on non-payment transcoding related concerns. IMO keeping `SegData` focused on non-payment transcoding related concerns and `Payment` focused on payment related concerns feels better.

**Comment by j0sh** [comment]
> but that's very, very opinionated.

It's not really opinionated looking at it as a functional grouping. The only time you're sending price info is when you also send a payment. Eg, the price info won't be there for offchain mode. Doesn't make sense to have a partially populated SegmentMetadata (based on whether a payment is included) when we could just put the info into the payment itself.

**Comment by kyriediculous** [comment]
I don't really mind putting it in the payment message and I don't think it really matters at this point, I'm just playing devil's advocate here. Some extra thoughts: 

The `Payment` message is related to the `pm` package exclusively, while `pixelsPerUnit` belongs to accounting logic. The latter is not necessarily dependent on the former. 

`TranscodeResult` also contains `OrchestratorInfo` which contains `TicketParams` and `PriceInfo` so at this point I wouldn't mind having a partially populated field on the 'other side' as well. 

After looking beyond the message and where to place it, but looking at how we are going to use it,  it does seem to be better to put it in ` Payment` if we are going to validate it in `ProcessPayment`, but that's the main reason for me.
