### ISSUE TITLE
O should validate pricePerPixel sent by B

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#955]
**Is your feature request related to a problem? Please describe.**

(To be filled in)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kyriediculous** [comment]
We could validate the `ExpectedPrice` B sends along with `Payment` in `Orchestrator.ProcessPayment` in a similar fashion to how we handle acceptable payment errors. 

Potentially we could also distinguish between an acceptable price and a non-acceptable one by implementing a maximum Delta. 

If the Delta is too large we would throw an error from `ProcessPayment` which makes B refetch `OrchestratorInfo` 

If the Delta is acceptable we would call `Recipient.SenderMonitor.AcceptErr()` to check whether any more acceptable errors are allowed for `sender` 

The drawback of this approach is that `PriceInfo` is a concern of `LivepeerNode` and not `LivepeerNode.Recipient` and thus not specific to the `pm` package. This implies we should not be using `pm.Error` here but simply something like the pseudocode below, which might not be the most beautiful solution. We'd also have to expose the `SenderMonitor.AcceptErr(sender)` method on the `Recipient` interface. Alternatively we could only check against a Delta and leave an acceptable error count out of the picture. 

```
...
if payment.Sender == nil || len(payment.Sender) == 0 {
	return fmt.Errorf("Could not find Sender for payment: %v", payment)
}

ok, err := orch.acceptablePrice(payment.Sender, payment.ExpectedPrice)
if  !ok { 
    return err
} else {
 glog.Errorf("%v", err)
}

seed := new(big.Int).SetBytes(payment.TicketParams.Seed)
...
```

```
func (orch *orchestrator) acceptablePrice(sender ethcommon.Address, ep *net.PriceInfo) (bool, error) {
  // convert ep to big.Rat 'epRat'
  orchPrice := orch.PriceInfo(sender)
  // convert orchPrice to big.Rat 'orchPriceRat'

 // happy case, price is good
  if eprat.Cmp(orchPriceRat) >= 0 {
 return true, nil
}
  
  // If price delta is not acceptable return an error
  // we are only concerned when orchPrice-Expected Price is positive
  if epRat.Sub(orchPriceRat, epRat).Cmp(orch.priceDelta) == 1 {
    return false, fmt.Errorf("unacceptable price")
 } else {
  // If price delta is acceptable see if we are not exceeding the max Error count. 
   return orch.node.Recipient.AcceptErr(sender), fmt.Errorf("Prices don't match but delta is acceptable")
}
}
```

**Comment by kyriediculous** [comment]
The design discussion resulted in an outline similar to the one above with a few changes:

1. Discard the use of a Delta for now and use 1-to-1 match
2. Extract the Acceptable error and errorCount logic out of the `pm` package and keep a shared errorCount for both acceptable pm ticket errors and acceptable price errors.* 

_* the drawback of (2) is that we would on reset the errorCount for a sender when a ticket is redeemed, which is doesn't share any concerns with acceptable price errors. The alternative would be to separate ErrorCounts for price errors and pm ticket errors._

**ErrorMonitor** 
```
type errorMonitor struct {
  mu sync.RWMutex
  errCounts map[ethcommon.Address]int
  maxErrCount int
}

type ErrorMonitor interface {
 AcceptErr(sender) bool
ClearErrCount(sender)
}

func NewErrorMonitor(maxErrCount int) ErrorMonitor 
```

This would also involve taking following steps:

1. Define an an errorMonitor field on the `LivepeerNode` 
```
type LivepeerNode struct {
...
Em *errorMonitor
...
}
```

2. Call the errorMonitor constructor `core.NewErrorMonitor` which returns a concrete type and set it on the node `LivepeerNode.Em`

3. Adjust `pm.NewSenderMonitor` to take in an argument of type `pm.ErrorMonitor interface` 

4. When invoking `pm.NewSenderMonitor`, pass in the `LivepeerNode.Em` concrete type. We can now alter values on the `LivepeerNode.Em` through the exposed interface methods. 

CAVEAT: We can not access these interface methods from `recipient.sm` as it is an interface and not a concrete type, meaning we can't access the `ErrorMonitor` interface type defined on the SenderMonitor. 

Possible solutions: 
* add a field of type `ErrorMonitor` to the recipient struct as well
* Expose an `AcceptErr` method from the SenderMonitor interface and create an additional method that essentially forwards the call
```
func (sm *senderMonitor) AcceptErr(sender ethcommon.Address) bool {
 return sm.em.AcceptErr(sender)
}
```

**Comment by yondonfu** [comment]
> add a field of type ErrorMonitor to the recipient struct as well

I favor this solution - the same `ErrorMonitor` instance can be injected as a dependency into `pm.Recipient` and `pm.SenderMonitor` during initialization. Since we're moving all the error counting logic into `ErrorMonitor`, I think types that require access to error counting logic should use the `ErrorMonitor` directly (with interfaces when necessary). Once we have the `ErrorMonitor`, `pm.SenderMonitor` will not need to be directly exposed to any of the implementation details pertaining to error counting so I don't think `pm.Recipient` should expect `pm.SenderMonitor` to know anything about error counting.
