### ISSUE TITLE
CI build for linux doesn't record version

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#965]
**Describe the bug**
CI build for linux doesn't record version information.

**To Reproduce**
1. download linux binary built in CI
  https://build.livepeer.live/0.3.3-9b95737b/livepeer-linux-amd64.tar.gz
2. run `./livepeeer -version`
3. see `Livepeer Node Version: undefined`

**Expected behavior**
Should show `Livepeer Node Version: 0.3.3-9b95737b`

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by iameli** [comment]
Hrmph, odd.

**Comment by darkdarkdragon** [comment]
This fixed now.
