### ISSUE TITLE
No column named pricePerPixel

### ISSUE THREAD

**Issue by ya7ya** [livepeer/go-livepeer#966]
**Describe the bug**
Users with an existing `datadir` that was generated pre PM updates will get this error

```bash
E0708 09:36:31.153310   16487 db.go:150] Unable to prepare updateOrchestrators stmt table orchestrators has no column named pricePerPixel
```

**To Reproduce**
1. download the latest release used on the mainnet and generate a new datadir
2. pull the latest `go-livepeer` and build it. 
3. run `./livepeer -datadir <existing datadir path>`

**Expected behavior**
new versions of livepeer *should* be able to migrate the db to the new schema in a seamless manner

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04

**Comment by j0sh** [comment]
Agreed that we should be careful about back compatibility and DB schema migrations in the future. There's already a placeholder for this:

https://github.com/livepeer/go-livepeer/blob/33fa9b29960d34193e39e18aba0052e8ffded8fb/common/db.go#L140-L142

Note that we basically dropped any compatibility promises once we stopped doing regular releases in favor of a big-bang Streamflow release. At this point, I don't think we should be putting too much effort into DB migration during an active development cycle. In your case, just remove the DB and restart.

Once we've released Streamflow and are back in a regular release cadence with external users, the DB migration path is definitely something we need to keep an eye on, and perhaps enforce via CI.

Before we actually do the SF release, we might also want to have a standalone migration tool to handle the DB, the CLI flag updates, etc so existing transcoders have a smoother transition to Streamflow. But that's a separate issue.

Tracking in https://github.com/livepeer/go-livepeer/issues/969 and https://github.com/livepeer/go-livepeer/issues/970
